LIBNAME LIBRARY V8 'Q:\BRFSS\2002\PROGRAMS\FORMATS'  SHORTFILEEXT;

PROC FORMAT LIBRARY = LIBRARY ;
      Value AGEGROUP
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            18  - 24         = 'Age 18 - 24'
            25  - 34         = 'Age 25 - 34'
            35  - 44         = 'Age 35 - 44'
            45  - 54         = 'Age 45 - 54'
            55  - 64         = 'Age 55 - 64'
            65  - 99         = 'Age 65 or older'
            ;
      Value ARTHDISB
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value ASDRVIST
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            88               = 'None'
            98               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value ASNOSLEP
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'One or two'
            2                = 'Three to four'
            3                = 'Five'
            4                = 'Six to ten'
            5                = 'More than ten'
            7                = 'Do not know/Not sure'
            8                = 'None'
            9                = 'Refused'
            ;
      Value ASPUNSAF
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes, not stomach related'
            2                = 'Yes, stomach problems'
            3                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value ASTHMAGE
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            11  - 96         = 'Age 11 or older'
            97               = 'Age 10 or younger'
            98               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value ASTHMEDS
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Less than once a week'
            2                = 'Once or twice a week'
            3                = 'More than 2 times a week, but not every day'
            4                = 'Once every day'
            5                = '2 or more times every day'
            7                = 'Do not know/Not sure'
            8                = 'Did not take any'
            9                = 'Refused'
            ;
      Value ASTHSYMP
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Less than once a week'
            2                = 'Once or twice a week'
            3                = 'More that 2 times a week, but not every day'
            4                = 'Every day, but not all the time'
            5                = 'Every day, all the time'
            7                = 'Do not know/Not sure'
            8                = 'Not at any time'
            9                = 'Refused'
            ;
      Value ATKDYWRK
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            97               = 'More than 96'
            98               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value ATKEVAC
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value ATKMEDIA
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'A lot'
            2                = 'Some'
            3                = 'Very little'
            4                = 'Not at all'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value ATKNOWRK
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value ATKRSWRK
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Damage to workplace'
            2                = 'Workplace closed or no transportation to workplace'
            3                = 'Personal injury'
            4                = 'Too upset to work'
            5                = 'Did not feel well enough to work'
            6                = 'Other'
            7                = 'Do not know/Not sure'
            8                = 'Did not feel safe'
            9                = 'Refused'
            ;
      Value BCMETFM_
            .                = 'Pregnant Now/Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Surgical'
            2                = 'Contraception'
            3                = 'Not Active/No Partner'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value BCMETML_
            .                = 'Partner Pregnant Now/Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Surgical'
            2                = 'Contraception'
            3                = 'Not Active/No Partner'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value BLDSUGAR
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            101  - 199       = 'Times per day'
            201  - 299       = 'Times per week'
            301  - 399       = 'Times per month'
            401  - 499       = 'Times per year'
            777              = 'Do not know/Not sure'
            888              = 'Never'
            999              = 'Refused'
            ;
      Value BPHIGH3_
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'Yes, but female told only during pregnancy'
            3                = 'No'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value BRCNTRL_
            .                = 'Pregnant Now/Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Use Birth Control'
            2                = 'No Birth Control'
            3                = 'Want Pregnancy'
            4                = 'Not Active/No Partner/Same Sex Partner'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value BRTHCNT
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            3                = 'No partner/not sexually active'
            4                = 'Same sex partner'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value CHILDREN
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            88               = 'None'
            99               = 'Refused'
            ;
      Value CHKHEMOA
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            77               = 'Do not know/Not sure'
            88               = 'None'
            98               = 'Never heard of hemoglobin "A one C" test'
            99               = 'Refused'
            ;
      Value CTELENUM
            .                = 'Unused or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            ;
      Value DIABAGE
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            98               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value DIABETES
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'Yes, but female told only during pregnancy'
            3                = 'No'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value DISPFMT
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            110              = 'Completed Interview'
            120              = 'Partial Complete Interview'
            ;
      Value DRADVICE
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes, lose weight'
            2                = 'Yes, gain weight'
            3                = 'Yes, maintain current weight'
            4                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value DROCCDY_
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            0                = 'No Drink-Occasions per day'
            1  - 899         = 'Drink-Occasions per day'
            900              = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value EDUCAF
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Never attended school or only kindergarten'
            2                = 'Grades 1 - 8 (Elementary)'
            3                = 'Grades 9 - 11 (Some high school)'
            4                = 'Grade 12 or GED (High school graduate)'
            5                = 'College 1 year to 3 years (Some college or technical school)'
            6                = 'College 4 years or more (College graduate)'
            9                = 'Refused'
            ;
      Value EMPLOYA
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Employed for wages'
            2                = 'Self-employed'
            3                = 'Out of work for more than 1 year'
            4                = 'Out of work for less that 1 year'
            5                = 'A homemaker'
            6                = 'A student'
            7                = 'Retired'
            8                = 'Unable to work'
            9                = 'Refused'
            ;
      Value EYEEXAM
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past month (< 1 month ago)'
            2                = 'Within the past year (1 month but < 12 months ago)'
            3                = 'Within the past 2 years (1 year but < 2 years ago)'
            4                = '2 or more years ago'
            7                = 'Do not know/Not sure'
            8                = 'Never'
            9                = 'Refused'
            ;
      Value FACILIT
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'A doctors office'
            2                = 'A public health clinic or community health center'
            3                = 'A hospital outpatient department'
            4                = 'A hospital emergency room'
            5                = 'Urgent care center'
            6                = 'Some other kind of place'
            7                = 'Do not know/Not sure'
            8                = 'No usual place'
            9                = 'Refused'
            ;
      Value FEWCAL
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes, fewer calories'
            2                = 'Yes, less fat'
            3                = 'Yes, fewer calories and less fat'
            4                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value FIRSTAID
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Take them the hospital'
            2                = 'Tell them to call their doctor'
            3                = 'Call 911'
            4                = 'Call their spouse or a family member'
            5                = 'Do something else'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value FLUPRO
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'A doctors office or HMO'
            2                = 'A health department'
            3                = 'Another type of clinic or health center'
            4                = 'A senior, recreation, or community center'
            5                = 'A store'
            6                = 'A hospital or emergency room'
            7                = 'Workplace'
            8                = 'Some other kind of place'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value FRTINDX
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Less than once per day or never'
            2                = 'Once but less than 3 times per day'
            3                = '3 but less than 5 times per day'
            4                = '5 or more times per day'
            9                = 'Do not know/Refused/Missing'
            ;
      Value HATTKAGE
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Age 40 or less'
            2                = 'Age 41 to 54'
            3                = 'Age 55 to 64'
            4                = 'Age 65 or older'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value HIVOPT
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Very important'
            2                = 'Somewhat important'
            3                = 'Not at all important'
            7                = 'Do not know/Not sure'
            8                = 'Depends on Risk'
            9                = 'Refused'
            ;
      Value HLTHPROB
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Arthritis/rheumatism'
            2                = 'Back or neck problem'
            3                = 'Fractures, bone/joint injury'
            4                = 'Walking problem'
            5                = 'Lung/breathing problem'
            6                = 'Hearing problem'
            7                = 'Eye/vision problem'
            8                = 'Heart problem'
            9                = 'Stroke problem'
            10               = 'Hypertension/high blood pressure'
            11               = 'Diabetes'
            12               = 'Cancer'
            13               = 'Depression/anxiety/emotional problem'
            14               = 'Other impairment/problem'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value HLTHSTAT
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Excellent'
            2                = 'Very good'
            3                = 'Good'
            4                = 'Fair'
            5                = 'Poor'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value HOUSESMK
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not allowed anywhere inside your home'
            2                = 'Allowed in some places or at some times'
            3                = 'Allowed anywhere inside the home'
            4                = 'No rules about smoking inside the home'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value HTIN
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1  - 98          = 'Height in inches'
            99               = 'Do not know/Refused/Missing'
            ;
      Value HTM
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1  - 998         = 'Height in meters [2 implied decimal places]'
            999              = 'Do not know/Refused/Missing'
            ;
      Value INCOME
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Less than $10,000'
            2                = 'Less than $15,000 ($10,000 to less than $15,000)'
            3                = 'Less than $20,000 ($15,000 to less than $20,000)'
            4                = 'Less than $25,000 ($20,000 to less than $25,000)'
            5                = 'Less than $35,000 ($25,000 to less than $35,000)'
            6                = 'Less than $50,000 ($35,000 to less than $50,000)'
            7                = 'Less than $75,000 ($50,000 to less than $75,000)'
            8                = '$75,000 or more'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value JOBACTIV
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Mostly sitting or standing'
            2                = 'Mostly walking'
            3                = 'Mostly heavy labor or physically demanding work'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value JOINTSYM
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value LASTDEN
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past year (< 12 months ago)'
            2                = 'Within the past 2 years (1 year but < 2 years ago)'
            3                = 'Within the past 5 years (2 years but < 5 years ago)'
            4                = '5 or more years ago'
            7                = 'Do not know/Not sure'
            8                = 'Never'
            9                = 'Refused'
            ;
      Value LONGACT
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            101  - 199       = 'Days'
            201  - 299       = 'Weeks'
            301  - 399       = 'Months'
            401  - 499       = 'Years'
            777              = 'Do not know/Not sure'
            999              = 'Refused'
            ;
      Value MARITALF
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Married'
            2                = 'Divorced'
            3                = 'Widowed'
            4                = 'Separated'
            5                = 'Never married'
            6                = 'A member of an unmarried couple'
            9                = 'Refused'
            ;
      Value MEDCARE
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value MEDREAS
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Cost [Include no insurance]'
            2                = 'Distance'
            3                = 'Office was not open when I could get there'
            4                = 'Too long a wait for an appointment'
            5                = 'Too long a wait in waiting room'
            6                = 'No child care'
            7                = 'No transportation'
            8                = 'No access for people with disabilities'
            9                = 'Medical provider did not speak my language'
            10               = 'Other'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value MODPADAY
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1  - 7           = 'Days per week'
            77               = 'Do not know/Not sure'
            88               = 'Do less than 10 mins of moderate activity at a time'
            99               = 'Refused'
            ;
      Value $MTHFMTC
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            ' 1'             = 'January'
            ' 2'             = 'February'
            ' 3'             = 'March'
            ' 4'             = 'April'
            ' 5'             = 'May'
            ' 6'             = 'June'
            ' 7'             = 'July'
            ' 8'             = 'August'
            ' 9'             = 'September'
            '10'             = 'October'
            '11'             = 'November'
            '12'             = 'December'
            ;
      Value NOBCUSE
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not sexually active/no partner'
            2                = 'Did not think was going to have sex/no regular partner'
            3                = 'You want a pregnancy'
            4                = 'You or your partner do not want to use birth control'
            5                = 'You or your partner do not like birth control/fear side effects'
            6                = 'You can not pay for birth control'
            7                = 'Lapse in use of a method'
            8                = 'Do not think you or your partner can get pregnant'
            9                = 'You or your partner had tubes tied (sterilization)'
            10               = 'You or your partner had a vasectomy (sterilization)'
            11               = 'You or your partner had a hysterectomy'
            12               = 'You or your partner are too old'
            13               = 'You or your partner are currently breast-feeding'
            14               = 'You or your partner just had a baby/postpartum'
            15               = 'Other reason'
            16               = 'Do not care if get pregnant'
            17               = 'Same sex partner'
            18               = 'Partner is pregnant now'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value NUMPHONS
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Residential telephone number'
            2                = 'Residential telephone numbers'
            3                = 'Residential telephone numbers'
            4                = 'Residential telephone numbers'
            5                = 'Residential telephone numbers'
            6                = 'Residential telephone numbers'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value ORACE
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'White'
            2                = 'Black or African American'
            3                = 'Asian'
            4                = 'Native Hawaiian or Other Pacific Islander'
            5                = 'American Indian, Alaska Native'
            6                = 'Other'
            7                = 'Do not know/Not sure'
            8                = 'Multiracial but preferred race not asked'
            9                = 'Refused'
            ;
      Value OTHERBC
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Tubes tied (sterilization)'
            2                = 'Vasectomy (sterilization)'
            3                = 'Pill'
            4                = 'Condoms'
            5                = 'Foam, jelly, cream'
            6                = 'Diaphragm'
            7                = 'Norplant'
            8                = 'IUD'
            9                = 'Shots (Depo-Provera)'
            10               = 'Withdrawal'
            11               = 'Not having sex at certain times (rhythm)'
            12               = 'No partner/not sexually active'
            13               = 'Other Method(s)'
            77               = 'Do not know/Not sure'
            87               = 'No Other Method(s)'
            99               = 'Refused'
            ;
      Value PERSDOC
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes, only one'
            2                = 'More than one'
            3                = 'No'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value PRECALL
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'To be called'
            3                = 'Pre-screened as non-working number'
            5                = 'Pre-screened as business number'
            ;
      Value PVTRESID
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            ;
      Value RACE2F
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'White only, Non-Hispanic'
            2                = 'Black only, Non-Hispanic'
            3                = 'Asian only, Non-Hispanic'
            4                = 'Native Hawaiian or other Pacific Islander only, No'
            5                = 'American Indian or Alaskan Native only, Non-Hispan'
            6                = 'Other race only, Non-Hispanic'
            7                = 'Multiracial, Non-Hispanic'
            8                = 'Hispanic'
            9                = 'Do not know/Not sure/Refused component question'
            ;
      Value REASONS
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'To make strong bones'
            2                = 'To prevent birth defects'
            3                = 'To prevent high blood pressure'
            4                = 'Some other reason'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value RMVTEETH
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = '1 to 5'
            2                = '6 or more, but not all'
            3                = 'All'
            7                = 'Do not know/Not sure'
            8                = 'None'
            9                = 'Refused'
            ;
      Value RSNNOCOV
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Lost job or changed employers'
            2                = 'Spouse or parent lost job or changed employers'
            3                = 'Became divorced or separated'
            4                = 'Spouse or parent died'
            5                = 'Became ineligible due to age or because left school'
            6                = 'Employer does not or stopped offering coverage'
            7                = 'Cut back to part time or temporary employee'
            8                = 'Benefits from employer or former employer ran out'
            9                = 'Could not afford to pay the premiums'
            10               = 'Insurance company refused coverage'
            11               = 'Lost Medicaid or Medical Assistance eligibility'
            77               = 'Do not know/Not sure'
            87               = 'Other'
            99               = 'Refused'
            ;
      Value SEATBELT
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Always'
            2                = 'Nearly always'
            3                = 'Sometimes'
            4                = 'Seldom'
            5                = 'Never'
            7                = 'Do not know/Not sure'
            8                = 'Never drive or ride in a car'
            9                = 'Refused'
            ;
      Value SERVINGS
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            101  - 199       = 'Per day'
            201  - 299       = 'Per week'
            301  - 399       = 'Per month'
            401  - 499       = 'Per year'
            555              = 'Never'
            777              = 'Do not know/Not sure'
            999              = 'Refused'
            ;
      Value SEXFMT
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Male'
            2                = 'Female'
            ;
      Value SMKPUBLC
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not allowed in any public areas'
            2                = 'Allowed in some public areas'
            3                = 'Allowed in all public areas'
            4                = 'No official policy'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value SMKWORK
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not allowed in any work areas'
            2                = 'Allowed in some work areas'
            3                = 'Allowed in all work areas'
            4                = 'No official policy'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value SMOKEDAY
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Every day'
            2                = 'Some days'
            3                = 'Not at all'
            9                = 'Refused'
            ;
      Value SUPPLE
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            101  - 199       = 'Times per day'
            201  - 299       = 'Times per week'
            301  - 399       = 'Times per month'
            777              = 'Do not know/Not sure'
            999              = 'Refused'
            ;
      Value TESTAIDS
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Private doctor or HMO'
            2                = 'Counceling and testing site'
            3                = 'Hospital'
            4                = 'Clinic'
            5                = 'In a jail or prison (or other correctional facility)'
            6                = 'Home'
            7                = 'Somewhere else'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value TIME1F
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past 6 months (< 6 months ago)'
            2                = 'Within the past year (6 months but < 12 months ago)'
            3                = 'Within the past 2 years (1 year but < 2 years ago)'
            4                = 'Within the past 5 years (2 years but < 5 years ago)'
            5                = '5 or more years ago'
            7                = 'Do not know/Not sure'
            8                = 'Never'
            9                = 'Refused'
            ;
      Value TIME2AF
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past year (< 12 months ago)'
            2                = 'Within the past 2 years (1 year but < 2 years ago)'
            3                = 'Within the past 5 years (2 years but < 5 years ago)'
            4                = 'Within the past 10 years (5 years but < 10 years ago)'
            5                = '10 or more years ago'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value TIME2F
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past year (< 12 months ago)'
            2                = 'Within the past 2 years (1 year but < 2 years ago)'
            3                = 'Within the past 5 years (2 years but < 5 years ago)'
            4                = '5 or more years ago'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value TIME3F
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past year (< 12 months ago)'
            2                = 'Within the past 2 years (1 year but < 2 years ago)'
            3                = 'Within the past 3 years (2 years but < 3 years ago)'
            4                = 'Within the past 5 years (3 years but < 5 years ago)'
            5                = '5 or more years ago'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value TIME4F
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Within the past month (< 1 month ago)'
            2                = 'Within the past 3 months (1 month but < 3 months ago)'
            3                = 'Within the past 6 months (3 months but < 6 months)'
            4                = 'Within the past year (6 months but < 1 year ago)'
            5                = 'Within the past 5 years (1 year but < 5 years ago)'
            6                = 'Within the past 10 years (5 years but < 10 years ago)'
            7                = '10 or more years'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value TRUEFALS
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'True'
            2                = 'False'
            7                = 'Do not know/Not Sure'
            9                = 'Refused'
            ;
      Value TYPCNTR
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Tubes tied (sterilization)'
            2                = 'Vasectomy (sterilization)'
            3                = 'Pill'
            4                = 'Condoms'
            5                = 'Foam, jelly, cream'
            6                = 'Diaphragm'
            7                = 'Norplant'
            8                = 'IUD'
            9                = 'Shots (Depo-Provera)'
            10               = 'Withdrawal'
            11               = 'Not having sex at certain times (rhythm)'
            12               = 'No partner/not sexually active'
            13               = 'Other Method(s)'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value UNK2DIG
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            77               = 'Do not know/Not sure'
            88               = 'Never smoked regularly'
            99               = 'Refused'
            ;
      Value UNK3DIG
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            777              = 'Do not know/Not sure'
            800  - 959       = 'Hours and minutes per day'
            999              = 'Refused'
            ;
      Value UNK4ADIG
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1  - 9998        = '1 or greater'
            9999             = 'Do not know/Refused/Missing'
            ;
      Value UNK4DIG
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            0                = 'Did not drink in the past month'
            1  - 9998        = 'Number of Drinks'
            9999             = 'Do not know/Refused/Missing'
            ;
      Value UNK6ADIG
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            11985  - 772002  = 'Code month and year'
            777777           = 'Do not know/Not sure'
            992002           = 'Code month and year'
            999999           = 'Refused'
            ;
      Value WEIGHT
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            777              = 'Do not know/Not sure'
            999              = 'Refused'
            ;
      Value WHYTEST
            .                = 'Not asked or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'It was required'
            2                = 'Someone suggested you should be tested'
            3                = 'You thought you may have gotten HIV through sex or drug use'
            4                = 'You just wanted to find out whether you had HIV'
            5                = 'You were worried that you could give HIV to someone'
            6                = 'You were pregnant'
            7                = 'It was done as part fo a routine medical check-up'
            8                = 'Some other reason'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value WTKG
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1  - 99998       = 'Weight in kilograms [2 implied decimal places]'
            99999            = 'Do not know/Refused/Missing'
            ;
      Value YESNDKR
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value YNDR
            .                = 'Module not used or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value YNDRM
            .                = 'Not asked, Module not used, or Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Yes'
            2                = 'No'
            7                = 'Do not know/Not sure'
            9                = 'Refused'
            ;
      Value _2RACEG
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Non-Hispanic White'
            2                = 'Non-White or Hispanic'
            9                = 'Do not know/Not sure/Refused Missing component question'
            ;
      Value _2RACEGR
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'White only, Non-Hispanic'
            2                = 'Black only, Non-Hispanic'
            3                = 'Other race only, Non-Hispanic'
            4                = 'Multiracial, Non-Hispanic'
            5                = 'Hispanic'
            9                = 'Do not know/Not sure/Refused component question'
            ;
      Value _AGE65YR
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Age 18 to 64'
            2                = 'Age 65 or older'
            3                = 'Do not know/Refused/Missing'
            ;
      Value _AGEG
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Age 18 to 34'
            2                = 'Age 35 to 54'
            3                = 'Age 55 or older'
            ;
      Value _AGEG5YR
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Age 18 - 24'
            2                = 'Age 25 to 29'
            3                = 'Age 30 to 34'
            4                = 'Age 35 to 39'
            5                = 'Age 40 to 44'
            6                = 'Age 45 to 49'
            7                = 'Age 50 to 54'
            8                = 'Age 55 to 59'
            9                = 'Age 60 to 64'
            10               = 'Age 65 to 69'
            11               = 'Age 70 to 74'
            12               = 'Age 75 to 79'
            13               = 'Age 80 or older'
            14               = 'Do not know/Refused/Missing'
            ;
      Value _AGEGFMT
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            0                = 'Age 18 or older'
            1                = 'Age 18 - 24'
            2                = 'Age 25 to 34'
            3                = 'Age 35 to 44'
            4                = 'Age 45 to 54'
            5                = 'Age 55 to 64'
            6                = 'Age 65 or older'
            7                = 'Age 18 to 34'
            8                = 'Age 35 to 54'
            9                = 'Age 55 or older'
            10               = 'Age 18 to 44'
            11               = 'Age 45 or older'
            ;
      Value _AIDSTST
            .                = 'Missing or Age greater than 64'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value _ALTEETH
            .                = 'Missing or Age Less Than 65'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at risk'
            2                = 'At risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _ASTHMST
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Current'
            2                = 'Former'
            3                = 'Never'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _BMI2CAT
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Neither overweight nor obese (_BMI2 < 2500)'
            2                = 'Overweight (2500 <= _BMI2 < 3000)'
            3                = 'Obese (3000 <= _BMI2 < 9999)'
            9                = 'Do not know/Refused/Missing (_BMI2 = 9999)'
            ;
      Value _CASTHMA
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not At Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _CNRACE
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            0                = 'Other/do not know/refused'
            1                = '1 category chosen'
            2                = '2 category chosen'
            3                = '3 category chosen'
            4                = '4 category chosen'
            5                = '5 category chosen'
            ;
      Value _CNRACEC
            .                = '_CNRACE was coded Other/do not know/refused'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            0                = 'zero or missing'
            1                = 'One category chosen'
            2                = 'Two or more categories chosen'
            ;
      Value _DENSTR
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Listed'
            2                = 'Unlisted'
            3                = 'Zero block'
            ;
      Value _DENTVST
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at risk'
            2                = 'At risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _EXTEETH
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at risk'
            2                = 'At risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _FCNTRAC
            .                = 'Pregnant Now/Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value _FLUSHOT
            .                = 'Missing or Age Less Than 65'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at risk'
            2                = 'At risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _HIGHRSK
            .                = 'Missing or Age greater than 64'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value _IMPAGE
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            18  - 24         = 'Age 18 to 24'
            25  - 34         = 'Age 25 to 34'
            35  - 44         = 'Age 35 to 44'
            45  - 54         = 'Age 45 to 54'
            55  - 64         = 'Age 55 to 64'
            65  - 99         = 'Age 65 or older'
            ;
      Value _LTASTHM
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not At Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _MCNTRAC
            .                = 'Partner Pregnant Now/Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value _MRACE
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'White only'
            2                = 'Black or African American only'
            3                = 'Asian Only'
            4                = 'Native Hawaiian or other Pacific Islander only'
            5                = 'American Indian or Alaskan Native only'
            6                = 'Other race only'
            7                = 'Multiracial'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value _PNEUMOC
            .                = 'Missing or Age Less Than 65'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at risk'
            2                = 'At risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _PRACE
            .                = 'Missing'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'White'
            2                = 'Black or African American'
            3                = 'Asian'
            4                = 'Native Hawaiian or other Pacific Islander'
            5                = 'American Indian or Alaskan Native'
            6                = 'Other race'
            7                = 'No preferred race'
            8                = 'Multiracial but preferred race not asked'
            77               = 'Do not know/Not sure'
            99               = 'Refused'
            ;
      Value _RF
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not At Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure Or Refused/Missing'
            ;
      Value _SMOKER
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Current smoker - now smokes every day'
            2                = 'Current smoker - now smokes some days'
            3                = 'Former smoker'
            4                = 'Never smoked'
            9                = 'Do not know/Refused/Missing'
            ;
      Value _STATE
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Alabama'
            2                = 'Alaska'
            4                = 'Arizona'
            5                = 'Arkansas'
            6                = 'California'
            8                = 'Colorado'
            9                = 'Connecticut'
            10               = 'Delaware'
            11               = 'District of Columbia'
            12               = 'Florida'
            13               = 'Georgia'
            15               = 'Hawaii'
            16               = 'Idaho'
            17               = 'Illinois'
            18               = 'Indiana'
            19               = 'Iowa'
            20               = 'Kansas'
            21               = 'Kentucky'
            22               = 'Louisiana'
            23               = 'Maine'
            24               = 'Maryland'
            25               = 'Massachusetts'
            26               = 'Michigan'
            27               = 'Minnesota'
            28               = 'Mississippi'
            29               = 'Missouri'
            30               = 'Montana'
            31               = 'Nebraska'
            32               = 'Nevada'
            33               = 'New Hampshire'
            34               = 'New Jersey'
            35               = 'New Mexico'
            36               = 'New York'
            37               = 'North Carolina'
            38               = 'North Dakota'
            39               = 'Ohio'
            40               = 'Oklahoma'
            41               = 'Oregon'
            42               = 'Pennsylvania'
            44               = 'Rhode Island'
            45               = 'South Carolina'
            46               = 'South Dakota'
            47               = 'Tennessee'
            48               = 'Texas'
            49               = 'Utah'
            50               = 'Vermont'
            51               = 'Virginia'
            53               = 'Washington'
            54               = 'West Virginia'
            55               = 'Wisconsin'
            56               = 'Wyoming'
            66               = 'Guam'
            72               = 'Puerto Rico'
            78               = 'Virgin Islands'
            ;
      Value _STDCNDM
            .                = 'Missing or Age greater than 64'
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Not at Risk'
            2                = 'At Risk'
            9                = 'Do not Know/Not Sure/Refused'
            ;
      Value _TOTIND
            .D               = 'DK/NS'
            .R               = 'REFUSED'
            1                = 'Had physical activity or exercise'
            2                = 'No physical activity or exercise in last 30 days'
            9                = 'Do not know/Refused/Missing'
            ;