 FORMAT   AGE            AGE.
          ALCDAY3        ALC3DAY.
          ARTHDIS2       ARTH2DIS.
          ARTHEDU        ARTHEDU.
          ARTHEXER       ARTHEXER.
          ARTHWGT        ARTHWGT.
          ARTTODAY       ARTTODAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASNOSLEP       ASNOSLEP.
          ASPUNSAF       ASPUNSAF.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMAGE       ASTHMAGE.
          ASTHMEDS       ASTHMEDS.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK        AVEDRNK.
          BIDINOW        BIDINOW.
          BIDISMK        BIDISMK.
          BINGEDRV       BINGEDRV.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BLOODCHO       BLOODCHO.
          BPHIGH3        BP3HIGH.
          BPMEDS         BPMEDS.
          BUYALCH        BUYALCH.
          CARROTS        CARROTS.
          CASTHDX        CASTHDX.
          CASTHNOW       CASTHNOW.
          CHILDREN       CHILDREN.
          CHKHEMO2       CHK2HEMO.
          CHOLCHK        CHOLCHK.
          CIGAR2         CIG2AR.
          CIGARNOW       CIGARNOW.
          CTELENUM       CTELENUM.
          CVDFVG01       CVD01FVG.
          CVDFAT02       CVD02FAT.
          CVDEXR03       CVD03EXR.
          CVDCRHD2       CVD2CRHD.
          CVDEXRS2       CVD2EXRS.
          CVDFATR2       CVD2FATR.
          CVDINFR2       CVD2INFR.
          CVDSTRK2       CVD2STRK.
          CVDASPRN       CVDASPRN.
          CVDFVEG        CVDFVEG.
          CVDREHAB       CVDREHAB.
          DENCLEAN       DENCLEAN.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABETES       DIABETES.
          DIABEYE        DIABEYE.
          DIABPILL       DIABPILL.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRADVICE       DRADVICE.
          DRETIME        DRETIME.
          DRNK2GE5       DRNK25GE.
          DRNKANY3       DRNK3ANY.
          DRNKBEER       DRNKBEER.
          DRNKLIQR       DRNKLIQR.
          DRNKLOC        DRNKLOC.
          DRNKWINE       DRNKWINE.
          DROCCDY_       DROCCDY_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FALL3MN        FALL3MN.
          FALLINJ        FALLINJ.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FEETSORE       FEETSORE.
          FEWCAL         FEWCAL.
          FIRESCP3       FIR3ESCP.
          FIREXIT        FIREXIT.
          FIRSTAID       FIRSTAID.
          FIRSTSMK       FIRSTSMK.
          FLUPRO2        FLU2PRO.
          FLUSHOT        FLUSHOT.
          FMONTH         FMONTH.
          FOLICACD       FOLICACD.
          FRPEXLOC       FRPEXLOC.
          FRPLANDO       FRPLANDO.
          FRUIT          FRUIT.
          FRUITJUI       FRUITJUI.
          GENHLTH        GENHLTH.
          GETCARE        GETCARE.
          GREENSAL       GREENSAL.
          HASYMP1        HA1SYMP.
          HASYMP2        HA2SYMP.
          HASYMP3        HA3SYMP.
          HASYMP4        HA4SYMP.
          HASYMP5        HA5SYMP.
          HASYMP6        HA6SYMP.
          HADHYST2       HAD2HYST.
          HADSIGM2       HAD2SIGM.
          HADMAM         HADMAM.
          HADPAP         HADPAP.
          HATTKAGE       HATTKAGE.
          HAVARTH2       HAV2ARTH.
          HEIGHT         HEIGHT.
          HISPANC2       HISP2ANC.
          HIVRISK2       HIV2RISK.
          HIVTST3        HIV3TST.
          HIVOPT1B       HIVOPT1B.
          HIVTF1A        HIVTF1A.
          HIVTF1B        HIVTF1B.
          HLTHPLAN       HLTHPLAN.
          HOUSESMK       HOUSESMK.
          HOWLONG        HOWLONG.
          HTIN2          HT2IN.
          HTM2           HT2M.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INDOORS        INDOORS.
          INSULIN        INSULIN.
          JOBACTIV       JOBACTIV.
          JOINTRT2       JOIN2TRT.
          JOINTSYM       JOINTSYM.
          LASTDEN2       LAST2DEN.
          LASTSIG2       LAST2SIG.
          LASTPAP        LASTPAP.
          LASTSMK        LASTSMK.
          LENGEXAM       LENGEXAM.
          LMTJOIN2       LMT2JOIN.
          LOSEWT         LOSEWT.
          LSTBLDS2       LST2BLDS.
          MAINTAIN       MAINTAIN.
          MARITAL        MARITAL.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MODCAT_        MODCAT_.
          MODPACT        MODPACT.
          MODPADAY       MODPADAY.
          MODPATIM       MODPATIM.
          MULTIVIT       MULTIVIT.
          NEXTMAM        NEXTMAM.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          NUMBURN        NUMBURN.
          ORACE2         O2RACE.
          PACAT_         PACAT_.
          PAIN30DY       PAIN30DY.
          PCSAIDS2       PCS2AIDS.
          PERSDOC2       PERS2DOC.
          PHYACT         PHYACT.
          PHYSHLTH       PHYSHLTH.
          PIPENOW        PIPENOW.
          PIPESMK        PIPESMK.
          PNEUVAC2       PNEU2VAC.
          POORHLTH       POORHLTH.
          POTATOES       POTATOES.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QSTLANG        QSTLANG.
          QUITSMOK       QUITSMOK.
          RACE2          RACE2FMT.
          RECOMMEN       RECOMMEN.
          REGSMK         REGSMK.
          RMVTEETH       RMVTEETH.
          RSNTST4        RSN4TST.
          SEX            SEX.
          SMKDETE3       SMK3DETE.
          SMKPUBLC       SMKPUBLC.
          SMKWORK        SMKWORK.
          SMOKE100       SMOK100_.
          SMOKEDAY       SMOKEDAY.
          STOPSMK2       STOP2SMK.
          STRSYMP1       STR1SYMP.
          STRSYMP2       STR2SYMP.
          STRSYMP3       STR3SYMP.
          STRSYMP4       STR4SYMP.
          STRSYMP5       STR5SYMP.
          STRSYMP6       STR6SYMP.
          STROKAGE       STROKAGE.
          SUNBURN        SUNBURN.
          TAKEVIT        TAKEVIT.
          TELSERV        TELSERV.
          TOLDHI2        TOLD2HI.
          HIVTSTD2       UNK6ADIG.
          USEEVER2       USE2EVER.
          USENOW2        USE2NOW.
          USEEQUIP       USEEQUIP.
          VACARE         VACARE.
          VEGETABL       VEGETABL.
          VETSTAT2       VET2STAT.
          VETERAN        VETERAN.
          VIGCAT_        VIGCAT_.
          VIGPACT        VIGPACT.
          VIGPADAY       VIGPADAY.
          VIGPATIM       VIGPATIM.
          VITAMINS       VITAMINS.
          WEIGHT         WEIGHT.
          WHRTST5        WHR5TST.
          WHYDONE3       WHY3DONE.
          WHYASPAN       WHYASPAN.
          WHYASPHA       WHYASPHA.
          WHYASPSK       WHYASPSK.
          WTDESIRE       WTDESIRE.
          WTKG           WTKG.
          _DENSTR2       _2DENSTR.
          _DRNKDY2       _2DRNKDY.
          _DRNKMO2       _2DRNKMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _RFBING2       _2RFBING.
          _RFDRHV2       _2RFDRHV.
          _RFDRMN2       _2RFDRMN.
          _RFDRWM2       _2RFDRWM.
          _RFSMOK2       _2RFSMOK.
          _SMOKER2       _2SMOKER.
          _BMI3          _3BMI.
          _RFBMI3        _3RFBMI.
          _RFHYPE4       _4RFHYPE.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AIDSTST       _AIDSTST.
          _ASTHMST       _ASTHMST.
          _BMI3CAT       _BMI3CAT.
          _CASTHMA       _CASTHMA.
          _CHLDCNT       _CHLDCNT.
          _CHOLCHK       _CHOLCHK.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _EDUCAG        _EDUCAG.
          _FLUSHOT       _FLUSHOT.
          _FRTINDX       _FRTINDX.
          _FV5SRV        _FV5SRV.
          _HIGHRSK       _HIGHRSK.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _LTASTHM       _LTASTHM.
          _MRACE         _MRACE.
          _PNEUMOC       _PNEUMOC.
          _PRACE         _PRACE.
          _RFCHOL        _RFCHOL.
          _RFHLTH        _RFHLTH.
          _RFNOPA        _RFNOPA.
          _RFPAMOD       _RFPAMOD.
          _RFPAREC       _RFPAREC.
          _RFPAVIG       _RFPAVIG.
          _STATE         _STATE.
          _STDCNDM       _STDCNDM.
          _TOTINDA       _TOTINDA.
        ;
