*****************************************************************************************
* FILE NAME:     SASOUT03.SAS                                                           *
* DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT  *
*                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF       *
* REFERENCES:                                                                           *
* INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES                   *
* FORMATS     FORMATS.sas7bcat      SAS FORMATS DATABASE                                *
* OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN       *
*                              <DATAIN> FILEREF                                         *
* UPDATED - 08/11/2004                                                                  *
*****************************************************************************************;
********************************
* Clear Output and Log Windows *
********************************;
DM OUTPUT 'clear' continue;
DM LOG    'clear' continue;
**********************************
* DEFINE SAS ENVIRONMENT OPTIONS *
**********************************;
OPTIONS PAGENO=1 NOFMTERR;
***************************************
* CLEAR EXISTING TITLES AND FOOTNOTES *
***************************************;
TITLE ;
FOOTNOTE ;
RUN ;
******************************************************************
* INSTRUCTIONS:                                                  *
* SPECIFY PATH OF WHERE ASCII DATAFILE IS STORED                 *
* SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED              *
* SPECIFY PATH OF WHERE SAS FORMAT LIBRARY IS STORED             *
* SPECIFY PATH OF WHERE THE FORMAT ASSIGNMET STATEMENT IS STORED *
******************************************************************;
 
*FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 950 ;
*****************************************************************************
* EXAMPLE:                                                                  *
*       FILENAME DATAIN 'C:\BRFSS\2003\CDBRFS03.ASC' LRECL = 950            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;
 
*LIBNAME DATAOUT V7 '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>'  ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME DATAOUT 'C:\'                                            *
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.sas7bdat             *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*       TO MAKE A VERSION 6 DATA SET, REMOVE THE   FROM THE                 *
*       LIBNAME LINE AND CHANGE THE V7 TO A V6                              *
*****************************************************************************;
 
*LIBNAME LIBRARY '<PATH OF STORED SAS FORMAT03.sas7bcat>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME LIBRARY 'C:\'                                            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;
 
*FILENAME FORMATIN '<PATH OF FORMAT ASSIGNMENT STATEMENT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          FILENAME FORMATIN 'C:\FORMATSTATEMENT.SAS'                       *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;
 
DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT
_STATE        1-2                     /* Record Identification */
_GEOSTR       3-4
_DENSTR2      5
PRECALL       6
REPNUM        7-11
REPDEPTH      12-13
FMONTH        14-15
IDATE         $16-23
IMONTH        $16-17
IDAY          $18-19
IYEAR         $20-23
INTVID        $24-26
DISPCODE      35-37
SEQNO         38-47
_PSU          38-47
NATTMPTS      48-49
NRECSEL       50-55
NRECSTR       56-64
CTELENUM      65
PVTRESID      66
NUMADULT      67-68
NUMMEN        69-70
NUMWOMEN      71-72
GENHLTH       73                      /* Section 1: Health Status */
PHYSHLTH      74-75
MENTHLTH      76-77
POORHLTH      78-79
HLTHPLAN      80                      /* Section 2: Health Care Access */
PERSDOC2      81
MEDCOST       82
EXERANY2      83                      /* Section 3: Exercise */
DIABETES      84                      /* Section 4: Diabetes */
BPHIGH3       85                      /* Section 5: Hypertension Awareness */
BPMEDS        86
BLOODCHO      87                      /* Section 6: Cholesterol Awareness */
CHOLCHK       88
TOLDHI2       89
FRUITJUI      90-92                   /* Section 7: Fruits and Vegetables */
FRUIT         93-95
GREENSAL      96-98
POTATOES      99-101
CARROTS       102-104
VEGETABL      105-107
LOSEWT        108                     /* Section 8: Weight Control */
MAINTAIN      109
FEWCAL        110
PHYACT        111
DRADVICE      112
ASTHMA2       113                     /* Section 9: Asthma */
ASTHNOW       114
FLUSHOT       115                     /* Section 10: Immunization */
PNEUVAC2      116
SMOKE100      117                     /* Section 11: Tobacco Use */
SMOKEDAY      118
STOPSMK2      119
ALCDAY3       120-122                 /* Section 12: Alcohol Consumption */
AVEDRNK       123-124
DRNK2GE5      125-126
SUNBURN       127                     /* Section 13: Excess Sun Exposure */
NUMBURN       128
AGE           129-130                 /* Section 14: Demographics */
HISPANC2      131
MRACE         $132-137
ORACE2        138
MARITAL       139
CHILDREN      140-141
EDUCA         142
EMPLOY        143
INCOME2       144-145
WEIGHT        146-148
WTDESIRE      149-151
HEIGHT        152-154
CTYCODE       155-157
NUMHHOL2      158
NUMPHON2      159
TELSERV       160
SEX           161
PREGNANT      162
PAIN30DY      163                     /* Section 15: Arthritis */
JOINTSYM      164
JOINTRT2      165
HAVARTH2      166
LMTJOIN2      167
ARTHDIS2      168
FALL3MN       169                     /* Section 16: Falls */
FALLINJ       170
QLACTLM2      171                     /* Section 17: Disability */
USEEQUIP      172
JOBACTIV      173                     /* Section 18: Physical Activity */
MODPACT       174
MODPADAY      175-176
MODPATIM      177-179
VIGPACT       180
VIGPADAY      181-182
VIGPATIM      183-185
VETERAN       186                     /* Section 19: Veterans Status */
VETSTAT2      187
VACARE        188
HIVTF1A       189                     /* Section 20: HIV/AIDS */
HIVTF1B       190
HIVOPT1B      191
HIVTST3       192
HIVTSTD2      193-198
RSNTST4       199-200
WHRTST5       201-202
HIVRISK2      203
PCSAIDS2      204
DIABAGE2      205-206                 /* Module 1: Diabetes */
INSULIN       207
DIABPILL      208
BLDSUGAR      209-211
FEETCHK2      212-214
FEETSORE      215
DOCTDIAB      216-217
CHKHEMO2      218-219
FEETCHK       220-221
EYEEXAM       222
DIABEYE       223
DIABEDU       224
LASTDEN2      225                     /* Module 2: Oral Health */
RMVTEETH      226
DENCLEAN      227
HADMAM        228                     /* Module 3: Women’s Health */
HOWLONG       229
NEXTMAM       230
WHYDONE3      231
PROFEXAM      232
LENGEXAM      233
HADPAP        234
LASTPAP       235
HADHYST2      236
FLUPRO2       237-238                 /* Module 4: Influenza */
SMKDETE3      239                     /* Module 5: Residential Fire */
FIRESCP3      240
FRPLANDO      241
FIREXIT       242
FRPEXLOC      243
ASTHMAGE      244-245                 /* Module 6: Adult Asthma History */
ASATTACK      246
ASERVIST      247-248
ASDRVIST      249-250
ASRCHKUP      251-252
ASACTLIM      253-255
ASYMPTOM      256
ASNOSLEP      257
ASTHMEDS      258
CASTHDX       259-260                 /* Module 7: Childhood Asthma */
CASTHNOW      261-262
HASYMP1       263                     /* Module 8: Heart Attack and Stroke */
HASYMP2       264
HASYMP3       265
HASYMP4       266
HASYMP5       267
HASYMP6       268
STRSYMP1      269
STRSYMP2      270
STRSYMP3      271
STRSYMP4      272
STRSYMP5      273
STRSYMP6      274
FIRSTAID      275
CVDFAT02      276                     /* Module 9: Cardiovascular Disease */
CVDFVG01      277
CVDEXR03      278
CVDFATR2      279
CVDFVEG       280
CVDEXRS2      281
CVDINFR2      282
CVDCRHD2      283
CVDSTRK2      284
HATTKAGE      285-286
STROKAGE      287-288
CVDREHAB      289
CVDASPRN      290
ASPUNSAF      291
WHYASPAN      292
WHYASPHA      293
WHYASPSK      294
VITAMINS      295                     /* Module 10: Folic Acid */
MULTIVIT      296
FOLICACD      297
TAKEVIT       298-300
RECOMMEN      301
FIRSTSMK      302-303                 /* Module 11: Tobacco Indicators */
REGSMK        304-305
LASTSMK       306-307
GETCARE       308
QUITSMOK      309
HOUSESMK      310
INDOORS       311
SMKPUBLC      312
SMKWORK       313
USEEVER2      314                     /* Module 12: Other Tobacco Products */
USENOW2       315
CIGAR2        316
CIGARNOW      317
PIPESMK       318
PIPENOW       319
BIDISMK       320
BIDINOW       321
ARTTODAY      322                     /* Module 13: Arthritis */
ARTHWGT       323
ARTHEXER      324
ARTHEDU       325
PSATEST       326                     /* Module 14: Prostate Cancer Screening */
PSATIME       327
DIGRECEX      328
DRETIME       329
PROSTATE      330
BLDSTOOL      331                     /* Module 15: Colorectal Cancer Screening */
LSTBLDS2      332
HADSIGM2      333
LASTSIG2      334
DRNKBEER      335-336                 /* Module 16: Binge Drinking */
DRNKWINE      337-338
DRNKLIQR      339-340
DRNKLOC       341
BUYALCH       342
BINGEDRV      343
QSTVER        595
QSTLANG       596-597
_STSTR        700-704                 /* Weighting And Stratification Variables */
_STRWT        705-714
_RAW          715-724
_WT2          725-734
_POSTSTR      735-744
_FINALWT      745-754
_REGION       755-756
_AGEG_        757-758
_SEXG_        759
_RACEG3_      760
_IMPAGE       761-762
_IMPNPH       763
_TOTINDA      768                     /* Section 3: Calculated Variables */
_RFHYPE4      769                     /* Section 5: Calculated Variables */
_CHOLCHK      770                     /* Section 6: Calculated Variables */
_RFCHOL       771
FTJUDAY_      772-774                 /* Section 7: Calculated Variables */
FRUTDAY_      775-777
GNSLDAY_      778-780
POTADAY_      781-783
CRTSDAY_      784-786
VEGEDAY_      787-789
_FRTSERV      790-794
_FRTINDX      795
_LTASTHM      796                     /* Section 9: Calculated Variables */
_CASTHMA      797
_ASTHMST      798
_FLUSHOT      799                     /* Section 10: Calculated Variables */
_PNEUMOC      800
_SMOKER2      801                     /* Section 11: Calculated Variables */
_RFSMOK2      802
DROCCDY_      803-805                 /* Section 12: Calculated Variables */
DRNKANY3      806
_RFBING2      807
_DRNKDY2      808-811
_DRNKMO2      812-815
_RFDRHV2      816
_RFDRMN2      817
_RFDRWM2      818
MRACEORG      $819-824                /* Section 14: Calculated Race Variables */
MRACEASC      $825-830
_PRACE        831-832
_MRACE        833-834
RACE2         835
_RACEG2       836
_RACEGR2      837
_CNRACE       838
_CNRACEC      839
_AGEG5YR      840-841
_AGE65YR      842
HTIN2         843-845
HTM2          846-848
WTKG          849-853
_BMI3         854-857
_BMI3CAT      858
_RFBMI3       859
_MODPAMN      860-862                 /* Section 18: Calculated Variables */
_VIGPAMN      863-865
MODCAT_       866
VIGCAT_       867
PACAT_        868
_RFPAMOD      869
_RFPAVIG      870
_RFPAREC      871
_RFNOPA       872
_AIDSTST      873                     /* Section 20: Calculated Variables */
_HIGHRSK      874
_STDCNDM      875
_RFHLTH       879                     /* Calculated Variable */
_FV5SRV       925
_CHLDCNT      926
_EDUCAG       927
_INCOMG       928
ENDOFREC
;
*****************************************************************
* TO INCLUDE THE FORMAT ASSIGNEMT STATEMENT REMOVE THE ASTERISK *
* FROM THE BEGINNING OF THE FOLLOWING LINE                      *
*****************************************************************;
* %INCLUDE FORMATIN ;
*************************************************
* THIS SECTION CREATES LABELS FOR THE VARIABLES *
*************************************************;
Label
AGE = 'REPORTED AGE IN YEARS'
ALCDAY3 = 'DRINK DAYS PER TIME (WK OR MO)'
ARTHDIS2 = 'ARTHRITIS AFFECTS YOUR PAID WORK'
ARTHEDU = 'EVER TAKEN CLASS IN MANAGING ARTHRITIS OR JOINT SYMPTOMS'
ARTHEXER = 'DR. SUGGEST USE OF PHYSICAL ACTIVITY OR EXERCISE FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTHWGT = 'DR. SUGGEST LOSE WEIGHT FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTTODAY = 'WHAT CAN YOU DO BECAUSE OF ARTHRITIS OR JOINT SYMPTOMS'
ASACTLIM = 'DAYS MISSED WORK DUE TO ASTHMA'
ASATTACK = 'ASTHMA ATTACK LAST 12 MOS'
ASDRVIST = 'DOC VISITS LAST 12 MOS FOR ASTHMA'
ASERVIST = 'ER VISITS LAST 12 MOS FOR ASTHMA'
ASNOSLEP = 'SLEEP PROBS FROM ASTHMA LAST 30 DAYS'
ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
ASRCHKUP = 'ROUTINE CHECKUPS LAST 12 MOS FOR ASTHMA'
ASTHMA2 = 'EVER HAD ASTHMA'
ASTHMAGE = 'AGE WHEN DOC SAID HAD ASTHMA'
ASTHMEDS = 'ASTHMA MED USAGE LAST 30 DAYS'
ASTHNOW = 'HAVE ASTHMA NOW'
ASYMPTOM = 'SYMPTOMS OF ASTHMA LAST 30 DAYS'
AVEDRNK = 'AVERAGE NUMBER OF DRINKS PER OCCASION'
BIDINOW = 'NOW SMOKE INDIAN CIGARETTES'
BIDISMK = 'EVER SMOKED INDIAN CIGARETTE'
BINGEDRV = 'DRIVE A MOTOR VEHICLE AFTER BINGE DRINKING'
BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
BPHIGH3 = 'EVER TOLD BLOOD PRESSURE HIGH'
BPMEDS = 'MEDS FOR BLOOD PRESSURE'
BUYALCH = 'HOW DID YOU GET BINGE DRINKING ALCOHOL'
CARROTS = 'HOW OFTEN DO YOU EAT CARROTS'
CASTHDX = 'CHILDREN DIAGNOSED W/ASTHMA'
CASTHNOW = '# CHILDREN STILL HAVE ASTHMA'
CHILDREN = '# CHILDREN UNDER 18 IN HOUSEHOLD'
CHKHEMO2 = 'CHECKED FOR HEMOGLOBIN A ONE C'
CHOLCHK = 'HOW LONG SINCE CHOLESTEROL CHECKED'
CIGAR2 = 'EVER SMOKED CIGAR'
CIGARNOW = 'CURRENTLY SMOKE CIGARS'
CRTSDAY_ = 'CARROT SERVINGS PER DAY'
CTELENUM = 'CORRECT NUMBER?'
CTYCODE = 'COUNTY CODE'
CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
CVDCRHD2 = 'EVER TOLD HAD CORONARY HEART DISEASE'
CVDEXR03 = 'RED HRT ATTK RISK: PHYS ACTIVITY'
CVDEXRS2 = 'DOC SAID EXERCISE LAST 12 MOS'
CVDFAT02 = 'RED HRT ATTK RISK: EAT FEWER FATTY FDS'
CVDFATR2 = 'DOC SAID EAT LESS FAT LAST 12 MOS'
CVDFVEG = 'DOC SAID EAT FRT/VEG LAST 12 MOS*/'
CVDFVG01 = 'RED HRT ATTK RISK: EAT FRTS/VEG'
CVDINFR2 = 'EVER TOLD HAD MYOCARDIAL INFARCTION'
CVDREHAB = 'REHAB AFTER HRT ATTK'
CVDSTRK2 = 'EVER TOLD HAD STROKE'
DENCLEAN = 'HOW LONG SINCE LAST TEETH CLEANING'
DIABAGE2 = 'AGE TOLD HAVE DIABETES'
DIABEDU = 'EVER TAKEN CLASS TO MANAGE DIABETES'
DIABETES = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
DIABEYE = 'DIABETES AFFECT EYES OR HAD RETINOPATHY'
DIABPILL = 'NOW TAKING DIABETES PILLS'
DIGRECEX = 'EVER HAD RECTAL EXAM'
DISPCODE = 'DISPOSITION OF INTERVIEW'
DOCTDIAB = 'TIMES SEEN HEALTH PROF FOR DIABETES'
DRADVICE = 'PROFESSIONAL ADVICE ABOUT WEIGHT'
DRETIME = 'TIME SINCE RECTAL EXAM'
DRNK2GE5 = 'FIVE OR MORE DRINKS ON AN OCCASION'
DRNKANY3 = 'CONSUMED ALCOHOL IN PAST 30 DAYS'
DRNKBEER = 'HOW MANY BEERS CONSUMED WHEN BINGE DRINKING'
DRNKLIQR = 'HOW MANY DRINKS OF LIQUOR CONSUMED WHEN BINGE DRINKING'
DRNKLOC = 'WHERE WERE YOU WHEN YOU BINGE DRANK'
DRNKWINE = 'HOW MANY GLASSES OF WINE CONSUMED WHEN BINGE DRINKING'
DROCCDY_ = 'DRINK-OCCASIONS-PER-DAY'
EDUCA = 'EDUCATION LEVEL'
EMPLOY = 'EMPLOYMENT STATUS'
ENDOFREC = 'END OF RECORD MARKER'
EXERANY2 = 'EXERCISE LAST 30 DAYS'
EYEEXAM = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
FALL3MN = 'HAD A FALL IN PAST THREE MONTHS'
FALLINJ = 'INJURED IN FALL IN PAST THREE MONTHS'
FEETCHK = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
FEETCHK2 = 'HOW OFTEN CHECK FEET FOR SORES'
FEETSORE = 'SORES ON FEET MORE THAN 4 WEEKS TO HEAL'
FEWCAL = 'FEWER CALORIES AND/OR LESS FAT'
FIRESCP3 = 'HAVE HOME FIRE ESCAPE PLAN'
FIREXIT = 'FIRE ESCAPE PLAN FOR EVERY ROOM'
FIRSTAID = 'STROKE SYMPT: 1ST RESP FOR H ATTK VICTIM'
FIRSTSMK = 'AGE SMOKED FIRST CIGARETTE'
FLUPRO2 = 'PLACE GOT LAST FLU SHOT'
FLUSHOT = 'HAD FLU SHOT IN PAST 12 MONTHS'
FMONTH = 'MONTH NAME OF SOURCE FILE'
FOLICACD = 'ANY VITAMINS CONTAIN FOLIC ACID'
FRPEXLOC = 'FIRE ESCAPE PLAN OUTSIDE MEETING PLACE'
FRPLANDO = 'HOW OFTEN PRACTICE FIRE ESCAPE PLAN'
FRUIT = 'HOW OFTEN DO YOU EAT FRUIT'
FRUITJUI = 'HOW OFTEN DO YOU DRINK FRUIT JUICES'
FRUTDAY_ = 'FRUIT SERVINGS PER DAY'
FTJUDAY_ = 'FRUIT JUICE SERVINGS PER DAY'
GENHLTH = 'GENERAL HEALTH'
GETCARE = 'MEDICAL CARE IN LAST 12 MOS'
GNSLDAY_ = 'GREEN SALAD SERVINGS PER DAY'
GREENSAL = 'HOW OFTEN DO YOU EAT GREEN SALAD'
HADHYST2 = 'EVER HAD A HYSTERECTOMY'
HADMAM = 'HAVE YOU EVER HAD A MAMMOGRAM'
HADPAP = 'EVER HAD A PAP SMEAR TEST'
HADSIGM2 = 'EVER HAD A SIGMOIDOSCOPY/COLONOSCOPY'
HASYMP1 = 'HRT ATTK SYMPTOM: JAW NECK BACK PAIN'
HASYMP2 = 'HRT ATTK SYMPTOM: LIGHTHEADED, FAINT'
HASYMP3 = 'HRT ATTK SYMPTOM: CHEST PAIN'
HASYMP4 = 'HRT ATTK SYMPTOM: LOSE VISION'
HASYMP5 = 'HRT ATTK SYMPTOM: ARM SHOULDER PAIN'
HASYMP6 = 'HRT ATTK SYMPTOM: SHORTNESS OF BREATH'
HATTKAGE = 'AGE AT 1ST HRT ATTK'
HAVARTH2 = 'TOLD HAVE ARTHRITIS BY DOCTOR'
HEIGHT = 'REPORTED HEIGHT IN FEET AND INCHES'
HISPANC2 = 'HISPANIC ORIGIN'
HIVOPT1B = 'HIV TESTING IMPORTANT'
HIVRISK2 = 'ANY HIGH RISK SITUATIONS APPLY'
HIVTF1A = 'HIV PREVENTION BETW PREG MOTHER/INFANT'
HIVTF1B = 'TRT FOR HIV PERSON TO LIVE LONGER'
HIVTST3 = 'EVER TSTD FOR HIV OTHR THAN BLOOD DONATN'
HIVTSTD2 = 'MO/YR OF HIV TEST'
HLTHPLAN = 'HAVE HEALTH CARE COVERAGE'
HOUSESMK = 'SMOKING ALLOWED AT HOME'
HOWLONG = 'HOW LONG SINCE LAST MAMMOGRAM'
HTIN2 = 'REPORTED HEIGHT IN INCHES.'
HTM2 = 'REPORTED HEIGHT IN METERS.'
IDATE = 'DATE OF INTERVIEW'
IDAY = 'DAY OF INTERVIEW'
IMONTH = 'MONTH OF INTERVIEW'
INCOME2 = 'INCOME LEVEL'
INDOORS = 'NORMALLY WORK INDOORS?'
INSULIN = 'NOW TAKING INSULIN'
INTVID = 'INTERVIEWER ID'
IYEAR = 'YEAR OF INTERVIEW'
JOBACTIV = 'PHYSICAL ACTIVITY ON JOB'
JOINTRT2 = 'SEEN DOC FOR JOINT SYMPTOMS'
JOINTSYM = 'JOINT SYMPTOMS 1ST BEGAN 3 MOS AGO?'
LASTDEN2 = 'HOW LONG SINCE LAST DENTIST VISIT'
LASTPAP = 'WHEN WAS LAST PAP SMEAR'
LASTSIG2 = 'LAST TIME HAD SIGMOIDOSCOPY/COLONOSCOPY'
LASTSMK = 'TIME SINCE LAST SMOKED REGULARLY'
LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
LMTJOIN2 = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
LOSEWT = 'TRYING TO LOSE WEIGHT'
LSTBLDS2 = 'HOW LONG SINCE LAST HOME BLOOD STOOL TST'
MAINTAIN = 'TRYING TO MAINTAIN CURRENT WEIGHT'
MARITAL = 'MARITAL STATUS'
MEDCOST = 'COULD NOT SEE DR. BECAUSE OF COST'
MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
MODCAT_ = 'MODERATE PHYSICAL ACTIVITY CATEGORIES'
MODPACT = 'MODERATE PHYSICAL ACTIVITY'
MODPADAY = 'DAYS PER WEEK OF MOD. PHYS. ACT.'
MODPATIM = 'MINS. PER DAY OF MOD. PHYS. ACT.'
MRACE = 'ORIGINAL REPORTED RACE'
MRACEASC = 'REPORTED MRACE VARIABLE WITH TRAILING 7,8,9’S REMOVED, IN ASCENDING ORDER.'
MRACEORG = 'REPORTED MRACE VARIABLE WITH TRAILING 7,8,9’S REMOVED.'
MULTIVIT = 'ANY OF VITS/SUPPLEMENTS A MULTIVITAMIN'
NATTMPTS = 'NUMBER OF ATTEMPTS'
NEXTMAM = 'TIME BETWEEN LAST TWO MAMMOGRAMS'
NRECSEL = 'NUMBER OF SAMPLE RECORDS FOR STRATUM'
NRECSTR = 'TOTAL PH. NOS. IN STRATUM FROM SAMPLE'
NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
NUMBURN = 'NUMBER OF SUNBURNS IN PAST 12 MONTHS'
NUMHHOL2 = 'MORE THAN ONE TELPHONE NUMBER IN HH'
NUMMEN = 'NUMBER OF ADULT MALES IN HOUSEHOLD'
NUMPHON2 = 'NUMBER OF RESIDENTIAL PHONE NUMBERS'
NUMWOMEN = 'NUMBER OF ADULT FEMALES IN HOUSEHOLD'
ORACE2 = 'PREFERRED RACE'
PACAT_ = 'OVERALL PHYSICAL ACTIVITY CATEGORIES'
PAIN30DY = 'HAD JOINT PAIN, SWELLING LST 30 DAYS'
PCSAIDS2 = 'TOLD BY DOC ABOUT STD PREV BY CONDOMS'
PERSDOC2 = 'HAVE PERSONAL HEALTH CARE PROVIDER'
PHYACT = 'INCREASED PHYSICAL ACTIVITY'
PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
PIPENOW = 'CURRENTLY SMOKE PIPE'
PIPESMK = 'EVER SMOKE PIPE'
PNEUVAC2 = 'EVER HAD PNEUMONIA VACCINATION'
POORHLTH = 'DAYS HEALTH IMPAIRED LAST MO'
POTADAY_ = 'POTATO SERVINGS PER DAY'
POTATOES = 'HOW OFTEN DO YOU EAT POTATOES'
PRECALL = 'PRECALLING STATUS'
PREGNANT = 'ARE YOU NOW PREGNANT'
PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
PROSTATE = 'EVER TOLD HAVE PROSTATE CANCER'
PSATEST = 'EVER HAD PSA'
PSATIME = 'TIME SINCE PSA'
PVTRESID = 'PRIVATE RESIDENCE?'
QLACTLM2 = 'ACTIVITIES LIMITED BY HEALTH PROBLEM'
QSTLANG = 'QUESTIONNAIRE LANGUAGE'
QSTVER = 'QUESTIONNAIRE VERSION'
QUITSMOK = 'DOCTOR ADVISED YOU TO QUIT SMOKING'
RACE2 = 'RACE/ETHNICITY CATEGORIES.'
RECOMMEN = 'REASONS HLTH EXPERTS RECMND FOLIC ACID'
REGSMK = 'AGE BEGAN SMOKING REGULARLY'
REPDEPTH = 'REPLICATE DEPTH'
REPNUM = 'REPLICATE NUMBER'
RMVTEETH = 'NUMBER OF PERMANENT TEETH REMOVED'
RSNTST4 = 'MAIN REASON FOR HIV TEST'
SEQNO = 'ANNUAL SEQUENCE NUMBER'
SEX = 'SEX'
SMKDETE3 = 'LAST TIME SMOKE ALARMS TESTED'
SMKPUBLC = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
SMKWORK = 'SMOKING POLICY AT WORK FOR WORK AREAS'
SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
SMOKEDAY = 'FREQUENCY OF DAYS NOW SMOKING'
STOPSMK2 = 'QUIT SMOKING A DAY OR MORE IN PAST YEAR'
STROKAGE = 'AGE AT 1ST STROKE'
STRSYMP1 = 'STROKE SYMPT: SUDDEN CONFUSION'
STRSYMP2 = 'STROKE SYMPT: NUMBNESS ON ONE SIDE BODY'
STRSYMP3 = 'STROKE SYMPT: SUDDEN VISION LOSS'
STRSYMP4 = 'STROKE SYMPT: SUDDEN CHEST PAIN'
STRSYMP5 = 'STROKE SYMPT: SUDDEN DIZZINESS'
STRSYMP6 = 'STROKE SYMPT: SEVERE UNXPLND HEADACHE'
SUNBURN = 'HAD A SUNBRUN IN PAST TWELVE MONTHS'
TAKEVIT = 'HOW OFTEN TAKE VITAMIN OR SUPPLEMENT'
TELSERV = 'HOUSEHOLD BEEN WITHOUT PHONE SERVICE IN LAST 12 MONTHS'
TOLDHI2 = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
USEEQUIP = 'REQ SPECIAL EQUIPMENT FOR HLTH PROBLEM'
USEEVER2 = 'EVER USED SMOKELESS TOBACCO PRODUCTS'
USENOW2 = 'CURRENTLY USE SMOKELESS TOBACCO PRODUCTS'
VACARE = 'RECEIVED HEALTH CARE FROM VA FACILITY'
VEGEDAY_ = 'VEGETABLE SERVINGS PER DAY'
VEGETABL = 'SERVINGS OF VEGETABLES'
VETERAN = 'ARE YOU A VETERAN'
VETSTAT2 = 'CURRENT VETERAN STATUS'
VIGCAT_ = 'VIGOROUS PHYSICAL ACTIVITY CATEGORIES'
VIGPACT = 'VIGOROUS PHYSICAL ACTIVITY'
VIGPADAY = 'DAYS PER WEEK OF VIG. PHYS. ACT.'
VIGPATIM = 'MINS. PER DAY OF VIG. PHYS. ACT.'
VITAMINS = 'CURRENTLY TAKE VIT PILLS OR SUPPLEMENTS'
WEIGHT = 'REPORTED WEIGHT IN POUNDS'
WHRTST5 = 'WHERE TESTED FOR HIV'
WHYASPAN = 'TAKE ASPIRIN TO RELIEVE PAIN'
WHYASPHA = 'TAKE ASPIRIN TO REDUCE HEART ATTACK'
WHYASPSK = 'TAKE ASPIRIN TO REDUCE STROKE'
WHYDONE3 = 'WAS MAMMOGRAM(S) DONE TO CHECK PROBLEM'
WTDESIRE = 'DESIRED WEIGHT'
WTKG = 'REPORTED WEIGHT IN KILOGRAMS.'
_AGE65YR = 'TWO LEVEL AGE CATEGORY.'
_AGEG5YR = 'FOURTEEN LEVEL AGE CATEGORY.'
_AGEG_ = 'AGE GROUPS USED IN POST-STRATIFICATION'
_AIDSTST = 'EVER BEEN TESTED FOR HIV RISK FACTOR.'
_ASTHMST = 'COMPUTED ASTHMA STATUS'
_BMI3 = 'BODY MASS INDEX.'
_BMI3CAT = 'BODY MASS INDEX- THREE LEVELS CATEGORY.'
_CASTHMA = 'RISK FACTOR FOR CURRENT ASTHMA PREVALENCE'
_CHLDCNT = 'NUMBER OF CHILDREN IN THE HOUSEHOLD'
_CHOLCHK = 'CHOLESTEROL CHECKED RISK FACTOR'
_CNRACE = 'NUMBER OF CENSUS RACE CATEGORIES CHOSEN.'
_CNRACEC = 'NUMBER OF CENSUS RACE CATEGORIES CHOSEN, COLLAPSED.'
_DENSTR2 = 'DENSITY STRATUM'
_DRNKDY2 = 'NUMBER OF ALCOHOL DRINKS PER DAY'
_DRNKMO2 = 'NUMBER OF ALCOHOL DRINKS PER MONTH'
_EDUCAG = 'LEVEL OF EDUCATION COMPLETED'
_FINALWT = 'PRODUCT OF _POSTSTR & _WT2'
_FLUSHOT = 'RISK FACTOR FOR RESPONDENTS AGED 65+ THAT HAD A FLU SHOT IN THE PAST 12 MONTHS.'
_FRTINDX = 'FRUIT & VEGETABLE SERVINGS INDEX'
_FRTSERV = 'FRUIT & VEGETABLE SERVINGS PER DAY'
_FV5SRV = 'CONSUMED FIVE OR MORE SERVINGS OF FRUITS OR VEGETABLES PER DAY'
_GEOSTR = 'STRATUM CODE'
_HIGHRSK = 'EVER PARTICIPATED IN HIGH-RISK BEHAVIOR RISK FACTOR.'
_IMPAGE = 'IMPUTED AGE USED IN POST-STRATIFICATION'
_IMPNPH = 'IMPUTED NUMBER OF PHONES USED IN POST-STRATIFICATION'
_INCOMG = 'INCOME CATEGORIES'
_LTASTHM = 'RISK FACTOR FOR LIFETIME ASTHMA PREVALENCE'
_MODPAMN = 'MINUTES OF MODERATE PHYSICAL ACITIVITY'
_MRACE = 'MULTIRACIAL RACE CATEGORIZATION.'
_PNEUMOC = 'RISK FACTOR FOR RESPONDENTS AGED 65+ THAT HAVE EVER HAD A PNEUMONIA SHOT.'
_POSTSTR = 'AGE, RACE, SEX WT ST POP'
_PRACE = 'PREFERRED RACE CATEGORY.'
_PSU = 'PRIMARY SAMPLING UNIT'
_RACEG2 = 'WHITE/HISPANIC RACE GROUP'
_RACEG3_ = 'RACE CATEGORIES USED IN POST-STRATIFICATION'
_RACEGR2 = '5 LEVEL RACE/ETHNICITY CATEGORY.'
_RAW = '# ADULTS/# PHONES'
_REGION = 'REGION'
_RFBING2 = 'BINGE DRINKING RISK FACTOR.'
_RFBMI3 = 'RISK FACTOR FOR OVERWEIGHT OR OBESE.'
_RFCHOL = 'HIGH CHOLESTEROL RISK FACTOR'
_RFDRHV2 = 'HEAVY DRINKING RISK'
_RFDRMN2 = 'HEAVY DRINKING AMONG MEN RISK FACTOR.'
_RFDRWM2 = 'HEAVY DRINKING AMONG FEMALES RISK FACTOR.'
_RFHLTH = 'HEALTH STATUS'
_RFHYPE4 = 'HIGH BLOOD PRESSURE RISK FACTOR'
_RFNOPA = 'NO PHYSICAL ACTIVITY OR EXERCISE RISK FACTOR'
_RFPAMOD = 'MODERATE PHYSICAL ACTIVITY RISK FACTOR'
_RFPAREC = 'RECOMMENDED PHYSICAL ACTIVITY RISK FACTOR'
_RFPAVIG = 'VIGOROUS PHYSICAL ACTIVITY RISK FACTOR'
_RFSMOK2 = 'CURRENT SMOKING STATUS RISK FACTOR.'
_SEXG_ = 'SEX CATEGORIES USED IN POST-STRAT'
_SMOKER2 = 'FOUR LEVEL SMOKER STATUS.'
_STATE = 'STATE FIPS CODE'
_STDCNDM = 'BEEN COUNSELED WITHIN THE PAST 12 MONTHS ON PREVENTION OF SEXUALLY TRANSMITTED DISEASES THROUGH CONDOM USE.'
_STRWT = 'STRATUM WEIGHT'
_STSTR = 'CONCATENATED STRATIFICATION VARIABLES'
_TOTINDA = 'NO LEISURE TIME PHYSICAL ACTIVITY OR EXERCISE PAST 30 DAYS'
_VIGPAMN = 'MINUTES OF VIGOROUS PHYSICAL ACTIVITY'
_WT2 = 'DESIGN WEIGHT'
;
RUN;
