 FORMAT   ADEAT1         AD1EAT.
          ADANXEV        ADANXEV.
          ADDEPEV        ADDEPEV.
          ADDOWN         ADDOWN.
          ADENERGY       ADENERGY.
          ADFAIL         ADFAIL.
          ADMOVE         ADMOVE.
          ADPLEASR       ADPLEASR.
          ADSLEEP        ADSLEEP.
          ADTHINK        ADTHINK.
          AGE            AGE.
          ALCDAY4        ALC4DAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASINHALR       ASINHALR.
          ASNOSLEP       ASNOSLEP.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMED3       ASTH3MED.
          ASTHMAGE       ASTHMAGE.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK2       AVE2DRNK.
          BINGEDRV       BINGEDRV.
          BINGEPAY       BINGEPAY.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          CASTHDX2       CASTH2DX.
          CASTHNO2       CASTH2NO.
          CELLFON        CELLFON.
          CHECKUP1       CHECK1UP.
          CHILDAGE       CHILDAGE.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CTELENUM       CTELENUM.
          CVDSTRK3       CVD3STRK.
          CVDCRHD4       CVD4CRHD.
          CVDINFR4       CVD4INFR.
          DENCLEAN       DENCLEAN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRETIME        DRETIME.
          DRNKBER1       DRNK1BER.
          DRNKLOC1       DRNK1LOC.
          DRNKWIN1       DRNK1WIN.
          DRNKDRI2       DRNK2DRI.
          DRNK3GE5       DRNK35GE.
          DRNKANY4       DRNK4ANY.
          DRNKLIQR       DRNKLIQR.
          DRNKPMIX       DRNKPMIX.
          DROCDY2_       DROCDY2_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EMTSUPRT       EMTSUPRT.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FALLINJ2       FALL2INJ.
          FALL3MN2       FALL32MN.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FLUSPRY2       FLU2SPRY.
          FLUSHOT3       FLU3SHOT.
          FLUSHTMY       FLUSHTMY.
          FLUSPRMY       FLUSPRMY.
          FMONTH         FMONTH.
          GENHLTH        GENHLTH.
          GP3DYFD1       GP3DY1FD.
          GP3DYPRS       GP3DYPRS.
          GP3DYWTR       GP3DYWTR.
          GPWELPR3       GP3WELPR.
          GPBATRAD       GPBATRAD.
          GPEMRCM1       GPEMR1CM.
          GPEMRIN1       GPEMR1IN.
          GPFLSLIT       GPFLSLIT.
          GPMNDEVC       GPMNDEVC.
          GPNOTEV1       GPNOT1EV.
          GPVACPL1       GPVAC1PL.
          HADSGCO1       HAD1SGCO.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HEIGHT3        HEIGHT.
          HISPANC2       HISP2ANC.
          HIVRISK2       HIV2RISK.
          HIVTST5        HIV5TST.
          HIVRDTST       HIVRDTST.
          HLTHPLAN       HLTHPLAN.
          HOUSSMK1       HOUS1SMK.
          HOWLONG        HOWLONG.
          HPVADVC1       HPV1ADVC.
          HPVCHVC1       HPV1CHVC.
          HPVADSHT       HPVADSHT.
          HPVADVC        HPVADVC.
          HPVCHSHT       HPVCHSHT.
          HPVCHVC        HPVCHVC.
          HRCHRNIL       HRCHRNIL.
          HRDIRCAR       HRDIRCAR.
          HRSTLHAV       HRSTLHAV.
          HRVOLNTR       HRVOLNTR.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INSULIN        INSULIN.
          LASTPAP2       LAST2PAP.
          LASTDEN3       LAST3DEN.
          LASTSIG3       LAST3SIG.
          LENGEXAM       LENGEXAM.
          LSATISFY       LSATISFY.
          LSTBLDS3       LST3BLDS.
          MARITAL        MARITAL.
          MAXDRNKS       MAXDRNKS.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MSCODE         MSCODE.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          _CASTHMA       NY.
          ORACE2         O2RACE.
          PAINACT2       PAIN2ACT.
          PDIABTST       PDIABTST.
          PERSDOC2       PERS2DOC.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC3       PNEU3VAC.
          POORHLTH       POORHLTH.
          PRECALL        PRECALL.
          PREDIAB        PREDIAB.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RCHISLAT       RCHISLAT.
          RCSRLTN2       RCS2RLTN.
          RCSBRACE       RCSBRACE.
          RCSGENDR       RCSGENDR.
          RMVTETH3       RMV3TETH.
          RRATWRK2       RR2ATWRK.
          RRCOGNT2       RR2COGNT.
          RREMTSM2       RR2EMTSM.
          RRPHYSM2       RR2PHYSM.
          RRHCARE3       RR3HCARE.
          RRCLASS2       RRCLASS.
          SEATBELT       SEATBELT.
          SEX            SEX.
          SHSALOWB       SHSALOWB.
          SHSALOWR       SHSALOWR.
          SHSALOWW       SHSALOWW.
          SHSINHOM       SHSINHOM.
          SHSINWRK       SHSINWRK.
          SMOKE100       SMOK100_.
          SMOKDAY2       SMOK2DAY.
          STOPSMK2       STOP2SMK.
          TELSERV2       TEL2SERV.
          HIVTSTD2       UNK6ADIG.
          USEEVER3       USE3EVER.
          USENOW3        USE3NOW.
          USEEQUIP       USEEQUIP.
          USOTHNW1       USOTH1NW.
          VACARE1        VA1CARE.
          VAIRQAFG       VAIRQAFG.
          VETERAN1       VET1ERAN.
          VETSTAT2       VET2STAT.
          VICTRCT2       VI2CTRCT.
          VIDFCLT2       VI2DFCLT.
          VIEYEXM2       VI2EYEXM.
          VIGLUMA2       VI2GLUMA.
          VIINSUR2       VI2INSUR.
          VINOCRE2       VI2NOCRE.
          VIPRFVS2       VI2PRFVS.
          VIREDIF2       VI2REDIF.
          VIMACDG2       VIMAC2DG.
          WEIGHT2        WEIGHT.
          WHRTST8        WHR7TST.
          WTKG2          WT2KG.
          WTCHGINT       WTCHGINT.
          WTYRAGO        WTYRAGO.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _PNEUMO2       _2PNEUMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _RFSEAT2       _2RFSEAT.
          _RFSIGM2       _2RFSIGM.
          _RFPAP32       _32RFPAP.
          _DRNKDY3       _3DRNKDY.
          _DRNKMO3       _3DRNKMO.
          _FLSHOT3       _3FLSHOT.
          _RFDRHV3       _3RFDRHV.
          _RFDRMN3       _3RFDRMN.
          _RFDRWM3       _3RFDRWM.
          _RFSEAT3       _3RFSEAT.
          _RFSMOK3       _3RFSMOK.
          _SMOKER3       _3SMOKER.
          _BMI4          _4BMI.
          _RFBING4       _4RFBING.
          _RFBMI4        _4RFBMI.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ALTETH2       _AL2TETH.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CAGEG_        _CAGEG_.
          _CHLDCNT       _CHLDCNT.
          _CIMPAGE       _CIMPAGE.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _CRACE         _CRACE.
          _CRACEG_       _CRACEG_.
          _CSEXG_        _CSEXG_.
          _DENVST1       _DEN1VST.
          _EDUCAG        _EDUCAG.
          _EXTETH2       _EX2TETH.
          _HCVU65        _HCV65U.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _MAM502Y       _MAM502Y.
          _MRACE         _MRACE.
          _PRACE         _PRACE.
          _RACEG3_       _RACEG3_.
          _RACE_G        _RACE_G.
          _RFBLDS2       _RF2BLDS.
          _RFHLTH        _RFHLTH.
          _RFMAM2Y       _RFMAM2Y.
          _RFPSA2Y       _RFPSA2Y.
          _SEXG_         _SEXG_.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
