*****************************************************************************************
* FILE NAME:     DUALOUT08V1.SAS                                                        *
* DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT  *
*                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF       *
* REFERENCES:                                                                           *
* INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES                   *
* FORMATS     FORMATS.SAS7BCAT      SAS FORMATS DATABASE                                *
* OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN       *
*                              <DATAIN> FILEREF                                         *
* UPDATED - 04/29/2009                                                                  *
*****************************************************************************************;
********************************
* Clear Output and Log Windows *
********************************;
DM OUTPUT 'clear' continue;
DM LOG    'clear' continue;
**********************************
* DEFINE SAS ENVIRONMENT OPTIONS *
**********************************;
OPTIONS PAGENO=1 NOFMTERR;
***************************************
* CLEAR EXISTING TITLES AND FOOTNOTES *
***************************************;
TITLE ;
FOOTNOTE ;
RUN ;
******************************************************************
* INSTRUCTIONS:                                                  *
* SPECIFY PATH OF WHERE ASCII DATAFILE IS STORED                 *
* SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED              *
* SPECIFY PATH OF WHERE SAS FORMAT LIBRARY IS STORED             *
* SPECIFY PATH OF WHERE THE FORMAT ASSIGNMET STATEMENT IS STORED *
******************************************************************;

*FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL =         1294 ;
*****************************************************************************
* EXAMPLE:                                                                  *
*       FILENAME DATAIN 'C:\BRFSS\2008\BRFS08V1.ASC' LRECL =         1294           *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

*LIBNAME DATAOUT V7 '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>'  ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME DATAOUT 'C:\'                                            *
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.sas7bdat             *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*LIBNAME LIBRARY '<PATH OF STORED SAS FORMAT08.SAS7BCAT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME LIBRARY 'C:\'                                            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*FILENAME FORMATIN '<PATH OF FORMAT ASSIGNMENT STATEMENT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          FILENAME FORMATIN 'C:\FORMATSTATEMENT.SAS'                       *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT
_STATE        1-2                     /* Record Identification */
_GEOSTR       3-4
_DENSTR2      5
PRECALL       6
REPNUM        7-11
REPDEPTH      12-13
FMONTH        14-15
IDATE         $16-23
IMONTH        $16-17
IDAY          $18-19
IYEAR         $20-23
INTVID        $24-26
DISPCODE      27-29
SEQNO         30-39
_PSU          30-39
NATTMPTS      40-41
NRECSEL       42-47
NRECSTR       48-56
CTELENUM      57
CELLFON       58
PVTRESID      59
NUMADULT      60-61
NUMMEN        62-63
NUMWOMEN      64-65
GENHLTH       73                      /* Section 1: Health Status */
PHYSHLTH      74-75                   /* Section 2: Healthy Days - Health-Related Quality of Life */
MENTHLTH      76-77
POORHLTH      78-79
HLTHPLAN      80                      /* Section 3: Health Care Access */
PERSDOC2      81
MEDCOST       82
CHECKUP1      83
QLREST2       84-85                   /* Section 4: Sleep */
EXERANY2      86                      /* Section 5: Exercise */
DIABETE2      87                      /* Section 6: Diabetes */
LASTDEN3      88                      /* Section 7: Oral Health */
RMVTETH3      89
DENCLEAN      90
CVDINFR4      91                      /* Section 8: Cardiovascular Disease Prevalence */
CVDCRHD4      92
CVDSTRK3      93
ASTHMA2       94                      /* Section 9: Asthma */
ASTHNOW       95
QLACTLM2      96                      /* Section 10: Disability */
USEEQUIP      97
SMOKE100      98                      /* Section 11: Tobacco Use */
SMOKDAY2      99
STOPSMK2      100
AGE           101-102                 /* Section 12: Demographics */
HISPANC2      103
MRACE         $104-109
ORACE2        110
VETERAN1      111
MARITAL       112
CHILDREN      113-114
EDUCA         115
EMPLOY        116
INCOME2       117-118
WEIGHT2       119-122
HEIGHT3       123-126
WTYRAGO       127-130
WTCHGINT      131
NUMHHOL2      140
NUMPHON2      141
TELSERV2      142
SEX           143
PREGNANT      144
DRNKANY4      145                     /* Section 13: Alcohol Consumption */
ALCDAY4       146-148
AVEDRNK2      149-150
DRNK3GE5      151-152
MAXDRNKS      153-154
FLUSHOT3      155                     /* Section 14: Immunization */
FLUSHTMY      156-161
FLUSPRY2      162
FLUSPRMY      163-168
PNEUVAC3      169
FALL3MN2      170-171                 /* Section 15: Falls */
FALLINJ2      172-173
SEATBELT      174                     /* Section 16: Seatbelt Use */
DRNKDRI2      175-176                 /* Section 17: Drinking and Driving */
HADMAM        177                     /* Section 18: Women´s Health */
HOWLONG       178
PROFEXAM      179
LENGEXAM      180
HADPAP2       181
LASTPAP2      182
HADHYST2      183
PSATEST       184                     /* Section 19: Prostate Cancer Screening */
PSATIME       185
DIGRECEX      186
DRETIME       187
PROSTATE      188
BLDSTOOL      189                     /* Section 20: Colorectal Cancer Screening */
LSTBLDS3      190
HADSIGM3      191
HADSGCO1      192
LASTSIG3      193
HIVTST5       194                     /* Section 21: HIV/AIDS */
HIVTSTD2      195-200
WHRTST8       201-202
HIVRDTST      203
HIVRISK2      204
EMTSUPRT      205                     /* Section 22: Emotional Support and Life Satisfaction */
LSATISFY      206
CPDEMO        $207-212                /* Cell Phone Pilot */
CPSCREN       $213-223
PDIABTST      227                     /* Module 1: Pre-Diabetes */
PREDIAB       228
DIABAGE2      229-230                 /* Module 2: Diabetes */
INSULIN       231
BLDSUGAR      232-234
FEETCHK2      235-237
DOCTDIAB      238-239
CHKHEMO3      240-241
FEETCHK       242-243
EYEEXAM       244
DIABEYE       245
DIABEDU       246
PAINACT2      247-248                 /* Module 3: Healthy Days (Symptoms) */
QLMENTL2      249-250
QLSTRES2      251-252
QLHLTH2       253-254
VIDFCLT2      255                     /* Module 4: Visual Impairment and Access to Eye Care */
VIREDIF2      256
VIPRFVS2      257
VINOCRE2      258-259
VIEYEXM2      260
VIINSUR2      261
VICTRCT2      262
VIGLUMA2      263
VIMACDG2      264
HRVOLNTR      265                     /* Module 5: Influenza - High Risk/Health Care Worker */
HRDIRCAR      266
HRCHRNIL      267
HRSTLHAV      268
DRNKBER1      269-270                 /* Module 6: Binge Drinking */
DRNKWIN1      271-272
DRNKLIQR      273-274
DRNKPMIX      275-276
DRNKLOC1      277
BINGEDRV      278
BINGEPAY      279-281
USEEVER3      282                     /* Module 7: Other Tobacco Products */
USENOW3       283
USOTHNW1      284
SHSINWRK      285-286                 /* Module 8: Secondhand Smoke I */
SHSINHOM      287-288
HOUSSMK1      289
SHSALOWB      290
SHSALOWR      291
SHSALOWW      292
ASTHMAGE      293-294                 /* Module 9: Adult Asthma History */
ASATTACK      295
ASERVIST      296-297
ASDRVIST      298-299
ASRCHKUP      300-301
ASACTLIM      302-304
ASYMPTOM      305
ASNOSLEP      306
ASTHMED3      307
ASINHALR      308
HPVADVC       309                     /* Module 10: Adult HPV (Human Papilloma Virus) */
HPVADSHT      310-311
VETSTAT2      312                     /* Module 11: Veterans Health Status */
VACARE1       313
VAIRQAFG      314
RRCLASS2      315                     /* Module 12: Reactions to Race */
RRCOGNT2      316
RRATWRK2      317
RRHCARE3      318
RRPHYSM2      319
RREMTSM2      320
ADPLEASR      321-322                 /* Module 13: Anxiety and Depression */
ADDOWN        323-324
ADSLEEP       325-326
ADENERGY      327-328
ADEAT1        329-330
ADFAIL        331-332
ADTHINK       333-334
ADMOVE        335-336
ADANXEV       337
ADDEPEV       338
GPWELPR3      339                     /* Module 14: General Preparedness */
GP3DYWTR      340
GP3DYFD1      341
GP3DYPRS      342
GPBATRAD      343
GPFLSLIT      344
GPEMRCM1      345
GPEMRIN1      346
GPVACPL1      347
GPMNDEVC      348
GPNOTEV1      349-350
RCSBIRTH      $366-371                /* Module 15: Random Child Selection */
RCSGENDR      372
RCHISLAT      373
RCSRACE       $374-379
RCSBRACE      380
RCSRLTN2      381
CASTHDX2      382                     /* Module 16: Childhood Asthma Prevalence */
CASTHNO2      383
HPVCHVC       384                     /* Module 17: Child HPV (Human Papilloma Virus) */
HPVCHSHT      385-386
QSTVER        741                     /* Questionnaire Version */
QSTLANG       742-743                 /* Questionnaire Language */
_STSTR        754-758                 /* Weighting And Stratification Variables */
_STRWT        759-768
_RAWQ1        809-818
_WT2Q1        819-828
_POSTQ1       829-838
_FINALQ1      839-848
_REGION       929-930
_AGEG_        931-932
_SEXG_        933
_RACEG3_      934
_IMPAGE       935-936
_IMPNPH       937
CRACEORG      $987-992                /* Child Demographic Variables */
CRACEASC      993-998
_CRACE        999-1000
CHILDAGE      1001-1003
_CIMPAGE      1004-1005               /* Child Demographic Variables */
_CSEXG_       1006
_CRACEG_      1007
_CAGEG_       1008-1010
_RAWCH1       1011-1020
_WT2CH1       1021-1030
_POSTCH1      1031-1040
_CHILDQ1      1041-1050
_RFHLTH       1211                    /* Section 1: Calculated Variables */
_HCVU65       1212                    /* Section 3: Calculated Variables */
_TOTINDA      1213                    /* Section 5: Calculated Variables */
_EXTETH2      1214                    /* Section 7: Calculated Variables */
_ALTETH2      1215
_DENVST1      1216
_LTASTHM      1217                    /* Section 9: Calculated Variables */
_CASTHMA      1218
_ASTHMST      1219
_SMOKER3      1220                    /* Section 11: Calculated Variables */
_RFSMOK3      1221
MRACEORG      $1222-1227              /* Section 12: Calculated Race Variables */
MRACEASC      $1228-1233
_PRACE        1234-1235
_MRACE        1236-1237
RACE2         1238
_RACEG2       1239
_RACEGR2      1240
_RACE_G       1241
_CNRACE       1242
_CNRACEC      1243
_AGEG5YR      1244-1245
_AGE65YR      1246
_AGE_G        1247
HTIN3         1248-1250
HTM3          1251-1253
WTKG2         1254-1258
_BMI4         1259-1262
_BMI4CAT      1263
_RFBMI4       1264
_CHLDCNT      1265
_EDUCAG       1266
_INCOMG       1267
DROCDY2_      1268-1270               /* Section 13: Calculated Variables */
_RFBING4      1271
_DRNKDY3      1272-1275
_DRNKMO3      1276-1279
_RFDRHV3      1280
_RFDRMN3      1281
_RFDRWM3      1282
_FLSHOT3      1283                    /* Section 14: Calculated Variables */
_PNEUMO2      1284
_RFSEAT2      1285                    /* Section 16: Calculated Variables */
_RFSEAT3      1286
_RFMAM2Y      1287                    /* Section 18: Calculated Variables */
_MAM502Y      1288
_RFPAP32      1289
_RFPSA2Y      1290                    /* Section 19: Calculated Variables */
_RFBLDS2      1291                    /* Section 20: Calculated Variables */
_RFSIGM2      1292
_AIDTST2      1293                    /* Section 21: Calculated Variables */
;
*****************************************************************
* TO INCLUDE THE FORMAT ASSIGNEMT STATEMENT REMOVE THE ASTERISK *
* FROM THE BEGINNING OF THE FOLLOWING LINE                      *
*****************************************************************;
* %INCLUDE FORMATIN ;
*************************************************
* THIS SECTION CREATES LABELS FOR THE VARIABLES *
*************************************************;
Label
ADANXEV = 'EVER TOLD YOU HAD AN ANXIETY DISORDER'
ADDEPEV = 'EVER TOLD YOU HAD A DEPRESSIVE DISORDER'
ADDOWN = 'DAYS FELT DOWN, DEPRESSED OR HOPELESS'
ADEAT1 = 'DAYS ATE TOO LITTLE OR TOO MUCH'
ADENERGY = 'DAYS WERE TIRED OR HAD LITTLE ENERGY'
ADFAIL = 'DAYS FELT LIKE FAILURE OR LET FAMILY DOWN'
ADMOVE = 'DAYS TALKED TO MOVE SLOWER OR FASTER THAN USUAL'
ADPLEASR = 'DAYS HAD LITTLE PLEASURE DOING THINGS'
ADSLEEP = 'DAYS HAD TROUBLE WITH SLEEP'
ADTHINK = 'DAYS HAD TROUBLE CONCENTRATING'
AGE = 'REPORTED AGE IN YEARS'
ALCDAY4 = 'DAYS IN PAST 30 HAD ALCOHOLIC BEVERAGE'
ASACTLIM = 'ACTIVITIES LIMITED DUE TO ASTHMA DURING PAST 12 MONTHS'
ASATTACK = 'ASTHMA DURING PAST 12 MONTHS'
ASDRVIST = 'URGENT ASTHMA TREATMENT DURING PAST 12 MONTHS'
ASERVIST = 'EMERGENCY ASTHMA CARE DURING PAST 12 MONTHS'
ASINHALR = 'TIMES USED ASTHMA INHALER DURING AN ATTACK IN PAST 30 DAYS'
ASNOSLEP = 'SLEEP DIFFICULTY DUE TO ASTHMA DURING PAST 30 DAYS'
ASRCHKUP = 'ROUTINE ASTHMA CARE DURING PAST 12 MONTHS'
ASTHMA2 = 'EVER TOLD HAD ASTHMA'
ASTHMAGE = 'AGE AT ASTHMA DIAGNOSIS'
ASTHMED3 = 'DAYS USED PRESCRIBED PREVENTATIVE ASTHMA MED IN PAST 30 DAYS'
ASTHNOW = 'STILL HAVE ASTHMA'
ASYMPTOM = 'ASTHMA SYMPTOMS DURING PAST 30 DAYS'
AVEDRNK2 = 'AVG ALCOHOLIC DRINKS PER DAY IN PAST 30'
BINGEDRV = 'DRIVE A MOTOR VEHICLE AFTER BINGE DRINKING?'
BINGEPAY = 'HOW MUCH DID YOU PAY FOR THE ALCOHOL YOU DRANK?'
BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
CASTHDX2 = 'HLTH PRO EVER SAID CHILD HAS ASTHMA'
CASTHNO2 = 'CHILD STILL HAVE ASTHMA?'
CELLFON = 'CELLULAR TELEPHONE'
CHECKUP1 = 'LENGTH OF TIME SINCE LAST ROUTINE CHECKUP'
CHILDAGE = 'CHILD AGE'
CHILDREN = 'NUMBER OF CHILDREN IN HOUSEHOLD'
CHKHEMO3 = 'TIMES CHECKED FOR GLYCOSYLATED HEMOGLOBIN'
CPDEMO = 'CELL PHONE PILOT DEMOGRAPHIC DATA'
CPSCREN = 'CELL PHONE PILOT SCREENING DATA'
CRACEASC = 'CRACEORG WITH RESPONSES IN ASCENDING ORDER'
CRACEORG = 'CRACE WITH TRAILING 7, 8, 9S REMOVED'
CTELENUM = 'CORRECT TELEPHONE NUMBER?'
CVDCRHD4 = 'EVER DIAGNOSED WITH ANGINA OR CORONARY HEART DISEASE'
CVDINFR4 = 'EVER DIAGNOSED WITH HEART ATTACK'
CVDSTRK3 = 'EVER DIAGNOSED WITH A STROKE'
DENCLEAN = 'WHEN TEETH LAST CLEANED BY DENTIST OR HYGIENIST'
DIABAGE2 = 'AGE WHEN TOLD DIABETIC'
DIABEDU = 'EVER TAKEN CLASS IN MANAGING DIABETES'
DIABETE2 = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
DIABEYE = 'EVER TOLD DIABETES HAS AFFECTED EYES'
DIGRECEX = 'EVER HAD DIGITAL RECTAL EXAM'
DISPCODE = 'FINAL DISPOSITION'
DOCTDIAB = 'TIMES SEEN HEALTH PROFESSIONAL FOR DIABETES'
DRETIME = 'TIME SINCE LAST DIGITAL RECTAL EXAM'
DRNK3GE5 = 'BINGE DRINKING'
DRNKANY4 = 'DRINK ANY ALCOHOLIC BEVERAGES IN PAST 30 DAYS'
DRNKBER1 = 'HOW MANY BEERS CONSUMED WHEN BINGE DRINKING'
DRNKDRI2 = 'DID YOU DRIVE AFTER HAVING TOO MUCH TO DRINK IN THE PAST 30 DAYS?'
DRNKLIQR = 'HOW MANY DRINKS OF LIQUOR CONSUMED WHEN BINGE DRINKING'
DRNKLOC1 = 'WHERE WERE YOU WHEN YOU BINGE DRANK'
DRNKPMIX = 'HOW MANY PRE-MIXED DRINKS CONSUMED WHEN BINGE DRINKING'
DRNKWIN1 = 'HOW MANY GLASSES OF WINE CONSUMED WHEN BINGE DRINKING'
DROCDY2_ = 'COMPUTED DRINK-OCCASIONS-PER-DAY'
EDUCA = 'EDUCATION LEVEL'
EMPLOY = 'EMPLOYMENT STATUS'
EMTSUPRT = 'HOW OFTEN GET EMOTIONAL SUPPORT NEEDED'
EXERANY2 = 'EXERCISE IN PAST 30 DAYS'
EYEEXAM = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
FALL3MN2 = 'HAD FALL PAST THREE MONTHS'
FALLINJ2 = 'INJURED IN FALL'
FEETCHK = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
FEETCHK2 = 'HOW OFTEN CHECK FEET FOR SORES OR IRRITATIONS'
FLUSHOT3 = 'FLU SHOT PAST 12 MOS'
FLUSHTMY = 'WHEN RECEIVED MOST RECENT FLU SHOT'
FLUSPRMY = 'WHEN RECEIVED MOST RECENT FLU SPRAY IN NOSE'
FLUSPRY2 = 'FLU SPRAY PAST 12 MOS'
FMONTH = 'FILE MONTH'
GENHLTH = 'GENERAL HEALTH'
GP3DYFD1 = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF NON-PERISHABLE FOOD FOR EVERYONE WHO LIVES THERE?'
GP3DYPRS = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF PRESCRIPTION MEDICATION FOR EACH PERSON WHO TAKES PRESCRIBED MEDICINES?'
GP3DYWTR = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF WATER FOR EVERYONE WHO LIVES THERE?'
GPBATRAD = 'DOES YOUR HOUSEHOLD HAVE A WORKING BATTERY OPERATED RADIO AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICITY IS OUT?'
GPEMRCM1 = 'IN A LARGE-SCALE DISASTER OR EMERGENCY, WHAT WOULD BE YOUR MAIN METHOD OF COMMUNICATING WITH RELATIVES AND FRIENDS?'
GPEMRIN1 = 'WHAT WOULD BE YOUR MAIN METHOD OF GETTING INFORMATION FROM AUTHORITIES IN A LARGE-SCALE DISASTER OR EMERGENCY?'
GPFLSLIT = 'DOES YOUR HOUSEHOLD HAVE A WORKING FLASHLIGHT AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICITY IS OUT?'
GPMNDEVC = 'IF PUBLIC AUTHORITIES ANNOUNCED MANDATORY EVACUATION FROM YOUR COMMUNITY DUE TO A LARGE-SCALE DISASTER OR EMERGENCY, WOULD YOU EVACUATE?'
GPNOTEV1 = 'WHAT WOULD BE THE MAIN REASON WHY YOU MIGHT NOT EVACUATE IF ASKED TO DO SO?'
GPVACPL1 = 'DOES YOUR HOUSEHOLD HAVE A DISASTER EVACUATION PLAN?'
GPWELPR3 = 'HOUSEHOLD PREPARED TO HANDLE LARGE-SCALE DISASTER OR EMERGENCY'
HADHYST2 = 'HAD HYSTERECTOMY'
HADMAM = 'HAVE YOU EVER HAD A MAMMOGRAM'
HADPAP2 = 'EVER HAD A PAP TEST'
HADSGCO1 = 'WAS LAST TEST A SIGMOIDOSCOPY OR COLONOSCOPY'
HADSIGM3 = 'EVER HAD SIGMOIDOSCOPY/COLONOSCOPY'
HEIGHT3 = 'REPORTED HEIGHT IN FEET AND INCHES'
HISPANC2 = 'HISPANIC/LATINO'
HIVRDTST = 'WAS YOUR LAST HIV TEST A RAPID TEST?'
HIVRISK2 = 'DO ANY HIGH RISK SITUATIONS APPLY'
HIVTST5 = 'EVER TESTED HIV'
HIVTSTD2 = 'MONTH AND YEAR OF LAST HIV TEST'
HLTHPLAN = 'HAVE ANY HEALTH CARE COVERAGE'
HOUSSMK1 = 'SMOKING POLICY AT HOME'
HOWLONG = 'HOW LONG SINCE LAST MAMMOGRAM'
HPVADSHT = 'NUMBER OF HPV SHOTS RECEIVED'
HPVADVC = 'EVER HAD THE HPV VACCINATION?'
HPVCHSHT = 'HOW MANY HPV SHOTS DID CHILD RECEIVE?'
HPVCHVC = 'CHILD  EVER HAD THE HPV VACCINATION?'
HRCHRNIL = 'HAVE YOU BEEN TOLD YOU CHRONIC HEALTH PROBLEM?'
HRDIRCAR = 'PROVIDE DIRECT PATIENT CARE AS PART OF ROUTINE WORK'
HRSTLHAV = 'STILL HAVE CHRONIC ILLNESS?'
HRVOLNTR = 'CURRENTLY VOLUNTEER OR WORK IN MEDICAL OR HEALTH CARE FACILITY'
HTIN3 = 'COMPUTED HEIGHT IN INCHES'
HTM3 = 'COMPUTED HEIGHT IN METERS'
IDATE = 'INTERVIEW DATE'
IDAY = 'INTERVIEW DAY'
IMONTH = 'INTERVIEW MONTH'
INCOME2 = 'INCOME LEVEL'
INSULIN = 'NOW TAKING INSULIN'
INTVID = 'INTERVIEWER IDENTIFICATION'
IYEAR = 'INTERVIEW YEAR'
LASTDEN3 = 'LAST VISITED DENTIST OR DENTAL CLINIC'
LASTPAP2 = 'HOW LONG SINCE LAST PAP TEST'
LASTSIG3 = 'TIME SINCE LAST SIGMOIDOSCOPY/COLONOSCOPY'
LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
LSATISFY = 'SATISFACTION WITH LIFE'
LSTBLDS3 = 'TIME SINCE LAST BLOOD STOOL TEST'
MARITAL = 'MARITAL STATUS'
MAXDRNKS = 'MOST DRINKS ON SINGLE OCCASION PAST 30 DAYS'
MEDCOST = 'COULD NOT SEE DR. BECAUSE OF COST'
MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
MRACE = 'MULTIPLE RACE'
MRACEASC = 'MRACEORG WITH RESPONSES IN ASCENDING ORDER CALCULATED VARIABLE'
MRACEORG = 'MRACE WITH TRAILING 7,8,9S REMOVED CALCULATED VARIABLE'
NATTMPTS = 'NUMBER OF ATTEMPTS'
NRECSEL = 'NUMBER OF SAMPLE RECORDS SELECTED FROM STRATUM'
NRECSTR = 'NUMBER OF TELEPHONE NUMBERS IN STRATUM FROM WHICH SAMPLE WAS SELECTED'
NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
NUMHHOL2 = 'HOUSEHOLD TELEPHONES'
NUMMEN = 'NUMBER OF ADULT MEN IN HOUSEHOLD'
NUMPHON2 = 'RESIDENTIAL PHONES'
NUMWOMEN = 'NUMBER OF ADULT WOMEN IN HOUSEHOLD'
ORACE2 = 'RESPONDENT RACE CHOICE'
PAINACT2 = 'HOW MANY DAYS HARD TO DO USUAL ACTIVITIES IN PAST 30 DAYS'
PDIABTST = 'HAD A TEST FOR HIGH BLOOD SUGAR IN PAST THREE YEARS'
PERSDOC2 = 'MULTIPLE HEALTH CARE PROFESSIONALS'
PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
PNEUVAC3 = 'PNEUMONIA SHOT EVER'
POORHLTH = 'POOR PHYSICAL HEALTH'
PRECALL = 'PRE-CALL STATUS CODE'
PREDIAB = 'EVER BEEN TOLD YOU HAVE PRE-DIABETES OR BORDERLINE DIABETES'
PREGNANT = 'PREGNANCY STATUS'
PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
PROSTATE = 'EVER TOLD YOU HAD PROSTATE CANCER'
PSATEST = 'EVER HAD PSA TEST'
PSATIME = 'TIME SINCE LAST PSA TEST'
PVTRESID = 'PRIVATE RESIDENCE?'
QLACTLM2 = 'ACTIVITY LIMITATION DUE TO HEALTH PROBLEMS'
QLHLTH2 = 'HOW MANY DAYS FULL OF ENERGY IN PAST 30 DAYS'
QLMENTL2 = 'HOW MANY DAYS DEPRESSED IN PAST 30 DAYS'
QLREST2 = 'HOW MANY DAYS DID YOU GET ENOUGH SLEEP IN PAST 30 DAYS'
QLSTRES2 = 'HOW MANY DAYS FELT ANXIOUS IN PAST 30 DAYS'
QSTLANG = 'LANGUAGE IDENTIFIER'
QSTVER = 'QUESTIONNAIRE VERSION IDENTIFIER'
RACE2 = 'COMPUTED RACE-ETHNICITY GROUPING'
RCHISLAT = 'ETHNICITY OF CHILD'
RCSBIRTH = 'BIRTH DATE OF CHILD'
RCSBRACE = 'RACE OF CHILD'
RCSGENDR = 'GENDER OF CHILD'
RCSRACE = 'RACE OF CHILD (MULTIPLE POSSIBLE)'
RCSRLTN2 = 'RELATIONSHIP TO CHILD'
REPDEPTH = 'REPLICATE DEPTH'
REPNUM = 'REPLICATE NUMBER'
RMVTETH3 = 'NUMBER OF PERMANENT TEETH REMOVED'
RRATWRK2 = 'HOW DO YOU FEEL YOU WERE TREATED AT WORK COMPARED TO PEOPLE OF OTHER RACES IN PAST 12 MONTHS?'
RRCLASS2 = 'HOW DO OTHER PEOPLE USUALLY CLASSIFY YOU IN THIS COUNTRY?'
RRCOGNT2 = 'HOW OFTEN DO YOU THINK ABOUT YOUR RACE?'
RREMTSM2 = 'TIMES PAST 30 DAYS FELT EMOTIONALLY UPSET BECAUSE OF TREATMENT DUE TO YOUR RACE'
RRHCARE3 = 'WHEN SEEKING HEALTH CARE PAST 12 MONTHS, WAS EXPERIENCE WORSE, SAME, BETTER THAN PEOPLE OF OTHER RACES?'
RRPHYSM2 = 'TIMES PAST 30 DAYS FELT PHYSICAL SYMPTOMS BECAUSE OF TREATMENT DUE TO YOUR RACE'
SEATBELT = 'HOW OFTEN USE SEATBELTS IN CAR?'
SEQNO = 'ANNUAL SEQUENCE NUMBER'
SEX = 'RESPONDENTS SEX'
SHSALOWB = 'SHOULD SMOKING BE ALLOWED IN BARS?'
SHSALOWR = 'SHOULD SMOKING BE ALLOWED IN RESTAURANTS?'
SHSALOWW = 'SHOULD SMOKING BE ALLOWED IN INDOOR WORKPLACES?'
SHSINHOM = 'ANYONE SMOKE IN YOUR HOME IN PAST 7 DAYS?'
SHSINWRK = 'ANYONE SMOKE IN YOUR INDOOR WORKPLACE IN PAST 7 DAYS?'
SMOKDAY2 = 'FREQUENCY OF DAYS NOW SMOKING'
SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
STOPSMK2 = 'STOPPED SMOKING IN PAST 12 MONTHS'
TELSERV2 = 'LOST PHONE SERVICE ONE WEEK+ LAST 12 MOS'
USEEQUIP = 'HEALTH PROBLEMS REQUIRING SPECIAL EQUIPMENT'
USEEVER3 = 'EVER USED SMOKELESS TOBACCO PRODUCTS'
USENOW3 = 'USE OF SMOKELESS TOBACCO PRODUCTS'
USOTHNW1 = 'DO YOU CURRENTLY USE ANY TOBACCO PRODUCTS OTHER THAN CIGARETTES?'
VACARE1 = 'RECEIVED SOME OR ALL OF YOUR HEALTH CARE FROM VA FACILITIES IN THE LAST 12 MONTHS'
VAIRQAFG = 'MILITARY DEPLOYMENT TO AFGHANISTAN OR IRAQ SINCE 9/11?'
VETERAN1 = 'ARE YOU A VETERAN'
VETSTAT2 = 'CURRENT VETERAN STATUS'
VICTRCT2 = 'HLTH CARE PRO SAID NOW HAVE CATARACTS'
VIDFCLT2 = 'DIFFICULTY RECOGNIZING FRIEND ACROSS STREET'
VIEYEXM2 = 'WHEN LAST EYEXAM'
VIGLUMA2 = 'HLTH CARE PRO EVER SAID HAVE GLAUCOMA'
VIINSUR2 = 'EYE CARE HEALTH INSURANCE'
VIMACDG2 = 'HLTH CARE PRO EVER SAID HAVE MACULAR DEGENERATION'
VINOCRE2 = 'REASON DID NOT USE EYE DOC PAST 12 MOS'
VIPRFVS2 = 'LAST TIME VISITED EYE CARE PROVIDER'
VIREDIF2 = 'DIFFICULTY READING TYPED TEXT'
WEIGHT2 = 'REPORTED WEIGHT IN POUNDS'
WHRTST8 = 'LOCATION OF LAST HIV TEST'
WTCHGINT = 'CHANGE IN WEIGHT SINCE YEAR AGO'
WTKG2 = 'COMPUTED WEIGHT IN KILOGRAMS'
WTYRAGO = 'REPORTED WEIGHT YEAR AGO IN POUNDS'
_AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS CALCULATED VARIABLE'
_AGEG5YR = 'REPORTED AGE IN FIVE-YEAR AGE CATEGORIES CALCULATED VARIABLE'
_AGEG_ = 'AGE GROUP CODES USED IN POST-STRATIFICATION.'
_AGE_G = 'IMPUTED AGE IN SIX GROUPS'
_AIDTST2 = 'EVER BEEN TESTED FOR HIV CALCULATED VARIABLE'
_ALTETH2 = 'ADULTS AGED 65+ WHO HAVE HAD ALL THEIR NATURAL TEETH EXTRACTED'
_ASTHMST = 'COMPUTED ASTHMA STATUS'
_BMI4 = 'COMPUTED BODY MASS INDEX'
_BMI4CAT = 'COMPUTED BODY MASS INDEX CATEGORIES'
_CAGEG_ = 'CHILD AGE GROUP CODES USED IN POST-STRATIFICATION.'
_CASTHMA = 'CURRENT ASTHMA CALCULATED VARIABLE'
_CHILDQ1 = 'FINAL WEIGHT QUESTIONNAIRE VERSION 1: POST-STRATIFICATION WEIGHT MULTIPLIED BY _WT2CH1'
_CHLDCNT = 'COMPUTED NUMBER OF CHILDREN IN HOUSEHOLD'
_CIMPAGE = 'IMPUTED CHILD AGE'
_CNRACE = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN'
_CNRACEC = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN, COLLAPSED'
_CRACE = 'CHILD NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_CRACEG_ = 'CHILD RACE GROUP CODES USED IN POST-STRATIFICATION.'
_CSEXG_ = 'CHILD GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_DENSTR2 = 'HOUSEHOLD DENSITY STRATUM CODE'
_DENVST1 = 'ADULTS THAT HAVE VISITED A DENTIST, DENTAL HYGENIST OR DENTAL CLINIC WITHIN THE PAST YEAR'
_DRNKDY3 = 'COMPUTED NUMBER OF DRINKS OF ALCOHOL BEVERAGES PER DAY'
_DRNKMO3 = 'COMPUTED TOTAL NUMBER DRINKS A MONTH'
_EDUCAG = 'COMPUTED LEVEL OF EDUCATION COMPLETED CATEGORIES'
_EXTETH2 = 'RISK FACTOR FOR HAVING HAD PERMANENT TEETH EXTRACTED'
_FINALQ1 = 'FINAL WEIGHT QUESTIONNAIRE VERSION 1: POST-STRATIFICATION WEIGHT MULTIPLIED BY _WT2'
_FLSHOT3 = 'FLU SHOT CALCULATED VARIABLE'
_GEOSTR = 'GEOGRAPHIC STRATUM CODE'
_HCVU65 = 'RESPONDENTS AGED 18-64 WITH HEALTH CARE COVERAGE'
_IMPAGE = 'AGE VALUE USED TO DETERMINE AGE GROUPS'
_IMPNPH = 'IMPUTED NUMBER OF PHONES'
_INCOMG = 'COMPUTED INCOME CATEGORIES'
_LTASTHM = 'LIFETIME ASTHMA CALCULATED VARIABLE'
_MAM502Y = 'WOMEN RESPONDENTS AGED 50+ THAT HAVE HAD A MAMMOGRAM IN THE PAST TWO YEARS'
_MRACE = 'COMPUTED NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_PNEUMO2 = 'PNEUMONIA VACCINATION CALCULATED VARIABLE'
_POSTCH1 = 'POST-STRATIFICATION CHILD WEIGHT QUESTIONNAIRE VERSION 1 (POPULATION ESTIMATE FOR AGE/GENDER/RACE CATEGORIES DIVIDED BY THE WEIGHTED SAMPLE FREQUENCY
BY AGE/RACE/GENDER).'
_POSTQ1 = 'POST-STRATIFICATION WEIGHT QUESTIONNAIRE VERSION 1 (POPULATION ESTIMATE FOR AGE/GENDER/RACE CATEGORIES DIVIDED BY THE WEIGHTED SAMPLE FREQUENCY BY AGE/
RACE/GENDER).'
_PRACE = 'COMPUTED PREFERRED RACE'
_PSU = 'PRIMARY SAMPLING UNIT'
_RACEG2 = 'COMPUTED NON-HISPANIC WHITES/ALL OTHERS RACE CATEGORIES RACE/ETHNIC GROUP CODES USED IN POST-STRATIFICATION.'
_RACEG3_ = 'RACE GROUP CODES USED IN POST-STRATIFICATION.'
_RACEGR2 = 'COMPUTED FIVE LEVEL RACE/ETHNICITY CATEGORY.'
_RACE_G = 'COMPUTED RACE GROUPS USED FOR INTERNET PREVALENCE TABLES'
_RAWCH1 = 'RAW CHILD WEIGHTING FACTOR QUESTIONNAIRE VERSION 1'
_RAWQ1 = 'RAW WEIGHTING FACTOR QUESTIONNAIRE VERSION 1'
_REGION = 'REGION'
_RFBING4 = 'BINGE DRINKING CALCULATED VARIABLE'
_RFBLDS2 = 'RESPONDENTS AGED 50+ THAT HAVE HAD A BLOOD STOOL TEST WITHIN THE PAST TWO YEARS'
_RFBMI4 = 'OVERWEIGHT OR OBESE CALCULATED VARIABLE'
_RFDRHV3 = 'HEAVY ALCOHOL CONSUMPTION  CALCULATED VARIABLE'
_RFDRMN3 = 'ADULT MEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFDRWM3 = 'ADULT WOMEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFHLTH = 'ADULTS WITH GOOD OR BETTER HEALTH'
_RFMAM2Y = 'WOMEN RESPONDENTS AGED 40+ THAT HAVE HAD A MAMMOGRAM IN THE PAST TWO YEARS'
_RFPAP32 = 'WOMEN RESPONDENTS AGED 18+ THAT HAVE HAD A PAP TEST IN THE PAST THREE YEARS'
_RFPSA2Y = 'MALE RESPONDENTS AGED 40+ THAT HAVE HAD A PSA TEST IN THE PAST 2 YEARS'
_RFSEAT2 = 'ALWAYS OR NEARLY ALWAYS WEAR SEAT BELTS'
_RFSEAT3 = 'ALWAYS WEAR SEAT BELTS'
_RFSIGM2 = 'RESPONDENTS AGED 50 OR OLDER THAT HAVE HAD A SIGMOIDOSCOPY OR COLONOSCOPY'
_RFSMOK3 = 'CURRENT SMOKING CALCULATED VARIABLE'
_SEXG_ = 'GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_SMOKER3 = 'COMPUTED SMOKING STATUS'
_STATE = 'STATE FIPS CODE'
_STRWT = 'STRATUM WEIGHT'
_STSTR = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
_TOTINDA = 'LEISURE TIME PHYSICAL ACTIVITY CALCULATED VARIABLE'
_WT2CH1 = 'CHILD DESIGN WEIGHT QUESTIONNAIRE VERSION 1'
_WT2Q1 = 'DESIGN WEIGHT QUESTIONNAIRE VERSION 1. THE PRODUCT OF THE PRECEDING FOUR FACTORS'
;
RUN;
