* INSTRUCTIONS:
* SPECIFY PATH OF INPUT DATAFILE
* SPECIFY THE LOCATION OF THE FORMATS.SC2 FILE
* AND SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED;

FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 788 ;
* EXAMPLE: FILENAME DATAIN 'C:\BRFSS\2000\GA00COMP.DAT' LRECL = 788 ;

LIBNAME LIBRARY V6 '<PATH OF 2001 FORMATS.SC2 FILE>' ;
* EXAMPLE: LIBNAME LIBRARY 'C:\SAS\FORMATS'
*          THE FORMATS.SC2 FILE MUST BE IN THE FOLDER GIVEN IN THE LIBNAME STATEMENT;

LIBNAME DATAOUT '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>' ;
* EXAMPLE: LIBNAME DATAOUT 'C:\'
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.SD2;
RUN ;
/*****************************************************************************************
 * FILE NAME:     SASOUT01.SAS
 *
 * DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT
 *                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF
 * EXTERNAL REFERENCES:
 *    TYPE         NAME                 DESCRIPTION OF REFERENCE
 * ----------  ---------------  ----------------------------------------------------------
 * INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES
 *
 * OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN
 *                              <DATAIN> FILEREF
 * MODIFICATION HISTORY:
 * NUM     DATE       PROGRAMMER      DESCRIPTION OF MODIFICATION
 * ---  ---------   --------------   -----------------------------------------------------
 * 000  04/04/2002    B. BARTOLI      INITIAL ISSUE
 * 001  05/17/2002    D. GILBERTZ     ADDED FORMAT ASSIGNMENTS
 *****************************************************************************************/

OPTIONS SOURCE NOTES NODATE PAGENO = 1 NOFMTERR;
TITLE ;
FOOTNOTE ;
RUN ;

DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT	_STATE		1-2			/* SAMPLE/RECORD IDENTIFICATION */
		_GEOSTR		3-4
		_DENSTR		5
		LISTSTAT	6
		PRECALL		7
		REPNUM		8-12
		REPDEPTH	13-14
		_RECORD		15-16
		FMONTH 		17-18
		IMONTH		$19-20
		IDAY		$21-22
		IYEAR		$23-26
		INTVID		$27-29
		AREACODE    30-32
		PREFIX      33-35
		SUFFIX      36-37
		DISPCODE	38-39
		WINDDOWN	40
		SEQNO		41-50
                _PSU            41-50
		NATTMPTS	51-52
		NRECSEL		53-58
		NRECSTR		59-67
		NUMADULT	68-69
		NUMMEN		70
		NUMWOMEN	71
		GENHLTH		72			/* SECTION 1, HEALTH STATUS */
		PHYSHLTH	73-74
		MENTHLTH	75-76
		POORHLTH	77-78
		HLTHPLAN	79			/* SECTION 2, HEALTH CARE ACCESS */
		NOCOVR12	80
		PERSDOC2	81
		EXERANY2	82			/* SECTION 3, EXERCISE */
		BPHIGH2		83			/* SECTION 4, HYPERTENSION AWARENESS */
		BPMEDS		84
		BLOODCHO	85			/* SECTION 5, CHOLESTEROL AWARENESS */
		CHOLCHK		86
		TOLDHI2		87
		ASTHMA2		88			/* SECTION 6, ASTHMA */
		ASTHNOW		89
		DIABETES	90			/* SECTION 7, DIABETES */
		PAIN12MN	91			/* SECTION 8, ARTHRITIS */
		SYMTMMTH	92
		LMTJOINT	93
		JOINTRT		94
		HAVARTH		95
		TRTARTH		96
		FLUSHOT		97			/* SECTION 9, IMMUNIZATION */
		PNEUVAC2	98
		SMOKE100	99			/* SECTION 10, TOBACCO USE */
		SMOKEDAY	100
		STOPSMK2	101
		ALCDAYS		102-104		/* SECTION 11, ALCOHOL CONSUMPTION */
		AVEDRNK		105-106
		DRNK2GE5	107-108
		FIREARM3	109			/* SECTION 12, FIREARMS */
		AGE			110-111		/* SECTION 13, DEMOGRAPHICS */
		HISPANC2	112
		MRACE		$113-118
		ORACE2		119
		MARITAL		120
		CHILDREN	121-122
		EDUCA		123
		EMPLOY		124
		INCOME2		125-126
		WEIGHT		127-129
		HEIGHT		130-132
		CTYCODE		133-135
		NUMHHOL2	136
		NUMPHON2	137
		CELLPHON	138
		SEX			139
		PREGNT2		140
		QLACTLM2	141			/* SECTION 14, DISABILITY */
		USEEQUIP	142
		JOBACTIV	143			/* SECTION 15, PHYSICAL ACTIVITY */
		MODPACT		144
		MODPADAY	145-146
		MODPATIM	147-149
		VIGPACT		150
		VIGPADAY	151-152
		VIGPATIM	153-155
		PSATEST		156			/* SECTION 16, PROSTATE CANCER SCREENING */
		PSATIME		157
		DIGRECEX	158
		DRETIME		159
		PROSTATE	160
		PROSHIST	161
		BLDSTOOL	162			/* SECTION 17, COLORECTAL CANCER SCREENING */
		LSTBLDS2	163
		HADSIGM2	164
		LASTSIG2	165
		HIVTF1A		166			/* SECTION 18, HIV/AIDS */
		HIVTF1B		167
		HIVOPT1A	168
		HIVOPT1B	169
		HIVTST3		170
		HIVTSTDT	171-174
		RSNTST3		175-176
		WHRTST4		177-178
		PCSAIDS2	179
		DIABAGE2	180-181		/* MODULE 1, DIABETES */
		INSULIN		182
		DIABPILL	183
		BLDSUGAR	184-186
		FEETCHK2	187-189
		FEETSORE	190
		DOCTDIAB	191-192
		CHKHEMO2	193-194
		FEETCHK		195-196
		EYEEXAM		197
		DIABEYE		198
		DIABEDU		199
		SEXINTMN	200-201		/* MODULE 2, SEXUAL BEHAVIOR */
		SEXCONDM	202
		CONDLAST	203
		CONEFF2		204
		NEWPARTN	205-206
		HIVRISK		207
		STDTREAT	208
		STDCLIN		209
		SEXBEHA2	210
		SELCPTN3	211
		SEX1PTN3	212
		USECOND3	213
		HLTHPRB2	214-215		/* MODULE 3, QUALITY OF LIFE AND CARE GIVING */
		LONGLMT2	216-218
		QLPERSN2	219
		QLROUTN2	220
		PAINACT2	221-222
		QLMENTL2	223-224
		QLSTRES2	225-226
		QLREST2		227-228
		QLHLTH2		229-230
		QLPCHEL2	231-232
		QLPCLEV2	233
		QLRCHEL2	234-235
		QLRCLEV2	236
		RSNOCOV2	237-238		/* MODULE 4, HEALTH CARE COVERAGE AND UTILIZATION */
		PSTPLAN2	239
		RSWOCOV2	240-241
		PRIMCARE	242
		MOSTCARE	243
		FACILIT2	244
		MEDCOST		245
		CHECKUP		246
		HADMAM		247			/* MODULE 5, WOMENS HEALTH */
		HOWLONG		248
		WHYDONE		249
		PROFEXAM	250
		LENGEXAM	251
		REASEXAM	252
		HADPAP		253
		LASTPAP		254
		WHYPAP		255
		HADHYST2	256
		LASTDEN2	257			/* MODULE 6, ORAL HEALTH */
		RMVTEETH	258
		DENCLEAN	259
		REASDENT	260-261
		DENTLINS	262
		ASTHMAGE	263-264		/* MODULE 7, ASTHMA HISTORY */
		ASATTACK	265
		ASERVIST	266-267
		ASDRVIST	268-269
		ASRCHKUP	270-271
		ASACTLIM	272-274
		ASYMPTOM	275
		ASNOSLEP	276
		ASTHMEDS	277
		ASTHCHLD	278-279
		ASKIDHAS	280-281
		HASYMP1		282			/* MODULE 8, HEART ATTACK AND STROKE */
		HASYMP2		283
		HASYMP3		284
		HASYMP4		285
		HASYMP5		286
		HASYMP6		287
		STRSYMP1	288
		STRSYMP2	289
		STRSYMP3	290
		STRSYMP4	291
		STRSYMP5	292
		STRSYMP6	293
		FIRSTAID	294
		CVDFAT02	295			/* MODULE 9, CARDIOVASCULAR DISEASE */
		CVDFVG01	296
		CVDEXR03	297
		CVDFATR2	298
		CVDFVEG		299
		CVDEXRS2	300
		CVDINFR2	301
		CVDCRHD2	302
		CVDSTRK2	303
		HATTKAGE	304-305
		STROKAGE	306-307
		CVDREHAB	308
		CVDASPRN	309
		ASPUNSAF	310
		WHYASPAN	311
		WHYASPHA	312
		WHYASPSK	313
		FRUITJUI	314-316		/* MODULE 10, FRUITS AND VEGETABLES */
		FRUIT		317-319
		GREENSAL	320-322
		POTATOES	323-325
		CARROTS		326-328
		VEGETABL	329-331
		LOSEWT		332			/* MODULE 11, WEIGHT CONTROL */
		MAINTAIN	333
		FEWCAL		334
		PHYACT		335
		WTDESIRE	336-338
		DRADVICE	339
		VITAMINS	340			/* MODULE 12, FOLIC ACID */
		MULTIVIT	341
		FOLICACD	342
		TAKEVIT		343-345
		RECOMMEN	346
		FIRSTSMK	347-348		/* MODULE 13, TOBACCO INDICATORS */
		REGSMK		349-350
		LASTSMK		351-352
		GETCARE		353
		QUITSMOK	354
		HOUSESMK	355
		INDOORS		356
		SMKPUBLC	357
		SMKWORK		358
		USEEVER2	359			/* MODULE 14, OTHER TOBACCO PRODUCTS */
		USENOW2		360
		CIGAR2		361
		CIGARNOW	362
		PIPESMK		363
		PIPENOW		364
		BIDISMK		365
		BIDINOW		366
		DISMOD		$367-398	/* DISABILITY MODULE */
          @400  STATEQUE        $CHAR200.       /* STATE ADDED QUESTIONS SECTION 400-599*/
                _QSTVER         600             /* QUESTIONNAIRE VERSION */
		MRACEORG	$616-621	/* SAMPLING AND WEIGHTING VARIABLES */
		MRACEASC	$622-627
		_PRACE		628-629
		_STSTR		631-635
		_STRWT		636-645
		_RAW		646-655
		_WT2		666-675
		_POSTSTR	676-685
		_FINALWT	686-695
                _REGION         696-697
		_AGEG_		706-707
		_SEXG_		708
		_RACEG3_	709
		_IMPAGE		710-711
		_IMPNPH		712
                _MSACODE        713-716
		_AGEG5YR	717-718		/* CALCULATED VARIABLES */
		_AGE65YR	719
		RACE2		720
		_RACEG2		721
		_RACEGR2	722
		_CNRACE		723
		_CNRACEC	724
		_BMI2		725-730
		_BMI2CAT	731
		_RFBMI2		732
		_RFHYPE3	733
		_CHOLCHK	734
		_RFCHOL		735
		_HASCJS		736
		_CJSLMT		737
		_CJSARTH	738
		_SMOKER2	739
		_RFSMOK2	740
		_DRNKMO		741-744
		_DRNKDAY	745-750
		_RFBINGE	751
		_RFDRHVY	752
		_RFDRKMN	753
		_RFDRKWM	754
		_TOTINDA	756
		_RFPAREC	758
		_RFPAMOD	759
		_RFPAVIG	760
		_SMKLESS	761
		_RFTOBAC	762
		_FRTINDX	763
		_FRTSERV	764-768
		HTIN		769-770
                HTM             771-773
	    WTKG		774-778
		_MODPAMN	779-781
		_VIGPAMN	782-784
		DRNKANY2	785
		_MRACE		786-787
		ENDOFREC	788			/* END OF RECORD MARKER */;

******************************
* ASSIGN LABELS TO VARIABLES *
******************************;
LABEL _STATE   = 'STATE FIPS CODE'
	_GEOSTR  = 'STRATUM CODE'
	_DENSTR  = 'DENSITY STRATUM'
	LISTSTAT = 'LISTED STATUS'
	PRECALL  = 'PRECALLING STATUS'
	REPNUM   = 'REPLICATE NUMBER'
	REPDEPTH = 'REPLICATE DEPTH'
	_RECORD  = 'RECORD NUMBER'
	FMONTH   = 'FILE MONTH'
	IMONTH   = 'MONTH OF INTERVIEW'
	IDAY	= 'DAY OF INTERVIEW'
	IYEAR	= 'YEAR OF INTERVIEW'
	INTVID   = 'INTERVIEWER ID'
	AREACODE = 'AREA CODE'
	PREFIX   = 'PREFIX'
	SUFFIX   = 'SUFFIX'
	DISPCODE = 'DISPOSITION OF INTERVIEW'
	WINDDOWN = 'INTERVIEW IN REGULAR OR WINDDOWN MODE'
	SEQNO	= 'SEQUENCE NUMBER'
	NATTMPTS = 'NUMBER OF ATTEMPTS'
	NRECSEL  = 'NUMBER OF SAMPLE RECORDS FOR STRATUM'
	NRECSTR  = 'NO. OF PH. NOS. IN STRATUM FROM SAMPLE'
	NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
	NUMMEN   = 'NUMBER OF ADULT MALES IN HOUSEHOLD'
	NUMWOMEN = 'NUMBER OF ADULT FEMALES IN HOUSEHOLD'
	GENHLTH  = 'GENERAL HEALTH'
	PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
	MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
	POORHLTH = 'POOR PHYSICAL HEALTH'
	HLTHPLAN = 'HAVE ANY KIND OF HEALTH PLAN'
	NOCOVR12 = 'NO HEALTH CARE COVERAGE IN PAST 12 MNTHS'
	PERSDOC2 = 'HAVE PERS DOC OR HLTH CARE PROVIDER'
	EXERANY2 = 'PARTICIPATE IN ANY PHYSICAL ACTIVITY'
	BPHIGH2  = 'EVER TOLD BLOOD PRESSURE HIGH'
	BPMEDS   = 'TAKING BLOOD PRESSURE MEDICINE'
	BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
	CHOLCHK  = 'HOW LONG SINCE CHOLESTEROL CHECKED'
	TOLDHI2  = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
	ASTHMA2  = 'EVER HAD ASTHMA'
	ASTHNOW  = 'HAVE ASTHMA NOW'
	DIABETES = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
	PAIN12MN = 'HAD PAIN, ACHING, STIFFNESS, SWELLING'
	SYMTMMTH = 'SYMPTOMS PRESENT AT LEAST ONE MONTH'
	LMTJOINT = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
	JOINTRT  = 'SEEN HEALTH PROF. ABOUT JOINT SYMPTOMS'
	HAVARTH  = 'TOLD HAVE ARTHRITIS BY DOCTOR'
	TRTARTH  = 'CURRENTLY TREATED BY DOC FOR ARTHRITIS'
	FLUSHOT  = 'HAD FLU SHOT IN PAST 12 MONTHS'
	PNEUVAC2 = 'EVER HAD PNEUMONIA VACCINATION'
	SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
	SMOKEDAY = 'FREQUENCY OF DAYS NOW SMOKING'
	STOPSMK2 = 'QUIT SMOKING A DAY OR MORE IN PAST YEAR'
	ALCDAYS  = 'ALCOHOLIC BEVERAGES IN PAST 30 DAYS'
    DRNKANY2 = 'CONSUME ALCHOL BEVERAGES PAST 30 DAYS'
    ALCOHOL2 = 'HOW OFTEN DRINK LIQUOR'
	AVEDRNK  = 'AVERAGE NUMBER OF DRINKS PER OCCASION'
	DRNK2GE5 = 'FIVE OR MORE DRINKS ON AN OCCASION'
	FIREARM3 = 'FIREARMS IN HOME'
	AGE	     = 'REPORTED AGE IN YEARS'
	HISPANC2 = 'HISPANIC ORIGIN'
	MRACE    = 'REPORTED RACE(S)'
	MRACEORG = 'REPORTED RACE(S) ORIGINAL ORDER'
	MRACEASC = 'REPORTED RACE(S) ASCENDING ORDER'
	ORACE2   = 'REPORTED BEST RACE'
	MARITAL  = 'MARITAL STATUS'
	CHILDREN = 'NUMBER OF CHILDREN'
	EDUCA	 = 'EDUCATION LEVEL'
	EMPLOY   = 'EMPLOYMENT STATUS'
	INCOME2  = 'INCOME LEVEL'
	WEIGHT   = 'REPORTED WEIGHT IN POUNDS'
	HEIGHT   = 'REPORTED HEIGHT IN FEET AND INCHES'
	HTIN	 = 'REPORTED HEIGHT IN INCHES'
	HTM	     = 'REPORTED HEIGHT IN METERS'
	WTKG	 = 'REPORTED WEIGHT IN KILOGRAMS'
	CTYCODE  = 'COUNTY CODE'
	NUMHHOL2 = 'MORE THAN ONE TELPHONE NUMBER IN HH'
	NUMPHON2 = 'NUMBER OF UNIQUE PHONE NUMBERS IN HH'
	CELLPHON = 'NUMBER OF ADULTS IN HH USE CELL PHONES'
	SEX	     = 'SEX'
	PREGNT2  = 'ARE YOU NOW PREGNANT'
	QLACTLM2 = 'ACTICITIES LIMITED DUE TO HEALTH PROBLEM'
	USEEQUIP = 'HEALTH PROBLEMS REQUIRE EQUIPMENT'
	JOBACTIV = 'PHYSICAL ACTIVITY AT WORK'
	_VIGPAMN = 'MINS. OF VIGOROUS PHYSYSICAL ACTIVITY'
	_MODPAMN = 'MINS. OF MODERATE PHYSYSICAL ACTIVITY'
	MODPACT  = 'MODERATE PHYSICAL ACTIVITY'
	MODPADAY = 'DAYS PER WEEK OF MOD. PHYS. ACT.'
	MODPATIM = 'MINS. PER DAY OF MOD. PHYS. ACT.'
	VIGPACT  = 'VIGOROUS PHYSICAL ACTIVITY'
	VIGPADAY = 'DAYS PER WEEK OF VIG. PHYS. ACT.'
	VIGPATIM = 'MINS. PER DAY OF VIG. PHYS. ACT.'
	PSATEST  = 'EVER HAD A PSA TEST'
	PSATIME  = 'HOW LONG SINCE LAST PSA TEST'
	DIGRECEX = 'EVER HAD A DIGITAL RECTAL EXAM'
	DRETIME  = 'HOW LONG SINCE LAST DIGITAL RECTAL EXAM'
	PROSTATE = 'EVER TOLD HAD PROSTATE CANCER'
	PROSHIST = 'RELATIVES WITH PROSTATE CANCER'
	BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
	LSTBLDS2 = 'HOW LONG SINCE LAST HOME BLOOD STOOL TST'
	HADSIGM2 = 'EVER HAD A SIGMOIDOSCOPY/COLONOSCOPY'
	LASTSIG2 = 'HOW LONG SINCE SIGMOIDOSCOPY/COLONOSCOPY'
	HIVTF1A  = 'REDUCE PREGNANT WOMAN PASS HIV TO BABY'
	HIVTF1B  = 'TREAT HIV-PERSON TO LIVE LONGER'
	HIVOPT1A = 'HIV TREATMENTS EFFECTIVE'
	HIVOPT1B = 'IMPORTANT TO KNOW HIV STATUS'
	HIVTST3  = 'EVER TSTD FOR HIV OTHR THAN BLOOD DONATN'
	HIVTSTDT = 'MONTH AND YEAR OF HIV TEST'
	RSNTST3  = 'MAIN REASON FOR HIV TEST'
	WHRTST4  = 'WHERE WAS LAST BLOOD TEST FOR HIV'
	PCSAIDS2 = 'PAST 12MO HIV-PREVENTION USING CONDOMS'
	DIABAGE2 = 'AGE WHEN TOLD DIABETIC'
	INSULIN  = 'NOW TAKING INSULIN'
	DIABPILL = 'NOW TAKING DIABETES PILLS'
	BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
	FEETCHK2 = 'HOW OFTEN CHECK FOR SORES/IRRITATIONS'
	FEETSORE = 'EVER HAD SORES/IRRITATIONS 4+ WEEKS'
	DOCTDIAB = 'TIMES SEEN HEALTH PROF FOR DIABETES'
	CHKHEMO2 = 'TIMES CHECK FOR GLYCOSYLATED HEMOGLOBIN'
	FEETCHK  = 'TIMES HEALTH PROF CHECK FEET PAST 12 MOS'
	EYEEXAM  = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
	DIABEYE  = 'EVER TOLD DIABETES HAS AFFECTED EYES'
	DIABEDU  = 'EVER TAKEN CLASS TO MANAGE DIABETES'
	SEXINTMN = 'HOW MANY PARTNERS IN PAST 12 MONTHS'
	SEXCONDM = 'CONDOM USED LAST INTERCOURSE'
	CONDLAST = 'WHY WAS CONDOM USED'
	CONEFF2  = 'CONDOM EFFECTIVENESS AGAINST HIV'
	NEWPARTN = 'NUMBER NEW SEX PRTNRS IN LAST 12 MONTHS'
	HIVRISK  = 'ANY HIGH RISK SITUATIONS APPLY'
	STDTREAT = 'TREATED FOR STD OR VD IN PAST FIVE YEARS'
	STDCLIN  = 'TREATED AT HEALTH DEPT STD CLINIC?'
	SEXBEHA2 = 'CHANGED SEXUAL BEHAVIOR LAST 12 MOS.'
	SELCPTN3 = 'DECREASE NUMB SEX PTNRS OR ABSTINENT'
	SEX1PTN3 = 'NOW HAVE SEX WITH ONLY THE SAME PARTNER'
	USECOND3 = 'NOW ALWAYS USE CONDOMS FOR PROTECTION'
	HLTHPRB2 = 'WHAT IS MAJOR HEALTH PROBLEM'
	LONGLMT2 = 'HOW LONG ACTIVITIES LIMITED'
	QLPERSN2 = 'NEED OTHERS TO HELP WITH PERSONAL CARE'
	QLROUTN2 = 'NEED OTHERS TO HELP WITH ROUTINE NEEDS'
	PAINACT2 = 'TIMES IN PAST MONTH PAIN INTERFERED'
	QLMENTL2 = 'TIMES IN PAST MONTH FELT DEPRESSED'
	QLSTRES2 = 'TIMES IN PAST MONTH BEEN STRESSED'
	QLREST2  = 'TIMES IN PAST MONTH NOT ENOUGH REST'
	QLHLTH2  = 'TIMES IN PAST MONTH FELT HEALTHY'
	QLPCHEL2 = 'WHO HELPS WITH PERSONAL CARE NEEDS'
	QLPCLEV2 = 'ADEQUACY OF PERSONAL CARE HELP'
	QLRCHEL2 = 'WHO HELPS WITH ROUTINE NEEDS'
	QLRCLEV2 = 'ADEQUACY OF ROUTINE HELP'
	RSNOCOV2 = 'MAIN REASON WITHOUT HEALTH CARE COVERAGE'
	PSTPLAN2 = 'HOW LONG WITHOUT HEALTH CARE COVERAGE'
	RSWOCOV2 = 'REASON N0 COVERAGE IN PAST TWELVE MONTHS'
	PRIMCARE = 'PARTICULAR DOCTOR OR CLINIC'
	MOSTCARE = 'ONE PLACE YOU GO MOST OFTEN'
	FACILIT2 = 'KIND OF PLACE YOU GO TO MOST OFTEN'
	MEDCOST  = 'TIME WHEN COULD NOT AFFORD TO SEE DOCTOR'
	CHECKUP  = 'HOW LONG SINCE LAST ROUTINE CHECKUP'
	HADMAM   = 'HAVE YOU EVER HAD A MAMMOGRAM'
	HOWLONG  = 'HOW LONG SINCE LAST MAMMOGRAM'
	WHYDONE  = 'REASON YOU HAD MAMMOGRAM'
	PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
	LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
	REASEXAM = 'REASON YOU HAD BREAST PHYSICAL EXAM'
	HADPAP   = 'EVER HAD A PAP SMEAR TEST'
	LASTPAP  = 'WHEN WAS LAST PAP SMEAR'
	WHYPAP   = 'REASON YOU HAD PAP SMEAR'
	HADHYST2 = 'EVER HAD A HYSTERECTOMY'
	LASTDEN2 = 'HOW LONG SINCE LAST DENTIST VISIT'
	RMVTEETH = 'NUMBER OF PERMANENT TEETH REMOVED'
	DENCLEAN = 'HOW LONG SINCE LAST TEETH CLEANING'
	REASDENT = 'MAIN REASON NOT VISIT DENTIST PAST YR'
	DENTLINS = 'DENTAL INSURANCE COVERAGE'
	ASTHMAGE = 'AGE FIRST TOLD HAD ASTHMA'
	ASATTACK = 'HAD ASTHMA ATTACK PAST 12 MOS.'
	ASERVIST = 'ASTHMA VISIT TO ER PAST 12 MOS.'
	ASDRVIST = 'ASTHMA VISIT TO DR PAST 12 MOS.'
	ASRCHKUP = 'ROUTINE DR ASTHMA VISIT PAST 12 MOS.'
	ASACTLIM = 'ASTHMA LIMITED ACTIVITY PAST 12 MOS.'
	ASYMPTOM = 'HAD ASTHMA SYMPTOMS PAST 30 DAYS'
	ASNOSLEP = 'SLEEP DIFFICULT ASTHMA PAST 30 DAYS'
	ASTHMEDS = 'HOW OFTEN TAKE ASTHMA MEDS PAST 30 DAYS'
	ASTHCHLD = 'NUMBER OF CHILDREN IN HH WITH ASTHMA'
	ASKIDHAS = 'DOES CHILD/CHILDREN STILL HAVE ASTHMA'
	HASYMP1  = 'JAW,NECK,BACK PAIN HA SYMPS'
	HASYMP2  = 'WEAK,LIGHTHEADED,FAINT FEELING HA SYMPS'
	HASYMP3  = 'CHEST PAIN/DISCOMFORT HA SYMPS'
	HASYMP4  = 'TROUBLE SEEING BOTH EYES HA SYMPS'
	HASYMP5  = 'ARM,SHOULDER PAIN/DISCOMFORT HA SYMPS'
	HASYMP6  = 'SHORTNESS OF BREATH HA SYMPS'
	STRSYMP1 = 'CONFUSION, TROUBLE SPEECH STR SYMPS'
	STRSYMP2 = 'NUMB/WEAK FACE/ARM/LEG STR SYMPS'
	STRSYMP3 = 'TROUBLE SEEING BOTH EYES STR SYMPS'
	STRSYMP4 = 'CHEST PAIN/DISCOMFORT STR SYMPS'
	STRSYMP5 = 'TROUBLE WALKING/DIZZY/BALANCE STR SYMPS'
	STRSYMP6 = 'SEVERE UNKNOWN HEADACHE STR SYMPS'
	FIRSTAID = 'FIRST THING TO DO FOR HA/STR'
	CVDFAT02 = 'ARE YOU EATING FEWER FAT/CHOLESTEROL'
	CVDFVG01 = 'ARE YOU EATING MORE FRUITS/VGETABLES'
	CVDEXR03 = 'ARE YOU MORE PHYSICALLY ACTIVE'
	CVDFATR2 = 'DOCTOR ADVISED FEWER FAT/CHOLESTEROL'
	CVDFVEG  = 'DOCTOR ADVISED MORE FRUITS/VGETABLES'
	CVDEXRS2 = 'DOCTOR ADVISED MORE PHYSICALLY ACTIVE'
	CVDINFR2 = 'EVER TOLD HAD MYOCARDIAL INFARCTION'
	CVDCRHD2 = 'EVER TOLD HAD CORONARY HEART DISEASE'
	CVDSTRK2 = 'EVER TOLD HAD STROKE'
	HATTKAGE = 'AGE OF FIRST HEART ATTACK'
	STROKAGE = 'AGE OF FIRST STROKE'
	CVDREHAB = 'DO ANY POST HA/STR REHAB'
	CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
	ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
	WHYASPAN = 'TAKE ASPIRIN TO RELIEVE PAIN'
	WHYASPHA = 'TAKE ASPIRIN TO REDUCE HEART ATTACK'
	WHYASPSK = 'TAKE ASPIRIN TO REDUCE STROKE'
	FRUITJUI = 'HOW OFTEN DO YOU DRINK FRUIT JUICES'
	FRUIT	= 'HOW OFTEN DO YOU EAT FRUIT'
	GREENSAL = 'HOW OFTEN DO YOU EAT GREEN SALAD'
	POTATOES = 'HOW OFTEN DO YOU EAT POTATOES'
	CARROTS  = 'HOW OFTEN DO YOU EAT CARROTS'
	VEGETABL = 'SERVINGS OF VEGETABLES'
	LOSEWT   = 'TRYING TO LOSE WEIGHT'
	MAINTAIN = 'TRYING TO MAINTAIN CURRENT WEIGHT'
	FEWCAL   = 'FEWER CALORIES AND/OR LESS FAT'
	PHYACT   = 'INCREASED PHYSICAL ACTIVITY'
	WTDESIRE = 'DESIRED WEIGHT'
	DRADVICE = 'PROFESSIONAL ADVICE ABOUT WEIGHT'
	VITAMINS = 'CURRENTLY TAKE VIT PILLS OR SUPPLEMENTS'
	MULTIVIT = 'ANY OF VITS/SUPPLEMENTS A MULTIVITAMIN'
	FOLICACD = 'ANY VITAMINS CONTAIN FOLIC ACID'
	TAKEVIT  = 'HOW OFTEN TAKE VITAMIN OR SUPPLEMENT'
	RECOMMEN = 'REASONS HLTH EXPERTS RECMND FOLIC ACID'
	FIRSTSMK = 'AGE FIRST SMOKED CIGARETTE'
	REGSMK   = 'AGE FIRST REGULARLY SMOKED CIGS'
	LASTSMK  = 'HOW LONG SINCE LAST SMOKED CIGS'
	GETCARE  = 'DR VISIT TO GET CARE FOR SELF'
	QUITSMOK = 'HEALTH PROF EVER ADVISED TO QUIT SMOKING'
	HOUSESMK = 'SMOKING ALLOWED IN HOME'
	INDOORS  = 'INDOOR WORK LOCATION'
	SMKPUBLC = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
        SMKWORK  = 'SMOKING POLICY AT WORK FOR WORK AREAS'
	USEEVER2 = 'EVER USED SMOKELESS TOBACCO PRODUCTS'
	USENOW2  = 'CURRENTLY USE SMOKELESS TOBACCO PRODUCTS'
	CIGAR2   = 'EVER SMOKED CIGAR'
	CIGARNOW = 'CURRENTLY SMOKE CIGARS'
	PIPESMK  = 'EVER SMOKED PIPE'
	PIPENOW  = 'CURRENTLY SMOKE PIPES'
	BIDISMK  = 'EVER SMOKED BIDI'
	BIDINOW  = 'CURRENTLY SMOKE BIDIS'
	STATEQUE = 'STATE ADDED QUESTIONS'
	DISMOD   = 'DISABILITY MODULE'
	ENDOFREC = 'END OF RECORD MARKER (1)'
	_QSTVER  = 'QUESTIONAIRE VERSION'
	_STSTR   = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
	_STRWT   = 'STRATUM WEIGHT'
	_RAW	 = "RAW: # ADULTS IN HH/# PH #'S TO HH"
	_WT2	 = 'DESIGN WEIGHT'
	_POSTSTR = 'POST STRATIFICATION WEIGHT'
	_FINALWT = 'FINAL WEIGHT'
	_REGION  = 'REGION'
	_PRACE   = 'PREFERRED RACE'
	_MRACE   = 'NON-HISPANIC RACE INCLUDING MULTI-RACIAL'
    RACE2    = 'RACE/ETHNICITY COMBINATION CODES'
	_RACEG3_ = 'POSTSTRTFCATION RACE GROUP CODES'
	_AGEG_   = 'POSTSTRATFCATION AGE GROUP CODES'
	_SEXG_   = 'POSTSTRATFCATION GENDER GRP CODES'
	_IMPAGE  = 'IMPUTED AGE'
	_MSACODE = 'METROPOLITAN STATISTICAL AREA CODE'
	_SMOKER2 = 'SMOKING STATUS(2)'
	_DRNKMO  = 'TOTAL NUMBER DRINKS A MONTH'
	_DRNKDAY = 'DRINKS PER DAY'
    _RFBINGE = 'BINGE DRINKING'
    _RFDRHVY = 'HEAVY ALCOHOL CONSUMPTION'
    _RFDRKMN = 'HEAVY ALCOHOL CONSUMPTION MEN'
    _RFDRKWM = 'HEAVY ALCOHOL CONSUMPTION WOMEN'
	_BMI2	 = 'BODY MASS INDEX'
	_BMI2CAT = '_BMI2 CATEGORIZED'
	_RFBMI2  = 'OVERWEIGHT OR OBESE'
	_TOTINDA = 'LEISURE TIME PHYSICAL ACTIVITY'
    _RFPAMOD = 'RISK FOR NOT MEETING MOD PA REC'
    _RFPAVIG = 'RISK FOR NOT MEETING VIG PA REC'
    _RFPAREC = 'RISK FOR NOT MEETING REG PA REC'
	_SMKLESS = 'SMOKELESS STATUS'
	_FRTSERV = 'DAILY SERVINGS OF FRUITS AND VEGETABLES'
	_FRTINDX = 'SUMMARY INDEX FOR FRUITS AND VEGETABLES'
	_RFHYPE3 = 'HYPERTENSION(3)'
	_RFSMOK2 = 'SMOKING(2)'
	_RFTOBAC = 'SMOKELESS TOBACCO (CURRENT USER)'
	_CHOLCHK = 'CHOLESTEROL CHECKED'
	_RFCHOL  = 'RISK FOR HIGH CHOLESTEROL'
	_AGEG	 = 'REPORTED AGE IN THREE AGE GROUPS'
	_AGEG5YR = 'REPORTED AGE IN 5 YEAR AGE CATEGORIES'
	_AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS'
	_RACEG2  = 'NON-HISPANIC WHITES/ALL OTHERS'
	_RACEGR2 = 'RACE AND ETHNICITY'
	_IMPNPH  = 'IMPUTTED # OF PHONES USED IN WEIGHTING'
	_CNRACE  = '# CENSUS RACE CATEGORIES CHOSEN'
	_CNRACEC = 'COLLAPSED # CENSUS RACE CATS. CHOSEN'
    _HASCJS  = 'CJS (CHRONIC JOINT SYMPTOMS) 2=YES,1=NO'
    _CJSLMT  = 'CJS AND LIMITED 2=YES,1=NO'
    _CJSARTH = 'CJS OR DR. DIAGNOSED ARTHRITIS 2=YES,1=NO'

;

FORMAT
  CELLPHON                                                      UNK1DIG.
  CHILDREN                                                      CHILDREN.
  JOBACTIV                                                      JOBACTIV.
  AGE                                                           AGEGROUP.
  ASPUNSAF                                                      ASPUNSAF.
  PSATIME  DRETIME                                              TIME3F.
  HIVTF1A HIVTF1B                                               TRUEFALS.
  DIABAGE2                                                      DIABAGE.
  HLTHPLAN
  EXERANY2  BPHIGH2 BLOODCHO ASTHMA2 PAIN12MN JOINTRT
  HAVARTH  FLUSHOT PNEUVAC2 SMOKE100 FIREARM3 HISPANC2
  NUMHHOL2 QLACTLM2 USEEQUIP MODPACT VIGPACT DRNKANY2
                                                                YNDR.
    ASTHNOW  BLDSTOOL
    CVDASPRN CVDCRHD2
    CVDEXR03 CVDEXRS2 CVDFAT02 CVDFATR2 CVDINFR2
    CVDSTRK2
    FOLICACD HADHYST2  HADMAM
    HADPAP   HADSIGM2
    HIVRISK  HIVTST3
    INDOORS  INSULIN  LMTJOINT LOSEWT
    MAINTAIN MOSTCARE MULTIVIT
    PHYACT
    PREGNT2 PROFEXAM NOCOVR12  SELCPTN3
    SEX1PTN3 SEXBEHA2 SEXCONDM STDCLIN
    STDTREAT STOPSMK2 SYMTMMTH
    TRTARTH  USECOND3 VITAMINS
    WHYASPAN WHYASPHA WHYASPSK _RFSMOK2
    BPMEDS   TOLDHI2
    PSATEST PROSTATE PROSHIST
    HIVTST3 PCSAIDS2 DIABPILL FEETSORE DIABEYE
    DIABEDU QLPERSN2 QLROUTN2 DENTLINS ASATTACK
    CVDFVG01 CVDEXR03 CVDFATR2
    CVDFVEG CVDEXRS2 CVDINFR2 CVDCRHD2 CVDSTRK2
    CVDREHAB GETCARE QUITSMOK USEEVER2 CIGAR2
    PIPESMK  BIDISMK
    DIGRECEX MEDCOST
                                                                YNDRM.
  HASYMP1 HASYMP2 HASYMP3 HASYMP4 HASYMP5
    HASYMP6 STRSYMP1 STRSYMP2 STRSYMP3 STRSYMP4
    STRSYMP5 STRSYMP6                                           YESNDKR.
  BLDSUGAR FEETCHK2                                             BLDSUGAR.
  CARROTS                                                       SERVINGS.
  CHOLCHK DENCLEAN                                              TIME2F.
  DRNK2GE5 AVEDRNK DOCTDIAB FEETCHK
   QLMENTL2 PAINACT2 QLSTRES2 QLREST2 QLHLTH2
   ASTHCHLD ASKIDHAS
   FIRSTSMK
                                                                UNK2DIG.
  CHKHEMO2                                                      CHKHEMOA.
  MODPADAY VIGPADAY                                             MODPADAY.
  CONDLAST                                                      CONDLAST.
  CONEFF2                                                       CONEFF.
  HIVOPT1A HIVOPT1B                                             HIVOPT.
  DIABETES                                                      DIABETES.
  DISPCODE                                                      DISPFMT.
  DRADVICE                                                      DRADVICE.
  EDUCA                                                         EDUCAF.
  EMPLOY                                                        EMPLOYA.
  HEIGHT ASACTLIM MODPATIM VIGPATIM
    ALCDAYS                                                     UNK3DIG.
  CTYCODE                                                       UNK3ADIG.
  EYEEXAM                                                       EYEEXAM.
  FACILIT2                                                      FACILIT.
  FEWCAL                                                        FEWCAL.
  FRUIT FRUITJUI GREENSAL VEGETABL POTATOES                     SERVINGS.
  GENHLTH                                                       HLTHSTAT.
  HOWLONG LASTPAP LENGEXAM                                      TIME3F.
  INCOME2                                                       INCOME.
  LASTDEN2 LSTBLDS2 CHECKUP                                     TIME2F.
  LASTSIG2                                                      TIME2AF.
  MARITAL                                                       MARITALF.
  MENTHLTH                                                      UNK2DIG.
  NUMPHON2                                                      NUMPHONS.
  PSTPLAN2                                                      TIME1F.
  NEWPARTN PHYSHLTH POORHLTH                                    UNK2DIG.
  PRIMCARE                                                      PRIMCARE.
  REASEXAM                                                      WHYDONE.
  RECOMMEN                                                      REASONS.
  RMVTEETH                                                      RMVTEETH.
  RSNOCOV2 RSWOCOV2                                             RSNNOCOV.
  RSNTST3                                                       WHYTEST.
  SEX                                                           SEXFMT.
  SEXINTMN                                                      UNK2DIG.
  SMKPUBLC                                                      SMKPUBLC.
  SMKWORK                                                       SMKWORK.
  SMOKEDAY USENOW2 CIGARNOW PIPENOW BIDINOW                     SMOKEDAY.
  TAKEVIT                                                       SUPPLE.
  WEIGHT WTDESIRE                                               WEIGHT.
  WHRTST4                                                       TESTAIDS.
  WHYDONE                                                       WHYDONE.
  WHYPAP                                                        WHYPAP.
  WINDDOWN                                                      WINDDOWN.
  _AGE65YR                                                      _AGE65YR.
  _AGEG_                                                       _AGEGFMT.
  _AGEG5YR                                                     _AGEG5YR.
  _CHOLCHK                                                     _CHOLCHK.
  _FRTINDX                                                     FRTINDX.
  _QSTVER                                                      _QSTVER.
  _RFSMOK2                                                     _RFSMOK.
  _RFTOBAC                                                     _RFTOBAC.
  _SEXG_                                                       _SEXG_.
  _SMKLESS                                                     _SMKLESS.
  _SMOKER2                                                     _SMOKER.
  _STATE                                                       _STATE.
  LISTSTAT                                                     LISTSTAT.
  PRECALL                                                      PRECALL.
  PERSDOC2                                                     PERSDOC.
  HLTHPRB2                                                     HLTHPROB.
  QLPCHEL2 QLRCHEL2                                            QLHELP.
  QLPCLEV2 QLRCLEV2                                            QLLEVL.
  REASDENT                                                     REASDENT.
  ASTHMAGE                                                     ASTHMAGE.
  ASYMPTOM                                                     ASTHSYMP.
  ASNOSLEP                                                     ASNOSLEP.
  ASTHMEDS                                                     ASTHMEDS.
  FIRSTAID                                                     FIRSTAID.
  REGSMK                                                       UNK2DIG.
  LASTSMK                                                      TIME4F.
  HOUSESMK                                                     HOUSESMK.
  LONGLMT2                                                    LONGACT.
  _AGEG5YR                                                     _AGEG5Y.
  _AGE65YR                                                     _AGE65YR.
  _RFBMI2  _RFHYPE3 _RFCHOL  _HASCJS  _CJSLMT
  _CJSARTH _RFSMOK2 _RFBINGE _RFDRHVY _RFDRKMN
   _RFDRKWM _RFPAMOD _RFPAVIG _TOTINDA _RFTOBAC
  _RFCHOL _RFBINGE _RFDRHVY _RFPAVIG
                                                               _RF.
  _PRACE                                                       _PRACE.
  ORACE2                                                       ORACE.
  _MRACE                                                       _MRACE.
  RACE2                                                        RACE2F.
  _RACEG2                                                      _2RACEG.
  _RACEGR2                                                     _2RACEGR.
  _RFPAREC                                                     _RFPAREC.
  PRECALL                                                      PRECALL.
  _DENSTR                                                      _DENSTR.
  _BMI2CAT                                                     _BMI2CAT.
  FMONTH                                                       MTHFMT.
  ASDRVIST ASERVIST ASRCHKUP                                   ASDRVIST.
  HATTKAGE STROKAGE                                            HATTKAGE.
  HIVTSTDT                                                     UNK4ADIG.
  _BMI2                                                        UNK6DIG.
  _DRNKMO                                                      _DRNKMO.
  _IMPNPH                                                      _IMPNPH.
  _RACEG3_                                                     _RACEG.
  _IMPAGE                                                      _IMPAGE.
  ;
  _PSU=SEQNO;
RUN;