* INSTRUCTIONS:                                                                          ;
* SPECIFY PATH OF RAW DATAFILE ON LINE 5, AND PATH OF WHERE SAS DATASET IS TO BE STORED  ;
* ON LINE 8                                                                              ;

FILENAME DATAIN '<PATH OF INPUT STATE RAW ASCII DATAFILE>' LRECL = 880 ;
* EXAMPLE: FILENAME DATAIN 'Q:\BRFSS\1999\ME\ME99COMP.DAT' LRECL = 880 ;                 ;

LIBNAME DATAOUT '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>' ;
* EXAMPLE: LIBNAME DATAOUT 'C:\' ;                                                       ;
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.SD2                               ;
RUN ;

/*****************************************************************************************
 * FILE NAME:     SASOUT99.SAS
 *
 * PROGRAMMER:    J. D. HATMAKER, TRW
 *
 * DESCRIPTION:   THIS PROGRAM CONVERTS A STATES RAW ASCII DATAFILE INTO A SAS DATABASE
 *
 * EXTERNAL REFERENCES:
 *    TYPE         NAME                 DESCRIPTION OF REFERENCE
 * ----------  ---------------  ----------------------------------------------------------
 * INPUT       DATAIN           FILEREF OF RAW ASCII DATAFILE
 *
 * OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF RAW ASCII DATA AS SPECIFIED IN
 *                              DATAIN FILEREF
 *
 * MODIFICATION HISTORY:
 * NUM     DATE       PROGRAMMER      DESCRIPTION OF MODIFICATION
 * ---  ---------   --------------   -----------------------------------------------------
 * 002  05/10/2000  J. D. HATMAKER   ADDED DISABLTY VARIABLE TO READ IN DISABILITY DATA
 *                                    IF APPLICABLE/PRESENT
 * 001  04/21/2000  J. D. HATMAKER   CHANGED INPUT STATEMENT FOR STATEQUE TO $CHAR184.
 * 000  03/30/2000  J. D. HATMAKER   INITIAL ISSUE
 *****************************************************************************************/

OPTIONS SOURCE NOTES NODATE PAGENO = 1 ;
TITLE ;
FOOTNOTE ;
RUN ;

DATA DATAOUT.SASDATA ;
 INFILE DATAIN MISSOVER ;
 LENGTH DEFAULT = 3 ;
 LENGTH _PSU 4
        NRECSEL NRECSTR BPSELWT _DENWT _STSTR _GEOWT _RAW
        _CSA _WT1 _POSTSTR _FINALWT _MSACODE _WTFORHT 8 ;
 INPUT
      _STATE        1-2
      _GEOSTR       3-4
      _DENSTR       5
      _PSU          6-11
      _RECORD      12-13
      IDATE       $14-21
      IMONTH      $14-15
      IDAY        $16-17
      IYEAR       $18-21
      INTVID      $22-23
      PHONENUM    $24-31
      AREACODE    $24-26
      PREFIX      $27-29
      SUFFIX      $30-31
      DISPCODE     32-33
      WINDDOWN     34
      SEQNO       $35-44
      NATTMPTS     45-46
      NRECSEL      47-52
      NRECSTR      53-61
      BPSELWT      62-71
      WAKSS1S2     72
      NUMADULT     73-74
      NUMMEN       75
      NUMWOMEN     76
      GENHLTH      77
      PHYSHLTH     78-79
      MENTHLTH     80-81
      POORHLTH     82-83
      HLTHPLAN     84
      MEDICAR2     85
      TYPCOVR1     86-87
      TYPCOVR2     88-89
      NOCOV12      90
      PASTPLAN     91
      MEDCOST      92
      CHECKUP      93
      BPTAKE       94
      BPHIGH       95
      HIGHGT1      96
      BLOODCHO     97
      CHOLCHK      98
      TOLDHI       99
      DIABETES    100
      LASTDEN2    101
      RMVTEETH    102
      DENCLEAN    103
      SUNBURN     104
      NUMBURN     105
      SMOKE100    106
      SMOKEDAY    107
      SMOKENUM    108-109
      SMOKNM30    110-111
      STOPSMOK    112
      LASTSMOK    113-114
      DRINKANY    115
      ALCOHOL     116-118
      NALCOCC     119-120
      DRINKGE5    121-122
      DRINKDRI    123-124
      AGE         125-126
      ORACE       127
      HISPANIC    128
      MARITAL     129
      CHLD04      130
      CHLD0512    131
      CHLD1317    132
      EDUCA       133
      EMPLOY      134
      INCOME2     135-136
      WEIGHT      137-139
      HEIGHT      140-142
      CTYCODE     143-145
      NUMHHOLD    146
      NUMPHONS    147
      SEX         148
      HADMAM      149
      HOWLONG     150
      WHYDONE     151
      PROFEXAM    152
      LENGEXAM    153
      REASEXAM    154
      HADPAP      155
      LASTPAP     156
      WHYPAP      157
      HADHYST     158
      PREGNANT    159
      FLUSHOT     160
      FLUPROV     161-162
      PNEUMVAC    163
      BLDSTOOL    164
      LSTBLDST    165
      HADSIGM     166
      LASTSIGM    167
      CHLDLT16    168-169
      BIKEHLMT    170
      SMKDETE2    171
      GRADE2      172-173
      CONDUSE     174
      GETHIV      175
      DONBLD85    176
      DON12MO     177
      HIVTST2A    178
      HIVTST2B    179
      HIV12MO     180
      TEST12MO    181
      RSNTST2     182-183
      WHRTST3     184-185
      RESULTS     186
      COUNSEL     187

      DIABAGE     188-189    /* MODULE 1 */
      INSULIN     190
      INSLNFRQ    191-193
      BLDSUGAR    194-196
      HEMOGLBN    197
      DOCTDIAB    198-199
      CHKHEMO     200-201
      FEETCHK     202-203
      EYEEXAM     204
      VISNDIST    205
      VISNREAD    206
      VISIONTV    207

      SEXINTMN    208-209    /* MODULE 2 */
      SEXCONDM    210
      CONDLAST    211
      CONEFF2     212
      NEWPARTN    213-214
      HIVRISK     215
      STDTREAT    216
      STDCLIN     217
      SEXBEHA2    218
      SELCPTN3    219
      SEX1PTN3    220
      USECOND3    221

      PREGLST5    222        /* MODULE 3 */
      LSTPREG     223
      LSTPREG2    224
      BRTHCNTL    225
      TYPCNTRL    226-227
      RSNNOBC     228-229
      WHRSVCS     230
      FAMPLAN     231
      LASTUSED    232

      RSNNOCOV    233-234    /* MODULE 4 */
      MCRELNGT    235
      DOCTLIST    236
      CERTDOCT    237
      HLTHCOVR    238
      RSNWOCOV    239-240

      RATECARE    241        /* MODULE 5 */
      PRIMCARE    242
      NOPRIMCR    243-244
      MOSTCARE    245
      FACILIT2    246
      DISTCARE    247
      NUMBDOC2    248
      CHNGDOCT    249
      LASTCHNG    250-251

      ASTHMA      252        /* MODULE 6 */
      ASTHNOW     253

      PCSEATHB    254        /* MODULE 7 */
      PCSEXER     255
      PCSINJPV    256
      PCSDRGAB    257
      PCSALCH     258
      PCSSMOK     259
      PCSAIDS     260

      CVDFATRK    261        /* MODULE 8 */
      CVDEXRSK    262
      CVDFAT02    263
      CVDEXR02    264
      CVDINFAR    265
      CVDCORHD    266
      CVDSTROK    267
      CVDASPRN    268
      ASPUNSAF    269
      WHYASPAN    270
      WHYASPHA    271
      WHYASPSK    272
      PASTMENO    273
      DICSESTR    274
      ESTRPILL    275
      CURESTRO    276
      ESTRHART    277
      ESTRBONE    278
      ESTRFLSH    279

      PAIN12MN    280        /* MODULE 9 */
      SYMTMMTH    281
      LMTJOINT    282
      HAVARTH     283
      TYPEARTH    284-285
      TRTARTH     286

      FRUITJUI    287-289    /* MODULE 10 */
      FRUIT       290-292
      GREENSAL    293-295
      POTATOES    296-298
      CARROTS     299-301
      VEGETABL    302-304

      EXERANY     305        /* MODULE 11 */
      EXERACT1    306-307
      EXERDIS1    308-310
      EXEROFT1    311-313
      EXERHMM1    314-316
      EXEROTH2    317
      EXERACT2    318-319
      EXERDIS2    320-322
      EXEROFT2    323-325
      EXERHMM2    326-328

      LOSEWT      329        /* MODULE 12 */
      MAINTAIN    330
      FEWCAL      331
      PHYACT      332
      WTDESIRE    333-335
      DRADVICE    336

      VITAMINS    337        /* MODULE 13 */
      MULTIVIT    338
      FOLICACD    339
      TAKEVIT     340-342
      RECOMMEN    343

      SUNBLOCK    344        /* MODULE 14 */
      SPFNUM      345-346
      AVOIDSUN    347
      SUNHAT      348
      SUNWEAR     349
      SUNSENS     350
      BURNTYPE    351

      HOWSAFE     352        /* MODULE 15 */
      RENTHOME    353
      CURADRS     354
      NMCLSFRD    355
      ENGHFOOD    356

      TOBACCO     357        /* MODULE 16 */
      INDOORS     358
      SMKPUBLC    359
      SMKWORK     360
      SMKREST     361
      SMKSCHLS    362
      SMKDAYCR    363
      SMKINDOR    364

      USEEVER     365        /* MODULE 17 */
      USENOW      366

 @373 DISABLTY $CHAR42.      /* MODULE 18 - DISABILITY IF APPLICABLE */

 @415 STATEQUE $CHAR184.     /* STATE ADDED QUESTIONS */

 /* SAMPLING DATA, WHICH NORMALLY OCCUPIES COLUMNS 601-733 */
 /* ARE NOT INCLUDED HEREIN, AND THEREFORE ARE SKIPPED     */

      _QSTVER     750
      _STSTR      751-756
      _DENWT      757-766
      _GEOWT      767-776
      _RAW        777-786
      _CSA        787-796
      _WT1        797-806
      _POSTSTR    807-816
      _FINALWT    817-826
      _REGION     827-828
      _RACEG2_    829
      _AGEG_      830-831
      _SEXG_      832
      _IMPAGE     833-834
      _MSACODE    835-838
      RACE        839-840
      _SMOKER2    841
      _DRNKMO     842-845
      _WTFORHT    846-850
      _BMI        851-853
      _TOTINDX    854
      _SMKLESS    855
      _FRTSERV    856-860
      _FRTINDX    861
      _RFHYPE2    862
      _RFSMOK2    863
      _RFDRACU    864
      _RFDRDRI    865
      _RFDRCHR    866
      _RFLIFES    867
      _RFREGUL    868
      _RFOBESE    869
      _RFWHBMI    870
      _RFTOBAC    871
      _CHOLCHK    872
      _BPCHECK    873
      _AGEG       874
      _AGEG5YR    875-876
      _AGE65YR    877
      _RACEG      878
      _RACEGR     879 ;

 LABEL _STATE   = 'STATE FIPS CODE'
       _GEOSTR  = 'STRATUM CODE'
       _DENSTR  = 'DENSITY STRATUM'
       _PSU     = 'PRIMARY SAMPLING UNIT'
       _RECORD  = 'RECORD NUMBER'
       IDATE    = 'DATE OF INTERVIEW'
       IMONTH   = 'MONTH OF INTERVIEW'
       IDAY     = 'DAY OF INTERVIEW'
       IYEAR    = 'YEAR OF INTERVIEW'
       INTVID   = 'INTERVIEWER ID'
       PHONENUM = 'PHONE NUMBER'
       AREACODE = 'AREA CODE'
       PREFIX   = 'PREFIX'
       SUFFIX   = 'SUFFIX'
       DISPCODE = 'DISPOSITION OF INTERVIEW'
       WINDDOWN = 'INTERVIEW IN REGULAR OR WINDDOWN MODE'
       SEQNO    = 'ANNUAL SEQUENCE NUMBER'
       NATTMPTS = 'NUMBER OF ATTEMPTS'
       NRECSEL  = 'NUMBER OF SAMPLE RECORDS FOR STRATUM'
       NRECSTR  = 'NO. OF PH. NOS. IN STRATUM FROM SAMPLE'
       BPSELWT  = 'BASIC PROBABILITY OF SELECTION WEIGHT'
       WAKSS1S2 = 'WAKSBERG STAGE ONE OR STAGE TWO NUMBER'
       NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
       NUMMEN   = 'NUMBER OF ADULT MALES IN HOUSEHOLD'
       NUMWOMEN = 'NUMBER OF ADULT FEMALES IN HOUSEHOLD'
       GENHLTH  = 'GENERAL HEALTH'
       PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
       MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
       POORHLTH = 'POOR PHYSICAL HEALTH'
       HLTHPLAN = 'HAVE ANY KIND OF HEALTH PLAN'
       MEDICAR2 = 'HAVE MEDICARE'
       TYPCOVR1 = 'TYPE COVERAGE PAYING FOR MOST MED CARE'
       TYPCOVR2 = 'TYPE COVERAGE MAYBE NOT CONSIDERED'
       NOCOV12  = 'NO HEALTH CARE COVERAGE IN PAST 12 MNTHS'
       PASTPLAN = 'LAST HAD HEALTH COVERAGE'
       MEDCOST  = 'TIME WHEN COULD NOT AFFORD TO SEE DOCTOR'
       CHECKUP  = 'HOW LONG SINCE LAST ROUTINE CHECKUP'
       BPTAKE   = 'HOW LONG SINCE BLOOD PRESSURE TAKEN'
       BPHIGH   = 'EVER TOLD BLOOD PRESSURE HIGH'
       HIGHGT1  = 'TOLD MORE THAN ONCE BP HIGH'
       BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
       CHOLCHK  = 'HOW LONG SINCE CHOLESTEROL CHECKED'
       TOLDHI   = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
       DIABETES = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
       LASTDEN2 = 'HOW LONG SINCE LAST DENTIST VISIT'
       RMVTEETH = 'NUMBER OF PERMANENT TEETH REMOVED'
       DENCLEAN = 'HOW LONG SINCE LAST TEETH CLEANING'
       SUNBURN  = 'HAD A SUNBURN IN LAST 12 MONTHS'
       NUMBURN  = 'NUMBER OF SUNBURNS'
       SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
       SMOKEDAY = 'FREQUENCY OF DAYS NOW SMOKING'
       SMOKENUM = 'NUMBER OF CIGARETTES NOW SMOKED PER DAY'
       SMOKNM30 = 'CIGS SMOKED WHEN SMOKED LT 30 DAYS'
       STOPSMOK = 'QUIT SMOKING A DAY OR MORE IN PAST YEAR'
       LASTSMOK = 'HOW LONG SINCE LAST SMOKED CIGS'
       DRINKANY = 'ALCOHOLIC BEVERAGES IN PAST MONTH'
       ALCOHOL  = 'HOW OFTEN DRINK LIQUOR'
       NALCOCC  = 'AVERAGE NUMBER OF DRINKS PER OCCASION'
       DRINKGE5 = 'FIVE OR MORE DRINKS ON AN OCCASION'
       DRINKDRI = 'DRINK AND DRIVE'
       AGE      = 'REPORTED AGE IN YEARS'
       ORACE    = 'ORIGINAL REPORTED RACE'
       HISPANIC = 'HISPANIC ORIGIN'
       MARITAL  = 'MARITAL STATUS'
       CHLD04   = 'NUMBER OF CHILDREN  LT  5 YEARS OLD'
       CHLD0512 = 'NUMBER OF CHILDREN 5 TO 12 YEARS OLD'
       CHLD1317 = 'NUMBER OF CHILDREN 13 TO 17 YEARS OLD'
       EDUCA    = 'EDUCATION LEVEL'
       EMPLOY   = 'EMPLOYMENT STATUS'
       INCOME2  = 'INCOME LEVEL'
       WEIGHT   = 'REPORTED WEIGHT IN POUNDS'
       HEIGHT   = 'REPORTED HEIGHT IN FEET AND INCHES'
       CTYCODE  = 'COUNTY CODE'
       NUMHHOLD = 'MORE THAN ONE TELPHONE NUMBER IN HH'
       NUMPHONS = 'NUMBER OF UNIQUE PHONE NUMBERS IN HH'
       SEX      = 'SEX'
       HADMAM   = 'HAVE YOU EVER HAD A MAMMOGRAM'
       HOWLONG  = 'HOW LONG SINCE LAST MAMMOGRAM'
       WHYDONE  = 'REASON YOU HAD MAMMOGRAM'
       PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
       LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
       REASEXAM = 'REASON YOU HAD BREAST PHYSICAL EXAM'
       HADPAP   = 'EVER HAD A PAP SMEAR TEST'
       LASTPAP  = 'WHEN WAS LAST PAP SMEAR'
       WHYPAP   = 'REASON YOU HAD PAP SMEAR'
       HADHYST  = 'EVER HAD A HYSTERECTOMY'
       PREGNANT = 'ARE YOU NOW PREGNANT'
       FLUSHOT  = 'HAD FLU SHOT IN PAST 12 MONTHS'
       FLUPROV  = 'KIND OF PLACE HAD FLU SHOT'
       PNEUMVAC = 'EVER HAD PNEUMONIA VACCINATION'
       BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
       LSTBLDST = 'HOW LONG SINCE LAST HOME BLOOD STOOL TST'
       HADSIGM  = 'EVER HAD A SIGMOIDOSCOPY/COLONOSCOPY'
       LASTSIGM = 'HOW LONG SINCE SIGMOIDOSCOPY/COLONOSCOPY'
       CHLDLT16 = 'AGE OF OLDEST CHILD UNDER AGE 16'
       BIKEHLMT = 'BICYCLE HELMET WORN WHEN RIDING'
       SMKDETE2 = 'LAST TIME TESTED SMOKE DETECTORS'
       GRADE2   = 'GRADE TO BEGIN HIV INFECTN AND AIDS EDUC'
       CONDUSE  = 'ENCOURAGE SEX ACTIVE TEEN TO USE CONDOM'
       GETHIV   = 'CHANCES OF GETTING INFECTED WITH HIV'
       DONBLD85 = 'DONATED BLOOD SINCE MARCH 1985'
       DON12MO  = 'DONATED BLOOD IN PAST 12 MONTHS'
       HIVTST2A = 'EVER TSTD FOR HIV OTHR THAN BLOOD DONATN'
       HIVTST2B = 'EVER TESTED FOR HIV'
       HIV12MO  = 'HIV TST PAST 12MO OTHR THAN BLOOD DONATN'
       TEST12MO = 'TESTED FOR HIV PAST 12 MONTHS'
       RSNTST2  = 'MAIN REASON FOR HIV TEST'
       WHRTST3  = 'WHERE WAS LAST BLOOD TEST FOR HIV'
       RESULTS  = 'RECEIVED RESULTS OF LAST TEST'
       COUNSEL  = 'RECEIVED COUNSELING ABOUT TEST RESULTS'
       DIABAGE  = 'AGE WHEN TOLD DIABETIC'
       INSULIN  = 'NOW TAKING INSULIN'
       INSLNFRQ = 'HOW OFTEN DO YOU USE INSULIN'
       BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
       HEMOGLBN = 'HEARD OF GLYCOSYLATED HEMOGLOBIN'
       DOCTDIAB = 'TIMES SEEN HEALTH PROF FOR DIABETES'
       CHKHEMO  = 'TIMES CHECK FOR GLYCOSYLATED HEMOGLOBIN'
       FEETCHK  = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
       EYEEXAM  = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
       VISNDIST = 'LIMITED VISION SEEING ACROSS STREET'
       VISNREAD = 'LIMITED VISION IN READING PRINT'
       VISIONTV = 'LIMITED VISION IN WATCHING TELEVISION'
       SEXINTMN = 'HOW MANY PARTNERS IN PAST 12 MONTHS'
       SEXCONDM = 'CONDOM USED LAST INTERCOURSE'
       CONDLAST = 'WHY WAS CONDOM USED'
       CONEFF2  = 'CONDOM EFFECTIVENESS AGAINST HIV'
       NEWPARTN = 'NUMBER NEW SEX PRTNRS IN LAST 12 MONTHS'
       HIVRISK  = 'ANY HIGH RISK SITUATIONS APPLY'
       STDTREAT = 'TREATED FOR STD OR VD IN PAST FIVE YEARS'
       STDCLIN  = 'TREATED AT HEALTH DEPT STD CLINIC?'
       SEXBEHA2 = 'CHANGED SEXUAL BEHAVIOR LAST 12 MOS.'
       SELCPTN3 = 'DECREASE NUMB SEX PTNRS OR ABSTINENT'
       SEX1PTN3 = 'NOW HAVE SEX WITH ONLY THE SAME PARTNER'
       USECOND3 = 'NOW ALWAYS USE CONDOMS FOR PROTECTION'
       PREGLST5 = 'PREGNANT IN LAST 5 YEARS'
       LSTPREG  = 'FEEL ABOUT BECOMING PREGNANT-LAST'
       LSTPREG2 = 'FEEL ABOUT BECOMING PREGNANT-CURRENT'
       BRTHCNTL = 'CURRENT BIRTH CONTROL USE'
       TYPCNTRL = 'BIRTH CONTROL TYPE'
       RSNNOBC  = 'REASON NO BIRTH CONTROL'
       WHRSVCS  = 'USUAL SOURCE FOR FEMALE HEALTH CARE'
       FAMPLAN  = 'EVER USE FAMILY PLANNING CLINIC'
       LASTUSED = 'WHEN LAST USED CLINIC'
       RSNNOCOV = 'MAIN REASON WITHOUT HEALTH CARE COVERAGE'
       MCRELNGT = 'HOW LONG HAD THIS HEALTH COVERAGE'
       DOCTLIST = 'BOOK OR LIST OF DOCTORS WITH PLAN'
       CERTDOCT = 'PLAN REQUIRES CERTAIN DOCTOR/CLINIC'
       HLTHCOVR = 'ANY OTHER TYPE HEALTH CARE COVERAGE'
       RSNWOCOV = 'REASON N0 COVERAGE IN PAST TWELVE MONTHS'
       RATECARE = 'RATE SATISFACTION WITH OVERALL CARE'
       PRIMCARE = 'PARTICULAR DOCTOR OR CLINIC'
       NOPRIMCR = 'MAIN REASON NO USUAL SOURCE OF CARE'
       MOSTCARE = 'ONE PLACE YOU GO MOST OFTEN'
       FACILIT2 = 'KIND OF PLACE YOU GO TO MOST OFTEN'
       DISTCARE = 'CONVENIENCE OF MEDICAL FACILITY LOCATION'
       NUMBDOC2 = 'ONE PARTICULAR DOCT FOR ROUTINE MED CARE'
       CHNGDOCT = 'LAST CHANGED DOCTORS'
       LASTCHNG = 'REASON CHANGED DOCTORS LAST TIME'
       ASTHMA   = 'EVER HAD ASTHMA'
       ASTHNOW  = 'HAVE ASTHMA NOW'
       PCSEATHB = 'DOCTOR TALKED ABOUT EATING HABITS'
       PCSEXER  = 'DOC TALKED ABOUT EXERCISE OR PHYS ACTVTY'
       PCSINJPV = 'DOCTOR TALKED ABOUT INJURY PREVENTION'
       PCSDRGAB = 'DOCTOR TALKED ABOUT DRUG ABUSE'
       PCSALCH  = 'DOCTOR TALKED ABOUT ALCOHOL USE'
       PCSSMOK  = 'DOCTOR TALKED ABOUT QUITTING SMOKING'
       PCSAIDS  = 'DOCTOR TALKED ABOUT SEXUAL PRACTICES'
       CVDFATRK = 'DOCTOR ADVISED FEWER FAT/CHOLESTEROL'
       CVDEXRSK = 'DOCTOR ADVISED EXERCISE MORE'
       CVDFAT02 = 'ARE YOU EATING FEWER FAT/CHOLESTEROL'
       CVDEXR02 = 'ARE YOU EXERCISING MORE'
       CVDINFAR = 'EVER TOLD HAD MYOCARDIAL INFARCTION'
       CVDCORHD = 'EVER TOLD HAD CORONARY HEART DISEASE'
       CVDSTROK = 'EVER TOLD HAD STROKE'
       CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
       ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
       WHYASPAN = 'TAKE ASPIRIN TO RELIEVE PAIN'
       WHYASPHA = 'TAKE ASPIRIN TO REDUCE HEART ATTACK'
       WHYASPSK = 'TAKE ASPIRIN TO REDUCE STROKE'
       PASTMENO = 'GONE THROUGH MENOPAUSE'
       DICSESTR = 'DOC DISCUSSED BENEFITS/RISKS OF ESTROGEN'
       ESTRPILL = 'DOCTOR PRESCRIBED ESTROGEN PILLS'
       CURESTRO = 'CURRENTLY TAKING ESTROGEN'
       ESTRHART = 'TAKE/TOOK ESTROGEN TO PREVENT HRT ATTACK'
       ESTRBONE = 'TAKE/TOOK ESTROGEN FOR BONES'
       ESTRFLSH = 'TAKE/TOOK ESTROGEN TO TREAT MENOPAUSE'
       PAIN12MN = 'HAD PAIN, ACHING, STIFFNESS, SWELLING'
       SYMTMMTH = 'SYMPTOMS PRESENT AT LEAST ONE MONTH'
       LMTJOINT = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
       HAVARTH  = 'TOLD HAVE ARTHRITIS BY DOCTOR'
       TYPEARTH = 'TYPE ARTHRITIS DOCTOR DIAGNOSED'
       TRTARTH  = 'CURRENTLY TREATED BY DOC FOR ARTHRITIS'
       FRUITJUI = 'HOW OFTEN DO YOU DRINK FRUIT JUICES'
       FRUIT    = 'HOW OFTEN DO YOU EAT FRUIT'
       GREENSAL = 'HOW OFTEN DO YOU EAT GREEN SALAD'
       POTATOES = 'HOW OFTEN DO YOU EAT POTATOES'
       CARROTS  = 'HOW OFTEN DO YOU EAT CARROTS'
       VEGETABL = 'SERVINGS OF VEGETABLES'
       EXERANY  = 'PARTICIPATE IN ANY PHYSICAL ACTIVITY'
       EXERACT1 = 'TYPE OF PHYSICAL ACTIVITY'
       EXERDIS1 = 'DISTANCE IN MILES AND TENTHS'
       EXEROFT1 = 'HOW MANY TIMES ACTIVITY DONE'
       EXERHMM1 = 'HOW LONG ACTIVITY DONE'
       EXEROTH2 = 'PARTICIPATE IN ANOTHER ACTIVITY'
       EXERACT2 = 'TYPE OF OTHER PHYSICAL ACTIVITY'
       EXERDIS2 = 'DISTANCE IN MILES AND TENTHS'
       EXEROFT2 = 'HOW MANY TIMES SECOND ACTIVITY DONE'
       EXERHMM2 = 'HOW LONG SECOND ACTIVITY DONE'
       LOSEWT   = 'TRYING TO LOSE WEIGHT'
       MAINTAIN = 'TRYING TO MAINTAIN CURRENT WEIGHT'
       FEWCAL   = 'FEWER CALORIES AND/OR LESS FAT'
       PHYACT   = 'INCREASED PHYSICAL ACTIVITY'
       WTDESIRE = 'DESIRED WEIGHT'
       DRADVICE = 'PROFESSIONAL ADVICE ABOUT WEIGHT'
       VITAMINS = 'CURRENTLY TAKE VIT PILLS OR SUPPLEMENTS'
       MULTIVIT = 'ANY OF VITS/SUPPLEMENTS A MULTIVITAMIN'
       FOLICACD = 'ANY VITAMINS CONTAIN FOLIC ACID'
       TAKEVIT  = 'HOW OFTEN TAKE VITAMIN OR SUPPLEMENT'
       RECOMMEN = 'REASONS HLTH EXPERTS RECMND FOLIC ACID'
       SUNBLOCK = 'HOW OFTEN USE SUNSCREEN'
       SPFNUM   = 'SPF OF SUNSCREEN'
       AVOIDSUN = 'HOW OFTEN STAY IN SHADE'
       SUNHAT   = 'HOW OFTEN WEAR HAT'
       SUNWEAR  = 'HOW OFTEN WEAR LONG-SLEEVED SHIRTS'
       SUNSENS  = 'HOW SENSITIVE TO SUN'
       BURNTYPE = 'HOW EASY TO SUNBURN'
       HOWSAFE  = 'HOW SAFE IS NEIGHBORHOOD FROM CRIME'
       RENTHOME = 'RENT OR OWN HOME'
       CURADRS  = 'HOW LONG AT CURRENT ADDRESS'
       NMCLSFRD = 'NUMBR OF FRIENDS/CLOSE RELATIVES TO HELP'
       ENGHFOOD = 'CNCRND ABOUT ENOUGH FOOD IN PAST 30 DAYS'
       TOBACCO  = 'SMOKING IN HOME PAST 30 DAYS'
       INDOORS  = 'INDOOR WORK LOCATION'
       SMKPUBLC = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
       SMKWORK  = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
       SMKREST  = 'SMOKING ALLOWED IN RESTAURANTS'
       SMKSCHLS = 'SMOKING ALLOWED IN SCHOOLS'
       SMKDAYCR = 'SMOKING ALLOWED IN DAY CARE CENTERS'
       SMKINDOR = 'SMOKING ALLOWED IN INDOOR WORK AREAS'
       USEEVER  = 'EVER USED SMOKELESS TOBACCO PRODUCTS'
       USENOW   = 'CURRENTLY USE SMOKELESS TOBACCO PRODUCTS'
       DISABLTY = 'DISABILITY QUESTIONS'
       STATEQUE = 'STATE ADDED QUESTIONS'
       _QSTVER  = 'QUESTIONAIRE VERSION'
       _STSTR   = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
       _DENWT   = 'DENSITY STRATUM WEIGHT'
       _GEOWT   = 'GEOGRAPHIC STRATUM WEIGHT'
       _RAW     = "RAW: # ADULTS IN HH/# PH #'S TO HH"
       _CSA     = 'CLUSTER SIZE ADJUSTMENT'
       _WT1     = 'DESIGN WEIGHT'
       _POSTSTR = 'POST STRATIFICATION WEIGHT'
       _FINALWT = 'FINAL WEIGHT'
       _REGION  = 'REGION'
       _RACEG2_ = 'RACE GROUP CODES USED IN POSTSTRTFCATION'
       _AGEG_   = 'AGE GROUP CODES USED IN POSTSTRATFCATION'
       _SEXG_   = 'GENDER GRP CODES USED IN POSTSTRTFCATION'
       _IMPAGE  = 'IMPUTED AGE'
       _MSACODE = 'METROPOLITAN STATISTICAL AREA CODE'
       RACE     = 'NEW RACE CODE'
       _SMOKER2 = 'SMOKING STATUS(2)'
       _DRNKMO  = 'TOTAL NUMBER DRINKS A MONTH'
       _WTFORHT = 'WEIGHT FOR HEIGHT PERCENT OF MEDIAN'
       _BMI     = 'BODY MASS INDEX'
       _TOTINDX = 'PHYSICAL ACTIVITY LEVEL'
       _SMKLESS = 'SMOKELESS STATUS'
       _FRTSERV = 'DAILY SERVINGS OF FRUITS AND VEGETABLES'
       _FRTINDX = 'SUMMARY INDEX FOR FRUITS AND VEGETABLES'
       _RFHYPE2 = 'HYPERTENSION(2)'
       _RFSMOK2 = 'SMOKING(2)'
       _RFDRACU = 'ACUTE DRINKING'
       _RFDRDRI = 'DRINKING AND DRIVING'
       _RFDRCHR = 'CHRONIC DRINKING'
       _RFLIFES = 'SEDENTARY LIFESTYLE'
       _RFREGUL = 'REGULAR AND SUSTAINED PHYSICAL ACTIVITY'
       _RFOBESE = 'OBESITY (WEIGHT FOR HEIGHT % OF MEDIAN)'
       _RFWHBMI = 'OBESITY (BASED ON BMI)'
       _RFTOBAC = 'SMOKELESS TOBACCO (CURRENT USER)'
       _CHOLCHK = 'CHOLESTEROL CHECKED'
       _BPCHECK = 'BLOOD PRESSURE CHECKED'
       _AGEG    = 'REPORTED AGE IN THREE AGE GROUPS'
       _AGEG5YR = 'REPORTED AGE IN 5 YEAR AGE CATEGORIES'
       _AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS'
       _RACEG   = 'NON-HISPANIC WHITES/ALL OTHERS'
       _RACEGR  = 'RACE AND ETHNICITY' ;
RUN ;
