 FORMAT   ACEDEPRS       ACEDEPRS.
          ACEDIVRC       ACEDIVRC.
          ACEDRINK       ACEDRINK.
          ACEDRUGS       ACEDRUGS.
          ACEHURT        ACEHURT.
          ACEHVSEX       ACEHVSEX.
          ACEPRISN       ACEPRISN.
          ACEPUNCH       ACEPUNCH.
          ACESWEAR       ACESWEAR.
          ACETOUCH       ACETOUCH.
          ACETTHEM       ACETTHEM.
          ADEAT1         AD1EAT.
          ADANXEV        ADANXEV.
          ADDEPEV        ADDEPEV.
          ADDOWN         ADDOWN.
          ADENERGY       ADENERGY.
          ADFAIL         ADFAIL.
          ADLTCHLD       ADLTCHLD.
          ADMOVE         ADMOVE.
          ADPLEASR       ADPLEASR.
          ADSLEEP        ADSLEEP.
          ADTHINK        ADTHINK.
          AGE            AGE.
          ALCDAY4        ALC4DAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASINHALR       ASINHALR.
          ASNOSLEP       ASNOSLEP.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMED3       ASTH3MED.
          ASTHMAGE       ASTHMAGE.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK2       AVE2DRNK.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BRTHCNT3       BRTH3CNT.
          CADULT         CADULT.
          CALLBACK       CALLBACK.
          CAREGIVE       CAREGIVE.
          CASTHDX2       CASTH2DX.
          CASTHNO2       CASTH2NO.
          CELLFON2       CELL2FON.
          CELLFON        CELLFON.
          CHECKUP1       CHECK1UP.
          CHILDAGE       CHILDAGE.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CIASSIST       CIASSIST.
          CIDIAGAZ       CIDIAGAZ.
          CIFAMCAR       CIFAMCAR.
          CIHCPROF       CIHCPROF.
          CIHOWOFT       CIHOWOFT.
          CIINTFER       CIINTFER.
          CIMEDS         CIMEDS.
          CIMEMLOS       CIMEMLOS.
          CINOADLT       CINOADLT.
          CIRBIAGE       CIRBIAGE.
          CNCRAGE        CNCRAGE.
          CNCRDIFF       CNCRDIFF.
          CNCRHAVE       CNCRHAVE.
          CNCRTYPE       CNCRTYPE.
          CPDEMO1        CP1DEMO.
          CPDEMO2        CP2DEMO.
          CPDEMO3        CP3DEMO.
          CPDEMO4        CP4DEMO.
          CRGVMST1       CRGV1MST.
          CRGVAGE        CRGVAGE.
          CRGVCHNG       CRGVCHNG.
          CRGVDIFF       CRGVDIFF.
          CRGVGNDR       CRGVGNDR.
          CRGVHRS        CRGVHRS.
          CRGVLONG       CRGVLONG.
          CRGVPROB       CRGVPROB.
          CRGVRELT       CRGVRELT.
          CSRVCLIN       CSRVCLIN.
          CSRVCTRL       CSRVCTRL.
          CSRVDEIN       CSRVDEIN.
          CSRVDOC        CSRVDOC.
          CSRVINSR       CSRVINSR.
          CSRVINST       CSRVINST.
          CSRVPAIN       CSRVPAIN.
          CSRVRTRN       CSRVRTRN.
          CSRVSUM        CSRVSUM.
          CSRVTRT        CSRVTRT.
          CSTATE         CSTATE.
          CTELNUM1       CTEL1NUM.
          CTELENUM       CTELENUM.
          CVDSTRK3       CVD3STRK.
          CVDCRHD4       CVD4CRHD.
          CVDINFR4       CVD4INFR.
          DENCLEAN       DENCLEAN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRETIME        DRETIME.
          DRNKDRI2       DRNK2DRI.
          DRNK3GE5       DRNK35GE.
          DRNKANY4       DRNK4ANY.
          DROCDY2_       DROCDY2_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EMTSUPRT       EMTSUPRT.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FALLINJ2       FALL2INJ.
          FALL3MN2       FALL32MN.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FLSHTMY1       FLSHT1MY.
          FLSPRMY1       FLSPR1MY.
          FLSYAQ01       FLSYA01Q.
          FLSYAQ02       FLSYA02Q.
          FLSYAQ03       FLSYA03Q.
          FLSYAQ04       FLSYA04Q.
          FLSYAQ05       FLSYA05Q.
          FLSYAQ06       FLSYA06Q.
          FLSYAQ07       FLSYA07Q.
          FLSYAQ08       FLSYA08Q.
          FLSYAQ09       FLSYA09Q.
          FLSYAQ10       FLSYA10Q.
          FLSYCQ01       FLSYC01Q.
          FLSYCQ02       FLSYC02Q.
          FLUSPRY3       FLU2SPRY.
          FLUSHOT4       FLU4SHOT.
          FLUSHCH2       FLUSH2CH.
          FMONTH         FMONTH.
          FPCHLDF2       FP2CHLDF.
          GENHLTH        GENHLTH.
          GP3DYFD1       GP3DY1FD.
          GP3DYPRS       GP3DYPRS.
          GP3DYWTR       GP3DYWTR.
          GPWELPR3       GP3WELPR.
          GPBATRAD       GPBATRAD.
          GPEMRCM1       GPEMR1CM.
          GPEMRIN1       GPEMR1IN.
          GPFLSLIT       GPFLSLIT.
          GPMNDEVC       GPMNDEVC.
          GPNOTEV1       GPNOT1EV.
          GPVACPL1       GPVAC1PL.
          H1N1AV01       H1N101AI.
          H1N1CV01       H1N101CI.
          H1N1AV02       H1N102AI.
          H1N1CV02       H1N102CI.
          H1N1AV03       H1N103AI.
          H1N1CV03       H1N103CI.
          H1N1CV04       H1N104CI.
          H1N1CV05       H1N105CI.
          H1N1CV06       H1N106CI.
          H1N1AQ01       H1N1A01Q.
          H1N1AQ02       H1N1A02Q.
          H1N1AQ03       H1N1A03Q.
          H1N1AQ04       H1N1A04Q.
          H1N1AQ05       H1N1A05Q.
          H1N1AQ06       H1N1A06Q.
          H1N1AQ07       H1N1A07Q.
          H1N1AQ08       H1N1A08Q.
          H1N1AQ09       H1N1A09Q.
          H1N1AQ10       H1N1A10Q.
          H1N1CQ01       H1N1C01Q.
          H1N1CQ02       H1N1C02Q.
          HADSGCO1       HAD1SGCO.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HAVARTH2       HAV2ARTH.
          HAVHPAD        HAVHPAD.
          HEIGHT3        HEIGHT.
          HISPANC2       HISP2ANC.
          HIVRISK2       HIV2RISK.
          HIVTST5        HIV5TST.
          HIVRDTST       HIVRDTST.
          HLTHPLAN       HLTHPLAN.
          HOWLONG        HOWLONG.
          HPVADVC2       HPV2ADVC.
          HPVADSHT       HPVADSHT.
          HPVCHSHT       HPVCHSHT.
          HPVCHVC        HPVCHVC.
          WRKHCF1        HR01HCW.
          DIRCONT1       HR02HCW.
          DRHPAD1        HR03HCW.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INSULIN        INSULIN.
          LANDLINE       LANDLINE.
          LASTSMK1       LAST1SMK.
          LASTPAP2       LAST2PAP.
          LASTDEN3       LAST3DEN.
          LASTSIG3       LAST3SIG.
          LENGEXAM       LENGEXAM.
          LSATISFY       LSATISFY.
          LSTBLDS3       LST3BLDS.
          MARITAL        MARITAL.
          MAXDRNKS       MAXDRNKS.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MSCODE         MSCODE.
          NOBCUSE3       NOBC3USE.
          NUMBURN2       NUM2BURN.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          _CASTHMA       NY.
          ORACE2         O2RACE.
          PAINACT2       PAIN2ACT.
          PDIABTST       PDIABTST.
          PERSDOC2       PERS2DOC.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC3       PNEU3VAC.
          POORHLTH       POORHLTH.
          PREDIAB1       PRE1DIAB.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESD2       PVT2RESD.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RCHISLAT       RCHISLAT.
          RCSRLTN2       RCS2RLTN.
          RCSBRACE       RCSBRACE.
          RCSGENDR       RCSGENDR.
          RCVFVCH4       $RCVFV4C.
          RENTHOM1       RENT1HOM.
          RMVTETH3       RMV3TETH.
          RRATWRK2       RR2ATWRK.
          RRCOGNT2       RR2COGNT.
          RREMTSM2       RR2EMTSM.
          RRPHYSM2       RR2PHYSM.
          RRHCARE3       RR3HCARE.
          RRCLASS2       RRCLASS.
          RSPSTATE       RSPSTATE.
          SCNTLPAD       SCNTLPAD.
          SCNTLWRK       SCNTLWRK.
          SCNTMEAL       SCNTMEAL.
          SCNTMONY       SCNTMONY.
          SCNTPAID       SCNTPAID.
          SCNTVOTE       SCNTVOTE.
          SCNTWORK       SCNTWORK.
          SEATBELT       SEATBELT.
          SEX            SEX.
          SHINGLES       SHINGLES.
          SLEPDAY        SLEPDAY.
          SLEPDRIV       SLEPDRIV.
          SLEPSNOR       SLEPSNOR.
          SLEPTIME       SLEPTIME.
          SMOKE100       SMOK100_.
          SMOKDAY2       SMOK2DAY.
          STOPSMK2       STOP2SMK.
          TELSERV3       TEL3SERV.
          TNSARCNT       TNSARCNT.
          TNSARCV        TNSARCV.
          TNSASHOT       TNSASHOT.
          TYPCNTR5       TYP5CNTR.
          HIVTSTD2       UNK6ADIG.
          USENOW3        USE3NOW.
          USEEQUIP       USEEQUIP.
          VETERAN2       VET2ERAN.
          VHCOMBAT       VHCOMBAT.
          VHCOUNSL       VHCOUNSL.
          VHDRPTSD       VHDRPTSD.
          VHDRTBI        VHDRTBI.
          VHSUICID       VHSUICID.
          VHTAKLIF       VHTAKLIF.
          VICTRCT2       VI2CTRCT.
          VIDFCLT2       VI2DFCLT.
          VIEYEXM2       VI2EYEXM.
          VIGLUMA2       VI2GLUMA.
          VIINSUR2       VI2INSUR.
          VINOCRE2       VI2NOCRE.
          VIPRFVS2       VI2PRFVS.
          VIREDIF2       VI2REDIF.
          VIMACDG2       VIMAC2DG.
          WEIGHT2        WEIGHT.
          WHRTST8        WHR7TST.
          WTKG2          WT2KG.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _PNEUMO2       _2PNEUMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _RFSEAT2       _2RFSEAT.
          _RFSIGM2       _2RFSIGM.
          _RFPAP32       _32RFPAP.
          _DRNKDY3       _3DRNKDY.
          _DRNKMO3       _3DRNKMO.
          _RFDRHV3       _3RFDRHV.
          _RFDRMN3       _3RFDRMN.
          _RFDRWM3       _3RFDRWM.
          _RFSEAT3       _3RFSEAT.
          _RFSMOK3       _3RFSMOK.
          _SMOKER3       _3SMOKER.
          _BMI4          _4BMI.
          _FLSHOT4       _4FLSHOT.
          _RFBING4       _4RFBING.
          _RFBMI4        _4RFBMI.
          _AGEG1_        _AGE1FMT.
          _AGEG2_        _AGE2FMT.
          _AGEG3_        _AGE3FMT.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ALTETH2       _AL2TETH.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CAGEG1_       _CAGEG1_.
          _CAGEG2_       _CAGEG2_.
          _CAGEG3_       _CAGEG3_.
          _CAGEG_        _CAGEG_.
          _CHLDCNT       _CHLDCNT.
          _CIMPAG1       _CIMP1AG.
          _CIMPAG2       _CIMP2AG.
          _CIMPAG3       _CIMP3AG.
          _CIMPAGE       _CIMPAGE.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _CRACE         _CRACE.
          _CRACE1_       _CRACE1_.
          _CRACE2_       _CRACE2_.
          _CRACE3_       _CRACE3_.
          _CRACEG_       _CRACEG_.
          _CSEXG1_       _CSEXG1_.
          _CSEXG2_       _CSEXG2_.
          _CSEXG3_       _CSEXG3_.
          _CSEXG_        _CSEXG_.
          _DENVST1       _DEN1VST.
          _EDUCAG        _EDUCAG.
          _EXTETH2       _EX2TETH.
          _HCVU65        _HCV65U.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _MAM502Y       _MAM502Y.
          _MRACE         _MRACE.
          _PRACE         _PRACE.
          _RACEG31       _RACE31G.
          _RACEG32       _RACE32G.
          _RACEG33       _RACE33G.
          _RACEG3_       _RACEG3_.
          _RACE_G        _RACE_G.
          _RFBLDS2       _RF2BLDS.
          _RFHLTH        _RFHLTH.
          _RFMAM2Y       _RFMAM2Y.
          _RFPSA2Y       _RFPSA2Y.
          _SEXG1_        _SEXG1_.
          _SEXG2_        _SEXG2_.
          _SEXG3_        _SEXG3_.
          _SEXG_         _SEXG_.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
