*****************************************************************************************
* FILE NAME:     DUALOUT10V3.SAS                                                        *
* DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT  *
*                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF       *
* REFERENCES:                                                                           *
* INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES                   *
* FORMATS     FORMATS.SAS7BCAT      SAS FORMATS DATABASE                                *
* OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN       *
*                              <DATAIN> FILEREF                                         *
* UPDATED - 03/30/2011                                                                  *
*****************************************************************************************;
********************************
* Clear Output and Log Windows *
********************************;
DM OUTPUT 'clear' continue;
DM LOG    'clear' continue;
**********************************
* DEFINE SAS ENVIRONMENT OPTIONS *
**********************************;
OPTIONS PAGENO=1 NOFMTERR;
***************************************
* CLEAR EXISTING TITLES AND FOOTNOTES *
***************************************;
TITLE ;
FOOTNOTE ;
RUN ;
******************************************************************
* INSTRUCTIONS:                                                  *
* SPECIFY PATH OF WHERE ASCII DATAFILE IS STORED                 *
* SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED              *
* SPECIFY PATH OF WHERE SAS FORMAT LIBRARY IS STORED             *
* SPECIFY PATH OF WHERE THE FORMAT ASSIGNMET STATEMENT IS STORED *
******************************************************************;

*FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 1518 ;
*****************************************************************************
* EXAMPLE:                                                                  *
*       FILENAME DATAIN 'C:\BRFSS\2010\BRFS10V3.ASC' LRECL = 1518           *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

*LIBNAME DATAOUT V7 '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>'  ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME DATAOUT 'C:\'                                            *
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.sas7bdat             *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*LIBNAME LIBRARY '<PATH OF STORED SAS FORMAT10.SAS7BCAT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME LIBRARY 'C:\'                                            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*FILENAME FORMATIN '<PATH OF FORMAT ASSIGNMENT STATEMENT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          FILENAME FORMATIN 'C:\FORMATSTATEMENT.SAS'                       *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT
_STATE        1-2                     /* Record Identification */
_GEOSTR       3-4
_DENSTR2      5
PRECALL       6
REPNUM        7-12
REPDEPTH      13-14
FMONTH        15-16
IDATE         $17-24
IMONTH        $17-18
IDAY          $19-20
IYEAR         $21-24
INTVID        $25-29
DISPCODE      30-32
SEQNO         33-42
_PSU          33-42
NATTMPTS      43-44
NRECSEL       45-50
NRECSTR       51-59
CTELENUM      60
CELLFON       61
PVTRESID      62
NUMADULT      63-64
NUMMEN        65-66
NUMWOMEN      67-68
GENHLTH       73                      /* Section 1: Health Status */
PHYSHLTH      74-75                   /* Section 2: Healthy Days - Health-Related Quality of Life */
MENTHLTH      76-77
POORHLTH      78-79
HLTHPLAN      80                      /* Section 3: Health Care Access */
PERSDOC2      81
MEDCOST       82
CHECKUP1      83
QLREST2       84-85                   /* Section 4: Sleep */
EXERANY2      86                      /* Section 5: Exercise */
DIABETE2      87                      /* Section 6: Diabetes */
LASTDEN3      88                      /* Section 7: Oral Health */
RMVTETH3      89
DENCLEAN      90
CVDINFR4      91                      /* Section 8: Cardiovascular Disease Prevalence */
CVDCRHD4      92
CVDSTRK3      93
ASTHMA2       94                      /* Section 9: Asthma */
ASTHNOW       95
QLACTLM2      96                      /* Section 10: Disability */
USEEQUIP      97
SMOKE100      98                      /* Section 11: Tobacco Use */
SMOKDAY2      99
STOPSMK2      100
LASTSMK1      101-102
USENOW3       103
AGE           104-105                 /* Section 12: Demographics */
HISPANC2      106
MRACE         $107-112
ORACE2        113
VETERAN2      114
MARITAL       115
CHILDREN      116-117
EDUCA         118
EMPLOY        119
INCOME2       120-121
WEIGHT2       122-125
HEIGHT3       126-129
NUMHHOL2      138
NUMPHON2      139
TELSERV3      140
CPDEMO1       141
CPDEMO2       142
CPDEMO3       143
CPDEMO4       144-146
SEX           147
PREGNANT      148
DRNKANY4      149                     /* Section 13: Alcohol Consumption */
ALCDAY4       150-152
AVEDRNK2      153-154
DRNK3GE5      155-156
MAXDRNKS      157-158
FLUSHOT4      159                     /* Section 14: Immunization */
FLSHTMY1      160-165
FLUSPRY3      166
FLSPRMY1      167-172
PNEUVAC3      173
FALL3MN2      174-175                 /* Section 15: Falls */
FALLINJ2      176-177
SEATBELT      178                     /* Section 16: Seatbelt Use */
DRNKDRI2      179-180                 /* Section 17: Drinking and Driving */
HADMAM        181                     /* Section 18: Women´s Health */
HOWLONG       182
PROFEXAM      183
LENGEXAM      184
HADPAP2       185
LASTPAP2      186
HADHYST2      187
PSATEST       188                     /* Section 19: Prostate Cancer Screening */
PSATIME       189
DIGRECEX      190
DRETIME       191
PROSTATE      192
BLDSTOOL      193                     /* Section 20: Colorectal Cancer Screening */
LSTBLDS3      194
HADSIGM3      195
HADSGCO1      196
LASTSIG3      197
HIVTST5       198                     /* Section 21: HIV/AIDS */
HIVTSTD2      199-204
WHRTST8       205-206
HIVRDTST      207
HIVRISK2      208
EMTSUPRT      209                     /* Section 22: Emotional Support and Life Satisfaction */
LSATISFY      210
FLSYAQ01      222                     /* Section 26: Adult Influenza Like Illness */
FLSYAQ02      223
FLSYAQ03      224
FLSYAQ04      225
FLSYAQ05      226
FLSYAQ06      227
FLSYAQ07      228
FLSYAQ08      229
FLSYAQ09      230-231
FLSYAQ10      232-233
FLSYCQ01      234                     /* Module 30: Child Influenza Like Illness */
FLSYCQ02      235
PDIABTST      245                     /* Module 1: Pre-Diabetes */
PREDIAB1      246
DIABAGE2      247-248                 /* Module 2: Diabetes */
INSULIN       249
BLDSUGAR      250-252
FEETCHK2      253-255
DOCTDIAB      256-257
CHKHEMO3      258-259
FEETCHK       260-261
EYEEXAM       262
DIABEYE       263
DIABEDU       264
PAINACT2      265-266                 /* Module 3: Healthy Days (Symptoms) */
QLMENTL2      267-268
QLSTRES2      269-270
QLHLTH2       271-272
VIDFCLT2      273                     /* Module 4: Visual Impairment and Access to Eye Care */
VIREDIF2      274
VIPRFVS2      275
VINOCRE2      276-277
VIEYEXM2      278
VIINSUR2      279
VICTRCT2      280
VIGLUMA2      281
VIMACDG2      282
NUMBURN2      283                     /* Module 5: Excess Sun Exposure */
SLEPTIME      284-285                 /* Module 6: Inadequate Sleep */
SLEPSNOR      286
SLEPDAY       287-288
SLEPDRIV      289
BRTHCNT3      290                     /* Module 7: Family Planning */
TYPCNTR5      291-292
NOBCUSE3      293-294
FPCHLDF2      295
ASTHMAGE      296-297                 /* Module 8: Adult Asthma History */
ASATTACK      298
ASERVIST      299-300
ASDRVIST      301-302
ASRCHKUP      303-304
ASACTLIM      305-307
ASYMPTOM      308
ASNOSLEP      309
ASTHMED3      310
ASINHALR      311
HAVARTH2      312                     /* Module 9: Arthritis Burden */
WRKHCF1       313                     /* Module 10: High Risk/Health Care Worker */
DIRCONT1      314
DRHPAD1       315
HAVHPAD       316
SHINGLES      317                     /* Module 11: Shingles (Zostavax or ZOS) */
TNSARCV       318                     /* Module 12: Tetanus Diptheria (Adults) */
TNSARCNT      319
TNSASHOT      320
HPVADVC2      321                     /* Module 13: Adult Human Papilloma Virus (HPV) */
HPVADSHT      322-323
CNCRHAVE      324                     /* Module 14: Cancer Survivorship */
CNCRDIFF      325
CNCRAGE       326-327
CNCRTYPE      328-329
CSRVTRT       330
CSRVDOC       331-332
CSRVSUM       333
CSRVRTRN      334
CSRVINST      335
CSRVINSR      336
CSRVDEIN      337
CSRVCLIN      338
CSRVPAIN      339
CSRVCTRL      340
CAREGIVE      341                     /* Module 15: Caregiver */
CRGVAGE       342-344
CRGVGNDR      345
CRGVRELT      346-347
CRGVLONG      348-350
CRGVPROB      351-352
CRGVMST1      353-354
CRGVHRS       355-357
CRGVDIFF      358-359
CRGVCHNG      360
RRCLASS2      361                     /* Module 16: Reactions to Race */
RRCOGNT2      362
RRATWRK2      363
RRHCARE3      364
RRPHYSM2      365
RREMTSM2      366
ADPLEASR      367-368                 /* Module 17: Anxiety and Depression */
ADDOWN        369-370
ADSLEEP       371-372
ADENERGY      373-374
ADEAT1        375-376
ADFAIL        377-378
ADTHINK       379-380
ADMOVE        381-382
ADANXEV       383
ADDEPEV       384
CIMEMLOS      385                     /* Module 18: Cognitive Impairment */
CINOADLT      386
CIRBIAGE      387-388
CIHOWOFT      389
CIASSIST      390
CIINTFER      391
CIFAMCAR      392
CIHCPROF      393
CIMEDS        394
CIDIAGAZ      395
RENTHOM1      396                     /* Module 19: Social Context */
SCNTMONY      397
SCNTMEAL      398
SCNTPAID      399
SCNTWORK      400-401
SCNTLPAD      402
SCNTLWRK      403-404
SCNTVOTE      405
GPWELPR3      406                     /* Module 20: General Preparedness */
GP3DYWTR      407
GP3DYFD1      408
GP3DYPRS      409
GPBATRAD      410
GPFLSLIT      411
GPEMRCM1      412
GPEMRIN1      413
GPVACPL1      414
GPMNDEVC      415
GPNOTEV1      416-417
VHCOMBAT      418                     /* Module 21: Veteran´s Health */
VHDRPTSD      419
VHDRTBI       420
VHCOUNSL      421
VHTAKLIF      422
VHSUICID      423
ACEDEPRS      424                     /* Module 22: Adverse Childhood Experience */
ACEDRINK      425
ACEDRUGS      426
ACEPRISN      427
ACEDIVRC      428
ACEPUNCH      429
ACEHURT       430
ACESWEAR      431
ACETOUCH      432
ACETTHEM      433
ACEHVSEX      434
RCSBIRTH      $460-465                /* Module 23: Random Child Selection */
RCSGENDR      466
RCHISLAT      467
RCSRACE       $468-473
RCSBRACE      474
RCSRLTN2      475
CASTHDX2      476                     /* Module 24: Childhood Asthma Prevalence */
CASTHNO2      477
FLUSHCH2      478                     /* Module 25: Childhood Immunization */
RCVFVCH4      479-484
HPVCHVC       485                     /* Module 26: Child Human Papilloma Virus (HPV) */
HPVCHSHT      486-487
CALLBACK      497                     /* Asthma Follow-up Call Back */
ADLTCHLD      498
QSTVER        860-861                 /* Questionnaire Version */
QSTLANG       862-863                 /* Questionnaire Language */
CPCOUNTY      $874-918                /* Cell Phone Pilot II */
H1N1AQ01      919                     /* Section 23: H1N1 Adult */
H1N1AQ02      920
H1N1AQ03      921
H1N1AQ04      922
H1N1AQ05      923
H1N1AQ06      924
H1N1AQ07      925
H1N1AQ08      926
H1N1AQ09      927-928
H1N1AQ10      929-930
H1N1CQ01      931                     /* Module 27: H1N1 Child */
H1N1CQ02      932
H1N1AV01      933                     /* Module 28: Novel H1N1 Adult Immunization */
H1N1AV02      934-935
H1N1AV03      936
H1N1CV01      937                     /* Module 29: Novel H1N1 Child Immunization */
H1N1CV02      938
H1N1CV03      939-940
H1N1CV04      941
H1N1CV05      942-943
H1N1CV06      944
_STSTR        945-949                 /* Weighting And Stratification Variables */
_STRWT        950-959
_RAWQ3        1080-1089
_WT2Q3        1090-1099
_POSTQ3       1100-1109
_FINALQ3      1110-1119
_REGION       1120-1121
_AGEG_        1122-1123
_AGEG1_       1124-1125
_AGEG2_       1126-1127
_AGEG3_       1128-1129
_SEXG_        1130
_SEXG1_       1131
_SEXG2_       1132
_SEXG3_       1133
_RACEG3_      1134
_RACEG31      1135
_RACEG32      1136
_RACEG33      1137
_IMPAGE       1138-1139
_IMPNPH       1140
CHILDAGE      1204-1206
_CIMPAG1      1207-1208               /* Child Weighting Variables */
_CSEXG1_      1209
_CRACE1_      1210
_CAGEG1_      1211-1213
_CIMPAG2      1254-1255
_CSEXG2_      1256
_CRACE2_      1257
_CAGEG2_      1258-1260
_CIMPAG3      1301-1302
_CSEXG3_      1303
_CRACE3_      1304
_CAGEG3_      1305-1307
_RAWCH3       1308-1317
_WT2CH3       1318-1327
_POSTCH3      1328-1337
_CHILDQ3      1338-1347
_CIMPAGE      1348-1349
_RFHLTH       1435                    /* Section 1: Calculated Variables */
_HCVU65       1436                    /* Section 3: Calculated Variables */
_TOTINDA      1437                    /* Section 5: Calculated Variables */
_EXTETH2      1438                    /* Section 7: Calculated Variables */
_ALTETH2      1439
_DENVST1      1440
_LTASTHM      1441                    /* Section 9: Calculated Variables */
_CASTHMA      1442
_ASTHMST      1443
_SMOKER3      1444                    /* Section 11: Calculated Variables */
_RFSMOK3      1445
MRACEORG      $1446-1451              /* Section 12: Calculated Race Variables */
MRACEASC      $1452-1457
_PRACE        1458-1459
_MRACE        1460-1461
RACE2         1462
_RACEG2       1463
_RACEGR2      1464
_RACE_G       1465
_CNRACE       1466
_CNRACEC      1467
_AGEG5YR      1468-1469
_AGE65YR      1470
_AGE_G        1471
HTIN3         1472-1474
HTM3          1475-1477
WTKG2         1478-1482
_BMI4         1483-1486
_BMI4CAT      1487
_RFBMI4       1488
_CHLDCNT      1489
_EDUCAG       1490
_INCOMG       1491
DROCDY2_      1492-1494               /* Section 13: Calculated Variables */
_RFBING4      1495
_DRNKDY3      1496-1499
_DRNKMO3      1500-1503
_RFDRHV3      1504
_RFDRMN3      1505
_RFDRWM3      1506
_FLSHOT4      1507                    /* Section 14: Calculated Variables */
_PNEUMO2      1508
_RFSEAT2      1509                    /* Section 16: Calculated Variables */
_RFSEAT3      1510
_RFMAM2Y      1511                    /* Section 18: Calculated Variables */
_MAM502Y      1512
_RFPAP32      1513
_RFPSA2Y      1514                    /* Section 19: Calculated Variables */
_RFBLDS2      1515                    /* Section 20: Calculated Variables */
_RFSIGM2      1516
_AIDTST2      1517                    /* Section 21: Calculated Variables */
;
*****************************************************************
* TO INCLUDE THE FORMAT ASSIGNEMT STATEMENT REMOVE THE ASTERISK *
* FROM THE BEGINNING OF THE FOLLOWING LINE                      *
*****************************************************************;
* %INCLUDE FORMATIN ;
*************************************************
* THIS SECTION CREATES LABELS FOR THE VARIABLES *
*************************************************;
Label
ACEDEPRS = 'LIVE WITH ANYONE DEPRESSED, MENTALLY ILL, OR SUICIDAL?'
ACEDIVRC = 'WERE YOUR PARENTS DIVORCED/SEPERATED?'
ACEDRINK = 'LIVE WITH A PROBLEM DRINKER/ALCOHOLIC?'
ACEDRUGS = 'LIVE WITH ANYONE WHO USED ILLEGAL DRUGS OR ABUSED PRESCRIPTIONS?'
ACEHURT = 'HOW OFTEN DID A PARENT PHYSICALLY HURT YOU IN ANY WAY?'
ACEHVSEX = 'HOW OFTEN DID ANYONE EVER FORCE YOU TO HAVE SEX?'
ACEPRISN = 'LIVE WITH ANYONE WHO SERVED TIME IN PRISON OR JAIL?'
ACEPUNCH = 'HOW OFTEN DID YOUR PARENTS BEAT EACH OTHER UP?'
ACESWEAR = 'HOW OFTEN DID A PARENT SWEAR AT YOU?'
ACETOUCH = 'HOW OFTEN DID ANYONE EVER TOUCH YOU SEXUALLY?'
ACETTHEM = 'HOW OFTEN DID ANYONE MAKE YOU TOUCH THEM SEXUALLY?'
ADANXEV = 'EVER TOLD YOU HAD AN ANXIETY DISORDER'
ADDEPEV = 'EVER TOLD YOU HAD A DEPRESSIVE DISORDER'
ADDOWN = 'DAYS FELT DOWN, DEPRESSED OR HOPELESS'
ADEAT1 = 'DAYS ATE TOO LITTLE OR TOO MUCH'
ADENERGY = 'DAYS WERE TIRED OR HAD LITTLE ENERGY'
ADFAIL = 'DAYS FELT LIKE FAILURE OR LET FAMILY DOWN'
ADLTCHLD = 'WHICH HOUSEHOLD MEMBER WAS SELECTED TO BE THE FOCUS OF THE CALLBACK.'
ADMOVE = 'DAYS TALKED TO MOVE SLOWER OR FASTER THAN USUAL'
ADPLEASR = 'DAYS HAD LITTLE PLEASURE DOING THINGS'
ADSLEEP = 'DAYS HAD TROUBLE WITH SLEEP'
ADTHINK = 'DAYS HAD TROUBLE CONCENTRATING'
AGE = 'REPORTED AGE IN YEARS'
ALCDAY4 = 'DAYS IN PAST 30 HAD ALCOHOLIC BEVERAGE'
ASACTLIM = 'ACTIVITIES LIMITED DUE TO ASTHMA DURING PAST 12 MONTHS'
ASATTACK = 'ASTHMA DURING PAST 12 MONTHS'
ASDRVIST = 'URGENT ASTHMA TREATMENT DURING PAST 12 MONTHS'
ASERVIST = 'EMERGENCY ASTHMA CARE DURING PAST 12 MONTHS'
ASINHALR = 'TIMES USED ASTHMA INHALER DURING AN ATTACK IN PAST 30 DAYS'
ASNOSLEP = 'SLEEP DIFFICULTY DUE TO ASTHMA DURING PAST 30 DAYS'
ASRCHKUP = 'ROUTINE ASTHMA CARE DURING PAST 12 MONTHS'
ASTHMA2 = 'EVER TOLD HAD ASTHMA'
ASTHMAGE = 'AGE AT ASTHMA DIAGNOSIS'
ASTHMED3 = 'DAYS USED PRESCRIBED PREVENTATIVE ASTHMA MED IN PAST 30 DAYS'
ASTHNOW = 'STILL HAVE ASTHMA'
ASYMPTOM = 'ASTHMA SYMPTOMS DURING PAST 30 DAYS'
AVEDRNK2 = 'AVG ALCOHOLIC DRINKS PER DAY IN PAST 30'
BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
BRTHCNT3 = 'ARE YOU DOING ANYTHING TO KEEP FROM GETTING PREGNANT?'
CALLBACK = 'ASTHMA FOLLOW-UP CALL BACK REQUEST'
CAREGIVE = 'PROVIDED REGULAR CARE FOR FAMILY OR FRIEND'
CASTHDX2 = 'HLTH PRO EVER SAID CHILD HAS ASTHMA'
CASTHNO2 = 'CHILD STILL HAVE ASTHMA?'
CELLFON = 'CELLULAR TELEPHONE'
CHECKUP1 = 'LENGTH OF TIME SINCE LAST ROUTINE CHECKUP'
CHILDAGE = 'CHILD AGE'
CHILDREN = 'NUMBER OF CHILDREN IN HOUSEHOLD'
CHKHEMO3 = 'TIMES CHECKED FOR GLYCOSYLATED HEMOGLOBIN'
CIASSIST = 'AS A RESULT OF PERSON’S CONFUSION OR MEMORY LOSS, IN WHICH AREAS DO YOU;” NEED THE MOST ASSISTANCE?'
CIDIAGAZ = 'HAS A HEALTH CARE PROFESSIONAL EVER SAID IT WAS ALZHEIMER’S DISEASE OR SOME OTHER FORM OF DEMENTIA?'
CIFAMCAR = 'HOW OFTEN HAS A FAMILY MEMBER OR FRIEND PROVIDED ANY CARE OR ASSISTANCE BECAUSE OF CONFUSION OR MEMORY LOSS?'
CIHCPROF = 'DISCUSSED WITH A HEALTH CARE PROFESSIONAL, INCREASES IN CONFUSION OR MEMORY LOSS?'
CIHOWOFT = 'GIVEN UP HOUSEHOLD ACTIVITIES OR CHORES YOU/THEY USED TO DO, BECAUSE OF CONFUSION OR MEMORY LOSS THAT IS HAPPE
NING MORE OFTEN OR IS GETTING WORSE?'
CIINTFER = 'HOW OFTEN HAS CONFUSION OR MEMORY LOSS INTERFERED WITH ABILITY TO WORK, VOLUNTEER, OR ENGAGE IN SOCIAL ACTIVIT
IES?'
CIMEDS = 'RECEIVED TREATMENT SUCH AS THERAPY OR MEDICATIONS FOR CONFUSION OR MEMORY LOSS?'
CIMEMLOS = 'HAVE YOU EXPERIENCED CONFUSION OR MEMORY LOSS THAT IS HAPPENING MORE OFTEN OR IS GETTING WORSE?'
CINOADLT = 'HOW MANY ADULTS IN YOUR HOUSEHOLD EXPERIENCED CONFUSION OR MEMORY LOSS THAT IS HAPPENING MORE OFTEN OR IS GETT
ING WORSE DURING THE PAST 12 MONTHS?'
CIRBIAGE = 'OF THESE PEOPLE, HOW OLD IS THIS PERSON?'
CNCRAGE = 'AGE TOLD HAD CANCER'
CNCRDIFF = 'HOW MANY TYPES OF CANCER?'
CNCRHAVE = 'EVER TOLD YOU HAD CANCER?'
CNCRTYPE = 'TYPE OF CANCER'
CPCOUNTY = 'CELL PHONE PILOT COUNTY NAME'
CPDEMO1 = 'DO YOU HAVE A CELL PHONE FOR PERSONAL USE?'
CPDEMO2 = 'DO YOU SHARE A CELL PHONE FOR PERSONAL USE?'
CPDEMO3 = 'DO YOU USUALLY SHARE THIS CELL PHONE?'
CPDEMO4 = 'WHAT PERCENT OF ALL CALLS ARE RECEIVED ON YOUR CELL PHONE?'
CRGVAGE = 'AGE OF PERSON TO WHOM YOU ARE GIVING CARE?'
CRGVCHNG = 'IN THE PAST YEAR, HAS THE PERSON EXPERIENCED CHANGES IN THINKING/REMEMBERING?'
CRGVDIFF = 'GREATEST DIFFICULTY YOU HAVE FACED AS A CAREGIVER'
CRGVGNDR = 'GENDER OF PERSON TO WHOM YOU ARE GIVING CARE?'
CRGVHRS = 'HOW MANY HOURS DO YOU PROVIDE CARE FOR PERSON?'
CRGVLONG = 'HOW LONG PROVIDED CARE FOR PERSON.'
CRGVMST1 = 'WHAT AREAS DOES PERSON MOST NEED YOUR HELP?'
CRGVPROB = 'WHAT IS THE MAJOR HEALTH PROBLEM, ILLNESS, DISABILITY FOR CARE FOR PERSON?'
CRGVRELT = 'RELATIONSHIP OF PERSON TO WHOM YOU ARE GIVING CARE?'
CSRVCLIN = 'PARTICIPATE IN CLINICAL TRIAL AS PART OF CANCER TREATMENT?'
CSRVCTRL = 'IS PAIN UNDER CONTROL?'
CSRVDEIN = 'EVER DENIED INSURANCE COVERAGE BECAUSE OF YOUR CANCER?'
CSRVDOC = 'WHAT TYPE OF DOCTOR PROVIDES MAJORITY OF YOUR CARE'
CSRVINSR = 'DID HEALTH INSURANCE PAY FOR ALL OF YOUR CANCER TREATMENT'
CSRVINST = 'INSTRUCTIONS WRITTEN OR PRINTED'
CSRVPAIN = 'CURRENTLY HAVE PHYSICAL PAIN FROM CANCER OR TREATMENT?'
CSRVRTRN = 'EVER RECEIVE INSTRUCTIONS FROM A DOCTOR FOR FOLLOW-UP CHECK-UPS'
CSRVSUM = 'DID YOU RECEIVE A SUMMARY OF CANCER TREATMENTS RECEIVED'
CSRVTRT = 'CURRENTLY RECEIVING TREATMENT FOR CANCER'
CTELENUM = 'CORRECT TELEPHONE NUMBER?'
CVDCRHD4 = 'EVER DIAGNOSED WITH ANGINA OR CORONARY HEART DISEASE'
CVDINFR4 = 'EVER DIAGNOSED WITH HEART ATTACK'
CVDSTRK3 = 'EVER DIAGNOSED WITH A STROKE'
DENCLEAN = 'WHEN TEETH LAST CLEANED BY DENTIST OR HYGIENIST'
DIABAGE2 = 'AGE WHEN TOLD DIABETIC'
DIABEDU = 'EVER TAKEN CLASS IN MANAGING DIABETES'
DIABETE2 = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
DIABEYE = 'EVER TOLD DIABETES HAS AFFECTED EYES'
DIGRECEX = 'EVER HAD DIGITAL RECTAL EXAM'
DIRCONT1 = 'DO YOU PROVIDE DIRECT PATIENT CARE AS PART OF YOUR ROUTINE WORK?'
DISPCODE = 'FINAL DISPOSITION'
DOCTDIAB = 'TIMES SEEN HEALTH PROFESSIONAL FOR DIABETES'
DRETIME = 'TIME SINCE LAST DIGITAL RECTAL EXAM'
DRHPAD1 = 'HAS A DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL EVER SAID THAT YOU HAVE…PROBLEM CAUSED BY A CHRONIC ILLNESS O
R BY MEDICINES; TAKEN FOR A CHRONIC ILLNESS?'
DRNK3GE5 = 'BINGE DRINKING'
DRNKANY4 = 'DRINK ANY ALCOHOLIC BEVERAGES IN PAST 30 DAYS'
DRNKDRI2 = 'DID YOU DRIVE AFTER HAVING TOO MUCH TO DRINK IN THE PAST 30 DAYS?'
DROCDY2_ = 'COMPUTED DRINK-OCCASIONS-PER-DAY'
EDUCA = 'EDUCATION LEVEL'
EMPLOY = 'EMPLOYMENT STATUS'
EMTSUPRT = 'HOW OFTEN GET EMOTIONAL SUPPORT NEEDED'
EXERANY2 = 'EXERCISE IN PAST 30 DAYS'
EYEEXAM = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
FALL3MN2 = 'HAD FALL PAST THREE MONTHS'
FALLINJ2 = 'INJURED IN FALL'
FEETCHK = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
FEETCHK2 = 'HOW OFTEN CHECK FEET FOR SORES OR IRRITATIONS'
FLSHTMY1 = 'WHEN RECEIVED MOST RECENT SEASONAL FLU SHOT'
FLSPRMY1 = 'WHEN RECEIVED MOST RECENT SEASONAL FLU SPRAY IN NOSE'
FLSYAQ01 = 'WERE YOU ILL WITH A FEVER IN PAST MONTH?'
FLSYAQ02 = 'DID YOU ALSO HAVE A COUGH AND/OR SORE THROAT?'
FLSYAQ03 = 'DID YOU VISIT A DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL FOR THIS ILLNESS?'
FLSYAQ04 = 'WHEN DID YOU VISIT THE DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL FOR THIS ILLNESS?'
FLSYAQ05 = 'WHAT DID THE DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL TELL YOU?'
FLSYAQ06 = 'DID YOU HAVE A FLU TEST THAT WAS POSITIVE FOR THIS ILLNESS?'
FLSYAQ07 = 'DID YOU RECEIVE TAMIFLU®, OSELTAMIVIR, RELENZA® OR ZANAMIVIR TO TREAT THIS ILLNESS?'
FLSYAQ08 = 'DID ANY OTHER MEMBERS OF YOUR HOUSEHOLD HAVE A FEVER WITH COUGH OR SORE THROAT LAST MONTH?'
FLSYAQ09 = 'HOW MANY HOUSEHOLD MEMBERS, INCLUDING YOU, WERE ILL LAST MONTH?'
FLSYAQ10 = 'HOW MANY PEOPLE IN YOUR HOUSEHOLD, INCLUDING YOU, WERE HOSPITALIZED FOR FLU DURING LAST MONTH?'
FLSYCQ01 = 'DID THE CHILD HAVE A FEVER WITH COUGH AND/OR SORE THROAT DURING THE LAST MONTH?'
FLSYCQ02 = 'DID THE CHILD VISIT A DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL FOR THIS ILLNESS?'
FLUSHCH2 = 'HAD SEASONAL FLU SHOT PAST 12 MOS'
FLUSHOT4 = 'SEASONAL FLU SHOT PAST 12 MOS'
FLUSPRY3 = 'SEASONAL FLU SPRAY PAST 12 MOS'
FMONTH = 'FILE MONTH'
FPCHLDF2 = 'HOW DO YOU FEEL ABOUT HAVING A CHILD NOW OR SOMETIME IN THE FUTURE?'
GENHLTH = 'GENERAL HEALTH'
GP3DYFD1 = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF NON-PERISHABLE FOOD FOR EVERYONE WHO LIVES THERE?'
GP3DYPRS = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF PRESCRIPTION MEDICATION FOR EACH PERSON WHO TAKES PRESCRIBED MEDICI
NES?'
GP3DYWTR = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF WATER FOR EVERYONE WHO LIVES THERE?'
GPBATRAD = 'DOES YOUR HOUSEHOLD HAVE A WORKING BATTERY OPERATED RADIO AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICIT
Y IS OUT?'
GPEMRCM1 = 'IN A LARGE-SCALE DISASTER OR EMERGENCY, WHAT WOULD BE YOUR MAIN METHOD OF COMMUNICATING WITH RELATIVES AND FRI
ENDS?'
GPEMRIN1 = 'WHAT WOULD BE YOUR MAIN METHOD OF GETTING INFORMATION FROM AUTHORITIES IN A LARGE-SCALE DISASTER OR EMERGENCY?
'
GPFLSLIT = 'DOES YOUR HOUSEHOLD HAVE A WORKING FLASHLIGHT AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICITY IS OUT?'
GPMNDEVC = 'IF PUBLIC AUTHORITIES ANNOUNCED MANDATORY EVACUATION FROM YOUR COMMUNITY DUE TO A LARGE-SCALE DISASTER OR EMER
GENCY, WOULD YOU EVACUATE?'
GPNOTEV1 = 'WHAT WOULD BE THE MAIN REASON WHY YOU MIGHT NOT EVACUATE IF ASKED TO DO SO?'
GPVACPL1 = 'DOES YOUR HOUSEHOLD HAVE A DISASTER EVACUATION PLAN?'
GPWELPR3 = 'HOUSEHOLD PREPARED TO HANDLE LARGE-SCALE DISASTER OR EMERGENCY'
H1N1AQ01 = 'WERE YOU ILL WITH A FEVER IN PAST MONTH?'
H1N1AQ02 = 'DID YOU ALSO HAVE A COUGH AND/OR SORE THROAT?'
H1N1AQ03 = 'WHEN DID YOU FIRST BECOME ILL WITH FEVER, COUGH OR SORE THROAT?
WHERE     (Qvariable LIKE N'h1n1%') OR

                 (Qvariable = N'exerany2')
WHEN DID YOU FIRST BECOME ILL WITH
H1N1AQ04 = 'DID YOU VISIT A DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL FOR THIS ILLNESS?'
H1N1AQ05 = 'WHAT DID THE DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL TELL YOU?'
H1N1AQ06 = 'DID YOU HAVE A FLU TEST THAT WAS POSITIVE FOR THIS ILLNESS?'
H1N1AQ07 = 'DID YOU RECEIVE TAMIFLU®, OSELTAMIVIR, RELENZA® OR ZANAMIVIR [ZA NA MI VEER] TO TREAT THIS ILLNESS?'
H1N1AQ08 = 'DID ANY OTHER MEMBERS OF YOUR HOUSEHOLD HAVE A FEVER WITH COUGH OR SORE THROAT DURING THE PAST MONTH?'
H1N1AQ09 = 'HOW MANY HOUSEHOLD MEMBERS, INCLUDING YOU, WERE ILL DURING THE PAST MONTH?'
H1N1AQ10 = 'HOW MANY PEOPLE IN YOUR HOUSEHOLD, INCLUDING YOU, WERE HOSPITALIZED FOR FLU DURING THE PAST MONTH?'
H1N1AV01 = 'SINCE SEPTEMBER, 2009, HAVE YOU BEEN VACCINATED EITHER WAY FOR THE H1N1 FLU?'
H1N1AV02 = 'DURING WHAT MONTH DID YOU RECEIVE YOUR H1N1 FLU VACCINE?'
H1N1AV03 = 'WAS THIS A SHOT OR VACCINE SPRAYED IN THE NOSE?'
H1N1CQ01 = 'HAS THE CHILD HAD A FEVER WITH COUGH AND/OR SORE THROAT DURING THE PAST MONTH?'
H1N1CQ02 = 'DID THE CHILD VISIT A DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL FOR THIS ILLNESS?'
H1N1CV01 = 'SINCE SEPTEMBER, 2009, HAS [FILL: HE/SHE] HAD A H1N1 FLU VACCINATION?'
H1N1CV02 = 'SINCE SEPTEMBER 2009, HOW MANY OF THESE H1N1 VACCINATIONS HAS [FILL: HE/SHE] RECEIVED?'
H1N1CV03 = 'DURING WHAT MONTH DID [FILL: HE/SHE] RECEIVE [FILL: HIS/HER] H1N1 FLU VACCINE?'
H1N1CV04 = 'WAS THIS A SHOT OR VACCINE SPRAYED IN THE NOSE?'
H1N1CV05 = 'DURING WHAT MONTH DID [FILL: HE/SHE] RECEIVE [FILL: HIS/HER] SECOND H1N1 FLU VACCINE?'
H1N1CV06 = 'WAS THIS A SHOT OR VACCINE SPRAYED IN THE NOSE?'
HADHYST2 = 'HAD HYSTERECTOMY'
HADMAM = 'HAVE YOU EVER HAD A MAMMOGRAM'
HADPAP2 = 'EVER HAD A PAP TEST'
HADSGCO1 = 'WAS LAST TEST A SIGMOIDOSCOPY OR COLONOSCOPY'
HADSIGM3 = 'EVER HAD SIGMOIDOSCOPY/COLONOSCOPY'
HAVARTH2 = 'TOLD HAVE ARTHRITIS'
HAVHPAD = 'STILL HAVE THIS HEALTH PROBLEM'
HEIGHT3 = 'REPORTED HEIGHT IN FEET AND INCHES'
HISPANC2 = 'HISPANIC/LATINO'
HIVRDTST = 'WAS YOUR LAST HIV TEST A RAPID TEST?'
HIVRISK2 = 'DO ANY HIGH RISK SITUATIONS APPLY'
HIVTST5 = 'EVER TESTED HIV'
HIVTSTD2 = 'MONTH AND YEAR OF LAST HIV TEST'
HLTHPLAN = 'HAVE ANY HEALTH CARE COVERAGE'
HOWLONG = 'HOW LONG SINCE LAST MAMMOGRAM'
HPVADSHT = 'NUMBER OF HPV SHOTS RECEIVED'
HPVADVC2 = 'EVER HAD THE HPV VACCINATION?'
HPVCHSHT = 'HOW MANY HPV SHOTS DID CHILD RECEIVE?'
HPVCHVC = 'CHILD  EVER HAD THE HPV VACCINATION?'
HTIN3 = 'COMPUTED HEIGHT IN INCHES'
HTM3 = 'COMPUTED HEIGHT IN METERS'
IDATE = 'INTERVIEW DATE'
IDAY = 'INTERVIEW DAY'
IMONTH = 'INTERVIEW MONTH'
INCOME2 = 'INCOME LEVEL'
INSULIN = 'NOW TAKING INSULIN'
INTVID = 'INTERVIEWER IDENTIFICATION'
IYEAR = 'INTERVIEW YEAR'
LASTDEN3 = 'LAST VISITED DENTIST OR DENTAL CLINIC'
LASTPAP2 = 'HOW LONG SINCE LAST PAP TEST'
LASTSIG3 = 'TIME SINCE LAST SIGMOIDOSCOPY/COLONOSCOPY'
LASTSMK1 = 'INTERVAL SINCE LAST SMOKED'
LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
LSATISFY = 'SATISFACTION WITH LIFE'
LSTBLDS3 = 'TIME SINCE LAST BLOOD STOOL TEST'
MARITAL = 'MARITAL STATUS'
MAXDRNKS = 'MOST DRINKS ON SINGLE OCCASION PAST 30 DAYS'
MEDCOST = 'COULD NOT SEE DR. BECAUSE OF COST'
MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
MRACE = 'MULTIPLE RACE'
MRACEASC = 'MRACEORG WITH RESPONSES IN ASCENDING ORDER CALCULATED VARIABLE'
MRACEORG = 'MRACE WITH TRAILING 7,8,9S REMOVED CALCULATED VARIABLE'
NATTMPTS = 'NUMBER OF ATTEMPTS'
NOBCUSE3 = 'WHAT IS MAIN REASON FOR NOT USING BIRTH CONTROL?'
NRECSEL = 'NUMBER OF SAMPLE RECORDS SELECTED FROM STRATUM'
NRECSTR = 'NUMBER OF TELEPHONE NUMBERS IN STRATUM FROM WHICH SAMPLE WAS SELECTED'
NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
NUMBURN2 = 'NUMBER OF SUNBURNS IN PAST 12 MONTHS'
NUMHHOL2 = 'HOUSEHOLD TELEPHONES'
NUMMEN = 'NUMBER OF ADULT MEN IN HOUSEHOLD'
NUMPHON2 = 'RESIDENTIAL PHONES'
NUMWOMEN = 'NUMBER OF ADULT WOMEN IN HOUSEHOLD'
ORACE2 = 'RESPONDENT RACE CHOICE'
PAINACT2 = 'HOW MANY DAYS HARD TO DO USUAL ACTIVITIES IN PAST 30 DAYS'
PDIABTST = 'HAD A TEST FOR HIGH BLOOD SUGAR IN PAST THREE YEARS'
PERSDOC2 = 'MULTIPLE HEALTH CARE PROFESSIONALS'
PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
PNEUVAC3 = 'PNEUMONIA SHOT EVER'
POORHLTH = 'POOR PHYSICAL HEALTH'
PRECALL = 'PRE-CALL STATUS CODE'
PREDIAB1 = 'EVER BEEN TOLD YOU HAVE PRE-DIABETES OR BORDERLINE DIABETES'
PREGNANT = 'PREGNANCY STATUS'
PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
PROSTATE = 'EVER TOLD YOU HAD PROSTATE CANCER'
PSATEST = 'EVER HAD PSA TEST'
PSATIME = 'TIME SINCE LAST PSA TEST'
PVTRESID = 'PRIVATE RESIDENCE?'
QLACTLM2 = 'ACTIVITY LIMITATION DUE TO HEALTH PROBLEMS'
QLHLTH2 = 'HOW MANY DAYS FULL OF ENERGY IN PAST 30 DAYS'
QLMENTL2 = 'HOW MANY DAYS DEPRESSED IN PAST 30 DAYS'
QLREST2 = 'HOW MANY DAYS DID YOU GET ENOUGH SLEEP IN PAST 30 DAYS'
QLSTRES2 = 'HOW MANY DAYS FELT ANXIOUS IN PAST 30 DAYS'
QSTLANG = 'LANGUAGE IDENTIFIER'
QSTVER = 'QUESTIONNAIRE VERSION IDENTIFIER'
RACE2 = 'COMPUTED RACE-ETHNICITY GROUPING'
RCHISLAT = 'ETHNICITY OF CHILD'
RCSBIRTH = 'BIRTH DATE OF CHILD'
RCSBRACE = 'RACE OF CHILD'
RCSGENDR = 'GENDER OF CHILD'
RCSRACE = 'RACE OF CHILD (MULTIPLE POSSIBLE)'
RCSRLTN2 = 'RELATIONSHIP TO CHILD'
RCVFVCH4 = 'DATE CHILD RCVD MOST RECENT SEASONAL FLU VACCINE(MMYYYY)'
RENTHOM1 = 'OWN OR RENT HOME'
REPDEPTH = 'REPLICATE DEPTH'
REPNUM = 'REPLICATE NUMBER'
RMVTETH3 = 'NUMBER OF PERMANENT TEETH REMOVED'
RRATWRK2 = 'HOW DO YOU FEEL YOU WERE TREATED AT WORK COMPARED TO PEOPLE OF OTHER RACES IN PAST 12 MONTHS?'
RRCLASS2 = 'HOW DO OTHER PEOPLE USUALLY CLASSIFY YOU IN THIS COUNTRY?'
RRCOGNT2 = 'HOW OFTEN DO YOU THINK ABOUT YOUR RACE?'
RREMTSM2 = 'TIMES PAST 30 DAYS FELT EMOTIONALLY UPSET BECAUSE OF TREATMENT DUE TO YOUR RACE'
RRHCARE3 = 'WHEN SEEKING HEALTH CARE PAST 12 MONTHS, WAS EXPERIENCE WORSE, SAME, BETTER THAN PEOPLE OF OTHER RACES?'
RRPHYSM2 = 'TIMES PAST 30 DAYS FELT PHYSICAL SYMPTOMS BECAUSE OF TREATMENT DUE TO YOUR RACE'
SCNTLPAD = 'HOW WERE YOU GENERALLY PAID FOR THE WORK YOU DID'
SCNTLWRK = 'HOW MANY HOURS PER WEEK DID YOU WORK'
SCNTMEAL = 'TIMES PAST 12 MONTHS WORRIED/STRESSED ABOUT HAVING ENOUGH MONEY TO BUY NUTRITIOUS MEALS?'
SCNTMONY = 'TIMES PAST 12 MONTHS WORRIED/STRESSED ABOUT HAVING ENOUGH MONEY TO PAY YOUR RENT/MORTGAGE?'
SCNTPAID = 'HOW ARE YOU GENERALLY PAID FOR THE WORK YOU DO'
SCNTVOTE = 'DID YOU VOTE IN THE LAST PRESIDENTIAL ELECTION?'
SCNTWORK = 'HOW MANY HOURS PER WEEK DO YOU WORK'
SEATBELT = 'HOW OFTEN USE SEATBELTS IN CAR?'
SEQNO = 'ANNUAL SEQUENCE NUMBER'
SEX = 'RESPONDENTS SEX'
SHINGLES = 'HAVE YOU HAD SHINGLES VACCINE?'
SLEPDAY = 'NUMBER OF DAYS IN PAST THIRTY FELL ASLEEP DURING THE DAY'
SLEPDRIV = 'NUMBER OF DAYS IN PAST THIRTY FELL ASLEEP WHILE DRIVING'
SLEPSNOR = 'DO YOU SNORE?'
SLEPTIME = 'HOW MUCH TIME DO YOU SLEEP'
SMOKDAY2 = 'FREQUENCY OF DAYS NOW SMOKING'
SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
STOPSMK2 = 'STOPPED SMOKING IN PAST 12 MONTHS'
TELSERV3 = 'LOST LANDLINE PHONE SERVICE ONE WEEK+ LAST 12 MOS'
TNSARCNT = 'WAS MOST RECENT TETANUS SHOT IN 2005 OR LATER?'
TNSARCV = 'RECEIVED TETANUS SHOT IN THE PAST 10 YEARS?'
TNSASHOT = 'DID TETANUS SHOT INCLUDED THE PERTUSSIS VACCINE?'
TYPCNTR5 = 'WHAT METHOD ARE YOU USING?'
USEEQUIP = 'HEALTH PROBLEMS REQUIRING SPECIAL EQUIPMENT'
USENOW3 = 'USE OF SMOKELESS TOBACCO PRODUCTS'
VETERAN2 = 'ARE YOU A VETERAN'
VHCOMBAT = 'EVER SERVE IN A COMBAT OR WAR ZONE?'
VHCOUNSL = 'RECEIVE PSYCHOLOGICAL OR PSYCHIATRIC COUNSELING OR TREATMENT PAST 12 MONTHS?'
VHDRPTSD = 'DOCTOR DIAGNOSED DEPRESSION, ANXIETY, OR POST TRAUMATIC STRESS DISORDER (PTSD)?'
VHDRTBI = 'DOCTOR DIAGNOSED TRAUMATIC BRAIN INJURY (TBI)?'
VHSUICID = 'ATTEMPT TO COMMIT SUICIDE IN PAST 12 MONTHS?'
VHTAKLIF = 'THOUGHT OF TAKING YOUR OWN LIFE IN THE PAST 12 MONTHS?'
VICTRCT2 = 'HLTH CARE PRO SAID NOW HAVE CATARACTS'
VIDFCLT2 = 'DIFFICULTY RECOGNIZING FRIEND ACROSS STREET'
VIEYEXM2 = 'WHEN LAST EYEXAM'
VIGLUMA2 = 'HLTH CARE PRO EVER SAID HAVE GLAUCOMA'
VIINSUR2 = 'EYE CARE HEALTH INSURANCE'
VIMACDG2 = 'HLTH CARE PRO EVER SAID HAVE MACULAR DEGENERATION'
VINOCRE2 = 'REASON DID NOT USE EYE DOC PAST 12 MOS'
VIPRFVS2 = 'LAST TIME VISITED EYE CARE PROVIDER'
VIREDIF2 = 'DIFFICULTY READING TYPED TEXT'
WEIGHT2 = 'REPORTED WEIGHT IN POUNDS'
WHRTST8 = 'LOCATION OF LAST HIV TEST'
WRKHCF1 = 'DO YOU CURRENTLY VOLUNTEER OR WORK IN A HOSPITAL, MEDICAL CLINIC, DOCTOR´S OFFICE, DENTIST´S OFFICE, NURSING HO
ME OR SOME OTHER HEALTH-CARE FACILITY?'
WTKG2 = 'COMPUTED WEIGHT IN KILOGRAMS'
_AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS CALCULATED VARIABLE'
_AGEG1_ = 'AGE GROUP CODES USED IN VERSION 1 POST-STRATIFICATION.'
_AGEG2_ = 'AGE GROUP CODES USED IN VERSION 2 POST-STRATIFICATION.'
_AGEG3_ = 'AGE GROUP CODES USED IN VERSION 3 POST-STRATIFICATION.'
_AGEG5YR = 'REPORTED AGE IN FIVE-YEAR AGE CATEGORIES CALCULATED VARIABLE'
_AGEG_ = 'AGE GROUP CODES USED IN POST-STRATIFICATION.'
_AGE_G = 'IMPUTED AGE IN SIX GROUPS'
_AIDTST2 = 'EVER BEEN TESTED FOR HIV CALCULATED VARIABLE'
_ALTETH2 = 'ADULTS AGED 65+ WHO HAVE HAD ALL THEIR NATURAL TEETH EXTRACTED'
_ASTHMST = 'COMPUTED ASTHMA STATUS'
_BMI4 = 'COMPUTED BODY MASS INDEX'
_BMI4CAT = 'COMPUTED BODY MASS INDEX CATEGORIES'
_CAGEG1_ = 'CHILD AGE GROUP CODES USED IN POST-STRATIFICATION.'
_CAGEG2_ = 'CHILD AGE GROUP CODES USED IN POST-STRATIFICATION.'
_CAGEG3_ = 'CHILD AGE GROUP CODES USED IN POST-STRATIFICATION.'
_CASTHMA = 'CURRENT ASTHMA CALCULATED VARIABLE'
_CHILDQ3 = 'FINAL WEIGHT QUESTIONNAIRE VERSION 3: POST-STRATIFICATION WEIGHT MULTIPLIED BY _WT2CH3'
_CHLDCNT = 'COMPUTED NUMBER OF CHILDREN IN HOUSEHOLD'
_CIMPAG1 = 'IMPUTED CHILD AGE'
_CIMPAG2 = 'IMPUTED CHILD AGE'
_CIMPAG3 = 'IMPUTED CHILD AGE'
_CIMPAGE = 'IMPUTED CHILD AGE'
_CNRACE = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN'
_CNRACEC = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN, COLLAPSED'
_CRACE1_ = 'CHILD RACE GROUP CODES USED IN POST-STRATIFICATION.'
_CRACE2_ = 'CHILD RACE GROUP CODES USED IN POST-STRATIFICATION.'
_CRACE3_ = 'CHILD RACE GROUP CODES USED IN POST-STRATIFICATION.'
_CSEXG1_ = 'CHILD GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_CSEXG2_ = 'CHILD GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_CSEXG3_ = 'CHILD GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_DENSTR2 = 'HOUSEHOLD DENSITY STRATUM CODE'
_DENVST1 = 'ADULTS THAT HAVE VISITED A DENTIST, DENTAL HYGENIST OR DENTAL CLINIC WITHIN THE PAST YEAR'
_DRNKDY3 = 'COMPUTED NUMBER OF DRINKS OF ALCOHOL BEVERAGES PER DAY'
_DRNKMO3 = 'COMPUTED TOTAL NUMBER DRINKS A MONTH'
_EDUCAG = 'COMPUTED LEVEL OF EDUCATION COMPLETED CATEGORIES'
_EXTETH2 = 'RISK FACTOR FOR HAVING HAD PERMANENT TEETH EXTRACTED'
_FINALQ3 = 'FINAL WEIGHT QUESTIONNAIRE VERSION 3: POST-STRATIFICATION WEIGHT MULTIPLIED BY _WT2'
_FLSHOT4 = 'FLU SHOT CALCULATED VARIABLE'
_GEOSTR = 'GEOGRAPHIC STRATUM CODE'
_HCVU65 = 'RESPONDENTS AGED 18-64 WITH HEALTH CARE COVERAGE'
_IMPAGE = 'AGE VALUE USED TO DETERMINE AGE GROUPS'
_IMPNPH = 'IMPUTED NUMBER OF PHONES'
_INCOMG = 'COMPUTED INCOME CATEGORIES'
_LTASTHM = 'LIFETIME ASTHMA CALCULATED VARIABLE'
_MAM502Y = 'WOMEN RESPONDENTS AGED 50+ THAT HAVE HAD A MAMMOGRAM IN THE PAST TWO YEARS'
_MRACE = 'COMPUTED NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_PNEUMO2 = 'PNEUMONIA VACCINATION CALCULATED VARIABLE'
_POSTCH3 = 'POST-STRATIFICATION CHILD WEIGHT QUESTIONNAIRE VERSION 3 (POPULATION ESTIMATE FOR AGE/GENDER/RACE CATEGORIES D
IVIDED BY THE WEIGHTED SAMPLE FREQUENCY BY AGE/RACE/GENDER).'
_POSTQ3 = 'POST-STRATIFICATION WEIGHT QUESTIONNAIRE VERSION 3 (POPULATION ESTIMATE FOR AGE/GENDER/RACE CATEGORIES DIVIDED
BY THE WEIGHTED SAMPLE FREQUENCY BY AGE/RACE/GENDER).'
_PRACE = 'COMPUTED PREFERRED RACE'
_PSU = 'PRIMARY SAMPLING UNIT'
_RACEG2 = 'COMPUTED NON-HISPANIC WHITES/ALL OTHERS RACE CATEGORIES RACE/ETHNIC GROUP CODES USED IN POST-STRATIFICATION.'
_RACEG31 = 'RACE GROUP CODES USED IN VERSION 1 POST-STRATIFICATION.'
_RACEG32 = 'RACE GROUP CODES USED IN VERSION 2 POST-STRATIFICATION.'
_RACEG33 = 'RACE GROUP CODES USED IN VERSION 3 POST-STRATIFICATION.'
_RACEG3_ = 'RACE GROUP CODES USED IN POST-STRATIFICATION.'
_RACEGR2 = 'COMPUTED FIVE LEVEL RACE/ETHNICITY CATEGORY.'
_RACE_G = 'COMPUTED RACE GROUPS USED FOR INTERNET PREVALENCE TABLES'
_RAWCH3 = 'RAW CHILD WEIGHTING FACTOR QUESTIONNAIRE VERSION 3'
_RAWQ3 = 'RAW WEIGHTING FACTOR QUESTIONNAIRE VERSION 3'
_REGION = 'REGION'
_RFBING4 = 'BINGE DRINKING CALCULATED VARIABLE'
_RFBLDS2 = 'RESPONDENTS AGED 50+ THAT HAVE HAD A BLOOD STOOL TEST WITHIN THE PAST TWO YEARS'
_RFBMI4 = 'OVERWEIGHT OR OBESE CALCULATED VARIABLE'
_RFDRHV3 = 'HEAVY ALCOHOL CONSUMPTION  CALCULATED VARIABLE'
_RFDRMN3 = 'ADULT MEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFDRWM3 = 'ADULT WOMEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFHLTH = 'ADULTS WITH GOOD OR BETTER HEALTH'
_RFMAM2Y = 'WOMEN RESPONDENTS AGED 40+ THAT HAVE HAD A MAMMOGRAM IN THE PAST TWO YEARS'
_RFPAP32 = 'WOMEN RESPONDENTS AGED 18+ THAT HAVE HAD A PAP TEST IN THE PAST THREE YEARS'
_RFPSA2Y = 'MALE RESPONDENTS AGED 40+ THAT HAVE HAD A PSA TEST IN THE PAST 2 YEARS'
_RFSEAT2 = 'ALWAYS OR NEARLY ALWAYS WEAR SEAT BELTS'
_RFSEAT3 = 'ALWAYS WEAR SEAT BELTS'
_RFSIGM2 = 'RESPONDENTS AGED 50 OR OLDER THAT HAVE HAD A SIGMOIDOSCOPY OR COLONOSCOPY'
_RFSMOK3 = 'CURRENT SMOKING CALCULATED VARIABLE'
_SEXG1_ = 'GENDER GROUP CODES USED IN VERSION 1 POST-STRATIFICATION.'
_SEXG2_ = 'GENDER GROUP CODES USED IN VERSION 2 POST-STRATIFICATION.'
_SEXG3_ = 'GENDER GROUP CODES USED IN VERSION 3 POST-STRATIFICATION.'
_SEXG_ = 'GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_SMOKER3 = 'COMPUTED SMOKING STATUS'
_STATE = 'STATE FIPS CODE'
_STRWT = 'STRATUM WEIGHT'
_STSTR = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
_TOTINDA = 'LEISURE TIME PHYSICAL ACTIVITY CALCULATED VARIABLE'
_WT2CH3 = 'CHILD DESIGN WEIGHT QUESTIONNAIRE VERSION 3'
_WT2Q3 = 'DESIGN WEIGHT QUESTIONNAIRE VERSION 3. THE PRODUCT OF THE PRECEDING FOUR FACTORS'
;
RUN;
