* INSTRUCTIONS:                                                                           ;
* SPECIFY PATH OF INPUT DATAFILE ON LINE 5, AND PATH OF WHERE SAS DATASET IS TO BE STORED ;
* ON LINE 8                                                                               ;

FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 892 ;
* EXAMPLE: FILENAME DATAIN 'C:\BRFSS\2000\GA00COMP.DAT' LRECL = 892 ;

LIBNAME DATAOUT '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>' ;
* EXAMPLE: LIBNAME DATAOUT 'C:\' ;
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.SD2                                ;
RUN ;

/*****************************************************************************************
 * FILE NAME:     SASOUT00.SAS
 *
 * PROGRAMMER:    J. D. HATMAKER, TRW
 *
 * DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT
 *                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF
 *
 * EXTERNAL REFERENCES:
 *    TYPE         NAME                 DESCRIPTION OF REFERENCE
 * ----------  ---------------  ----------------------------------------------------------
 * INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES
 *
 * OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN
 *                              <DATAIN> FILEREF
 *
 * MODIFICATION HISTORY:
 * NUM     DATE       PROGRAMMER      DESCRIPTION OF MODIFICATION
 * ---  ---------   --------------   -----------------------------------------------------
 * 002  01/10/2001  J. D. HATMAKER   FINAL ISSUE
 * 001  01/09/2001  J. D. HATMAKER   UPDATED FOR NEW _BMI VARIABLES
 * 000  11/21/2000  J. D. HATMAKER   INITIAL ISSUE
 *****************************************************************************************/

OPTIONS SOURCE NOTES NODATE PAGENO = 1 ;
TITLE ;
FOOTNOTE ;
RUN ;

DATA DATAOUT.SASDATA ;
 INFILE DATAIN MISSOVER ;
 INPUT   _STATE        1-2
         _GEOSTR       3-4
         _DENSTR       5
         LISTSTAT      6
         PRECALL       7
         REPNUM        8-12
         REPDEPTH     13-14
         _RECORD      15-16
         IDATE       $17-24
         IMONTH      $17-18
         IDAY        $19-20
         IYEAR       $21-24
         INTVID      $25-27
         PHONENUM    $28-35
         AREACODE    $28-30
         PREFIX      $31-33
         SUFFIX      $34-35
         DISPCODE     36-37
         WINDDOWN     38
         SEQNO        39-44
         _PSU         39-44
         NATTMPTS     45-46
         NRECSEL      47-52
         NRECSTR      53-61
         NUMADULT     62-63
         NUMMEN       64
         NUMWOMEN     65

         GENHLTH      66    /* SECTION 1, HEALTH STATUS */
         PHYSHLTH     67-68
         MENTHLTH     69-70
         POORHLTH     71-72

         HLTHPLAN     73    /* SECTION 2, HEALTH CARE ACCESS */
         MEDICAR2     74
         TYPCOVR1     75-76
         TYPCOVR2     77-78
         NOCOV12      79
         PASTPLAN     80
         MEDCOST      81
         CHECKUP      82

         ASTHMA       83    /* SECTION 3, ASTHMA */
         ASTHNOW      84

         DIABETES     85    /* SECTION 4, DIABETES */

         CARETAKR     86    /* SECTION 5, CARE GIVING */
         LTCHELP      87-88

         EXERANY      89    /* SECTION 6, EXERCISE */
         EXERACT1     90-91
         EXERDIS1     92-94
         EXEROFT1     95-97
         EXERHMM1     98-100
         EXEROTH2    101
         EXERACT2    102-103
         EXERDIS2    104-106
         EXEROFT2    107-109
         EXERHMM2    110-112

         SMOKE100   113     /* SECTION 7, TOBACCO USE */
         SMOKEDAY   114
         SMOKENUM   115-116
         SMOKNM30   117-118
         STOPSMOK   119
         LASTSMOK   120-121

         FRUITJUI   122-124 /* SECTION 8, FRUITS AND VEGETABLES */
         FRUIT      125-127
         GREENSAL   128-130
         POTATOES   131-133
         CARROTS    134-136
         VEGETABL   137-139

         LOSEWT     140     /* SECTION 9, WEIGHT CONTROL */
         MAINTAIN   141
         FEWCAL     142
         PHYACT     143
         DRADVICE   144

         AGE        145-146 /* SECTION 10, DEMOGRAPHICS */
         ORACE      147
         HISPANIC   148
         MARITAL    149
         CHLD04     150
         CHLD0512   151
         CHLD1317   152
         EDUCA      153
         EMPLOY     154
         INCOME2    155-156
         VETERAN    157
         VETSTAT    158
         VACARE     159
         WEIGHT     160-162
         WTDESIRE   163-165
         HEIGHT     166-168
         HTF        166
         HTI        167-168
         CTYCODE    169-171
         NUMHHOLD   172
         NUMPHONS   173
         SEX        174

         HADMAM     175     /* SECTION 11, WOMENS HEALTH */
         HOWLONG    176
         WHYDONE    177
         PROFEXAM   178
         LENGEXAM   179
         REASEXAM   180
         HADPAP     181
         LASTPAP    182
         WHYPAP     183
         HADHYST    184
         PREGNANT   185

         GRADE2     186-187 /* SECTION 12, HIV/AIDS */
         CONDUSE    188
         GETHIV     189
         DONBLD85   190
         DON12MO    191
         HIVTST2A   192
         HIVTST2B   193
         HIV12MO    194
         TEST12MO   195
         RSNTST2    196-197
         WHRTST3    198-199
         RESULTS    200
         COUNSEL    201

         DIABAGE2   202-203 /* MODULE 1, DIABETES */
         INSULIN    204
         DIABPILL   205
         BLDSUGAR   206-208
         FEETCHK2   209-211
         FEETSORE   212
         DOCTDIAB   213-214
         CHKHEMO2   215-216
         FEETCHK    217-218
         EYEEXAM    219
         DIABEYE    220
         DIABEDU    221

         SEXINTMN   222-223 /* MODULE 2, SEXUAL BEHAVIOR */
         SEXCONDM   224
         CONDLAST   225
         CONEFF2    226
         NEWPARTN   227-228
         HIVRISK    229
         STDTREAT   230
         STDCLIN    231
         SEXBEHA2   232
         SELCPTN3   233
         SEX1PTN3   234
         USECOND3   235

         PREGLST5   236     /* MODULE 3, FAMILY PLANNING */
         LSTPREG    237
         LSTPREG2   238
         BRTHCNTL   239
         TYPCNTRL   240-241
         RSNNOBC    242-243
         WHRSVCS    244
         FAMPLAN    245
         LASTUSED   246

         RSNNOCOV   247-248 /* MODULE 4, HEALTH CARE COVERAGE AND UTILIZATION */
         RSNWOCOV   249-250
         PRIMCARE   251
         MOSTCARE   252
         FACILIT2   253

         PERSDOC    254     /* MODULE 5, HEALTH CARE SATISFACTION */
         ERCARE     255-256 /* NOTICE THAT PERSDOC IS SHARED BY MODULES 4 AND 5 */
         DRVISIT    257
         DRLISTEN   258
         DRRELATE   259
         DRESPECT   260
         DRPTTIME   261
         HCRATE     262

         LASTDEN2   263     /* MODULE 6, ORAL HEALTH */
         RMVTEETH   264
         DENCLEAN   265
         REASDENT   266-267
         DENTLINS   268

         BPTAKE     269     /* MODULE 7, HYPERTENSION AWARENESS */
         BPHIGH     270
         HIGHGT1    271

         BLOODCHO   272     /* MODULE 8, CHOLESTEROL AWARENESS */
         CHOLCHK    273
         TOLDHI     274

         BLDSTOOL   275     /* MODULE 9, COLORECTAL CANCER SCREENING */
         LSTBLDST   276
         HADSIGM    277
         LASTSIGM   278

         FLUSHOT    279     /* MODULE 10, IMMUNIZATION */
         PNEUMVAC   280

         CHLDLT16   281-282 /* MODULE 11, INJURY CONTROL */
         BIKEHLMT   283
         SMKDETE2   284

         DRINKANY   285     /* MODULE 12, ALCOHOL CONSUMPTION */
         ALCOHOL    286-288
         NALCOCC    289-290
         DRINKGE5   291-292
         DRINKDRI   293-294

         CVDFATRK   295     /* MODULE 13, CARDIOVASCULAR DISEASE */
         CVDEXRSK   296
         CVDFAT02   297
         CVDEXR02   298
         CVDINFAR   299
         CVDCORHD   300
         CVDSTROK   301
         CVDASPRN   302
         ASPUNSAF   303
         WHYASPAN   304
         WHYASPHA   305
         WHYASPSK   306
         PASTMENO   307
         DICSESTR   308
         ESTRPILL   309
         CURESTRO   310
         ESTRHART   311
         ESTRBONE   312
         ESTRFLSH   313

         PAIN12MN   314     /* MODULE 14, ARTHRITIS */
         SYMTMMTH   315
         LMTJOINT   316
         HAVARTH    317
         TYPEARTH   318-319
         TRTARTH    320

         QLACTLMT   321     /* MODULE 15, QUALITY OF LIFE AND CARE GIVING */
         HLTHPROB   322-323
         LONGLMTD   324-326
         QLPERSNL   327
         QLROUTIN   328
         PAINACTV   329-330
         QLMENTAL   331-332
         QLSTRESS   333-334
         QLREST     335-336
         QLHLTHY    337-338
         QLPCHELP   339-340
         QLPCLEVL   341
         QLRCHELP   342-343
         QLRCLEVL   344

         VITAMINS   345     /* MODULE 16, FOLIC ACID */
         MULTIVIT   346
         FOLICACD   347
         TAKEVIT    348-350
         RECOMMEN   351

         SUNBLOCK   352     /* MODULE 17, SKIN CANCER */
         SPFNUM     353-354
         AVOIDSUN   355
         SUNHAT     356
         SUNWEAR    357
         SUNSENS    358
         BURNTYPE   359

         TOBACCO    360     /* MODULE 18, TOBACCO USE PREVENTION */
         INDOORS    361
         SMKPUBLC   362
         SMKWORK    363
         SMKREST    364
         SMKSCHLS   365
         SMKDAYCR   366
         SMKINDOR   367
         QUITSMOK   368

         USEEVER    369     /* MODULE 19, SMOKELESS TOBACCO */
         USENOW     370

  @371   DISABLTY  $CHAR23. /* DISABILITY SECTION */

                            /* COLUMNS 394-399, RESERVED FOR CDC */

  @400   STATEQUE $CHAR200. /* STATE ADDED QUESTIONS SECTION */

                            /* COLUMNS 600-609, RESERVED FOR CDC */

                            /* SAMPLING DATA SECTION, COLUMNS 610-746 */

                            /* COLUMNS 747-764 ARE BLANK */

         _QSTVER    765     /* QUESTIONAIRE VERSION      */

         _STSTR     766-771
         _DENWT     772-781
         _GEOWT     782-791
         _RAW       792-801
         _CSA       802-811
         _WT1       812-821
         _POSTSTR   822-831
         _FINALWT   832-841
         _REGION    842-843
         _RACEG2_   844
         _AGEG_     845-846
         _SEXG_     847
         _IMPAGE    848-849
         _IMPNPH    850
         _MSACODE   851-854
         RACE       855-856
         _SMOKER2   857
         _DRNKMO    858-861
         _BMI2      862-864
         _BMI2CAT   865
         _RFBMI     866
         _TOTINDX   867
         _TOTINDA   868
         _TOTINDB   869
         _SMKLESS   870
         _FRTSERV   871-875
         _FRTINDX   876
         _RFHYPE2   877
         _RFSMOK2   878
         _RFDRACU   879
         _RFDRDRI   880
         _RFDRCHR   881
         _RFREGUL   882
         _RFTOBAC   883
         _CHOLCHK   884
         _BPCHECK   885
         _AGEG      886
         _AGEG5YR   887-888
         _AGE65YR   889
         _RACEG     890
         _RACEGR    891 ;

  LABEL _STATE   = 'STATE FIPS CODE'
        _GEOSTR  = 'STRATUM CODE'
        _DENSTR  = 'DENSITY STRATUM'
        LISTSTAT = 'LISTED STATUS'
        PRECALL  = 'PRECALLING STATUS'
        REPNUM   = 'REPLICATE NUMBER'
        REPDEPTH = 'REPLICATE DEPTH'
        _PSU     = 'PRIMARY SAMPLING UNIT'
        _RECORD  = 'RECORD NUMBER'
        IDATE    = 'DATE OF INTERVIEW'
        IMONTH   = 'MONTH OF INTERVIEW'
        IDAY     = 'DAY OF INTERVIEW'
        IYEAR    = 'YEAR OF INTERVIEW'
        INTVID   = 'INTERVIEWER ID'
        PHONENUM = 'PHONE NUMBER'
        AREACODE = 'AREA CODE'
        PREFIX   = 'PREFIX'
        SUFFIX   = 'SUFFIX'
        DISPCODE = 'DISPOSITION OF INTERVIEW'
        WINDDOWN = 'INTERVIEW IN REGULAR OR WINDDOWN MODE'
        SEQNO    = 'SEQUENCE NUMBER'
        NATTMPTS = 'NUMBER OF ATTEMPTS'
        NRECSEL  = 'NUMBER OF SAMPLE RECORDS FOR STRATUM'
        NRECSTR  = 'NO. OF PH. NOS. IN STRATUM FROM SAMPLE'
        NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
        NUMMEN   = 'NUMBER OF ADULT MALES IN HOUSEHOLD'
        NUMWOMEN = 'NUMBER OF ADULT FEMALES IN HOUSEHOLD'
        GENHLTH  = 'GENERAL HEALTH'
        PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
        MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
        POORHLTH = 'POOR PHYSICAL HEALTH'
        HLTHPLAN = 'HAVE ANY KIND OF HEALTH PLAN'
        MEDICAR2 = 'HAVE MEDICARE'
        TYPCOVR1 = 'TYPE COVERAGE PAYING FOR MOST MED CARE'
        TYPCOVR2 = 'TYPE COVERAGE MAYBE NOT CONSIDERED'
        NOCOV12  = 'NO HEALTH CARE COVERAGE IN PAST 12 MNTHS'
        PASTPLAN = 'LAST HAD HEALTH COVERAGE'
        MEDCOST  = 'TIME WHEN COULD NOT AFFORD TO SEE DOCTOR'
        CHECKUP  = 'HOW LONG SINCE LAST ROUTINE CHECKUP'
        BPTAKE   = 'HOW LONG SINCE BLOOD PRESSURE TAKEN'
        BPHIGH   = 'EVER TOLD BLOOD PRESSURE HIGH'
        HIGHGT1  = 'TOLD MORE THAN ONCE BP HIGH'
        BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
        CHOLCHK  = 'HOW LONG SINCE CHOLESTEROL CHECKED'
        TOLDHI   = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
        DIABETES = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
        CARETAKR = 'PROV. CARE FOR SOMEONE 60+ IN PAST MONTH'
        LTCHELP  = 'WHO WOULD CALL TO ARRANGE LONG-TERM CARE'
        LASTDEN2 = 'HOW LONG SINCE LAST DENTIST VISIT'
        RMVTEETH = 'NUMBER OF PERMANENT TEETH REMOVED'
        DENCLEAN = 'HOW LONG SINCE LAST TEETH CLEANING'
        REASDENT = 'MAIN REASON NOT VISIT DENTIST PAST YR'
        DENTLINS = 'DENTAL INSURANCE COVERAGE'
        SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
        SMOKEDAY = 'FREQUENCY OF DAYS NOW SMOKING'
        SMOKENUM = 'NUMBER OF CIGARETTES NOW SMOKED PER DAY'
        SMOKNM30 = 'CIGS SMOKED WHEN SMOKED LT 30 DAYS'
        STOPSMOK = 'QUIT SMOKING A DAY OR MORE IN PAST YEAR'
        LASTSMOK = 'HOW LONG SINCE LAST SMOKED CIGS'
        DRINKANY = 'ALCOHOLIC BEVERAGES IN PAST MONTH'
        ALCOHOL  = 'HOW OFTEN DRINK LIQUOR'
        NALCOCC  = 'AVERAGE NUMBER OF DRINKS PER OCCASION'
        DRINKGE5 = 'FIVE OR MORE DRINKS ON AN OCCASION'
        DRINKDRI = 'DRINK AND DRIVE'
        AGE      = 'REPORTED AGE IN YEARS'
        ORACE    = 'ORIGINAL REPORTED RACE'
        HISPANIC = 'HISPANIC ORIGIN'
        MARITAL  = 'MARITAL STATUS'
        CHLD04   = 'NUMBER OF CHILDREN  LT  5 YEARS OLD'
        CHLD0512 = 'NUMBER OF CHILDREN 5 TO 12 YEARS OLD'
        CHLD1317 = 'NUMBER OF CHILDREN 13 TO 17 YEARS OLD'
        EDUCA    = 'EDUCATION LEVEL'
        EMPLOY   = 'EMPLOYMENT STATUS'
        INCOME2  = 'INCOME LEVEL'
        VETERAN  = 'EVER SERVED IN THE U.S. ARMED FORCES'
        VETSTAT  = 'CURRENT MILITARY STATUS'
        VACARE   = 'RECEIVED CARE IN VA FACIL. PAST 12 MOS.'
        WEIGHT   = 'REPORTED WEIGHT IN POUNDS'
        HEIGHT   = 'REPORTED HEIGHT IN FEET AND INCHES'
        HTF      = 'HEIGHT FEET'
        HTI      = 'HEIGHT INCHES'
        CTYCODE  = 'COUNTY CODE'
        NUMHHOLD = 'MORE THAN ONE TELPHONE NUMBER IN HH'
        NUMPHONS = 'NUMBER OF UNIQUE PHONE NUMBERS IN HH'
        SEX      = 'SEX'
        HADMAM   = 'HAVE YOU EVER HAD A MAMMOGRAM'
        HOWLONG  = 'HOW LONG SINCE LAST MAMMOGRAM'
        WHYDONE  = 'REASON YOU HAD MAMMOGRAM'
        PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
        LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
        REASEXAM = 'REASON YOU HAD BREAST PHYSICAL EXAM'
        HADPAP   = 'EVER HAD A PAP SMEAR TEST'
        LASTPAP  = 'WHEN WAS LAST PAP SMEAR'
        WHYPAP   = 'REASON YOU HAD PAP SMEAR'
        HADHYST  = 'EVER HAD A HYSTERECTOMY'
        PREGNANT = 'ARE YOU NOW PREGNANT'
        FLUSHOT  = 'HAD FLU SHOT IN PAST 12 MONTHS'
        PNEUMVAC = 'EVER HAD PNEUMONIA VACCINATION'
        BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
        LSTBLDST = 'HOW LONG SINCE LAST HOME BLOOD STOOL TST'
        HADSIGM  = 'EVER HAD A SIGMOIDOSCOPY/COLONOSCOPY'
        LASTSIGM = 'HOW LONG SINCE SIGMOIDOSCOPY/COLONOSCOPY'
        CHLDLT16 = 'AGE OF OLDEST CHILD UNDER AGE 16'
        BIKEHLMT = 'BICYCLE HELMET WORN WHEN RIDING'
        SMKDETE2 = 'LAST TIME TESTED SMOKE DETECTORS'
        GRADE2   = 'GRADE TO BEGIN HIV INFECTN AND AIDS EDUC'
        CONDUSE  = 'ENCOURAGE SEX ACTIVE TEEN TO USE CONDOM'
        GETHIV   = 'CHANCES OF GETTING INFECTED WITH HIV'
        DONBLD85 = 'DONATED BLOOD SINCE MARCH 1985'
        DON12MO  = 'DONATED BLOOD IN PAST 12 MONTHS'
        HIVTST2A = 'EVER TSTD FOR HIV OTHR THAN BLOOD DONATN'
        HIVTST2B = 'EVER TESTED FOR HIV'
        HIV12MO  = 'HIV TST PAST 12MO OTHR THAN BLOOD DONATN'
        TEST12MO = 'TESTED FOR HIV PAST 12 MONTHS'
        RSNTST2  = 'MAIN REASON FOR HIV TEST'
        WHRTST3  = 'WHERE WAS LAST BLOOD TEST FOR HIV'
        RESULTS  = 'RECEIVED RESULTS OF LAST TEST'
        COUNSEL  = 'RECEIVED COUNSELING ABOUT TEST RESULTS'
        DIABAGE2 = 'AGE WHEN TOLD DIABETIC'
        INSULIN  = 'NOW TAKING INSULIN'
        DIABPILL = 'NOW TAKING DIABETES PILLS'
        BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
        FEETCHK2 = 'HOW OFTEN CHECK FOR SORES/IRRITATIONS'
        FEETSORE = 'EVER HAD SORES/IRRITATIONS 4+ WEEKS'
        DOCTDIAB = 'TIMES SEEN HEALTH PROF FOR DIABETES'
        CHKHEMO2 = 'TIMES CHECK FOR GLYCOSYLATED HEMOGLOBIN'
        FEETCHK  = 'TIMES HEALTH PROF CHECK FEET PAST 12 MOS'
        EYEEXAM  = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
        DIABEYE  = 'EVER TOLD DIABETES HAS AFFECTED EYES'
        DIABEDU  = 'EVER TAKEN CLASS TO MANAGE DIABETES'
        SEXINTMN = 'HOW MANY PARTNERS IN PAST 12 MONTHS'
        SEXCONDM = 'CONDOM USED LAST INTERCOURSE'
        CONDLAST = 'WHY WAS CONDOM USED'
        CONEFF2  = 'CONDOM EFFECTIVENESS AGAINST HIV'
        NEWPARTN = 'NUMBER NEW SEX PRTNRS IN LAST 12 MONTHS'
        HIVRISK  = 'ANY HIGH RISK SITUATIONS APPLY'
        STDTREAT = 'TREATED FOR STD OR VD IN PAST FIVE YEARS'
        STDCLIN  = 'TREATED AT HEALTH DEPT STD CLINIC?'
        SEXBEHA2 = 'CHANGED SEXUAL BEHAVIOR LAST 12 MOS.'
        SELCPTN3 = 'DECREASE NUMB SEX PTNRS OR ABSTINENT'
        SEX1PTN3 = 'NOW HAVE SEX WITH ONLY THE SAME PARTNER'
        USECOND3 = 'NOW ALWAYS USE CONDOMS FOR PROTECTION'
        PREGLST5 = 'PREGNANT IN LAST 5 YEARS'
        LSTPREG  = 'FEEL ABOUT BECOMING PREGNANT-LAST'
        LSTPREG2 = 'FEEL ABOUT BECOMING PREGNANT-CURRENT'
        BRTHCNTL = 'CURRENT BIRTH CONTROL USE'
        TYPCNTRL = 'BIRTH CONTROL TYPE'
        RSNNOBC  = 'REASON NO BIRTH CONTROL'
        WHRSVCS  = 'USUAL SOURCE FOR FEMALE HEALTH CARE'
        FAMPLAN  = 'EVER USE FAMILY PLANNING CLINIC'
        LASTUSED = 'WHEN LAST USED CLINIC'
        RSNNOCOV = 'MAIN REASON WITHOUT HEALTH CARE COVERAGE'
        RSNWOCOV = 'REASON N0 COVERAGE IN PAST TWELVE MONTHS'
        PRIMCARE = 'PARTICULAR DOCTOR OR CLINIC'
        MOSTCARE = 'ONE PLACE YOU GO MOST OFTEN'
        FACILIT2 = 'KIND OF PLACE YOU GO TO MOST OFTEN'
        PERSDOC  = 'HAVE PERS DOC OR HLTH CARE PROVIDER'
        ERCARE   = 'ER VISITS IN PAST 12 MONTHS'
        DRVISIT  = 'DOCTOR VISITS IN PAST 12 MONTHS'
        DRLISTEN = 'HOW OFTEN HLTH CARE PROV LISTN CAREFULLY'
        DRRELATE = 'HOW OFTEN HLTH CARE PROV EXPLAIN CLEARLY'
        DRESPECT = 'HOW OFTEN HLTH CARE PROV SHOW RESPECT'
        DRPTTIME = 'HOW OFTEN HLTH CARE PROV SPEND ENGH TIME'
        HCRATE   = 'HEALTH CARE RATING'
        ASTHMA   = 'EVER HAD ASTHMA'
        ASTHNOW  = 'HAVE ASTHMA NOW'
        CVDFATRK = 'DOCTOR ADVISED FEWER FAT/CHOLESTEROL'
        CVDEXRSK = 'DOCTOR ADVISED EXERCISE MORE'
        CVDFAT02 = 'ARE YOU EATING FEWER FAT/CHOLESTEROL'
        CVDEXR02 = 'ARE YOU EXERCISING MORE'
        CVDINFAR = 'EVER TOLD HAD MYOCARDIAL INFARCTION'
        CVDCORHD = 'EVER TOLD HAD CORONARY HEART DISEASE'
        CVDSTROK = 'EVER TOLD HAD STROKE'
        CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
        ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
        WHYASPAN = 'TAKE ASPIRIN TO RELIEVE PAIN'
        WHYASPHA = 'TAKE ASPIRIN TO REDUCE HEART ATTACK'
        WHYASPSK = 'TAKE ASPIRIN TO REDUCE STROKE'
        PASTMENO = 'GONE THROUGH MENOPAUSE'
        DICSESTR = 'DOC DISCUSSED BENEFITS/RISKS OF ESTROGEN'
        ESTRPILL = 'DOCTOR PRESCRIBED ESTROGEN PILLS'
        CURESTRO = 'CURRENTLY TAKING ESTROGEN'
        ESTRHART = 'TAKE/TOOK ESTROGEN TO PREVENT HRT ATTACK'
        ESTRBONE = 'TAKE/TOOK ESTROGEN FOR BONES'
        ESTRFLSH = 'TAKE/TOOK ESTROGEN TO TREAT MENOPAUSE'
        PAIN12MN = 'HAD PAIN, ACHING, STIFFNESS, SWELLING'
        SYMTMMTH = 'SYMPTOMS PRESENT AT LEAST ONE MONTH'
        LMTJOINT = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
        HAVARTH  = 'TOLD HAVE ARTHRITIS BY DOCTOR'
        TYPEARTH = 'TYPE ARTHRITIS DOCTOR DIAGNOSED'
        TRTARTH  = 'CURRENTLY TREATED BY DOC FOR ARTHRITIS'
        QLACTLMT = 'ACTICITIES LIMITED DUE TO HEALTH PROBLEM'
        HLTHPROB = 'WHAT IS MAJOR HEALTH PROBLEM'
        LONGLMTD = 'HOW LONG ACTIVITIES LIMITED'
        QLPERSNL = 'NEED OTHERS TO HELP WITH PERSONAL CARE'
        QLROUTIN = 'NEED OTHERS TO HELP WITH ROUTINE NEEDS'
        PAINACTV = 'TIMES IN PAST MONTH PAIN INTERFERED'
        QLMENTAL = 'TIMES IN PAST MONTH FELT DEPRESSED'
        QLSTRESS = 'TIMES IN PAST MONTH BEEN STRESSED'
        QLREST   = 'TIMES IN PAST MONTH NOT ENOUGH REST'
        QLHLTHY  = 'TIMES IN PAST MONTH FELT HEALTHY'
        QLPCHELP = 'WHO HELPS WITH PERSONAL CARE NEEDS'
        QLPCLEVL = 'ADEQUACY OF PERSONAL CARE HELP'
        QLRCHELP = 'WHO HELPS WITH ROUTINE NEEDS'
        QLRCLEVL = 'ADEQUACY OF ROUTINE HELP'
        FRUITJUI = 'HOW OFTEN DO YOU DRINK FRUIT JUICES'
        FRUIT    = 'HOW OFTEN DO YOU EAT FRUIT'
        GREENSAL = 'HOW OFTEN DO YOU EAT GREEN SALAD'
        POTATOES = 'HOW OFTEN DO YOU EAT POTATOES'
        CARROTS  = 'HOW OFTEN DO YOU EAT CARROTS'
        VEGETABL = 'SERVINGS OF VEGETABLES'
        EXERANY  = 'PARTICIPATE IN ANY PHYSICAL ACTIVITY'
        EXERACT1 = 'TYPE OF PHYSICAL ACTIVITY'
        EXERDIS1 = 'DISTANCE IN MILES AND TENTHS'
        EXEROFT1 = 'HOW MANY TIMES ACTIVITY DONE'
        EXERHMM1 = 'HOW LONG ACTIVITY DONE'
        EXEROTH2 = 'PARTICIPATE IN ANOTHER ACTIVITY'
        EXERACT2 = 'TYPE OF OTHER PHYSICAL ACTIVITY'
        EXERDIS2 = 'DISTANCE IN MILES AND TENTHS'
        EXEROFT2 = 'HOW MANY TIMES SECOND ACTIVITY DONE'
        EXERHMM2 = 'HOW LONG SECOND ACTIVITY DONE'
        LOSEWT   = 'TRYING TO LOSE WEIGHT'
        MAINTAIN = 'TRYING TO MAINTAIN CURRENT WEIGHT'
        FEWCAL   = 'FEWER CALORIES AND/OR LESS FAT'
        PHYACT   = 'INCREASED PHYSICAL ACTIVITY'
        WTDESIRE = 'DESIRED WEIGHT'
        DRADVICE = 'PROFESSIONAL ADVICE ABOUT WEIGHT'
        VITAMINS = 'CURRENTLY TAKE VIT PILLS OR SUPPLEMENTS'
        MULTIVIT = 'ANY OF VITS/SUPPLEMENTS A MULTIVITAMIN'
        FOLICACD = 'ANY VITAMINS CONTAIN FOLIC ACID'
        TAKEVIT  = 'HOW OFTEN TAKE VITAMIN OR SUPPLEMENT'
        RECOMMEN = 'REASONS HLTH EXPERTS RECMND FOLIC ACID'
        SUNBLOCK = 'HOW OFTEN USE SUNSCREEN'
        SPFNUM   = 'SPF OF SUNSCREEN'
        AVOIDSUN = 'HOW OFTEN STAY IN SHADE'
        SUNHAT   = 'HOW OFTEN WEAR HAT'
        SUNWEAR  = 'HOW OFTEN WEAR LONG-SLEEVED SHIRTS'
        SUNSENS  = 'HOW SENSITIVE TO SUN'
        BURNTYPE = 'HOW EASY TO SUNBURN'
        TOBACCO  = 'SMOKING IN HOME PAST 30 DAYS'
        INDOORS  = 'INDOOR WORK LOCATION'
        SMKPUBLC = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
        SMKWORK  = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
        SMKREST  = 'SMOKING ALLOWED IN RESTAURANTS'
        SMKSCHLS = 'SMOKING ALLOWED IN SCHOOLS'
        SMKDAYCR = 'SMOKING ALLOWED IN DAY CARE CENTERS'
        SMKINDOR = 'SMOKING ALLOWED IN INDOOR WORK AREAS'
        QUITSMOK = 'HEALTH PROF EVER ADVISED TO QUIT SMOKING'
        USEEVER  = 'EVER USED SMOKELESS TOBACCO PRODUCTS'
        USENOW   = 'CURRENTLY USE SMOKELESS TOBACCO PRODUCTS'
        DISABLTY = 'DISABILITY QUESTIONS'
        STATEQUE = 'STATE ADDED QUESTIONS'
        _QSTVER  = 'QUESTIONAIRE VERSION'
        _STSTR   = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
        _DENWT   = 'DENSITY STRATUM WEIGHT'
        _GEOWT   = 'GEOGRAPHIC STRATUM WEIGHT'
        _RAW     = "RAW: # ADULTS IN HH/# PH #'S TO HH"
        _CSA     = 'CLUSTER SIZE ADJUSTMENT'
        _WT1     = 'DESIGN WEIGHT'
        _POSTSTR = 'POST STRATIFICATION WEIGHT'
        _FINALWT = 'FINAL WEIGHT'
        _REGION  = 'REGION'
        _RACEG2_ = 'RACE GROUP CODES USED IN POSTSTRTFCATION'
        _AGEG_   = 'AGE GROUP CODES USED IN POSTSTRATFCATION'
        _SEXG_   = 'GENDER GRP CODES USED IN POSTSTRTFCATION'
        _IMPAGE  = 'IMPUTED AGE'
        _MSACODE = 'METROPOLITAN STATISTICAL AREA CODE'
        RACE     = 'NEW RACE CODE'
        _SMOKER2 = 'SMOKING STATUS(2)'
        _DRNKMO  = 'TOTAL NUMBER DRINKS A MONTH'
        _BMI2    = 'BODY MASS INDEX'
        _BMI2CAT = '_BMI2 CATEGORIZED'
        _RFBMI   = 'OVERWEIGHT OR OBESE'
        _TOTINDX = 'PHYSICAL ACTIVITY LEVEL'
        _TOTINDA = 'LEISURE TIME PHYSICAL ACTIVITY'
        _TOTINDB = 'REGULAR AND VIGOROUS PHYSICAL ACTIVITY'
        _SMKLESS = 'SMOKELESS STATUS'
        _FRTSERV = 'DAILY SERVINGS OF FRUITS AND VEGETABLES'
        _FRTINDX = 'SUMMARY INDEX FOR FRUITS AND VEGETABLES'
        _RFHYPE2 = 'HYPERTENSION(2)'
        _RFSMOK2 = 'SMOKING(2)'
        _RFDRACU = 'ACUTE DRINKING'
        _RFDRDRI = 'DRINKING AND DRIVING'
        _RFDRCHR = 'CHRONIC DRINKING'
        _RFREGUL = 'REGULAR AND SUSTAINED PHYSICAL ACTIVITY'
        _RFTOBAC = 'SMOKELESS TOBACCO (CURRENT USER)'
        _CHOLCHK = 'CHOLESTEROL CHECKED'
        _BPCHECK = 'BLOOD PRESSURE CHECKED'
        _AGEG    = 'REPORTED AGE IN THREE AGE GROUPS'
        _AGEG5YR = 'REPORTED AGE IN 5 YEAR AGE CATEGORIES'
        _AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS'
        _RACEG   = 'NON-HISPANIC WHITES/ALL OTHERS'
        _RACEGR  = 'RACE AND ETHNICITY'
        _IMPNPH  = 'IMPUTTED # OF PHONES USED IN WEIGHTING' ;
RUN ;

FILENAME DATAIN CLEAR ;
LIBNAME DATAOUT CLEAR ;
RUN ;
