 FORMAT   AGE            AGE.
          ALCDAY4        ALC4DAY.
          ARTHEDU        ARTHEDU.
          ARTHEXER       ARTHEXER.
          ARTHWGT        ARTHWGT.
          ARTTODAY       ARTTODAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASINHALR       ASINHALR.
          ASNOSLEP       ASNOSLEP.
          ASPUNSAF       ASPUNSAF.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMED2       ASTH2MED.
          ASTHMAGE       ASTHMAGE.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK2       AVE2DRNK.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BLOODCHO       BLOODCHO.
          BPHIGH4        BP4HIGH.
          BPALCADV       BPALCADV.
          BPALCHOL       BPALCHOL.
          BPEATADV       BPEATADV.
          BPEATHBT       BPEATHBT.
          BPEXER         BPEXER.
          BPEXRADV       BPEXRADV.
          BPHI2MR        BPHI2MR.
          BPMEDADV       BPMEDADV.
          BPMEDS         BPMEDS.
          BPSALT         BPSALT.
          BPSLTADV       BPSLTADV.
          CARROTS        CARROTS.
          CASTHDX2       CASTH2DX.
          CASTHNO2       CASTH2NO.
          CELLFON        CELLFON.
          CHECKUP        CHECKUP.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CHOLCHK        CHOLCHK.
          CIFLUMST       CIFLUMST.
          CIFLUSHT       CIFLUSHT.
          CTELENUM       CTELENUM.
          CVDCRHD3       CVD3CRHD.
          CVDINFR3       CVD3INFR.
          CVDSTRK3       CVD3STRK.
          CVDASPRN       CVDASPRN.
          DENCLEAN       DENCLEAN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIABPILL       DIABPILL.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRADVICE       DRADVICE.
          DRETIME        DRETIME.
          DRNK2GE5       DRNK25GE.
          DRNKANY4       DRNK4ANY.
          DROCDY2_       DROCDY2_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FEETSORE       FEETSORE.
          FEWCAL         FEWCAL.
          FIRSTAID       FIRSTAID.
          FLUSPRY2       FLU2SPRY.
          FLUSHOT3       FLU3SHOT.
          FMONTH         FMONTH.
          FRUIT          FRUIT.
          FRUITJUI       FRUITJUI.
          GREENSAL       GREENSAL.
          HASYMP1        HA1SYMP.
          HASYMP2        HA2SYMP.
          HASYMP3        HA3SYMP.
          HASYMP4        HA4SYMP.
          HASYMP5        HA5SYMP.
          HASYMP6        HA6SYMP.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HAREHAB        HAREHAB.
          HAVARTH2       HAV2ARTH.
          HECHMHOM       HECHMHOM.
          HECHMYRD       HECHMYRD.
          HEIGHT3        HEIGHT.
          HEWTRDRK       HEWTRDRK.
          HEWTRSRC       HEWTRSRC.
          HISPANC2       HISP2ANC.
          HIVRISK2       HIV2RISK.
          HIVTST5        HIV5TST.
          HLTHPLAN       HLTHPLAN.
          HOUSESMK       HOUSESMK.
          HOWLONG        HOWLONG.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IAQCODTR       IAQCODTR.
          IAQGASAP       IAQGASAP.
          IAQHTDYS       IAQHTDYS.
          IAQHTSRC       IAQHTSRC.
          IAQMOLD        IAQMOLD.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INDOORS        INDOORS.
          INSULIN        INSULIN.
          IPVPVL12       IPV12PVL.
          IPVPHHRT       IPVPHHRT.
          IPVPHYVL       IPVPHYVL.
          IPVRELTN       IPVRELTN.
          IPVSXINJ       IPVSXINJ.
          IPVTHRAT       IPVTHRAT.
          IPVUWSEX       IPVUWSEX.
          JOBACTIV       JOBACTIV.
          JOINTRT2       JOIN2TRT.
          JOINTSYM       JOINTSYM.
          LASTPAP2       LAST2PAP.
          LASTSIG2       LAST2SIG.
          LASTDEN3       LAST3DEN.
          LENGEXAM       LENGEXAM.
          LMTJOIN2       LMT2JOIN.
          LOSEWT         LOSEWT.
          LSTBLDS2       LST2BLDS.
          MAINTAIN       MAINTAIN.
          MARITAL        MARITAL.
          MAXDRNKS       MAXDRNKS.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MODCAT_        MODCAT_.
          MODPACT        MODPACT.
          MODPADAY       MODPADAY.
          MODPATIM       MODPATIM.
          MSCODE         MSCODE.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          _CASTHMA       NY.
          ORACE2         O2RACE.
          OSTPROS        OSTPROS.
          PACAT_         PACAT_.
          PAINACT2       PAIN2ACT.
          PAIN30DY       PAIN30DY.
          PERSDOC2       PERS2DOC.
          PHYACT         PHYACT.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC3       PNEU3VAC.
          POORHLTH       POORHLTH.
          POTATOES       POTATOES.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RCHISLAT       RCHISLAT.
          RCSBRACE       RCSBRACE.
          RCSGENDR       RCSGENDR.
          RCSRELTN       RCSRELTN.
          RMVTEETH       RMVTEETH.
          RREMTSM1       RR1EMTSM.
          RRPHYSM1       RR1PHYSM.
          SCDSCMED       SCDSCMED.
          SCDSCMTH       SCDSCMTH.
          SCGETCAR       SCGETCAR.
          SCLSTSMK       SCLSTSMK.
          SCQITSMK       SCQITSMK.
          SEX            SEX.
          SMKPUBLC       SMKPUBLC.
          SMKWORK        SMKWORK.
          SMOKE100       SMOK100_.
          SMOKDAY2       SMOK2DAY.
          STOPSMK2       STOP2SMK.
          STRSYMP1       STR1SYMP.
          STRSYMP2       STR2SYMP.
          STRSYMP3       STR3SYMP.
          STRSYMP4       STR4SYMP.
          STRSYMP5       STR5SYMP.
          STRSYMP6       STR6SYMP.
          STREHAB        STREHAB.
          SVEANOSX       SVEANOSX.
          SVEHDSEX       SVEHDSEX.
          SVGENDER       SVGENDER.
          SVHADSEX       SVHADSEX.
          SVNOSEX        SVNOSEX.
          SVNOTCH        SVNOTCH.
          SVRELATN       SVRELATN.
          SVSEXTCH       SVSEXTCH.
          TELSERV2       TEL2SERV.
          TOLDHI2        TOLD2HI.
          HIVTSTD2       UNK6ADIG.
          USEEQUIP       USEEQUIP.
          VEGETABL       VEGETABL.
          VETSTAT2       VET2STAT.
          VETERAN        VETERAN.
          VIATWORK       VIATWORK.
          VICATRCT       VICATRCT.
          VIDIFCLT       VIDIFCLT.
          VIEYEEXM       VIEYEEXM.
          VIGCAT_        VIGCAT_.
          VIGLUCMA       VIGLUCMA.
          VIGPACT        VIGPACT.
          VIGPADAY       VIGPADAY.
          VIGPATIM       VIGPATIM.
          VIINSUR        VIINSUR.
          VIMACDEG       VIMACDEG.
          VIMISWRK       VIMISWRK.
          VINOCARE       VINOCARE.
          VIPRFVST       VIPRFVST.
          VIREADIF       VIREADIF.
          VITELDIF       VITELDIF.
          WEIGHT2        WEIGHT.
          WHRTST7        WHR7TST.
          WTKG2          WT2KG.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _PNEUMO2       _2PNEUMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _DRNKDY3       _3DRNKDY.
          _DRNKMO3       _3DRNKMO.
          _FLSHOT3       _3FLSHOT.
          _RFBING3       _3RFBING.
          _RFDRHV3       _3RFDRHV.
          _RFDRMN3       _3RFDRMN.
          _RFDRWM3       _3RFDRWM.
          _RFSMOK3       _3RFSMOK.
          _SMOKER3       _3SMOKER.
          _BMI4          _4BMI.
          _RFBMI4        _4RFBMI.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CHLDCNT       _CHLDCNT.
          _CHOLCHK       _CHOLCHK.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _CRACE         _CRACE.
          _DRDXART       _DRDXART.
          _EDUCAG        _EDUCAG.
          _FRTINDX       _FRTINDX.
          _FV5SRV        _FV5SRV.
          _HIGHRSK       _HIGHRSK.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _MRACE         _MRACE.
          _PRACE         _PRACE.
          _RACE_G        _RACE_G.
          _RFCHOL        _RFCHOL.
          _RFNOPA        _RFNOPA.
          _RFPAMOD       _RFPAMOD.
          _RFPAREC       _RFPAREC.
          _RFPAVIG       _RFPAVIG.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
