 FORMAT   ACEDEPRS       ACEDEPRS.
          ACEDIVRC       ACEDIVRC.
          ACEDRINK       ACEDRINK.
          ACEDRUGS       ACEDRUGS.
          ACEHURT        ACEHURT.
          ACEHVSEX       ACEHVSEX.
          ACEPRISN       ACEPRISN.
          ACEPUNCH       ACEPUNCH.
          ACESWEAR       ACESWEAR.
          ACETOUCH       ACETOUCH.
          ACETTHEM       ACETTHEM.
          AGE            AGE.
          ALCDAY4        ALC4DAY.
          ARTHDIS2       ARTH2DIS.
          ARTHEDU        ARTHEDU.
          ARTHEXER       ARTHEXER.
          ARTHSOCL       ARTHSOCL.
          ARTHWGT        ARTHWGT.
          ARTTODAY       ARTTODAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASINHALR       ASINHALR.
          ASNOSLEP       ASNOSLEP.
          ASPUNSAF       ASPUNSAF.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMED3       ASTH3MED.
          ASTHMAGE       ASTHMAGE.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK2       AVE2DRNK.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BLOODCHO       BLOODCHO.
          BPHIGH4        BP4HIGH.
          BPALCADV       BPALCADV.
          BPALCHOL       BPALCHOL.
          BPEATADV       BPEATADV.
          BPEATHBT       BPEATHBT.
          BPEXER         BPEXER.
          BPEXRADV       BPEXRADV.
          BPHI2MR        BPHI2MR.
          BPMEDADV       BPMEDADV.
          BPMEDS         BPMEDS.
          BPSALT         BPSALT.
          BPSLTADV       BPSLTADV.
          CADULT         CADULT.
          CALLBACK       CALLBACK.
          CAREGIVE       CAREGIVE.
          CARROTS        CARROTS.
          CASTHDX2       CASTH2DX.
          CASTHNO2       CASTH2NO.
          CELLFON2       CELL2FON.
          CELLFON        CELLFON.
          CHECKUP1       CHECK1UP.
          CHILDAGE       CHILDAGE.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CHOLCHK        CHOLCHK.
          CMDGPBAT       CMDGPBAT.
          CMDGPDSL       CMDGPDSL.
          CMDGPGEN       CMDGPGEN.
          CMDGPLOC       CMDGPLOC.
          CMDGPOWN       CMDGPOWN.
          CMDGPPWR       CMDGPPWR.
          CMDGPRUN       CMDGPRUN.
          CNCRAGE        CNCRAGE.
          CNCRDIFF       CNCRDIFF.
          CNCRHAVE       CNCRHAVE.
          CNCRTYPE       CNCRTYPE.
          CPDEMO1        CP1DEMO.
          CPDEMO2        CP2DEMO.
          CPDEMO3        CP3DEMO.
          CPDEMO4        CP4DEMO.
          CRGVAGE        CRGVAGE.
          CRGVCHNG       CRGVCHNG.
          CRGVDIFF       CRGVDIFF.
          CRGVGNDR       CRGVGNDR.
          CRGVHRS        CRGVHRS.
          CRGVLONG       CRGVLONG.
          CRGVMOST       CRGVMOST.
          CRGVPROB       CRGVPROB.
          CRGVRELT       CRGVRELT.
          CSRVCLIN       CSRVCLIN.
          CSRVCTRL       CSRVCTRL.
          CSRVDEIN       CSRVDEIN.
          CSRVDOC        CSRVDOC.
          CSRVINSR       CSRVINSR.
          CSRVINST       CSRVINST.
          CSRVPAIN       CSRVPAIN.
          CSRVRTRN       CSRVRTRN.
          CSRVSUM        CSRVSUM.
          CSRVTRT        CSRVTRT.
          CSTATE         CSTATE.
          CTELNUM1       CTEL1NUM.
          CTELENUM       CTELENUM.
          CVDSTRK3       CVD3STRK.
          CVDCRHD4       CVD4CRHD.
          CVDINFR4       CVD4INFR.
          CVDASPRN       CVDASPRN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRETIME        DRETIME.
          DRNK3GE5       DRNK35GE.
          DRNKANY4       DRNK4ANY.
          DROCDY2_       DROCDY2_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EMTSUPRT       EMTSUPRT.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FIRSTAID       FIRSTAID.
          FLUSPRY2       FLU2SPRY.
          FLUSHOT3       FLU3SHOT.
          FLUSHCH1       FLUSH1CH.
          FLUSHTMY       FLUSHTMY.
          FLUSPRMY       FLUSPRMY.
          FMONTH         FMONTH.
          FRUIT          FRUIT.
          FRUITJUI       FRUITJUI.
          GENHLTH        GENHLTH.
          GP3DYFD1       GP3DY1FD.
          GP3DYPRS       GP3DYPRS.
          GP3DYWTR       GP3DYWTR.
          GPWELPR3       GP3WELPR.
          GPBATRAD       GPBATRAD.
          GPEMRCM1       GPEMR1CM.
          GPEMRIN1       GPEMR1IN.
          GPFLSLIT       GPFLSLIT.
          GPMNDEVC       GPMNDEVC.
          GPNOTEV1       GPNOT1EV.
          GPVACPL1       GPVAC1PL.
          GREENSAL       GREENSAL.
          H1N1AV01       H1N101AI.
          H1N1CV01       H1N101CI.
          H1N1AV02       H1N102AI.
          H1N1CV02       H1N102CI.
          H1N1AV03       H1N103AI.
          H1N1CV03       H1N103CI.
          H1N1CV04       H1N104CI.
          H1N1CV05       H1N105CI.
          H1N1CV06       H1N106CI.
          H1N1AQ01       H1N1A01Q.
          H1N1AQ02       H1N1A02Q.
          H1N1AQ03       H1N1A03Q.
          H1N1AQ04       H1N1A04Q.
          H1N1AQ05       H1N1A05Q.
          H1N1AQ06       H1N1A06Q.
          H1N1AQ07       H1N1A07Q.
          H1N1AQ08       H1N1A08Q.
          H1N1AQ09       H1N1A09Q.
          H1N1AQ10       H1N1A10Q.
          H1N1CQ01       H1N1C01Q.
          H1N1CQ02       H1N1C02Q.
          HAREHAB1       HA1REHAB.
          HASYMP1        HA1SYMP.
          HASYMP2        HA2SYMP.
          HASYMP3        HA3SYMP.
          HASYMP4        HA4SYMP.
          HASYMP5        HA5SYMP.
          HASYMP6        HA6SYMP.
          HADSGCO1       HAD1SGCO.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HAVARTH2       HAV2ARTH.
          HAVHPAD        HAVHPAD.
          HEIGHT3        HEIGHT.
          HISPANC2       HISP2ANC.
          HIVRISK2       HIV2RISK.
          HIVTST5        HIV5TST.
          HIVRDTST       HIVRDTST.
          HLTHPLAN       HLTHPLAN.
          HOWLONG        HOWLONG.
          HPVADSHT       HPVADSHT.
          HPVADVC        HPVADVC.
          HPVCHSHT       HPVCHSHT.
          HPVCHVC        HPVCHVC.
          WRKHCF1        HR01HCW.
          DIRCONT1       HR02HCW.
          DRHPAD1        HR03HCW.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IAQCODT1       IAQ1CODT.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INSULIN        INSULIN.
          JOBACTIV       JOBACTIV.
          JOINPAIN       JOINPAIN.
          LANDLINE       LANDLINE.
          LASTSMK1       LAST1SMK.
          LASTPAP2       LAST2PAP.
          LASTSIG3       LAST3SIG.
          LENGEXAM       LENGEXAM.
          LMTJOIN2       LMT2JOIN.
          LSATISFY       LSATISFY.
          LSTBLDS3       LST3BLDS.
          MARITAL        MARITAL.
          MAXDRNKS       MAXDRNKS.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MISDEPRD       MISDEPRD.
          MISEFFRT       MISEFFRT.
          MISHOPLS       MISHOPLS.
          MISNERVS       MISNERVS.
          MISNOWRK       MISNOWRK.
          MISPHLPF       MISPHLPF.
          MISRSTLS       MISRSTLS.
          MISTMNT        MISTMNT.
          MISTRHLP       MISTRHLP.
          MISWTLES       MISWTLES.
          MODCAT_        MODCAT_.
          MODPACT        MODPACT.
          MODPADAY       MODPADAY.
          MODPATIM       MODPATIM.
          MSCODE         MSCODE.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          _CASTHMA       NY.
          ORACE2         O2RACE.
          PACAT_         PACAT_.
          PAINACT2       PAIN2ACT.
          PDIABTST       PDIABTST.
          PERSDOC2       PERS2DOC.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC3       PNEU3VAC.
          POORHLTH       POORHLTH.
          POTATOES       POTATOES.
          PREDIAB1       PRE1DIAB.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESD2       PVT2RESD.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RCHISLAT       RCHISLAT.
          RCSRLTN2       RCS2RLTN.
          RCSBRACE       RCSBRACE.
          RCSGENDR       RCSGENDR.
          RENTHOM1       RENT1HOM.
          RRATWRK2       RR2ATWRK.
          RRCOGNT2       RR2COGNT.
          RREMTSM2       RR2EMTSM.
          RRPHYSM2       RR2PHYSM.
          RRHCARE3       RR3HCARE.
          RRCLASS2       RRCLASS.
          RSPSTATE       RSPSTATE.
          SCNTLPAD       SCNTLPAD.
          SCNTLWRK       SCNTLWRK.
          SCNTMEAL       SCNTMEAL.
          SCNTMONY       SCNTMONY.
          SCNTPAID       SCNTPAID.
          SCNTVOTE       SCNTVOTE.
          SCNTWORK       SCNTWORK.
          SEX            SEX.
          SHINGLES       SHINGLES.
          SLEPDAY        SLEPDAY.
          SLEPDRIV       SLEPDRIV.
          SLEPSNOR       SLEPSNOR.
          SLEPTIME       SLEPTIME.
          SMOKE100       SMOK100_.
          SMOKDAY2       SMOK2DAY.
          STREHAB1       ST1REHAB.
          STOPSMK2       STOP2SMK.
          STRSYMP1       STR1SYMP.
          STRSYMP2       STR2SYMP.
          STRSYMP3       STR3SYMP.
          STRSYMP4       STR4SYMP.
          STRSYMP5       STR5SYMP.
          STRSYMP6       STR6SYMP.
          TELSERV2       TEL2SERV.
          TNSARCNT       TNSARCNT.
          TNSARCV        TNSARCV.
          TNSASHOT       TNSASHOT.
          TNSCRCNT       TNSCRCNT.
          TNSCRCV        TNSCRCV.
          TNSCSHOT       TNSCSHOT.
          TOLDHI2        TOLD2HI.
          HIVTSTD2       UNK6ADIG.
          USENOW3        USE3NOW.
          USEEQUIP       USEEQUIP.
          VEGETABL       VEGETABL.
          VETERAN2       VET2ERAN.
          VICTRCT2       VI2CTRCT.
          VIDFCLT2       VI2DFCLT.
          VIEYEXM2       VI2EYEXM.
          VIGLUMA2       VI2GLUMA.
          VIINSUR2       VI2INSUR.
          VINOCRE2       VI2NOCRE.
          VIPRFVS2       VI2PRFVS.
          VIREDIF2       VI2REDIF.
          VIGCAT_        VIGCAT_.
          VIGPACT        VIGPACT.
          VIGPADAY       VIGPADAY.
          VIGPATIM       VIGPATIM.
          VIMACDG2       VIMAC2DG.
          WEIGHT2        WEIGHT.
          WHRTST8        WHR7TST.
          WTKG2          WT2KG.
          WTCHGINT       WTCHGINT.
          WTYRAGO        WTYRAGO.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _PNEUMO2       _2PNEUMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _DRNKDY3       _3DRNKDY.
          _DRNKMO3       _3DRNKMO.
          _FLSHOT3       _3FLSHOT.
          _RFDRHV3       _3RFDRHV.
          _RFDRMN3       _3RFDRMN.
          _RFDRWM3       _3RFDRWM.
          _RFSMOK3       _3RFSMOK.
          _SMOKER3       _3SMOKER.
          _BMI4          _4BMI.
          _RFBING4       _4RFBING.
          _RFBMI4        _4RFBMI.
          _RFHYPE5       _5RFHYPE.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CAGEG_        _CAGEG_.
          _CHLDCNT       _CHLDCNT.
          _CHOLCHK       _CHOLCHK.
          _CIMPAGE       _CIMPAGE.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _CRACE         _CRACE.
          _CRACEG_       _CRACEG_.
          _CSEXG_        _CSEXG_.
          _DRDXART       _DRDXART.
          _EDUCAG        _EDUCAG.
          _FRTINDX       _FRTINDX.
          _FV5SRV        _FV5SRV.
          _HCVU65        _HCV65U.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _MRACE         _MRACE.
          _PA150RC       _PA150RC.
          _PA300RC       _PA300RC.
          _PRACE         _PRACE.
          _RACEG3_       _RACEG3_.
          _RACE_G        _RACE_G.
          _RFCHOL        _RFCHOL.
          _RFHLTH        _RFHLTH.
          _RFNOPA        _RFNOPA.
          _RFPAMOD       _RFPAMOD.
          _RFPAREC       _RFPAREC.
          _RFPAVIG       _RFPAVIG.
          _SEXG_         _SEXG_.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
