*****************************************************************************************
* FILE NAME:     SASOUT09.SAS                                                           *
* DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT  *
*                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF       *
* REFERENCES:                                                                           *
* INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES                   *
* FORMATS     FORMATS.SAS7BCAT      SAS FORMATS DATABASE                                *
* OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN       *
*                              <DATAIN> FILEREF                                         *
* UPDATED - 01/21/2010                                                                  *
*****************************************************************************************;
********************************
* Clear Output and Log Windows *
********************************;
DM OUTPUT 'clear' continue;
DM LOG    'clear' continue;
**********************************
* DEFINE SAS ENVIRONMENT OPTIONS *
**********************************;
OPTIONS PAGENO=1 NOFMTERR;
***************************************
* CLEAR EXISTING TITLES AND FOOTNOTES *
***************************************;
TITLE ;
FOOTNOTE ;
RUN ;
******************************************************************
* INSTRUCTIONS:                                                  *
* SPECIFY PATH OF WHERE ASCII DATAFILE IS STORED                 *
* SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED              *
* SPECIFY PATH OF WHERE SAS FORMAT LIBRARY IS STORED             *
* SPECIFY PATH OF WHERE THE FORMAT ASSIGNMET STATEMENT IS STORED *
******************************************************************;

*FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 1536 ;
*****************************************************************************
* EXAMPLE:                                                                  *
*       FILENAME DATAIN 'C:\BRFSS\2009\CDBRFS09.ASC' LRECL = 1536           *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

*LIBNAME DATAOUT V7 '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>'
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME DATAOUT 'C:\'                                            *
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.sas7bdat             *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*LIBNAME LIBRARY '<PATH OF STORED SAS FORMAT09.SAS7BCAT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME LIBRARY 'C:\'                                            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*FILENAME FORMATIN '<PATH OF FORMAT ASSIGNMENT STATEMENT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          FILENAME FORMATIN 'C:\FORMATSTATEMENT.SAS'                       *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT
_STATE        1-2                     /* Record Identification */
_GEOSTR       3-4
_DENSTR2      5
PRECALL       6
REPNUM        7-12
REPDEPTH      13-14
FMONTH        15-16
IDATE         $17-24
IMONTH        $17-18
IDAY          $19-20
IYEAR         $21-24
INTVID        $25-29
DISPCODE      30-32
SEQNO         33-42
_PSU          33-42
NATTMPTS      43-44
NRECSEL       45-50
NRECSTR       51-59
CTELENUM      60
CELLFON       61
PVTRESID      62
NUMADULT      63-64
NUMMEN        65-66
NUMWOMEN      67-68
GENHLTH       73                      /* Section 1: Health Status */
PHYSHLTH      74-75                   /* Section 2: Healthy Days - Health-Relate
d Quality of Life */
MENTHLTH      76-77
POORHLTH      78-79
HLTHPLAN      80                      /* Section 3: Health Care Access */
PERSDOC2      81
MEDCOST       82
CHECKUP1      83
QLREST2       84-85                   /* Section 4: Sleep */
EXERANY2      86                      /* Section 5: Exercise */
DIABETE2      87                      /* Section 6: Diabetes */
BPHIGH4       88                      /* Section 7: Hypertension Awareness */
BPMEDS        89
BLOODCHO      90                      /* Section 8: Cholesterol Awareness */
CHOLCHK       91
TOLDHI2       92
CVDINFR4      93                      /* Section 9: Cardiovascular Disease Prevalence */
CVDCRHD4      94
CVDSTRK3      95
ASTHMA2       96                      /* Section 10: Asthma */
ASTHNOW       97
SMOKE100      98                      /* Section 11: Tobacco Use */
SMOKDAY2      99
STOPSMK2      100
LASTSMK1      101-102
USENOW3       103
AGE           104-105                 /* Section 12: Demographics */
HISPANC2      106
MRACE         $107-112
ORACE2        113
VETERAN2      114
MARITAL       115
CHILDREN      116-117
EDUCA         118
EMPLOY        119
INCOME2       120-121
WEIGHT2       122-125
HEIGHT3       126-129
WTYRAGO       130-133
WTCHGINT      134
CTYCODE       135-137
NUMHHOL2      143
NUMPHON2      144
TELSERV2      145
SEX           146
PREGNANT      147
CAREGIVE      148                     /* Section 13: Caregiver Status */
QLACTLM2      149                     /* Section 14: Disability */
USEEQUIP      150
DRNKANY4      151                     /* Section 15: Alcohol Consumption */
ALCDAY4       152-154
AVEDRNK2      155-156
DRNK3GE5      157-158
MAXDRNKS      159-160
FLUSHOT3      161                     /* Section 16: Immunization */
FLUSHTMY      162-167
FLUSPRY2      168
FLUSPRMY      169-174
PNEUVAC3      175
PF09Q01       751
PF09Q02       752
PF09Q03       753
PF09Q04       754
PF09Q05       755
PF09Q06       756-757
PF09Q07       758-759
PF09Q08       760-761
PF09Q09       762
PF09Q10       763
HAVARTH2      176                     /* Section 17: Arthritis Burden */
LMTJOIN2      177
ARTHDIS2      178
ARTHSOCL      179
JOINPAIN      180-181
FRUITJUI      182-184                 /* Section 18: Fruits & Vegetables */
FRUIT         185-187
GREENSAL      188-190
POTATOES      191-193
CARROTS       194-196
VEGETABL      197-199
JOBACTIV      200                     /* Section 19: Physical Activity */
MODPACT       201
MODPADAY      202-203
MODPATIM      204-206
VIGPACT       207
VIGPADAY      208-209
VIGPATIM      210-212
HIVTST5       213                     /* Section 20: HIV/AIDS */
HIVTSTD2      214-219
WHRTST8       220-221
HIVRDTST      222
HIVRISK2      223
EMTSUPRT      224                     /* Section 21: Emotional Support and Life Satisfaction */
LSATISFY      225
CNCRHAVE      226                     /* Section 22: Cancer Survivors */
CNCRDIFF      227
CNCRAGE       228-229
CNCRTYPE      230-231
CPDEMO1       232                     /* Section 23: Cell Phone */
CPDEMO2       233
CPDEMO3       234
CPDEMO4       235-237
PDIABTST      245                     /* Module 1: Pre-Diabetes */
PREDIAB1      246
DIABAGE2      247-248                 /* Module 2: Diabetes */
INSULIN       249
BLDSUGAR      250-252
FEETCHK2      253-255
DOCTDIAB      256-257
CHKHEMO3      258-259
FEETCHK       260-261
EYEEXAM       262
DIABEYE       263
DIABEDU       264
PAINACT2      265-266                 /* Module 3: Healthy Days (Symptoms) */
QLMENTL2      267-268
QLSTRES2      269-270
QLHLTH2       271-272
VIDFCLT2      273                     /* Module 4: Visual Impairment and Access to Eye Care */
VIREDIF2      274
VIPRFVS2      275
VINOCRE2      276-277
VIEYEXM2      278
VIINSUR2      279
VICTRCT2      280
VIGLUMA2      281
VIMACDG2      282
SLEPTIME      283-284                 /* Module 5: Inadequate Sleep */
SLEPSNOR      285
SLEPDAY       288-289
SLEPDRIV      290
HAREHAB1      291                     /* Module 6: Cardiovascular Health */
STREHAB1      292
CVDASPRN      293
ASPUNSAF      294
BPEATHBT      295                     /* Module 7: Actions to Control High Blood  Pressure */
BPSALT        296
BPALCHOL      297
BPEXER        298
BPEATADV      299
BPSLTADV      300
BPALCADV      301
BPEXRADV      302
BPMEDADV      303
BPHI2MR       304
HASYMP1       305                     /* Module 8: Heart Attack and Stroke */
HASYMP2       306
HASYMP3       307
HASYMP4       308
HASYMP5       309
HASYMP6       310
STRSYMP1      311
STRSYMP2      312
STRSYMP3      313
STRSYMP4      314
STRSYMP5      315
STRSYMP6      316
FIRSTAID      317
HADMAM        318                     /* Module 9: Women´s Health */
HOWLONG       319
PROFEXAM      320
LENGEXAM      321
HADPAP2       322
LASTPAP2      323
HADHYST2      324
PSATEST       325                     /* Module 10: Prostate Cancer Screening */
PSATIME       326
DIGRECEX      327
DRETIME       328
PROSTATE      329
BLDSTOOL      330                     /* Module 11: Colorectal Cancer Screening */
LSTBLDS3      331
HADSIGM3      332
HADSGCO1      333
LASTSIG3      334
CSRVTRT       335                     /* Module 12: Cancer Survivorship */
CSRVDOC       336-337
CSRVSUM       338
CSRVRTRN      339
CSRVINST      340
CSRVINSR      341
CSRVDEIN      342
CSRVCLIN      343
CSRVPAIN      344
CSRVCTRL      345
ASTHMAGE      346-347                 /* Module 13: Adult Asthma History */
ASATTACK      348
ASERVIST      349-350
ASDRVIST      351-352
ASRCHKUP      353-354
ASACTLIM      355-357
ASYMPTOM      358
ASNOSLEP      359
ASTHMED3      360
ASINHALR      361
ARTTODAY      362                     /* Module 14: Arthritis Management */
ARTHWGT       363
ARTHEXER      364
ARTHEDU       365
TNSARCV       366                     /* Module 15: Tetanus Diptheria (Adults) */
TNSARCNT      367
TNSASHOT      368
HPVADVC       369                     /* Module 16: Adult Human Papilloma Virus (HPV) */
HPVADSHT      370-371
SHINGLES      372                     /* Module 17: Shingles */
CRGVAGE       373-375                 /* Module 18: Caregiver */
CRGVGNDR      376
CRGVRELT      377-378
CRGVLONG      379-381
CRGVPROB      382-383
CRGVMOST      384-385
CRGVHRS       386-388
CRGVDIFF      389-390
CRGVCHNG      391
GPWELPR3      392                     /* Module 19: General Preparedness */
GP3DYWTR      393
GP3DYFD1      394
GP3DYPRS      395
GPBATRAD      396
GPFLSLIT      397
GPEMRCM1      398
GPEMRIN1      399
GPVACPL1      400
GPMNDEVC      401
GPNOTEV1      402-403
RRCLASS2      404                     /* Module 20: Reactions to Race */
RRCOGNT2      405
RRATWRK2      406
RRHCARE3      407
RRPHYSM2      408
RREMTSM2      409
MISNERVS      410                     /* Module 21: Mental Illness & Stigma */
MISHOPLS      411
MISRSTLS      412
MISDEPRD      413
MISEFFRT      414
MISWTLES      415
MISNOWRK      416-417
MISTMNT       418
MISTRHLP      419
MISPHLPF      420
IAQCODT1      421                     /* Module 22: Carbon Monoxide Detectors and Gas Powered Generators */
CMDGPPWR      422
CMDGPBAT      423
CMDGPGEN      424
CMDGPDSL      425
CMDGPLOC      426
CMDGPRUN      427
CMDGPOWN      428
RENTHOM1      429                     /* Module 23: Social Context */
SCNTMONY      430
SCNTMEAL      431
SCNTPAID      432
SCNTWORK      433-434
SCNTLPAD      435
SCNTLWRK      436-437
SCNTVOTE      438
ACEDEPRS      439                     /* Module 24: Adverse Childhood Experience */
ACEDRINK      440
ACEDRUGS      441
ACEPRISN      442
ACEDIVRC      443
ACEPUNCH      444
ACEHURT       445
ACESWEAR      446
ACETOUCH      447
ACETTHEM      448
ACEHVSEX      449
RCSBIRTH      $465-470                /* Module 25: Random Child Selection */
RCSGENDR      471
RCHISLAT      472
RCSRACE       $473-478
RCSBRACE      479
RCSRLTN2      480
CASTHDX2      481                     /* Module 26: Childhood Asthma Prevalence */
CASTHNO2      482
FLUSHCH1      483                     /* Module 27: Childhood Immunization */
RCVFVCH3      484-489
HPVCHVC       490                     /* Module 28: Child Human Papilloma Virus (HPV) */
HPVCHSHT      491-492
TNSCRCV       493                     /* Module 29: Tetanus Diptheria (Adolescents) */
TNSCRCNT      494
TNSCSHOT      495
QSTVER        860                     /* Questionnaire Version */
_STSTR        948-952                 /* Weighting And Stratification Variables */
_STRWT        953-962
_RAW          963-972
_WT2          973-982
_POSTSTR      983-992
_FINALWT      993-1002
_REGION       1123-1124
_AGEG_        1125-1126
_SEXG_        1127
_RACEG3_      1128
_IMPAGE       1129-1130
_IMPNPH       1131
_ITSCF1       1132-1141
_ITSCF2       1142-1151
_ITSPOST      1152-1161
_ITSFINL      1162-1171
MSCODE        1180
CRACEORG      $1181-1186              /* Child Demographic Variables */
CRACEASC      1187-1192
_CRACE        1193-1194
CHILDAGE      1195-1197
_CIMPAGE      1198-1199               /* Child Demographic Variables */
_CSEXG_       1200
_CRACEG_      1201
_CAGEG_       1202-1204
_RAWCH        1325-1334
_WT2CH        1335-1344
_POSTCH       1345-1354
_CHILDWT      1355-1364
_RAWHH        1365-1374               /* Household Weighting Variables */
_WT2HH        1375-1384
_POSTHH       1385-1394
_HOUSEWT      1395-1404
_RFHLTH       1405                    /* Section 1: Calculated Variables */
_HCVU65       1406                    /* Section 3: Calculated Variables */
_TOTINDA      1407                    /* Section 5: Calculated Variables */
_RFHYPE5      1408                    /* Section 7: Calculated Variables */
_CHOLCHK      1409                    /* Section 8: Calculated Variables */
_RFCHOL       1410
_LTASTHM      1411                    /* Section 10: Calculated Variables */
_CASTHMA      1412
_ASTHMST      1413
_SMOKER3      1414                    /* Section 11: Calculated Variables */
_RFSMOK3      1415
MRACEORG      $1416-1421              /* Section 12: Calculated Race Variables */
MRACEASC      $1422-1427
_PRACE        1428-1429
_MRACE        1430-1431
RACE2         1432
_RACEG2       1433
_RACEGR2      1434
_RACE_G       1435
_CNRACE       1436
_CNRACEC      1437
_AGEG5YR      1438-1439
_AGE65YR      1440
_AGE_G        1441
HTIN3         1442-1444
HTM3          1445-1447
WTKG2         1448-1452
_BMI4         1453-1456
_BMI4CAT      1457
_RFBMI4       1458
_CHLDCNT      1459
_EDUCAG       1460
_INCOMG       1461
DROCDY2_      1462-1464               /* Section 15: Calculated Variables */
_RFBING4      1465
_DRNKDY3      1466-1469
_DRNKMO3      1470-1473
_RFDRHV3      1474
_RFDRMN3      1475
_RFDRWM3      1476
_FLSHOT3      1477                    /* Section 16: Calculated Variables */
_PNEUMO2      1478
_DRDXART      1479                    /* Section 17: Calculated Variables */
FTJUDAY_      1480-1482               /* Section 18: Calculated Variables */
FRUTDAY_      1483-1485
GNSLDAY_      1486-1488
POTADAY_      1489-1491
CRTSDAY_      1492-1494
VEGEDAY_      1495-1497
_FRTSERV      1498-1502
_FRTINDX      1503
_FV5SRV       1504
_MODPAMN      1505-1507               /* Section 19: Calculated Variables */
_VIGPAMN      1508-1510
MODCAT_       1511
VIGCAT_       1512
PACAT_        1513
_RFPAMOD      1514
_RFPAVIG      1515
_RFPAREC      1516
_RFNOPA       1517
_MODMNWK      1518-1522
_VIGMNWK      1523-1527
_TOTMNWK      1528-1532
_PA150RC      1533
_PA300RC      1534
_AIDTST2      1535                    /* Section 20: Calculated Variables */
;
*****************************************************************
* TO INCLUDE THE FORMAT ASSIGNEMT STATEMENT REMOVE THE ASTERISK *
* FROM THE BEGINNING OF THE FOLLOWING LINE                      *
*****************************************************************;
* %INCLUDE FORMATIN ;
*************************************************
* THIS SECTION CREATES LABELS FOR THE VARIABLES *
*************************************************;
Label
ACEDEPRS = 'LIVE WITH ANYONE DEPRESSED, MENTALLY ILL, OR SUICIDAL?'
ACEDIVRC = 'WERE YOUR PARENTS DIVORCED/SEPERATED?'
ACEDRINK = 'LIVE WITH A PROBLEM DRINKER/ALCOHOLIC?'
ACEDRUGS = 'LIVE WITH ANYONE WHO USED ILLEGAL DRUGS OR ABUSED PRESCRIPTIONS?'
ACEHURT = 'HOW OFTEN DID A PARENT PHYSICALLY HURT YOU IN ANY WAY?'
ACEHVSEX = 'HOW OFTEN DID ANYONE EVER FORCE YOU TO HAVE SEX?'
ACEPRISN = 'LIVE WITH ANYONE WHO SERVED TIME IN PRISON OR JAIL?'
ACEPUNCH = 'HOW OFTEN DID YOUR PARENTS BEAT EACH OTHER UP?'
ACESWEAR = 'HOW OFTEN DID A PARENT SWEAR AT YOU?'
ACETOUCH = 'HOW OFTEN DID ANYONE EVER TOUCH YOU SEXUALLY?'
ACETTHEM = 'HOW OFTEN DID ANYONE MAKE YOU TOUCH THEM SEXUALLY?'
AGE = 'REPORTED AGE IN YEARS'
ALCDAY4 = 'DAYS IN PAST 30 HAD ALCOHOLIC BEVERAGE'
ARTHDIS2 = 'DOES ARTHRITIS AFFECT WHETHER YOU WORK'
ARTHEDU = 'EVER TAKEN CLASS IN MANAGING ARTHRITIS OR JOINT SYMPTOMS'
ARTHEXER = 'DR. SUGGEST USE OF PHYSICAL ACTIVITY OR EXERCISE FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTHSOCL = 'SOCIAL ACTIVITIES LIMITED BECAUSE OF JOINT SYMPTOMS'
ARTHWGT = 'DR. SUGGEST LOSE WEIGHT FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTTODAY = 'WHAT CAN YOU DO BECAUSE OF ARTHRITIS OR JOINT SYMPTOMS'
ASACTLIM = 'ACTIVITIES LIMITED DUE TO ASTHMA DURING PAST 12 MONTHS'
ASATTACK = 'ASTHMA DURING PAST 12 MONTHS'
ASDRVIST = 'URGENT ASTHMA TREATMENT DURING PAST 12 MONTHS'
ASERVIST = 'EMERGENCY ASTHMA CARE DURING PAST 12 MONTHS'
ASINHALR = 'TIMES USED ASTHMA INHALER DURING AN ATTACK IN PAST 30 DAYS'
ASNOSLEP = 'SLEEP DIFFICULTY DUE TO ASTHMA DURING PAST 30 DAYS'
ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
ASRCHKUP = 'ROUTINE ASTHMA CARE DURING PAST 12 MONTHS'
ASTHMA2 = 'EVER TOLD HAD ASTHMA'
ASTHMAGE = 'AGE AT ASTHMA DIAGNOSIS'
ASTHMED3 = 'DAYS USED PRESCRIBED PREVENTATIVE ASTHMA MED IN PAST 30 DAYS'
ASTHNOW = 'STILL HAVE ASTHMA'
ASYMPTOM = 'ASTHMA SYMPTOMS DURING PAST 30 DAYS'
AVEDRNK2 = 'AVG ALCOHOLIC DRINKS PER DAY IN PAST 30'
BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
BPALCADV = 'HLTH CARE PRO EVER ADVISED REDUCED ALCOHOL USE TO REDUCE BP'
BPALCHOL = 'REDUCE ALCOHOL USE FOR BP?'
BPEATADV = 'HLTH CARE PRO EVER ADVISED CHANGE IN EATING HABITS TO REDUCE BP'
BPEATHBT = 'CHANGE EATING HABITS FOR BP?'
BPEXER = 'EXERCISING TO LOWER BP?'
BPEXRADV = 'HLTH CARE PRO EVER ADVISED EXERCISE TO REDUCE BP'
BPHI2MR = 'TOLD HAD HIGH BP DURING 2+ VISITS TO HLTH CARE PRO?'
BPHIGH4 = 'EVER TOLD BLOOD PRESSURE HIGH'
BPMEDADV = 'HLTH CARE PRO EVER ADVISED MEDS TO REDUCE BP'
BPMEDS = 'CURRENTLY TAKING BLOOD PRESSURE MEDICATION'
BPSALT = 'REDUCE SALT INTAKE TO LOWER BP?'
BPSLTADV = 'HLTH CARE PRO EVER ADVISED USING LESS SALT TO REDUCE BP'
CALLBACK = 'ASTHMA FOLLOW-UP CALL BACK REQUEST'
CAREGIVE = 'PROVIDED REGULAR CARE FOR FAMILY OR FRIEND'
CARROTS = 'HOW OFTEN DO YOU EAT CARROTS'
CASTHDX2 = 'HLTH PRO EVER SAID CHILD HAS ASTHMA'
CASTHNO2 = 'CHILD STILL HAVE ASTHMA?'
CELLFON = 'CELLULAR TELEPHONE'
CHECKUP1 = 'LENGTH OF TIME SINCE LAST ROUTINE CHECKUP'
CHILDAGE = 'CHILD AGE'
CHILDREN = 'NUMBER OF CHILDREN IN HOUSEHOLD'
CHKHEMO3 = 'TIMES CHECKED FOR GLYCOSYLATED HEMOGLOBIN'
CHOLCHK = 'HOW LONG SINCE CHOLESTEROL CHECKED'
CMDGPBAT = 'LAST TIME BATTERIES IN CARBON MONOXIDE DETECTOR WERE CHANGED'
CMDGPDSL = 'HAS ANYONE IN HOUSEHOLD EVER USED DIESEL-POWERED GENERATOR TO PROVIDE ELECTRIC POWER?'
CMDGPGEN = 'HAS ANYONE IN HOUSEHOLD EVER USED GAS-POWERED GENERATOR TO PROVIDE ELECTRIC POWER?'
CMDGPLOC = 'WHERE IS GENERATOR WHEN IT IS RUNNING?'
CMDGPOWN = 'OWN, RENT, OR BORROW THE GENERATOR?'
CMDGPPWR = 'DOES YOUR CARBON MONOXIDE DETECTOR USE A BATTERY?'
CMDGPRUN = 'MOST IMPACT ON WHERE GENERATOR IS WHILE RUNNING?'
CNCRAGE = 'AGE TOLD HAD CANCER'
CNCRDIFF = 'HOW MANY TYPES OF CANCER?'
CNCRHAVE = 'EVER TOLD YOU HAD CANCER?'
CNCRTYPE = 'TYPE OF CANCER'
CPCOUNTY = 'CELL PHONE PILOT COUNTY NAME'
CPDEMO1 = 'DO YOU HAVE A CELL PHONE FOR PERSONAL USE?'
CPDEMO2 = 'DO YOU SHARE A CELL PHONE FOR PERSONAL USE?'
CPDEMO3 = 'DO YOU USUALLY SHARE THIS CELL PHONE?'
CPDEMO4 = 'WHAT PERCENT OF ALL CALLS ARE RECEIVED ON YOUR CELL PHONE?'
CRACEASC = 'CRACEORG WITH RESPONSES IN ASCENDING ORDER'
CRACEORG = 'CRACE WITH TRAILING 7, 8, 9S REMOVED'
CRGVAGE = 'AGE OF PERSON TO WHOM YOU ARE GIVING CARE?'
CRGVCHNG = 'IN THE PAST YEAR, HAS THE PERSON EXPERIENCED CHANGES IN THINKING/REMEMBERING?'
CRGVDIFF = 'GREATEST DIFFICULTY YOU HAVE FACED AS A CAREGIVER'
CRGVGNDR = 'GENDER OF PERSON TO WHOM YOU ARE GIVING CARE?'
CRGVHRS = 'HOW MANY HOURS DO YOU PROVIDE CARE FOR PERSON?'
CRGVLONG = 'HOW LONG PROVIDED CARE FOR PERSON.'
CRGVMOST = 'WHAT AREAS DOES PERSON MOST NEED YOUR HELP?'
CRGVPROB = 'WHAT IS THE MAJOR HEALTH PROBLEM, ILLNESS, DISABILITY FOR CARE FOR PERSON?'
CRGVRELT = 'RELATIONSHIP OF PERSON TO WHOM YOU ARE GIVING CARE?'
CRTSDAY_ = 'COMPUTED CARROT SERVINGS PER DAY'
CSRVCLIN = 'PARTICIPATE IN CLINICAL TRIAL AS PART OF CANCER TREATMENT?'
CSRVCTRL = 'IS PAIN UNDER CONTROL?'
CSRVDEIN = 'EVER DENIED INSURANCE COVERAGE BECAUSE OF YOUR CANCER?'
CSRVDOC = 'WHAT TYPE OF DOCTOR PROVIDES MAJORITY OF YOUR CARE'
CSRVINSR = 'DID HEALTH INSURANCE PAY FOR ALL OF YOUR CANCER TREATMENT'
CSRVINST = 'INSTRUCTIONS WRITTEN OR PRINTED'
CSRVPAIN = 'CURRENTLY HAVE PHYSICAL PAIN FROM CANCER OR TREATMENT?'
CSRVRTRN = 'EVER RECEIVE INSTRUCTIONS FROM A DOCTOR FOR FOLLOW-UP CHECK-UPS'
CSRVSUM = 'DID YOU RECEIVE A SUMMARY OF CANCER TREATMENTS RECEIVED'
CSRVTRT = 'CURRENTLY RECEIVING TREATMENT FOR CANCER'
CTELENUM = 'CORRECT TELEPHONE NUMBER?'
CTYCODE = 'COUNTY CODE'
CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
CVDCRHD4 = 'EVER DIAGNOSED WITH ANGINA OR CORONARY HEART DISEASE'
CVDINFR4 = 'EVER DIAGNOSED WITH HEART ATTACK'
CVDSTRK3 = 'EVER DIAGNOSED WITH A STROKE'
DIABAGE2 = 'AGE WHEN TOLD DIABETIC'
DIABEDU = 'EVER TAKEN CLASS IN MANAGING DIABETES'
DIABETE2 = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
DIABEYE = 'EVER TOLD DIABETES HAS AFFECTED EYES'
DIGRECEX = 'EVER HAD DIGITAL RECTAL EXAM'
DIRCONT1 = 'DO YOU PROVIDE DIRECT PATIENT CARE AS PART OF YOUR ROUTINE WORK?'
DISPCODE = 'FINAL DISPOSITION'
DOCTDIAB = 'TIMES SEEN HEALTH PROFESSIONAL FOR DIABETES'
DRETIME = 'TIME SINCE LAST DIGITAL RECTAL EXAM'
DRHPAD1 = 'HAS A DOCTOR, NURSE, OR OTHER HEALTH PROFESSIONAL EVER SAID THAT YOU HAVE…PROBLEM CAUSED BY A CHRONIC ILLNESS OR BY MEDICINES; TAKEN FOR A CHRONIC ILLNESS?'
DRNK3GE5 = 'BINGE DRINKING'
DRNKANY4 = 'DRINK ANY ALCOHOLIC BEVERAGES IN PAST 30 DAYS'
DROCDY2_ = 'COMPUTED DRINK-OCCASIONS-PER-DAY'
EDUCA = 'EDUCATION LEVEL'
EMPLOY = 'EMPLOYMENT STATUS'
EMTSUPRT = 'HOW OFTEN GET EMOTIONAL SUPPORT NEEDED'
EXERANY2 = 'EXERCISE IN PAST 30 DAYS'
EYEEXAM = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
FEETCHK = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
FEETCHK2 = 'HOW OFTEN CHECK FEET FOR SORES OR IRRITATIONS'
FIRSTAID = 'FIRST AID FOR HEART ATTACK AND STROKE'
FLUSHCH1 = 'HAD FLU SHOT PAST 12 MOS'
FLUSHOT3 = 'FLU SHOT PAST 12 MOS'
FLUSHTMY = 'WHEN RECEIVED MOST RECENT FLU SHOT'
FLUSPRMY = 'WHEN RECEIVED MOST RECENT FLU SPRAY IN NOSE'
FLUSPRY2 = 'FLU SPRAY PAST 12 MOS'
FMONTH = 'FILE MONTH'
FRUIT = 'HOW OFTEN DO YOU EAT FRUIT'
FRUITJUI = 'HOW OFTEN DO YOU DRINK FRUIT JUICES'
FRUTDAY_ = 'COMPUTED FRUIT SERVINGS PER DAY'
FTJUDAY_ = 'COMPUTED FRUIT JUICE SERVINGS PER DAY'
GENHLTH = 'GENERAL HEALTH'
GNSLDAY_ = 'COMPUTED GREEN SALAD SERVINGS PER DAY'
GP3DYFD1 = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF NON-PERISHABLE FOOD FOR EVERYONE WHO LIVES THERE?'
GP3DYPRS = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF PRESCRIPTION MEDICATION FOR EACH PERSON WHO TAKES PRESCRIBED MEDICINES?'
GP3DYWTR = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF WATER FOR EVERYONE WHO LIVES THERE?'
GPBATRAD = 'DOES YOUR HOUSEHOLD HAVE A WORKING BATTERY OPERATED RADIO AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICITY IS OUT?'
GPEMRCM1 = 'IN A LARGE-SCALE DISASTER OR EMERGENCY, WHAT WOULD BE YOUR MAIN METHOD OF COMMUNICATING WITH RELATIVES AND FRIENDS?'
GPEMRIN1 = 'WHAT WOULD BE YOUR MAIN METHOD OF GETTING INFORMATION FROM AUTHORITIES IN A LARGE-SCALE DISASTER OR EMERGENCY?'
GPFLSLIT = 'DOES YOUR HOUSEHOLD HAVE A WORKING FLASHLIGHT AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICITY IS OUT?'
GPMNDEVC = 'IF PUBLIC AUTHORITIES ANNOUNCED MANDATORY EVACUATION FROM YOUR COMMUNITY DUE TO A LARGE-SCALE DISASTER OR EMERGENCY, WOULD YOU EVACUATE?'
GPNOTEV1 = 'WHAT WOULD BE THE MAIN REASON WHY YOU MIGHT NOT EVACUATE IF ASKED TO DO SO?'
GPVACPL1 = 'DOES YOUR HOUSEHOLD HAVE A DISASTER EVACUATION PLAN?'
GPWELPR3 = 'HOUSEHOLD PREPARED TO HANDLE LARGE-SCALE DISASTER OR EMERGENCY'
GREENSAL = 'HOW OFTEN DO YOU EAT GREEN SALAD'
HADHYST2 = 'HAD HYSTERECTOMY'
HADMAM = 'HAVE YOU EVER HAD A MAMMOGRAM'
HADPAP2 = 'EVER HAD A PAP TEST'
HADSGCO1 = 'WAS LAST TEST A SIGMOIDOSCOPY OR COLONOSCOPY'
HADSIGM3 = 'EVER HAD SIGMOIDOSCOPY/COLONOSCOPY'
HAREHAB1 = 'OUTPATIENT REHAB AFTER HEART ATTACK HOSP STAY'
HASYMP1 = 'HEART ATTACK SYMPTOMS - JAW/BACK/NECK PAIN'
HASYMP2 = 'HEART ATTACK SYMPTOMS - WEAK/LIGHT-HEADED/FAINT'
HASYMP3 = 'HEART ATTACK SYMPTOMS - CHEST PAIN/DISCOMFORT'
HASYMP4 = 'HEART ATTACK SYMPTOMS - VISION PROBLEMS'
HASYMP5 = 'HEART ATTACK SYMPTOMS - PAIN OR DISCOMFORT IN ARMS/SHOULDER'
HASYMP6 = 'HEART ATTACK SYMPTOMS - SHORTNESS OF BREATH'
HAVARTH2 = 'TOLD HAVE ARTHRITIS'
HAVHPAD = 'STILL HAVE THIS HEALTH PROBLEM'
HEIGHT3 = 'REPORTED HEIGHT IN FEET AND INCHES'
HISPANC2 = 'HISPANIC/LATINO'
HIVRDTST = 'WAS YOUR LAST HIV TEST A RAPID TEST?'
HIVRISK2 = 'DO ANY HIGH RISK SITUATIONS APPLY'
HIVTST5 = 'EVER TESTED HIV'
HIVTSTD2 = 'MONTH AND YEAR OF LAST HIV TEST'
HLTHPLAN = 'HAVE ANY HEALTH CARE COVERAGE'
HOWLONG = 'HOW LONG SINCE LAST MAMMOGRAM'
HPVADSHT = 'NUMBER OF HPV SHOTS RECEIVED'
HPVADVC = 'EVER HAD THE HPV VACCINATION?'
HPVCHSHT = 'HOW MANY HPV SHOTS DID CHILD RECEIVE?'
HPVCHVC = 'CHILD  EVER HAD THE HPV VACCINATION?'
HTIN3 = 'COMPUTED HEIGHT IN INCHES'
HTM3 = 'COMPUTED HEIGHT IN METERS'
IAQCODT1 = 'DO YOU HAVE A CO DETECTOR IN YOUR HOME?'
IDATE = 'INTERVIEW DATE'
IDAY = 'INTERVIEW DAY'
IMONTH = 'INTERVIEW MONTH'
INCOME2 = 'INCOME LEVEL'
INSULIN = 'NOW TAKING INSULIN'
INTVID = 'INTERVIEWER IDENTIFICATION'
IYEAR = 'INTERVIEW YEAR'
JOBACTIV = 'PHYSICAL ACTIVITY AT WORK'
JOINPAIN = 'HOW BAD WAS JOINT PAIN'
LASTPAP2 = 'HOW LONG SINCE LAST PAP TEST'
LASTSIG3 = 'TIME SINCE LAST SIGMOIDOSCOPY/COLONOSCOPY'
LASTSMK1 = 'INTERVAL SINCE LAST SMOKED'
LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
LMTJOIN2 = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
LSATISFY = 'SATISFACTION WITH LIFE'
LSTBLDS3 = 'TIME SINCE LAST BLOOD STOOL TEST'
MARITAL = 'MARITAL STATUS'
MAXDRNKS = 'MOST DRINKS ON SINGLE OCCASION PAST 30 DAYS'
MEDCOST = 'COULD NOT SEE DR. BECAUSE OF COST'
MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
MISDEPRD = 'HOW OFTEN FEEL DEPRESSED PAST 30 DAYS'
MISEFFRT = 'HOW OFTEN FEEL EVERYTHING WAS AN EFFORT PAST 30 DAYS'
MISHOPLS = 'HOW OFTEN FEEL HOPELESS PAST 30 DAYS'
MISNERVS = 'HOW OFTEN FEEL NERVOUS PAST 30 DAYS'
MISNOWRK = 'EMOTIONAL PROBLEM KEPT YOU FROM DOING WORK PAST 30 DAYS'
MISPHLPF = 'PEOPLE ARE GENERALLY CARING TOWARD PEOPLE WITH MENTAL ILLNESS'
MISRSTLS = 'HOW OFTEN FEEL RESTLESS PAST 30 DAYS'
MISTMNT = 'RECEIVING MEDICINE OR TREATMENT FROM HEALTH PRO FOR EMOTIONAL PROBLEM'
MISTRHLP = 'MENTAL HEALTH TREATMENT CAN HELP PEOPLE LEAD NORMAL LIFE'
MISWTLES = 'HOW OFTEN FEEL WORTHLESS PAST 30 DAYS'
MODCAT_ = 'COMPUTED MODERATE PHYSICAL ACTIVITY CATEGORIES'
MODPACT = 'MODERATE PHYSICAL ACTIVITY'
MODPADAY = 'MODERATE PHYSICAL ACTIVITY DAYS'
MODPATIM = 'MODERATE PHYSICAL ACTIVITY TIME'
MRACE = 'MULTIPLE RACE'
MRACEASC = 'MRACEORG WITH RESPONSES IN ASCENDING ORDER CALCULATED VARIABLE'
MRACEORG = 'MRACE WITH TRAILING 7,8,9S REMOVED CALCULATED VARIABLE'
MSCODE = 'METROPOLITAN STATUS CODE'
NATTMPTS = 'NUMBER OF ATTEMPTS'
NRECSEL = 'NUMBER OF SAMPLE RECORDS SELECTED FROM STRATUM'
NRECSTR = 'NUMBER OF TELEPHONE NUMBERS IN STRATUM FROM WHICH SAMPLE WAS SELECTED'
NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
NUMHHOL2 = 'HOUSEHOLD TELEPHONES'
NUMMEN = 'NUMBER OF ADULT MEN IN HOUSEHOLD'
NUMPHON2 = 'RESIDENTIAL PHONES'
NUMWOMEN = 'NUMBER OF ADULT WOMEN IN HOUSEHOLD'
ORACE2 = 'RESPONDENT RACE CHOICE'
PACAT_ = 'COMPUTED OVERALL PHYSICAL ACTIVITY CATEGORIES'
PAINACT2 = 'HOW MANY DAYS HARD TO DO USUAL ACTIVITIES IN PAST 30 DAYS'
PDIABTST = 'HAD A TEST FOR HIGH BLOOD SUGAR IN PAST THREE YEARS'
PERSDOC2 = 'MULTIPLE HEALTH CARE PROFESSIONALS'
PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
PNEUVAC3 = 'PNEUMONIA SHOT EVER'
POORHLTH = 'POOR PHYSICAL HEALTH'
POTADAY_ = 'COMPUTED POTATO SERVINGS PER DAY'
POTATOES = 'HOW OFTEN DO YOU EAT POTATOES'
PRECALL = 'PRE-CALL STATUS CODE'
PREDIAB1 = 'EVER BEEN TOLD YOU HAVE PRE-DIABETES OR BORDERLINE DIABETES'
PREGNANT = 'PREGNANCY STATUS'
PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
PROSTATE = 'EVER TOLD YOU HAD PROSTATE CANCER'
PSATEST = 'EVER HAD PSA TEST'
PSATIME = 'TIME SINCE LAST PSA TEST'
PVTRESID = 'PRIVATE RESIDENCE?'
QLACTLM2 = 'ACTIVITY LIMITATION DUE TO HEALTH PROBLEMS'
QLHLTH2 = 'HOW MANY DAYS FULL OF ENERGY IN PAST 30 DAYS'
QLMENTL2 = 'HOW MANY DAYS DEPRESSED IN PAST 30 DAYS'
QLREST2 = 'HOW MANY DAYS DID YOU GET ENOUGH SLEEP IN PAST 30 DAYS'
QLSTRES2 = 'HOW MANY DAYS FELT ANXIOUS IN PAST 30 DAYS'
QSTLANG = 'LANGUAGE IDENTIFIER'
QSTVER = 'QUESTIONNAIRE VERSION IDENTIFIER'
RACE2 = 'COMPUTED RACE-ETHNICITY GROUPING'
RCHISLAT = 'ETHNICITY OF CHILD'
RCSBIRTH = 'BIRTH DATE OF CHILD'
RCSBRACE = 'RACE OF CHILD'
RCSGENDR = 'GENDER OF CHILD'
RCSRACE = 'RACE OF CHILD (MULTIPLE POSSIBLE)'
RCSRLTN2 = 'RELATIONSHIP TO CHILD'
RCVFVCH3 = 'DATE CHILD RCVD MOST RECENT FLU VACCINE(MMYYYY)'
RENTHOM1 = 'OWN OR RENT HOME'
REPDEPTH = 'REPLICATE DEPTH'
REPNUM = 'REPLICATE NUMBER'
RRATWRK2 = 'HOW DO YOU FEEL YOU WERE TREATED AT WORK COMPARED TO PEOPLE OF OTHER RACES IN PAST 12 MONTHS?'
RRCLASS2 = 'HOW DO OTHER PEOPLE USUALLY CLASSIFY YOU IN THIS COUNTRY?'
RRCOGNT2 = 'HOW OFTEN DO YOU THINK ABOUT YOUR RACE?'
RREMTSM2 = 'TIMES PAST 30 DAYS FELT EMOTIONALLY UPSET BECAUSE OF TREATMENT DUE TO YOUR RACE'
RRHCARE3 = 'WHEN SEEKING HEALTH CARE PAST 12 MONTHS, WAS EXPERIENCE WORSE, SAME, BETTER THAN PEOPLE OF OTHER RACES?'
RRPHYSM2 = 'TIMES PAST 30 DAYS FELT PHYSICAL SYMPTOMS BECAUSE OF TREATMENT DUE TO YOUR RACE'
SCNTLPAD = 'HOW WERE YOU GENERALLY PAID FOR THE WORK YOU DID'
SCNTLWRK = 'HOW MANY HOURS PER WEEK DID YOU WORK'
SCNTMEAL = 'TIMES PAST 12 MONTHS WORRIED/STRESSED ABOUT HAVING ENOUGH MONEY TO BUY NUTRITIOUS MEALS?'
SCNTMONY = 'TIMES PAST 12 MONTHS WORRIED/STRESSED ABOUT HAVING ENOUGH MONEY TO PAY YOUR RENT/MORTGAGE?'
SCNTPAID = 'HOW ARE YOU GENERALLY PAID FOR THE WORK YOU DO'
SCNTVOTE = 'DID YOU VOTE IN THE LAST PRESIDENTIAL ELECTION?'
SCNTWORK = 'HOW MANY HOURS PER WEEK DO YOU WORK'
SEQNO = 'ANNUAL SEQUENCE NUMBER'
SEX = 'RESPONDENTS SEX'
SHINGLES = 'HAVE YOU HAD SHINGLES VACCINE?'
SLEPDAY = 'NUMBER OF DAYS IN PAST THIRTY FELL ASLEEP DURING THE DAY'
SLEPDRIV = 'NUMBER OF DAYS IN PAST THIRTY FELL ASLEEP WHILE DRIVING'
SLEPSNOR = 'DO YOU SNORE?'
SLEPTIME = 'HOW MUCH TIME DO YOU SLEEP'
SMOKDAY2 = 'FREQUENCY OF DAYS NOW SMOKING'
SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
STOPSMK2 = 'STOPPED SMOKING IN PAST 12 MONTHS'
STREHAB1 = 'OUTPATIENT REHAB AFTER HOSP STAY FOR STROKE'
STRSYMP1 = 'STROKE SYMPTOMS - CONFUSION/TROUBLE SPEAKING'
STRSYMP2 = 'STROKE SYMPTOMS - NUMBNESS OR WEAKNESS OF FACE/ARM/LEG'
STRSYMP3 = 'STROKE SYMPTOMS - VISION PROBLEMS'
STRSYMP4 = 'STROKE SYMPTOMS - CHEST PAIN/DISCOMFORT'
STRSYMP5 = 'STROKE SYMPTOMS - TROUBLE WALKING/DIZZINESS/LOSS OF BALANCE'
STRSYMP6 = 'STROKE SYMPTOMS - SEVERE HEADACHE'
TELSERV2 = 'LOST PHONE SERVICE ONE WEEK+ LAST 12 MOS'
TNSARCNT = 'WAS MOST RECENT TETANUS SHOT IN 2005 OR LATER?'
TNSARCV = 'RECEIVED TETANUS SHOT IN THE PAST 10 YEARS?'
TNSASHOT = 'DID TETANUS SHOT INCLUDED THE PERTUSSIS VACCINE?'
TNSCRCNT = 'WAS ADOLESCENT MOST RECENT TETANUS SHOT IN 2005 OR LATER?'
TNSCRCV = 'ADOLESCENT RECEIVED TETANUS SHOT IN THE PAST 10 YEARS?'
TNSCSHOT = 'DID ADOLESCENT TETANUS SHOT INCLUDED THE PERTUSSIS VACCINE?'
TOLDHI2 = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
USEEQUIP = 'HEALTH PROBLEMS REQUIRING SPECIAL EQUIPMENT'
USENOW3 = 'USE OF SMOKELESS TOBACCO PRODUCTS'
VEGEDAY_ = 'COMPUTED VEGETABLE SERVINGS PER DAY'
VEGETABL = 'SERVINGS OF VEGETABLES'
VETERAN2 = 'ARE YOU A VETERAN'
VICTRCT2 = 'HLTH CARE PRO SAID NOW HAVE CATARACTS'
VIDFCLT2 = 'DIFFICULTY RECOGNIZING FRIEND ACROSS STREET'
VIEYEXM2 = 'WHEN LAST EYEXAM'
VIGCAT_ = 'COMPUTED VIGOROUS PHYSICAL ACTIVITY CATEGORIES'
VIGLUMA2 = 'HLTH CARE PRO EVER SAID HAVE GLAUCOMA'
VIGPACT = 'VIGOROUS PHYSICAL ACTIVITY'
VIGPADAY = 'VIGOROUS PHYSICAL ACTIVITY DAYS'
VIGPATIM = 'VIGOROUS PHYSICAL ACTIVITY TIME'
VIINSUR2 = 'EYE CARE HEALTH INSURANCE'
VIMACDG2 = 'HLTH CARE PRO EVER SAID HAVE MACULAR DEGENERATION'
VINOCRE2 = 'REASON DID NOT USE EYE DOC PAST 12 MOS'
VIPRFVS2 = 'LAST TIME VISITED EYE CARE PROVIDER'
VIREDIF2 = 'DIFFICULTY READING TYPED TEXT'
WEIGHT2 = 'REPORTED WEIGHT IN POUNDS'
WHRTST8 = 'LOCATION OF LAST HIV TEST'
WRKHCF1 = 'DO YOU CURRENTLY VOLUNTEER OR WORK IN A HOSPITAL, MEDICAL CLINIC, DOCTOR´S OFFICE, DENTIST´S OFFICE, NURSING HOME OR SOME OTHER HEALTH-CARE FACILITY?'
WTCHGINT = 'CHANGE IN WEIGHT SINCE YEAR AGO'
WTKG2 = 'COMPUTED WEIGHT IN KILOGRAMS'
WTYRAGO = 'REPORTED WEIGHT YEAR AGO IN POUNDS'
_AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS CALCULATED VARIABLE'
_AGEG5YR = 'REPORTED AGE IN FIVE-YEAR AGE CATEGORIES CALCULATED VARIABLE'
_AGEG_ = 'AGE GROUP CODES USED IN POST-STRATIFICATION.'
_AGE_G = 'IMPUTED AGE IN SIX GROUPS'
_AIDTST2 = 'EVER BEEN TESTED FOR HIV CALCULATED VARIABLE'
_ASTHMST = 'COMPUTED ASTHMA STATUS'
_BMI4 = 'COMPUTED BODY MASS INDEX'
_BMI4CAT = 'COMPUTED BODY MASS INDEX CATEGORIES'
_CAGEG_ = 'CHILD AGE GROUP CODES USED IN POST-STRATIFICATION.'
_CASTHMA = 'CURRENT ASTHMA CALCULATED VARIABLE'
_CHILDWT = 'FINAL CHILD WEIGHT'
_CHLDCNT = 'COMPUTED NUMBER OF CHILDREN IN HOUSEHOLD'
_CHOLCHK = 'CHOLESTEROL CHECKED CALCULATED VARIABLE'
_CIMPAGE = 'IMPUTED CHILD AGE'
_CNRACE = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN'
_CNRACEC = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN, COLLAPSED'
_CRACE = 'CHILD NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_CRACEG_ = 'CHILD RACE GROUP CODES USED IN POST-STRATIFICATION.'
_CSEXG_ = 'CHILD GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_DENSTR2 = 'HOUSEHOLD DENSITY STRATUM CODE'
_DRDXART = 'RESPONDENTS DIAGNOSED WITH ARTHRITIS'
_DRNKDY3 = 'COMPUTED NUMBER OF DRINKS OF ALCOHOL BEVERAGES PER DAY'
_DRNKMO3 = 'COMPUTED TOTAL NUMBER DRINKS A MONTH'
_EDUCAG = 'COMPUTED LEVEL OF EDUCATION COMPLETED CATEGORIES'
_FINALWT = 'FINAL WEIGHT'
_FLSHOT3 = 'FLU SHOT CALCULATED VARIABLE'
_FRTINDX = 'SUMMARY INDEX FOR FRUITS AND VEGETABLES CALCULATED VARIABLE'
_FRTSERV = 'COMPUTED TOTAL NUMBER OF SERVINGS OF FRUITS AND VEGETABLES CONSUMED PER DAY'
_FV5SRV = 'CONSUMED FIVE OR MORE SERVINGS OF FRUITS OR VEGETABLES PER DAY CALCULATED VARIABLE'
_GEOSTR = 'GEOGRAPHIC STRATUM CODE'
_HCVU65 = 'RESPONDENTS AGED 18-64 WITH HEALTH CARE COVERAGE'
_HOUSEWT = 'FINAL HOUSEHOLD WEIGHT'
_IMPAGE = 'AGE VALUE USED TO DETERMINE AGE GROUPS'
_IMPNPH = 'IMPUTED NUMBER OF PHONES'
_INCOMG = 'COMPUTED INCOME CATEGORIES'
_ITSCF1 = 'INTERRUPTION IN TELEPHONE SERVICE CORRECTION FACTOR'
_ITSCF2 = 'INTERRUPTION IN TELEPHONE SERVICE CORRECTION FACTOR (ADJUSTED _WT2)'
_ITSFINL = 'INTERRUPTION IN TELEPHONE SERVICE FINAL WEIGHTING FACTOR'
_ITSPOST = 'INTERRUPTION IN TELEPHONE SERVICE POST STRATIFICATION CORRECTION FACTOR'
_LTASTHM = 'LIFETIME ASTHMA CALCULATED VARIABLE'
_MODMNWK = 'COMPUTED MINUTES OF MODERATE PHYSICAL ACITIVITY PER WEEK'
_MODPAMN = 'COMPUTED MINUTES OF MODERATE PHYSICAL ACITIVITY'
_MRACE = 'COMPUTED NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_PA150RC = '150 MINUTE PHYSICAL ACTIVITY CALCULATED VARIABLE'
_PA300RC = '300 MINUTE PHYSICAL ACTIVITY CALCULATED VARIABLE'
_PNEUMO2 = 'PNEUMONIA VACCINATION CALCULATED VARIABLE'
_POSTCH = 'POST-STRATIFICATION CHILD WEIGHT'
_POSTHH = 'POST-STRATIFICATION HOUSEHOLD WEIGHT'
_POSTSTR = 'POST-STRATIFICATION WEIGHT'
_PRACE = 'COMPUTED PREFERRED RACE'
_PSU = 'PRIMARY SAMPLING UNIT'
_RACEG2 = 'COMPUTED NON-HISPANIC WHITES/ALL OTHERS RACE CATEGORIES RACE/ETHNIC GROUP CODES USED IN POST-STRATIFICATION.'
_RACEG3_ = 'RACE GROUP CODES USED IN POST-STRATIFICATION.'
_RACEGR2 = 'COMPUTED FIVE LEVEL RACE/ETHNICITY CATEGORY.'
_RACE_G = 'COMPUTED RACE GROUPS USED FOR INTERNET PREVALENCE TABLES'
_RAW = 'RAW WEIGHTING FACTOR'
_RAWCH = 'RAW CHILD WEIGHTING FACTOR'
_RAWHH = 'RAW HOUSEHOLD  WEIGHTING FACTOR'
_REGION = 'REGION'
_RFBING4 = 'BINGE DRINKING CALCULATED VARIABLE'
_RFBMI4 = 'OVERWEIGHT OR OBESE CALCULATED VARIABLE'
_RFCHOL = 'HIGH CHOLESTEROL CALCULATED VARIABLE'
_RFDRHV3 = 'HEAVY ALCOHOL CONSUMPTION  CALCULATED VARIABLE'
_RFDRMN3 = 'ADULT MEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFDRWM3 = 'ADULT WOMEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFHLTH = 'ADULTS WITH GOOD OR BETTER HEALTH'
_RFHYPE5 = 'HIGH BLOOD PRESSURE CALCULATED VARIABLE'
_RFNOPA = 'NO PHYSICAL ACTIVITY OR EXERCISE CALCULATED VARIABLE'
_RFPAMOD = 'MODERATE PHYSICAL ACTIVITY CALCULATED VARIABLE'
_RFPAREC = 'RECOMMENDED PHYSICAL ACTIVITY CALCULATED VARIABLE'
_RFPAVIG = 'VIGOROUS PHYSICAL ACTIVITY CALCULATED VARIABLE'
_RFSMOK3 = 'CURRENT SMOKING CALCULATED VARIABLE'
_SEXG_ = 'GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_SMOKER3 = 'COMPUTED SMOKING STATUS'
_STATE = 'STATE FIPS CODE'
_STRWT = 'STRATUM WEIGHT'
_STSTR = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
_TOTINDA = 'LEISURE TIME PHYSICAL ACTIVITY CALCULATED VARIABLE'
_TOTMNWK = 'COMPUTED MINUTES OF TOTAL PHYSICAL ACITIVITY PER WEEK'
_VIGMNWK = 'COMPUTED MINUTES OF VIGOROUS PHYSICAL ACTIVITY PER WEEK'
_VIGPAMN = 'COMPUTED MINUTES OF VIGOROUS PHYSICAL ACTIVITY'
_WT2 = 'DESIGN WEIGHT'
_WT2CH = 'CHILD DESIGN WEIGHT'
_WT2HH = 'HOUSEHOLD DESIGN WEIGHT'
;
RUN;
