*****************************************************************************************
* FILE NAME:     DUALOUT07V2.SAS                                                        *
* DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT  *
*                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF       *
* REFERENCES:                                                                           *
* INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES                   *
* FORMATS     FORMATS.SAS7BCAT      SAS FORMATS DATABASE                                *
* OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN       *
*                              <DATAIN> FILEREF                                         *
* UPDATED - 02/27/2008                                                                  *
*****************************************************************************************;
********************************
* Clear Output and Log Windows *
********************************;
DM OUTPUT 'clear' continue;
DM LOG    'clear' continue;
**********************************
* DEFINE SAS ENVIRONMENT OPTIONS *
**********************************;
OPTIONS PAGENO=1 NOFMTERR;
***************************************
* CLEAR EXISTING TITLES AND FOOTNOTES *
***************************************;
TITLE ;
FOOTNOTE ;
RUN ;
******************************************************************
* INSTRUCTIONS:                                                  *
* SPECIFY PATH OF WHERE ASCII DATAFILE IS STORED                 *
* SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED              *
* SPECIFY PATH OF WHERE SAS FORMAT LIBRARY IS STORED             *
* SPECIFY PATH OF WHERE THE FORMAT ASSIGNMET STATEMENT IS STORED *
******************************************************************;

*FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 1289 ;
*****************************************************************************
* EXAMPLE:                                                                  *
*       FILENAME DATAIN 'C:\BRFSS\2007\BRFS07V2.ASC' LRECL = 1289           *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

*LIBNAME DATAOUT V7 '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>'  ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME DATAOUT 'C:\'                                            *
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.sas7bdat             *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*LIBNAME LIBRARY '<PATH OF STORED SAS FORMAT07.SAS7BCAT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME LIBRARY 'C:\'                                            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*FILENAME FORMATIN '<PATH OF FORMAT ASSIGNMENT STATEMENT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          FILENAME FORMATIN 'C:\FORMATSTATEMENT.SAS'                       *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT
_STATE        1-2                     /* Record Identification */
_GEOSTR       3-4
_DENSTR2      5
PRECALL       6
REPNUM        7-11
REPDEPTH      12-13
FMONTH        14-15
IDATE         $16-23
IMONTH        $16-17
IDAY          $18-19
IYEAR         $20-23
INTVID        $24-26
DISPCODE      27-29
SEQNO         30-39
_PSU          30-39
NATTMPTS      40-41
NRECSEL       42-47
NRECSTR       48-56
CTELENUM      57
CELLFON       58
PVTRESID      59
NUMADULT      60-61
NUMMEN        62-63
NUMWOMEN      64-65
GENHLTH       73                      /* Section 1: Health Status */
PHYSHLTH      74-75                   /* Section 2: Healthy Days - Health-Related Quality of Life */
MENTHLTH      76-77
POORHLTH      78-79
HLTHPLAN      80                      /* Section 3: Health Care Access */
PERSDOC2      81
MEDCOST       82
CHECKUP1      83
EXERANY2      84                      /* Section 4: Exercise */
DIABETE2      85                      /* Section 5: Diabetes */
BPHIGH4       86                      /* Section 6: Hypertension Awareness */
BPMEDS        87
BLOODCHO      88                      /* Section 7: Cholesterol Awareness */
CHOLCHK       89
TOLDHI2       90
CVDINFR4      91                      /* Section 8: Cardiovascular Disease Prevalence */
CVDCRHD4      92
CVDSTRK3      93
ASTHMA2       94                      /* Section 9: Asthma */
ASTHNOW       95
FLUSHOT3      96                      /* Section 10: Immunization */
FLUSPRY2      97
PNEUVAC3      98
HEPBVAC       99
HEPBRSN2      100
SMOKE100      101                     /* Section 11: Tobacco Use */
SMOKDAY2      102
STOPSMK2      103
AGE           104-105                 /* Section 12: Demographics */
HISPANC2      106
MRACE         $107-112
ORACE2        113
VETERAN1      114
MARITAL       115
CHILDREN      116-117
EDUCA         118
EMPLOY        119
INCOME2       120-121
WEIGHT2       122-125
HEIGHT3       126-129
WTYRAGO       130-133
WTCHGINT      134
NUMHHOL2      143
NUMPHON2      144
TELSERV2      145
SEX           146
PREGNANT      147
DRNKANY4      148                     /* Section 13: Alcohol Consumption */
ALCDAY4       149-151
AVEDRNK2      152-153
DRNK3GE5      154-155
MAXDRNKS      156-157
QLACTLM2      158                     /* Section 14: Disability */
USEEQUIP      159
PAIN30DY      160                     /* Section 15: Arthritis Burden */
JOINTSYM      161
JOINTRT2      162
HAVARTH2      163
LMTJOIN2      164
FRUITJUI      165-167                 /* Section 16: Fruits & Vegetables */
FRUIT         168-170
GREENSAL      171-173
POTATOES      174-176
CARROTS       177-179
VEGETABL      180-182
JOBACTIV      183                     /* Section 17: Physical Activity */
MODPACT       184
MODPADAY      185-186
MODPATIM      187-189
VIGPACT       190
VIGPADAY      191-192
VIGPATIM      193-195
HIVTST5       196                     /* Section 18: HIV/AIDS */
HIVTSTD2      197-202
WHRTST8       203-204
HIVRDTST      205
EMTSUPRT      206                     /* Section 19: Emotional Support and Life Satisfaction */
LSATISFY      207
DIAR30DY      208                     /* Section 20: Gastrointestinal Disease */
DIADRVST      209
DIARSMP       210
RCSBIRTH      $226-231                /* Module 1: Random Child Selection */
RCSGENDR      232
RCHISLAT      233
RCSRACE       $234-239
RCSBRACE      240
RCSRLTN2      241
CASTHDX2      242                     /* Module 2: Childhood Asthma Prevalence */
CASTHNO2      243
DIABAGE2      244-245                 /* Module 3: Diabetes */
INSULIN       246
DIABPILL      247
BLDSUGAR      248-250
FEETCHK2      251-253
FEETSORE      254
DOCTDIAB      255-256
CHKHEMO3      257-258
FEETCHK       259-260
EYEEXAM       261
DIABEYE       262
DIABEDU       263
VIDFCLT2      264                     /* Module 4: Visual Impairment and Access to Eye Care */
VIREDIF2      265
VIPRFVS2      266
VINOCRE2      267-268
VIEYEXM2      269
VIINSUR2      270
VICTRCT2      271
VIGLUMA2      272
VIMACDG2      273
VIATWRK2      274
PAINACT2      275-276                 /* Module 5: Healthy Days (Symptoms) */
QLMENTL2      277-278
QLSTRES2      279-280
QLREST2       281-282
QLHLTH2       283-284
HAREHAB       285                     /* Module 6: Cardiovascular Health */
STREHAB       286
CVDASPRN      287
ASPUNSAF      288
BPEATHBT      289                     /* Module 7: Actions to Control High Blood Pressure */
BPSALT        290
BPALCHOL      291
BPEXER        292
BPEATADV      293
BPSLTADV      294
BPALCADV      295
BPEXRADV      296
BPMEDADV      297
BPHI2MR       298
HASYMP1       299                     /* Module 8: Heart Attack and Stroke */
HASYMP2       300
HASYMP3       301
HASYMP4       302
HASYMP5       303
HASYMP6       304
STRSYMP1      305
STRSYMP2      306
STRSYMP3      307
STRSYMP4      308
STRSYMP5      309
STRSYMP6      310
FIRSTAID      311
HADMAM        312                     /* Module 9: Women´s Health */
HOWLONG       313
PROFEXAM      314
LENGEXAM      315
HADPAP2       316
LASTPAP2      317
HADHYST2      318
PSATEST       319                     /* Module 10: Prostate Cancer Screening */
PSATIME       320
DIGRECEX      321
DRETIME       322
PROSTATE      323
BLDSTOOL      324                     /* Module 11: Colorectal Cancer Screening */
LSTBLDS2      325
HADSIGM3      326
HADSGCOL      327
LASTSIG2      328
ASTHMAGE      329-330                 /* Module 12: Adult Asthma History */
ASATTACK      331
ASERVIST      332-333
ASDRVIST      334-335
ASRCHKUP      336-337
ASACTLIM      338-340
ASYMPTOM      341
ASNOSLEP      342
ASTHMED3      343
ASINHALR      344
ARTTODAY      345                     /* Module 13: Arthritis Management */
ARTHWGT       346
ARTHEXER      347
ARTHEDU       348
VETSTAT2      349                     /* Module 14: Veterans Health Status */
VACARE        350
VAIRQAFG      351
RRCLASS2      352                     /* Module 15: Reactions to Race */
RRCOGNT2      353
RRATWRK2      354
RRHCARE3      355
RRPHYSM2      356
RREMTSM2      357
MISNERVS      358                     /* Module 16: Mental Illness & Stigma */
MISHOPLS      359
MISRSTLS      360
MISDEPRD      361
MISEFFRT      362
MISWTLES      363
MISNOWRK      364-365
MISTMNT       366
MISTRHLP      367
MISPHLPF      368
SVSAFE        369                     /* Module 17: Sexual Violence */
SVSEXTCH      370
SVNOTCH2      371
SVEHDSEX      372
SVHDSX12      373
SVEANOSX      374
SVNOSX12      375
SVRELAT2      376-377
SVGENDER      378
IPVSAFE       379                     /* Module 18: Intimate Partner Violence */
IPVTHRAT      380
IPVPHYV2      381
IPVPHHRT      382
IPVUWSEX      383
IPVPVL12      384
IPVSXINJ      385
IPVRELT2      386-387
GPWELPR2      388                     /* Module 19: General Preparedness */
GPVACPLN      389
GP3DYWTR      390
GP3DYFOD      391
GP3DYPRS      392
GPBATRAD      393
GPFLSLIT      394
GPMNDEVC      395
GPNOTEVC      396-397
GPEMRCOM      398
GPEMRINF      399
QSTVER        741                     /* Questionnaire Version */
QSTLANG       742-743                 /* Questionnaire Language */
_STSTR        800-804                 /* Weighting And Stratification Variables */
_STRWT        805-814
_RAWQ2        895-904
_WT2Q2        905-914
_POSTQ2       915-924
_FINALQ2      925-934
_REGION       935-936
_AGEG_        937-938
_SEXG_        939
_RACEG3_      940
_IMPAGE       941-942
_IMPNPH       943
CRACEORG      $993-998                /* Child Demographic Variables */
CRACEASC      999-1004
_CRACE        1005-1006
CHILDAGE      1007-1009
_CSEXG_       1010
_CRACEG_      1011
_CAGEG_       1012-1014
_RAWCH2       1025-1034
_WT2CH2       1055-1064
_POSTCH2      1085-1094
_CHILDQ2      1115-1124
_RFHLTH       1175                    /* Section 1: Calculated Variables */
_HCVU65       1176                    /* Section 3: Calculated Variables */
_TOTINDA      1177                    /* Section 4: Calculated Variables */
_RFHYPE5      1178                    /* Section 6: Calculated Variables */
_CHOLCHK      1179                    /* Section 7: Calculated Variables */
_RFCHOL       1180
_LTASTHM      1181                    /* Section 9: Calculated Variables */
_CASTHMA      1182
_ASTHMST      1183
_FLSHOT3      1184                    /* Section 10: Calculated Variables */
_PNEUMO2      1185
_SMOKER3      1186                    /* Section 11: Calculated Variables */
_RFSMOK3      1187
MRACEORG      $1188-1193              /* Section 12: Calculated Race Variables */
MRACEASC      $1194-1199
_PRACE        1200-1201
_MRACE        1202-1203
_RACEG2       1204
_RACEGR2      1205
_RACE_G       1206
_CNRACE       1207
_CNRACEC      1208
RACE2         1209
_AGEG5YR      1210-1211
_AGE65YR      1212
_AGE_G        1213
HTIN3         1214-1216
HTM3          1217-1219
WTKG2         1220-1224
_BMI4         1225-1228
_BMI4CAT      1229
_RFBMI4       1230
_CHLDCNT      1231
_EDUCAG       1232
_INCOMG       1233
DROCDY2_      1234-1236               /* Section 13: Calculated Variables */
_RFBING4      1237
_DRNKDY3      1238-1241
_DRNKMO3      1242-1245
_RFDRHV3      1246
_RFDRMN3      1247
_RFDRWM3      1248
_DRDXART      1249                    /* Section 15: Calculated Variables */
FTJUDAY_      1250-1252               /* Section 16: Calculated Variables */
FRUTDAY_      1253-1255
GNSLDAY_      1256-1258
POTADAY_      1259-1261
CRTSDAY_      1262-1264
VEGEDAY_      1265-1267
_FRTSERV      1268-1272
_FRTINDX      1273
_FV5SRV       1274
_MODPAMN      1275-1277               /* Section 17: Calculated Variables */
_VIGPAMN      1278-1280
MODCAT_       1281
VIGCAT_       1282
PACAT_        1283
_RFPAMOD      1284
_RFPAVIG      1285
_RFPAREC      1286
_RFNOPA       1287
_AIDTST2      1288                    /* Section 18: Calculated Variables */
;
*****************************************************************
* TO INCLUDE THE FORMAT ASSIGNEMT STATEMENT REMOVE THE ASTERISK *
* FROM THE BEGINNING OF THE FOLLOWING LINE                      *
*****************************************************************;
* %INCLUDE FORMATIN ;
*************************************************
* THIS SECTION CREATES LABELS FOR THE VARIABLES *
*************************************************;
Label
AGE = 'REPORTED AGE IN YEARS'
ALCDAY4 = 'DAYS IN PAST 30 HAD ALCOHOLIC BEVERAGE'
ARTHEDU = 'EVER TAKEN CLASS IN MANAGING ARTHRITIS OR JOINT SYMPTOMS'
ARTHEXER = 'DR. SUGGEST USE OF PHYSICAL ACTIVITY OR EXERCISE FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTHWGT = 'DR. SUGGEST LOSE WEIGHT FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTTODAY = 'WHAT CAN YOU DO BECAUSE OF ARTHRITIS OR JOINT SYMPTOMS'
ASACTLIM = 'ACTIVITIES LIMITED DUE TO ASTHMA DURING PAST 12 MONTHS'
ASATTACK = 'ASTHMA DURING PAST 12 MONTHS'
ASDRVIST = 'URGENT ASTHMA TREATMENT DURING PAST 12 MONTHS'
ASERVIST = 'EMERGENCY ASTHMA CARE DURING PAST 12 MONTHS'
ASINHALR = 'TIMES USED ASTHMA INHALER DURING AN ATTACK IN PAST 30 DAYS'
ASNOSLEP = 'SLEEP DIFFICULTY DUE TO ASTHMA DURING PAST 30 DAYS'
ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
ASRCHKUP = 'ROUTINE ASTHMA CARE DURING PAST 12 MONTHS'
ASTHMA2 = 'EVER TOLD HAD ASTHMA'
ASTHMAGE = 'AGE AT ASTHMA DIAGNOSIS'
ASTHMED3 = 'DAYS USED PRESCRIBED PREVENTATIVE ASTHMA MED IN PAST 30 DAYS'
ASTHNOW = 'STILL HAVE ASTHMA'
ASYMPTOM = 'ASTHMA SYMPTOMS DURING PAST 30 DAYS'
AVEDRNK2 = 'AVG ALCOHOLIC DRINKS PER DAY IN PAST 30'
BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
BPALCADV = 'HLTH CARE PRO EVER ADVISED REDUCED ALCOHOL USE TO REDUCE BP'
BPALCHOL = 'REDUCE ALCOHOL USE FOR BP?'
BPEATADV = 'HLTH CARE PRO EVER ADVISED CHANGE IN EATING HABITS TO REDUCE BP'
BPEATHBT = 'CHANGE EATING HABITS FOR BP?'
BPEXER = 'EXERCISING TO LOWER BP?'
BPEXRADV = 'HLTH CARE PRO EVER ADVISED EXERCISE TO REDUCE BP'
BPHI2MR = 'TOLD HAD HIGH BP DURING 2+ VISITS TO HLTH CARE PRO?'
BPHIGH4 = 'EVER TOLD BLOOD PRESSURE HIGH'
BPMEDADV = 'HLTH CARE PRO EVER ADVISED MEDS TO REDUCE BP'
BPMEDS = 'CURRENTLY TAKING BLOOD PRESSURE MEDICATION'
BPSALT = 'REDUCE SALT INTAKE TO LOWER BP?'
BPSLTADV = 'HLTH CARE PRO EVER ADVISED USING LESS SALT TO REDUCE BP'
CARROTS = 'HOW OFTEN DO YOU EAT CARROTS'
CASTHDX2 = 'HLTH PRO EVER SAID CHILD HAS ASTHMA'
CASTHNO2 = 'CHILD STILL HAVE ASTHMA?'
CELLFON = 'CELLULAR TELEPHONE'
CHECKUP1 = 'LENGTH OF TIME SINCE LAST ROUTINE CHECKUP'
CHILDAGE = 'CHILD AGE'
CHILDREN = 'NUMBER OF CHILDREN IN HOUSEHOLD'
CHKHEMO3 = 'TIMES CHECKED FOR GLYCOSYLATED HEMOGLOBIN'
CHOLCHK = 'HOW LONG SINCE CHOLESTEROL CHECKED'
CRACEASC = 'CRACEORG WITH RESPONSES IN ASCENDING ORDER'
CRACEORG = 'CRACE WITH TRAILING 7, 8, 9S REMOVED'
CRTSDAY_ = 'COMPUTED CARROT SERVINGS PER DAY'
CTELENUM = 'CORRECT TELEPHONE NUMBER?'
CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
CVDCRHD4 = 'EVER DIAGNOSED WITH ANGINA OR CORONARY HEART DISEASE'
CVDINFR4 = 'EVER DIAGNOSED WITH HEART ATTACK'
CVDSTRK3 = 'EVER DIAGNOSED WITH A STROKE'
DIABAGE2 = 'AGE WHEN TOLD DIABETIC'
DIABEDU = 'EVER TAKEN CLASS IN MANAGING DIABETES'
DIABETE2 = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
DIABEYE = 'EVER TOLD DIABETES HAS AFFECTED EYES'
DIABPILL = 'NOW TAKING DIABETES PILLS'
DIADRVST = 'VISIT HEALTH PRO FOR THIS DIARRHEAL DISEASE?'
DIAR30DY = 'DIARRHEA PAST 30 DAYS?'
DIARSMP = 'GIVE STOOL SAMPLE TO HEALTH PRO?'
DIGRECEX = 'EVER HAD DIGITAL RECTAL EXAM'
DISPCODE = 'FINAL DISPOSITION'
DOCTDIAB = 'TIMES SEEN HEALTH PROFESSIONAL FOR DIABETES'
DRETIME = 'TIME SINCE LAST DIGITAL RECTAL EXAM'
DRNK3GE5 = 'BINGE DRINKING'
DRNKANY4 = 'DRINK ANY ALCOHOLIC BEVERAGES IN PAST 30 DAYS'
DROCDY2_ = 'COMPUTED DRINK-OCCASIONS-PER-DAY'
EDUCA = 'EDUCATION LEVEL'
EMPLOY = 'EMPLOYMENT STATUS'
EMTSUPRT = 'HOW OFTEN GET EMOTIONAL SUPPORT NEEDED'
EXERANY2 = 'EXERCISE IN PAST 30 DAYS'
EYEEXAM = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
FEETCHK = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
FEETCHK2 = 'HOW OFTEN CHECK FEET FOR SORES OR IRRITATIONS'
FEETSORE = 'EVER HAD FEET SORES OR IRRITATIONS LASTING MORE THAN FOUR WEEKS'
FIRSTAID = 'FIRST AID FOR HEART ATTACK AND STROKE'
FLUSHOT3 = 'FLU SHOT PAST 12 MOS'
FLUSPRY2 = 'FLU SPRAY PAST 12 MOS'
FMONTH = 'FILE MONTH'
FRUIT = 'HOW OFTEN DO YOU EAT FRUIT'
FRUITJUI = 'HOW OFTEN DO YOU DRINK FRUIT JUICES'
FRUTDAY_ = 'COMPUTED FRUIT SERVINGS PER DAY'
FTJUDAY_ = 'COMPUTED FRUIT JUICE SERVINGS PER DAY'
GENHLTH = 'GENERAL HEALTH'
GNSLDAY_ = 'COMPUTED GREEN SALAD SERVINGS PER DAY'
GP3DYFOD = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF NON-PERISHABLE FOOD FOR EVERYONE WHO LIVES THERE?'
GP3DYPRS = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF PRESCRIPTION MEDICATION FOR EACH PERSON WHO TAKES PRESCRIBED MEDICI
NES?'
GP3DYWTR = 'DOES YOUR HOUSEHOLD HAVE A 3-DAY SUPPLY OF WATER FOR EVERYONE WHO LIVES THERE?'
GPBATRAD = 'DOES YOUR HOUSEHOLD HAVE A WORKING BATTERY OPERATED RADIO AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICIT
Y IS OUT?'
GPEMRCOM = 'IN A LARGE-SCALE DISASTER OR EMERGENCY, WHAT WOULD BE YOUR MAIN METHOD OF COMMUNICATING WITH RELATIVES AND FRI
ENDS?'
GPEMRINF = 'WHAT WOULD BE YOUR MAIN METHOD OF GETTING INFORMATION FROM AUTHORITIES IN A LARGE-SCALE DISASTER OR EMERGENCY?
'
GPFLSLIT = 'DOES YOUR HOUSEHOLD HAVE A WORKING FLASHLIGHT AND WORKING BATTERIES FOR YOUR USE IF THE ELECTRICITY IS OUT?'
GPMNDEVC = 'IF PUBLIC AUTHORITIES ANNOUNCED MANDATORY EVACUATION FROM YOUR COMMUNITY DUE TO A LARGE-SCALE DISASTER OR EMER
GENCY, WOULD YOU EVACUATE?'
GPNOTEVC = 'WHAT WOULD BE THE MAIN REASON WHY YOU MIGHT NOT EVACUATE IF ASKED TO DO SO?'
GPVACPLN = 'DOES YOUR HOUSEHOLD HAVE A DISASTER EVACUATION PLAN?'
GPWELPR2 = 'HOUSEHOLD PREPARED TO HANDLE LARGE-SCALE DISASTER OR EMERGENCY'
GREENSAL = 'HOW OFTEN DO YOU EAT GREEN SALAD'
HADHYST2 = 'HAD HYSTERECTOMY'
HADMAM = 'HAVE YOU EVER HAD A MAMMOGRAM'
HADPAP2 = 'EVER HAD A PAP TEST'
HADSGCOL = 'MOST RECENT EXAM CALLED SIGMOIDOSCOPY OR COLONOSCOPY?'
HADSIGM3 = 'EVER HAD SIGMOIDOSCOPY/COLONOSCOPY'
HAREHAB = 'OUTPATIENT REHAB AFTER HEART ATTACK HOSP STAY'
HASYMP1 = 'HEART ATTACK SYMPTOMS - JAW/BACK/NECK PAIN'
HASYMP2 = 'HEART ATTACK SYMPTOMS - WEAK/LIGHT-HEADED/FAINT'
HASYMP3 = 'HEART ATTACK SYMPTOMS - CHEST PAIN/DISCOMFORT'
HASYMP4 = 'HEART ATTACK SYMPTOMS - VISION PROBLEMS'
HASYMP5 = 'HEART ATTACK SYMPTOMS - PAIN OR DISCOMFORT IN ARMS/SHOULDER'
HASYMP6 = 'HEART ATTACK SYMPTOMS - SHORTNESS OF BREATH'
HAVARTH2 = 'TOLD HAVE ARTHRITIS'
HEIGHT3 = 'REPORTED HEIGHT IN FEET AND INCHES'
HEPBRSN2 = 'ANY HEPATITIS B BEHAVIORS TRUE FOR YOU?'
HEPBVAC = 'EVER HAD HEPATITIS B VACCINE'
HISPANC2 = 'HISPANIC/LATINO'
HIVRDTST = 'WAS YOUR LAST HIV TEST A RAPID TEST?'
HIVTST5 = 'EVER TESTED HIV'
HIVTSTD2 = 'MONTH AND YEAR OF LAST HIV TEST'
HLTHPLAN = 'HAVE ANY HEALTH CARE COVERAGE'
HOWLONG = 'HOW LONG SINCE LAST MAMMOGRAM'
HTIN3 = 'COMPUTED HEIGHT IN INCHES'
HTM3 = 'COMPUTED HEIGHT IN METERS'
IDATE = 'INTERVIEW DATE'
IDAY = 'INTERVIEW DAY'
IMONTH = 'INTERVIEW MONTH'
INCOME2 = 'INCOME LEVEL'
INSULIN = 'NOW TAKING INSULIN'
INTVID = 'INTERVIEWER IDENTIFICATION'
IPVPHHRT = 'SEX PARTNER EVER VIOLENT'
IPVPHYV2 = 'SEX PARTNER EVER ATTEMPTED VIOLENCE'
IPVPVL12 = 'HAD UNWANTED SEX OR VIOLENCE FROM SEX PARTNER LAST 12 MOS'
IPVRELT2 = 'RELATIONSHIP TO SEX PARTNER LAST VIOLENCE OR UNWANTED SEX'
IPVSAFE = 'IN A SAFE PLACE TO ANSWER QUESTIONS'
IPVSXINJ = 'INJURIES FROM VIOLENCE OR UNWANTED SEX PAST 12 MOS'
IPVTHRAT = 'SEX PARTNER EVER THREATENED VIOLENCE'
IPVUWSEX = 'EVER HAD UNWANTED SEX W/ PARTNER'
IYEAR = 'INTERVIEW YEAR'
JOBACTIV = 'PHYSICAL ACTIVITY AT WORK'
JOINTRT2 = 'TREATED FOR JOINT SYMPTOMS'
JOINTSYM = 'JOINT SYMPTOMS THREE MONTHS OLD'
LASTPAP2 = 'HOW LONG SINCE LAST PAP TEST'
LASTSIG2 = 'TIME SINCE LAST SIGMOIDOSCOPY/COLONOSCOPY'
LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
LMTJOIN2 = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
LSATISFY = 'SATISFACTION WITH LIFE'
LSTBLDS2 = 'TIME SINCE LAST BLOOD STOOL TEST'
MARITAL = 'MARITAL STATUS'
MAXDRNKS = 'MOST DRINKS ON SINGLE OCCASION PAST 30 DAYS'
MEDCOST = 'COULD NOT SEE DR. BECAUSE OF COST'
MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
MISDEPRD = 'HOW OFTEN FEEL DEPRESSED PAST 30 DAYS'
MISEFFRT = 'HOW OFTEN FEEL EVERYTHING WAS AN EFFORT PAST 30 DAYS'
MISHOPLS = 'HOW OFTEN FEEL HOPELESS PAST 30 DAYS'
MISNERVS = 'HOW OFTEN FEEL NERVOUS PAST 30 DAYS'
MISNOWRK = 'EMOTIONAL PROBLEM KEPT YOU FROM DOING WORK PAST 30 DAYS'
MISPHLPF = 'PEOPLE ARE GENERALLY CARING TOWARD PEOPLE WITH MENTAL ILLNESS'
MISRSTLS = 'HOW OFTEN FEEL RESTLESS PAST 30 DAYS'
MISTMNT = 'RECEIVING MEDICINE OR TREATMENT FROM HEALTH PRO FOR EMOTIONAL PROBLEM'
MISTRHLP = 'MENTAL HEALTH TREATMENT CAN HELP PEOPLE LEAD NORMAL LIFE'
MISWTLES = 'HOW OFTEN FEEL WORTHLESS PAST 30 DAYS'
MODCAT_ = 'COMPUTED MODERATE PHYSICAL ACTIVITY CATEGORIES'
MODPACT = 'MODERATE PHYSICAL ACTIVITY'
MODPADAY = 'MODERATE PHYSICAL ACTIVITY DAYS'
MODPATIM = 'MODERATE PHYSICAL ACTIVITY TIME'
MRACE = 'MULTIPLE RACE'
MRACEASC = 'MRACEORG WITH RESPONSES IN ASCENDING ORDER CALCULATED VARIABLE'
MRACEORG = 'MRACE WITH TRAILING 7,8,9S REMOVED CALCULATED VARIABLE'
NATTMPTS = 'NUMBER OF ATTEMPTS'
NRECSEL = 'NUMBER OF SAMPLE RECORDS SELECTED FROM STRATUM'
NRECSTR = 'NUMBER OF TELEPHONE NUMBERS IN STRATUM FROM WHICH SAMPLE WAS SELECTED'
NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
NUMHHOL2 = 'HOUSEHOLD TELEPHONES'
NUMMEN = 'NUMBER OF ADULT MEN IN HOUSEHOLD'
NUMPHON2 = 'RESIDENTIAL PHONES'
NUMWOMEN = 'NUMBER OF ADULT WOMEN IN HOUSEHOLD'
ORACE2 = 'RESPONDENT RACE CHOICE'
PACAT_ = 'COMPUTED OVERALL PHYSICAL ACTIVITY CATEGORIES'
PAIN30DY = 'HAD PAIN, ACHING, STIFFNESS, SWELLING'
PAINACT2 = 'HOW MANY DAYS HARD TO DO USUAL ACTIVITIES IN PAST 30 DAYS'
PERSDOC2 = 'MULTIPLE HEALTH CARE PROFESSIONALS'
PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
PNEUVAC3 = 'PNEUMONIA SHOT EVER'
POORHLTH = 'POOR PHYSICAL HEALTH'
POTADAY_ = 'COMPUTED POTATO SERVINGS PER DAY'
POTATOES = 'HOW OFTEN DO YOU EAT POTATOES'
PRECALL = 'PRE-CALL STATUS CODE'
PREGNANT = 'PREGNANCY STATUS'
PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
PROSTATE = 'EVER TOLD YOU HAD PROSTATE CANCER'
PSATEST = 'EVER HAD PSA TEST'
PSATIME = 'TIME SINCE LAST PSA TEST'
PVTRESID = 'PRIVATE RESIDENCE?'
QLACTLM2 = 'ACTIVITY LIMITATION DUE TO HEALTH PROBLEMS'
QLHLTH2 = 'HOW MANY DAYS FULL OF ENERGY IN PAST 30 DAYS'
QLMENTL2 = 'HOW MANY DAYS DEPRESSED IN PAST 30 DAYS'
QLREST2 = 'HOW MANY DAYS DID YOU GET ENOUGH SLEEP IN PAST 30 DAYS'
QLSTRES2 = 'HOW MANY DAYS FELT ANXIOUS IN PAST 30 DAYS'
QSTLANG = 'LANGUAGE IDENTIFIER'
QSTVER = 'QUESTIONNAIRE VERSION IDENTIFIER'
RACE2 = 'COMPUTED RACE-ETHNICITY GROUPING'
RCHISLAT = 'ETHNICITY OF CHILD'
RCSBIRTH = 'BIRTH DATE OF CHILD'
RCSBRACE = 'RACE OF CHILD'
RCSGENDR = 'GENDER OF CHILD'
RCSRACE = 'RACE OF CHILD (MULTIPLE POSSIBLE)'
RCSRLTN2 = 'RELATIONSHIP TO CHILD'
REPDEPTH = 'REPLICATE DEPTH'
REPNUM = 'REPLICATE NUMBER'
RRATWRK2 = 'HOW DO YOU FEEL YOU WERE TREATED AT WORK COMPARED TO PEOPLE OF OTHER RACES IN PAST 12 MONTHS?'
RRCLASS2 = 'HOW DO OTHER PEOPLE USUALLY CLASSIFY YOU IN THIS COUNTRY?'
RRCOGNT2 = 'HOW OFTEN DO YOU THINK ABOUT YOUR RACE?'
RREMTSM2 = 'TIMES PAST 30 DAYS FELT EMOTIONALLY UPSET BECAUSE OF TREATMENT DUE TO YOUR RACE'
RRHCARE3 = 'WHEN SEEKING HEALTH CARE PAST 12 MONTHS, WAS EXPERIENCE WORSE, SAME, BETTER THAN PEOPLE OF OTHER RACES?'
RRPHYSM2 = 'TIMES PAST 30 DAYS FELT PHYSICAL SYMPTOMS BECAUSE OF TREATMENT DUE TO YOUR RACE'
SEQNO = 'ANNUAL SEQUENCE NUMBER'
SEX = 'RESPONDENTS SEX'
SMOKDAY2 = 'FREQUENCY OF DAYS NOW SMOKING'
SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
STOPSMK2 = 'STOPPED SMOKING IN PAST 12 MONTHS'
STREHAB = 'OUTPATIENT REHAB AFTER HOSP STAY FOR STROKE'
STRSYMP1 = 'STROKE SYMPTOMS - CONFUSION/TROUBLE SPEAKING'
STRSYMP2 = 'STROKE SYMPTOMS - NUMBNESS OR WEAKNESS OF FACE/ARM/LEG'
STRSYMP3 = 'STROKE SYMPTOMS - VISION PROBLEMS'
STRSYMP4 = 'STROKE SYMPTOMS - CHEST PAIN/DISCOMFORT'
STRSYMP5 = 'STROKE SYMPTOMS - TROUBLE WALKING/DIZZINESS/LOSS OF BALANCE'
STRSYMP6 = 'STROKE SYMPTOMS - SEVERE HEADACHE'
SVEANOSX = 'SOMEONE EVER ATTEMPT TO HAVE SEX AGAINST WILL BUT DID NOT HAPPEN'
SVEHDSEX = 'SOMEONE EVER HAD SEX WITH YOU AGAINST YOUR WILL'
SVGENDER = 'PERSON’S GENDER WHO HAD SEX WITH YOU AGAINST YOUR WILL'
SVHDSX12 = 'HAPPENED IN THE PAST 12 MONTHS'
SVNOSX12 = 'HAPPENED IN THE PAST 12 MONTHS'
SVNOTCH2 = 'SOMEONE PAST 12 MOS PUT YOU IN UNWANTED SEX SITUATION W/O TOUCHING'
SVRELAT2 = 'RELATIONSHIP TO PERSON MOST RECENTLY ATTEMPTING OR HAVING UNWANTED SEX'
SVSAFE = 'IN A SAFE PLACE TO ANSWER QUESTIONS'
SVSEXTCH = 'UNWANTED TOUCHING OF SEXUAL PARTS OF BODY PAST 12 MOS'
TELSERV2 = 'LOST PHONE SERVICE ONE WEEK+ LAST 12 MOS'
TOLDHI2 = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
USEEQUIP = 'HEALTH PROBLEMS REQUIRING SPECIAL EQUIPMENT'
VACARE = 'RECEIVED SOME OR ALL OF YOUR HEALTH CARE FROM VA FACILITIES IN THE LAST 12 MONTHS'
VAIRQAFG = 'MILITARY DEPLOYMENT TO AFGHANISTAN OR IRAQ SINCE 9/11?'
VEGEDAY_ = 'COMPUTED VEGETABLE SERVINGS PER DAY'
VEGETABL = 'SERVINGS OF VEGETABLES'
VETERAN1 = 'ARE YOU A VETERAN'
VETSTAT2 = 'CURRENT VETERAN STATUS'
VIATWRK2 = 'EYE INJURY AT WORKPLACE'
VICTRCT2 = 'HLTH CARE PRO SAID NOW HAVE CATARACTS'
VIDFCLT2 = 'DIFFICULTY RECOGNIZING FRIEND ACROSS STREET'
VIEYEXM2 = 'WHEN LAST EYEXAM'
VIGCAT_ = 'COMPUTED VIGOROUS PHYSICAL ACTIVITY CATEGORIES'
VIGLUMA2 = 'HLTH CARE PRO EVER SAID HAVE GLAUCOMA'
VIGPACT = 'VIGOROUS PHYSICAL ACTIVITY'
VIGPADAY = 'VIGOROUS PHYSICAL ACTIVITY DAYS'
VIGPATIM = 'VIGOROUS PHYSICAL ACTIVITY TIME'
VIINSUR2 = 'EYE CARE HEALTH INSURANCE'
VIMACDG2 = 'HLTH CARE PRO EVER SAID HAVE MACULAR DEGENERATION'
VINOCRE2 = 'REASON DID NOT USE EYE DOC PAST 12 MOS'
VIPRFVS2 = 'LAST TIME VISITED EYE CARE PROVIDER'
VIREDIF2 = 'DIFFICULTY READING TYPED TEXT'
WEIGHT2 = 'REPORTED WEIGHT IN POUNDS'
WHRTST8 = 'LOCATION OF LAST HIV TEST'
WTCHGINT = 'CHANGE IN WEIGHT SINCE YEAR AGO'
WTKG2 = 'COMPUTED WEIGHT IN KILOGRAMS'
WTYRAGO = 'REPORTED WEIGHT YEAR AGO IN POUNDS'
_AGE65YR = 'REPORTED AGE IN TWO AGE GROUPS CALCULATED VARIABLE'
_AGEG5YR = 'REPORTED AGE IN FIVE-YEAR AGE CATEGORIES CALCULATED VARIABLE'
_AGEG_ = 'AGE GROUP CODES USED IN POST-STRATIFICATION.'
_AGE_G = 'IMPUTED AGE IN SIX GROUPS'
_AIDTST2 = 'EVER BEEN TESTED FOR HIV CALCULATED VARIABLE'
_ASTHMST = 'COMPUTED ASTHMA STATUS'
_BMI4 = 'COMPUTED BODY MASS INDEX'
_BMI4CAT = 'COMPUTED BODY MASS INDEX CATEGORIES'
_CAGEG_ = 'CHILD AGE GROUP CODES USED IN POST-STRATIFICATION.'
_CASTHMA = 'CURRENT ASTHMA CALCULATED VARIABLE'
_CHILDQ2 = 'FINAL CHILD WEIGHT'
_CHLDCNT = 'COMPUTED NUMBER OF CHILDREN IN HOUSEHOLD'
_CHOLCHK = 'CHOLESTEROL CHECKED CALCULATED VARIABLE'
_CNRACE = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN'
_CNRACEC = 'COMPUTED NUMBER OF CENSUS RACE CATEGORIES CHOSEN, COLLAPSED'
_CRACE = 'CHILD NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_CRACEG_ = 'CHILD RACE GROUP CODES USED IN POST-STRATIFICATION.'
_CSEXG_ = 'CHILD GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_DENSTR2 = 'HOUSEHOLD DENSITY STRATUM CODE'
_DRDXART = 'RESPONDENTS DIAGNOSED WITH ARTHRITIS'
_DRNKDY3 = 'COMPUTED NUMBER OF DRINKS OF ALCOHOL BEVERAGES PER DAY'
_DRNKMO3 = 'COMPUTED TOTAL NUMBER DRINKS A MONTH'
_EDUCAG = 'COMPUTED LEVEL OF EDUCATION COMPLETED CATEGORIES'
_FINALQ2 = 'FINAL WEIGHT'
_FLSHOT3 = 'FLU SHOT CALCULATED VARIABLE'
_FRTINDX = 'SUMMARY INDEX FOR FRUITS AND VEGETABLES CALCULATED VARIABLE'
_FRTSERV = 'COMPUTED TOTAL NUMBER OF SERVINGS OF FRUITS AND VEGETABLES CONSUMED PER DAY'
_FV5SRV = 'CONSUMED FIVE OR MORE SERVINGS OF FRUITS OR VEGETABLES PER DAY CALCULATED VARIABLE'
_GEOSTR = 'GEOGRAPHIC STRATUM CODE'
_HCVU65 = 'RESPONDENTS AGED 18-64 WITH HEALTH CARE COVERAGE'
_IMPAGE = 'AGE VALUE USED TO DETERMINE AGE GROUPS'
_IMPNPH = 'IMPUTED NUMBER OF PHONES'
_INCOMG = 'COMPUTED INCOME CATEGORIES'
_LTASTHM = 'LIFETIME ASTHMA CALCULATED VARIABLE'
_MODPAMN = 'COMPUTED MINUTES OF MODERATE PHYSICAL ACITIVITY'
_MRACE = 'COMPUTED NON-HISPANIC RACE INCLUDING MULTIRACIAL'
_PNEUMO2 = 'PNEUMONIA VACCINATION CALCULATED VARIABLE'
_POSTCH2 = 'POST-STRATIFICATION CHILD WEIGHT'
_POSTQ2 = 'POST-STRATIFICATION WEIGHT'
_PRACE = 'COMPUTED PREFERRED RACE'
_PSU = 'PRIMARY SAMPLING UNIT'
_RACEG2 = 'COMPUTED NON-HISPANIC WHITES/ALL OTHERS RACE CATEGORIES RACE/ETHNIC GROUP CODES USED IN POST-STRATIFICATION.'
_RACEG3_ = 'RACE GROUP CODES USED IN POST-STRATIFICATION.'
_RACEGR2 = 'COMPUTED FIVE LEVEL RACE/ETHNICITY CATEGORY.'
_RACE_G = 'COMPUTED RACE GROUPS USED FOR INTERNET PREVALENCE TABLES'
_RAWQ2 = 'RAW WEIGHTING FACTOR'
_RAWCH2 = 'RAW CHILD WEIGHTING FACTOR'
_REGION = 'REGION'
_RFBING4 = 'BINGE DRINKING CALCULATED VARIABLE'
_RFBMI4 = 'OVERWEIGHT OR OBESE CALCULATED VARIABLE'
_RFCHOL = 'HIGH CHOLESTEROL CALCULATED VARIABLE'
_RFDRHV3 = 'HEAVY ALCOHOL CONSUMPTION  CALCULATED VARIABLE'
_RFDRMN3 = 'ADULT MEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFDRWM3 = 'ADULT WOMEN HEAVY ALCOHOL CONSUMPTION CALCULATED VARIABLE'
_RFHLTH = 'ADULTS WITH GOOD OR BETTER HEALTH'
_RFHYPE5 = 'HIGH BLOOD PRESSURE CALCULATED VARIABLE'
_RFNOPA = 'NO PHYSICAL ACTIVITY OR EXERCISE CALCULATED VARIABLE'
_RFPAMOD = 'MODERATE PHYSICAL ACTIVITY CALCULATED VARIABLE'
_RFPAREC = 'RECOMMENDED PHYSICAL ACTIVITY CALCULATED VARIABLE'
_RFPAVIG = 'VIGOROUS PHYSICAL ACTIVITY CALCULATED VARIABLE'
_RFSMOK3 = 'CURRENT SMOKING CALCULATED VARIABLE'
_SEXG_ = 'GENDER GROUP CODES USED IN POST-STRATIFICATION.'
_SMOKER3 = 'COMPUTED SMOKING STATUS'
_STATE = 'STATE FIPS CODE'
_STRWT = 'STRATUM WEIGHT'
_STSTR = 'SAMPLE DESIGN STRATIFICATION VARIABLE'
_TOTINDA = 'LEISURE TIME PHYSICAL ACTIVITY CALCULATED VARIABLE'
_VIGPAMN = 'COMPUTED MINUTES OF VIGOROUS PHYSICAL ACTIVITY'
_WT2Q2 = 'DESIGN WEIGHT'
_WT2CH2 = 'CHILD DESIGN WEIGHT'
;
RUN;
