 FORMAT   AGE            AGE.
          ALCDAY4        ALC4DAY.
          ARTHEDU        ARTHEDU.
          ARTHEXER       ARTHEXER.
          ARTHWGT        ARTHWGT.
          ARTTODAY       ARTTODAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASINHALR       ASINHALR.
          ASNOSLEP       ASNOSLEP.
          ASPUNSAF       ASPUNSAF.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMED3       ASTH3MED.
          ASTHMAGE       ASTHMAGE.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK2       AVE2DRNK.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BLOODCHO       BLOODCHO.
          BPHIGH4        BP4HIGH.
          BPALCADV       BPALCADV.
          BPALCHOL       BPALCHOL.
          BPEATADV       BPEATADV.
          BPEATHBT       BPEATHBT.
          BPEXER         BPEXER.
          BPEXRADV       BPEXRADV.
          BPHI2MR        BPHI2MR.
          BPMEDADV       BPMEDADV.
          BPMEDS         BPMEDS.
          BPSALT         BPSALT.
          BPSLTADV       BPSLTADV.
          CARROTS        CARROTS.
          CASTHDX2       CASTH2DX.
          CASTHNO2       CASTH2NO.
          CELLFON        CELLFON.
          CHECKUP1       CHECK1UP.
          CHILDAGE       CHILDAGE.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CHOLCHK        CHOLCHK.
          CTELENUM       CTELENUM.
          CVDSTRK3       CVD3STRK.
          CVDCRHD4       CVD4CRHD.
          CVDINFR4       CVD4INFR.
          CVDASPRN       CVDASPRN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIABPILL       DIABPILL.
          DIADRVST       DIADRVST.
          DIAR30DY       DIAR30DY.
          DIARSMP        DIARSMP.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRETIME        DRETIME.
          DRNK3GE5       DRNK35GE.
          DRNKANY4       DRNK4ANY.
          DROCDY2_       DROCDY2_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EMTSUPRT       EMTSUPRT.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FEETSORE       FEETSORE.
          FIRSTAID       FIRSTAID.
          FLUSPRY2       FLU2SPRY.
          FLUSHOT3       FLU3SHOT.
          FMONTH         FMONTH.
          FRUIT          FRUIT.
          FRUITJUI       FRUITJUI.
          GENHLTH        GENHLTH.
          GPWELPR2       GP2WELPR.
          GP3DYFOD       GP3DYFOD.
          GP3DYPRS       GP3DYPRS.
          GP3DYWTR       GP3DYWTR.
          GPBATRAD       GPBATRAD.
          GPEMRCOM       GPEMRCOM.
          GPEMRINF       GPEMRINF.
          GPFLSLIT       GPFLSLIT.
          GPMNDEVC       GPMNDEVC.
          GPNOTEVC       GPNOTEVC.
          GPVACPLN       GPVACPLN.
          GREENSAL       GREENSAL.
          HASYMP1        HA1SYMP.
          HASYMP2        HA2SYMP.
          HASYMP3        HA3SYMP.
          HASYMP4        HA4SYMP.
          HASYMP5        HA5SYMP.
          HASYMP6        HA6SYMP.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HADSGCOL       HADSGCOL.
          HAREHAB        HAREHAB.
          HAVARTH2       HAV2ARTH.
          HEIGHT3        HEIGHT.
          HEPBVAC        HEPBVAC.
          HISPANC2       HISP2ANC.
          HIVTST5        HIV5TST.
          HIVRDTST       HIVRDTST.
          HLTHPLAN       HLTHPLAN.
          HOWLONG        HOWLONG.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INSULIN        INSULIN.
          IPVPVL12       IPV12PVL.
          IPVPHYV2       IPV2PHYV.
          IPVRELT2       IPV2RELT.
          IPVPHHRT       IPVPHHRT.
          IPVSAFE        IPVSAFE.
          IPVSXINJ       IPVSXINJ.
          IPVTHRAT       IPVTHRAT.
          IPVUWSEX       IPVUWSEX.
          JOBACTIV       JOBACTIV.
          JOINTRT2       JOIN2TRT.
          JOINTSYM       JOINTSYM.
          LASTPAP2       LAST2PAP.
          LASTSIG2       LAST2SIG.
          LENGEXAM       LENGEXAM.
          LMTJOIN2       LMT2JOIN.
          LSATISFY       LSATISFY.
          LSTBLDS2       LST2BLDS.
          MARITAL        MARITAL.
          MAXDRNKS       MAXDRNKS.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MISNOWRK       MISNOWRK.
          MISPHLPF       MISPHLPF.
          MODCAT_        MODCAT_.
          MODPACT        MODPACT.
          MODPADAY       MODPADAY.
          MODPATIM       MODPATIM.
          MSCODE         MSCODE.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          _CASTHMA       NY.
          ORACE2         O2RACE.
          PACAT_         PACAT_.
          PAINACT2       PAIN2ACT.
          PAIN30DY       PAIN30DY.
          PERSDOC2       PERS2DOC.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC3       PNEU3VAC.
          POORHLTH       POORHLTH.
          POTATOES       POTATOES.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RCHISLAT       RCHISLAT.
          RCSRLTN2       RCS2RLTN.
          RCSBRACE       RCSBRACE.
          RCSGENDR       RCSGENDR.
          RRATWRK2       RR2ATWRK.
          RRCOGNT2       RR2COGNT.
          RREMTSM2       RR2EMTSM.
          RRPHYSM2       RR2PHYSM.
          RRHCARE3       RR3HCARE.
          RRCLASS2       RRCLASS.
          SEX            SEX.
          SMOKE100       SMOK100_.
          SMOKDAY2       SMOK2DAY.
          STOPSMK2       STOP2SMK.
          STRSYMP1       STR1SYMP.
          STRSYMP2       STR2SYMP.
          STRSYMP3       STR3SYMP.
          STRSYMP4       STR4SYMP.
          STRSYMP5       STR5SYMP.
          STRSYMP6       STR6SYMP.
          STREHAB        STREHAB.
          SVHDSX12       SV12HDSX.
          SVNOSX12       SV12NOSX.
          SVNOTCH2       SV2NOTCH.
          SVRELAT2       SV2RELAT.
          SVEANOSX       SVEANOSX.
          SVEHDSEX       SVEHDSEX.
          SVGENDER       SVGENDER.
          SVSAFE         SVSAFE.
          SVSEXTCH       SVSEXTCH.
          TELSERV2       TEL2SERV.
          TOLDHI2        TOLD2HI.
          HIVTSTD2       UNK6ADIG.
          USEEQUIP       USEEQUIP.
          VACARE         VACARE.
          VAIRQAFG       VAIRQAFG.
          VEGETABL       VEGETABL.
          VETERAN1       VET1ERAN.
          VETSTAT2       VET2STAT.
          VICTRCT2       VI2CTRCT.
          VIDFCLT2       VI2DFCLT.
          VIEYEXM2       VI2EYEXM.
          VIGLUMA2       VI2GLUMA.
          VIINSUR2       VI2INSUR.
          VINOCRE2       VI2NOCRE.
          VIPRFVS2       VI2PRFVS.
          VIREDIF2       VI2REDIF.
          VIATWRK2       VIAT2WRK.
          VIGCAT_        VIGCAT_.
          VIGPACT        VIGPACT.
          VIGPADAY       VIGPADAY.
          VIGPATIM       VIGPATIM.
          VIMACDG2       VIMAC2DG.
          WEIGHT2        WEIGHT.
          WHRTST8        WHR7TST.
          WTKG2          WT2KG.
          WTCHGINT       WTCHGINT.
          WTYRAGO        WTYRAGO.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _PNEUMO2       _2PNEUMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _DRNKDY3       _3DRNKDY.
          _DRNKMO3       _3DRNKMO.
          _FLSHOT3       _3FLSHOT.
          _RFDRHV3       _3RFDRHV.
          _RFDRMN3       _3RFDRMN.
          _RFDRWM3       _3RFDRWM.
          _RFSMOK3       _3RFSMOK.
          _SMOKER3       _3SMOKER.
          _BMI4          _4BMI.
          _RFBING4       _4RFBING.
          _RFBMI4        _4RFBMI.
          _RFHYPE5       _5RFHYPE.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CAGEG_        _CAGEG_.
          _CHLDCNT       _CHLDCNT.
          _CHOLCHK       _CHOLCHK.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _CRACE         _CRACE.
          _CRACEG_       _CRACEG_.
          _CSEXG_        _CSEXG_.
          _DRDXART       _DRDXART.
          _EDUCAG        _EDUCAG.
          _FRTINDX       _FRTINDX.
          _FV5SRV        _FV5SRV.
          _HCVU65        _HCV65U.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _MRACE         _MRACE.
          _PRACE         _PRACE.
          _RACEG3_       _RACEG3_.
          _RACE_G        _RACE_G.
          _RFCHOL        _RFCHOL.
          _RFHLTH        _RFHLTH.
          _RFNOPA        _RFNOPA.
          _RFPAMOD       _RFPAMOD.
          _RFPAREC       _RFPAREC.
          _RFPAVIG       _RFPAVIG.
          _SEXG_         _SEXG_.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
