 FORMAT   ADANXEV        ADANXEV.
          ADDEPEV        ADDEPEV.
          ADDOWN         ADDOWN.
          ADEAT          ADEAT.
          ADENERGY       ADENERGY.
          ADFAIL         ADFAIL.
          ADMOVE         ADMOVE.
          ADPLEASR       ADPLEASR.
          ADSLEEP        ADSLEEP.
          ADTHINK        ADTHINK.
          AGE            AGE.
          ALCDAY4        ALC4DAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASINHALR       ASINHALR.
          ASNOSLEP       ASNOSLEP.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMED2       ASTH2MED.
          ASTHMAGE       ASTHMAGE.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK2       AVE2DRNK.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BRTHCNT3       BRTH3CNT.
          CASTHDX2       CASTH2DX.
          CASTHNO2       CASTH2NO.
          CELLFON1       CELL1FON.
          CHECKUP        CHECKUP.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CIFLUSH2       CI2FLUSH.
          CTELENUM       CTELENUM.
          CVDCRHD3       CVD3CRHD.
          CVDINFR3       CVD3INFR.
          CVDSTRK3       CVD3STRK.
          DENCLEAN       DENCLEAN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIABPILL       DIABPILL.
          DIGRECEX       DIGRECEX.
          DIRCONT        DIRCONT.
          DOCTDIAB       DOCTDIAB.
          DRETIME        DRETIME.
          DRHPAD         DRHPAD.
          DRHPCH         DRHPCH.
          DRINKDRI       DRINKDRI.
          DRNK3GE5       DRNK35GE.
          DRNKANY4       DRNK4ANY.
          DROCDY2_       DROCDY2_.
          EDUCA          EDUCA.
          EMPLOY         EMPLOY.
          EMTSUPRT       EMTSUPRT.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FALLINJ2       FALL2INJ.
          FALL3MN2       FALL32MN.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FEETSORE       FEETSORE.
          FLUSPRY2       FLU2SPRY.
          FLUSHOT3       FLU3SHOT.
          FMONTH         FMONTH.
          FOLICACD       FOLICACD.
          FPCHLDFT       FPCHLDFT.
          FPCHLDHS       FPCHLDHS.
          GENHLTH        GENHLTH.
          GP3DYFOD       GP3DYFOD.
          GP3DYPRS       GP3DYPRS.
          GP3DYWTR       GP3DYWTR.
          GPBATRAD       GPBATRAD.
          GPEMRCOM       GPEMRCOM.
          GPEMRINF       GPEMRINF.
          GPFLSLIT       GPFLSLIT.
          GPMNDEVC       GPMNDEVC.
          GPNOTEVC       GPNOTEVC.
          GPVACPLN       GPVACPLN.
          GPWELPRD       GPWELPRD.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HAVHPAD        HAVHPAD.
          HAVHPCH        HAVHPCH.
          HECHMHOM       HECHMHOM.
          HECHMYRD       HECHMYRD.
          HEIGHT3        HEIGHT.
          HEPBRSN        HEPBRSN.
          HEPBVAC        HEPBVAC.
          HEWTRDRK       HEWTRDRK.
          HEWTRSRC       HEWTRSRC.
          HISPANC2       HISP2ANC.
          HIVTST5        HIV5TST.
          HIVRDTST       HIVRDTST.
          HLTHPLAN       HLTHPLAN.
          HOUSESMK       HOUSESMK.
          HOWLONG        HOWLONG.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IAQCODTR       IAQCODTR.
          IAQGASAP       IAQGASAP.
          IAQHTDYS       IAQHTDYS.
          IAQHTSRC       IAQHTSRC.
          IAQMOLD        IAQMOLD.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INDOORS        INDOORS.
          INSULIN        INSULIN.
          IPVPVL12       IPV12PVL.
          IPVPHYV1       IPV1PHYV.
          IPVPHHRT       IPVPHHRT.
          IPVSAFE        IPVSAFE.
          IPVSXINJ       IPVSXINJ.
          IPVTHRAT       IPVTHRAT.
          IPVUWSEX       IPVUWSEX.
          LASTPAP2       LAST2PAP.
          LASTSIG2       LAST2SIG.
          LASTDEN3       LAST3DEN.
          LENGEXAM       LENGEXAM.
          LSATISFY       LSATISFY.
          LSTBLDS2       LST2BLDS.
          MARITAL        MARITAL.
          MAXDRNKS       MAXDRNKS.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MSCODE         MSCODE.
          MULTIVIT       MULTIVIT.
          NOBCUSE2       NOBC2USE.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          _CASTHMA       NY.
          ORACE2         O2RACE.
          PAINACT2       PAIN2ACT.
          PERSDOC2       PERS2DOC.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC3       PNEU3VAC.
          POORHLTH       POORHLTH.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RCHISLAT       RCHISLAT.
          RCSRELN1       RCS1RELN.
          RCSBRACE       RCSBRACE.
          RCSGENDR       RCSGENDR.
          RECOMMEN       RECOMMEN.
          RMVTETH3       RMV3TETH.
          RNOFVCH2       RNOFV2CH.
          RREMTSM1       RR1EMTSM.
          RRPHYSM1       RR1PHYSM.
          RRCOGNT2       RR2COGNT.
          RRHCARE2       RR2HCARE.
          RRATWORK       RRATWORK.
          RRCLASS2       RRCLASS.
          RSNOFAD2       RSNOF2AD.
          SEATBELT       SEATBELT.
          SEX            SEX.
          SMKPUBLC       SMKPUBLC.
          SMKWORK        SMKWORK.
          SMOKE100       SMOK100_.
          SMOKDAY2       SMOK2DAY.
          STOPSMK2       STOP2SMK.
          SVHDSX12       SV12HDSX.
          SVNOSX12       SV12NOSX.
          SVRELAT2       SV2RELAT.
          SVEANOS1       SVEA1NOS.
          SVEHDSE1       SVEHD1SE.
          SVGENDER       SVGENDER.
          SVNOTCH        SVNOTCH.
          SVSAFE         SVSAFE.
          SVSEXTCH       SVSEXTCH.
          TAKEVIT        TAKEVIT.
          TELSERV2       TEL2SERV.
          TYPCNTR4       TYP4CNTR.
          HIVTSTD2       UNK6ADIG.
          USEEQUIP       USEEQUIP.
          VETERAN        VETERAN.
          VICTRCT2       VI2CTRCT.
          VIDFCLT2       VI2DFCLT.
          VIEYEXM2       VI2EYEXM.
          VIGLUMA2       VI2GLUMA.
          VIINSUR2       VI2INSUR.
          VINOCRE2       VI2NOCRE.
          VIPRFVS2       VI2PRFVS.
          VIREDIF2       VI2REDIF.
          VIATWRK2       VIAT2WRK.
          VIMACDG2       VIMAC2DG.
          VITAMINS       VITAMINS.
          WEIGHT2        WEIGHT.
          WHRTST7        WHR7TST.
          WRKHCF         WRKHCF.
          WTKG2          WT2KG.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _PNEUMO2       _2PNEUMO.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _RFSEAT2       _2RFSEAT.
          _RFSIGM2       _2RFSIGM.
          _RFPAP32       _32RFPAP.
          _DRNKDY3       _3DRNKDY.
          _DRNKMO3       _3DRNKMO.
          _FLSHOT3       _3FLSHOT.
          _RFDRHV3       _3RFDRHV.
          _RFDRMN3       _3RFDRMN.
          _RFDRWM3       _3RFDRWM.
          _RFSEAT3       _3RFSEAT.
          _RFSMOK3       _3RFSMOK.
          _SMOKER3       _3SMOKER.
          _BMI4          _4BMI.
          _RFBING4       _4RFBING.
          _RFBMI4        _4RFBMI.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ALTETH2       _AL2TETH.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CAGEG_        _CAGEG_.
          _CHLDCNT       _CHLDCNT.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _CRACE         _CRACE.
          _CRACEG_       _CRACEG_.
          _CSEXG_        _CSEXG_.
          _DENVST1       _DEN1VST.
          _EDUCAG        _EDUCAG.
          _EXTETH2       _EX2TETH.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _MAM502Y       _MAM502Y.
          _MRACE         _MRACE.
          _PRACE         _PRACE.
          _RACEG3_       _RACEG3_.
          _RACEG4_       _RACEG4_.
          _RACE_G        _RACE_G.
          _RFBLDST       _RFBLDST.
          _RFHLTH        _RFHLTH.
          _RFMAM2Y       _RFMAM2Y.
          _RFPSA2Y       _RFPSA2Y.
          _SEXG_         _SEXG_.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
