 FORMAT   AGE            AGE.
          ALCDAY3        ALC3DAY.
          ARTHDISB       ARTHDISB.
          ARTHEDU        ARTHEDU.
          ARTHEXER       ARTHEXER.
          ARTHWGT        ARTHWGT.
          ARTTODAY       ARTTODAY.
          ASACTLIM       ASACTLIM.
          ASATTACK       ASATTACK.
          ASDRVIST       ASDRVIST.
          ASERVIST       ASERVIST.
          ASNOSLEP       ASNOSLEP.
          ASPUNSAF       ASPUNSAF.
          ASRCHKUP       ASRCHKUP.
          ASTHMA2        AST2HMA.
          ASTHMAGE       ASTHMAGE.
          ASTHMEDS       ASTHMEDS.
          ASTHNOW        ASTHNOW.
          ASYMPTOM       ASYMPTOM.
          AVEDRNK        AVEDRNK.
          BINGEDRV       BINGEDRV.
          BLDSTOOL       BLDSTOOL.
          BLDSUGAR       BLDSUGAR.
          BLOODCHO       BLOODCHO.
          BPHIGH3        BP3HIGH.
          BPMEDS         BPMEDS.
          BRTHCNT3       BRTH3CNT.
          BUYALCHH       BUYALCH.
          CASTHDX        CASTHDX.
          CASTHNOW       CASTHNOW.
          CHILDREN       CHILDREN.
          CHKHEMO3       CHK3HEMO.
          CHOLCHK        CHOLCHK.
          CONEFF2        CON2EFF.
          CONDLAST       CONDLAST.
          CTELENUM       CTELENUM.
          CVDFVG01       CVD01FVG.
          CVDFAT02       CVD02FAT.
          CVDEXR03       CVD03EXR.
          CVDCRHD2       CVD2CRHD.
          CVDEXRS2       CVD2EXRS.
          CVDFATR2       CVD2FATR.
          CVDINFR2       CVD2INFR.
          CVDSTRK2       CVD2STRK.
          CVDASPRN       CVDASPRN.
          CVDFVEG        CVDFVEG.
          CVDREHAB       CVDREHAB.
          DENCLEAN       DENCLEAN.
          DIABETE2       DIA2BETE.
          DIABAGE2       DIAB2AGE.
          DIABEDU        DIABEDU.
          DIABEYE        DIABEYE.
          DIABPILL       DIABPILL.
          DIGRECEX       DIGRECEX.
          DOCTDIAB       DOCTDIAB.
          DRETIME        DRETIME.
          DRINKDRI       DRINKDRI.
          DRNK2GE5       DRNK25GE.
          DRNKANY3       DRNK3ANY.
          DRNKBEER       DRNKBEER.
          DRNKLIQR       DRNKLIQR.
          DRNKLOC        DRNKLOC.
          DRNKWINE       DRNKWINE.
          DROCCDY_       DROCCDY_.
          EDUCA          EDUCA.
          EFILLAIR       EFILLAIR.
          EFILLPOL       EFILLPOL.
          EMPLOY         EMPLOY.
          EXERANY2       EXER2ANY.
          EYEEXAM        EYEEXAM.
          FEETCHK2       FEET2CHK.
          FEETCHK        FEETCHK.
          FEETSORE       FEETSORE.
          FIREARM4       FIRE4ARM.
          FIRSTAID       FIRSTAID.
          FLUPRO2        FLU2PRO.
          FLUSHOT2       FLU2SHOT.
          FLUSPRAY       FLUSPRAY.
          FMONTH         FMONTH.
          FOLICACD       FOLICACD.
          FPCHLDFT       FPCHLDFT.
          FPCHLDHS       FPCHLDHS.
          FVLFSAD        FVLFSAD.
          GENHLTH        GENHLTH.
          GUNLOAD        GUNLOAD.
          HASYMP1        HA1SYMP.
          HASYMP2        HA2SYMP.
          HASYMP3        HA3SYMP.
          HASYMP4        HA4SYMP.
          HASYMP5        HA5SYMP.
          HASYMP6        HA6SYMP.
          HADHYST2       HAD2HYST.
          HADPAP2        HAD2PAP.
          HADSIGM3       HAD3SIGM.
          HADMAM         HADMAM.
          HATTKAGE       HATTKAGE.
          HAVARTH2       HAV2ARTH.
          HECHMHOM       HECHMHOM.
          HECHMYRD       HECHMYRD.
          HEIGHT2        HEIGHT.
          HEWTRDRK       HEWTRDRK.
          HEWTRSRC       HEWTRSRC.
          HISPANC2       HISP2ANC.
          HIVRISK2       HIV2RISK.
          HIVTST4        HIV4TST.
          HIVTF1A        HIVTF1A.
          HIVTF1B        HIVTF1B.
          HIVTSTBY       HIVTSTBY.
          HIVTSTCL       HIVTSTCL.
          HIVTSTNM       HIVTSTNM.
          HLTHPLAN       HLTHPLAN.
          HOUSESMK       HOUSESMK.
          HOWLONG        HOWLONG.
          HTIN3          HT3IN.
          HTM3           HT3M.
          IAQCODTR       IAQCODTR.
          IAQGASAP       IAQGASAP.
          IAQHTDYS       IAQHTDYS.
          IAQHTSRC       IAQHTSRC.
          IAQMOLD        IAQMOLD.
          IMONTH         $IMONTH.
          INCOME2        IN2COME.
          INDOORS        INDOORS.
          INSULIN        INSULIN.
          JOINTRT2       JOIN2TRT.
          JOINTSYM       JOINTSYM.
          LASTDEN2       LAST2DEN.
          LASTPAP2       LAST2PAP.
          LASTSIG2       LAST2SIG.
          LENGEXAM       LENGEXAM.
          LMTJOIN2       LMT2JOIN.
          LOADULK2       LOAD2ULK.
          LSTBLDS2       LST2BLDS.
          MARITAL        MARITAL.
          MEDCOST        MEDCOST.
          MENTHLTH       MENTHLTH.
          MULTIVIT       MULTIVIT.
          NEWPARTN       NEWPARTN.
          NOBCUSE2       NOBC2USE.
          NUMHHOL2       NUM2HHOL.
          NUMPHON2       NUM2PHON.
          NUMBURN        NUMBURN.
          ORACE2         O2RACE.
          PAINACT2       PAIN2ACT.
          PAIN30DY       PAIN30DY.
          PCSAIDS2       PCS2AIDS.
          PERSDOC2       PERS2DOC.
          PHYSHLTH       PHYSHLTH.
          PNEUVAC2       PNEU2VAC.
          POORHLTH       POORHLTH.
          PRECALL        PRECALL.
          PREGNANT       PREGNANT.
          PROFEXAM       PROFEXAM.
          PROSTATE       PROSTATE.
          PSATEST        PSATEST.
          PSATIME        PSATIME.
          PVTRESID       PVTRESID.
          QLACTLM2       QL2ACTLM.
          QLHLTH2        QL2HLTH.
          QLMENTL2       QL2MENTL.
          QLREST2        QL2REST.
          QLSTRES2       QL2STRES.
          QSTLANG        QSTLANG.
          RACE2          RACE2FMT.
          RECOMMEN       RECOMMEN.
          RMVTEETH       RMVTEETH.
          RSNTST4        RSN4TST.
          SCDSCMED       SCDSCMED.
          SCDSCMTH       SCDSCMTH.
          SCGETCAR       SCGETCAR.
          SCLSTSMK       SCLSTSMK.
          SCQITSMK       SCQITSMK.
          SEX            SEX.
          SEXCONDM       SEXCONDM.
          SEXINTMN       SEXINTMN.
          SMKPUBLC       SMKPUBLC.
          SMKWORK        SMKWORK.
          SMOKE100       SMOK100_.
          SMOKEDAY       SMOKEDAY.
          STDCLIN        STDCLIN.
          STDTREAT       STDTREAT.
          STOPSMK2       STOP2SMK.
          STRSYMP1       STR1SYMP.
          STRSYMP2       STR2SYMP.
          STRSYMP3       STR3SYMP.
          STRSYMP4       STR4SYMP.
          STRSYMP5       STR5SYMP.
          STRSYMP6       STR6SYMP.
          STROKAGE       STROKAGE.
          SUNBURN        SUNBURN.
          TAKEVIT        TAKEVIT.
          TELSERV        TELSERV.
          TOLDHI2        TOLD2HI.
          TYPCNTR3       TYP3CNTR.
          HIVTSTD2       UNK6ADIG.
          USEEVER2       USE2EVER.
          USENOW2        USE2NOW.
          USEEQUIP       USEEQUIP.
          USEOTHNW       USEOTHNW.
          VACARE         VACARE.
          VETSTAT2       VET2STAT.
          VETERAN        VETERAN.
          VITAMINS       VITAMINS.
          WEIGHT2        WEIGHT.
          WHRTST6        WHR6TST.
          WHYASPAN       WHYASPAN.
          WHYASPHA       WHYASPHA.
          WHYASPSK       WHYASPSK.
          WTKG2F         WT2KG.
          _AIDTST2       _2AIDTST.
          _DENSTR2       _2DENSTR.
          _DRNKDY2       _2DRNKDY.
          _DRNKMO2       _2DRNKMO.
          _FLSHOT2       _2FLSHOT.
          _RACEG2        _2RACEG.
          _RACEGR2       _2RACEGR.
          _RFBING2       _2RFBING.
          _RFDRHV2       _2RFDRHV.
          _RFDRMN2       _2RFDRMN.
          _RFDRWM2       _2RFDRWM.
          _RFFRAR2       _2RFFRAR.
          _RFSIGM2       _2RFSIGM.
          _RFSMOK2       _2RFSMOK.
          _SMOKER2       _2SMOKER.
          _STDCND2       _2STDCND.
          _RFPAP32       _32RFPAP.
          _BMI4          _4BMI.
          _RFBMI4        _4RFBMI.
          _AGE65YR       _AGE65YR.
          _AGEG5YR       _AGEG5YR.
          _AGEG_         _AGEGFMT.
          _AGE_G         _AGE_G.
          _ALTEETH       _ALTEETH.
          _ASTHMST       _ASTHMST.
          _BMI4CAT       _BMI4CAT.
          _CASTHMA       _CASTHMA.
          _CHLDCNT       _CHLDCNT.
          _CNRACE        _CNRACE.
          _CNRACEC       _CNRACEC.
          _DENTVST       _DENTVST.
          _EDUCAG        _EDUCAG.
          _EXTEETH       _EXTEETH.
          _HIGHRSK       _HIGHRSK.
          _IMPAGE        _IMPAGE.
          _IMPNPH        _IMPNPH.
          _INCOMG        _INCOMG.
          _LTASTHM       _LTASTHM.
          _MRACE         _MRACE.
          _PNEUMOC       _PNEUMOC.
          _PRACE         _PRACE.
          _RACE_G        _RACE_G.
          _RFBLDST       _RFBLDST.
          _RFFRARM       _RFFRARM.
          _RFHLTH        _RFHLTH.
          _RFMAM2Y       _RFMAM2Y.
          _RFPSA2Y       _RFPSA2Y.
          _STATE         _STATE.
          _TOTINDA       _TOTINDA.
        ;
