*****************************************************************************************
* FILE NAME:     SASOUT04.SAS                                                           *
* DESCRIPTION:   THIS PROGRAM CONVERTS A STATES ASCII DATAFILE OF COMPLETES LOCATED AT  *
*                <DATAIN> FILEREF, INTO A SAS DATABASE STORED AT <DATAOUT> LIBREF       *
* REFERENCES:                                                                           *
* INPUT       DATAIN           FILEREF OF ASCII DATAFILE OF COMPLETES                   *
* FORMATS     FORMATS.sas7bcat      SAS FORMATS DATABASE                                *
* OUTPUT      DATAOUT.SASDATA  SAS DATABASE VERSION OF ASCII DATA AS SPECIFIED IN       *
*                              <DATAIN> FILEREF                                         *
* UPDATED - 09/22/2005                                                                  *
*****************************************************************************************;
********************************
* Clear Output and Log Windows *
********************************;
DM OUTPUT 'clear' continue;
DM LOG    'clear' continue;
**********************************
* DEFINE SAS ENVIRONMENT OPTIONS *
**********************************;
OPTIONS PAGENO=1 NOFMTERR;
***************************************
* CLEAR EXISTING TITLES AND FOOTNOTES *
***************************************;
TITLE ;
FOOTNOTE ;
RUN ;
******************************************************************
* INSTRUCTIONS:                                                  *
* SPECIFY PATH OF WHERE ASCII DATAFILE IS STORED                 *
* SPECIFY PATH OF WHERE SAS DATASET IS TO BE STORED              *
* SPECIFY PATH OF WHERE SAS FORMAT LIBRARY IS STORED             *
* SPECIFY PATH OF WHERE THE FORMAT ASSIGNMET STATEMENT IS STORED *
******************************************************************;

*FILENAME DATAIN '<PATH OF INPUT STATE ASCII DATAFILE OF COMPLETES>' LRECL = 991 ;
*****************************************************************************
* EXAMPLE:                                                                  *
*       FILENAME DATAIN 'C:\BRFSS\2004\CDBRFS04.ASC' LRECL = 991            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

*LIBNAME DATAOUT V7 '<PATH OF PERMANENTLY STORED SAS DATASET VERSION OF DATAIN FILEREF>'  ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME DATAOUT 'C:\'                                            *
*          A SAS DATABASE WILL BE STORED AT C:\SASDATA.sas7bdat             *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*       TO MAKE A VERSION 6 DATA SET, REMOVE THE   FROM THE                 *
*       LIBNAME LINE AND CHANGE THE V7 TO A V6                              *
*****************************************************************************;

*LIBNAME LIBRARY '<PATH OF STORED SAS FORMAT03.sas7bcat>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          LIBNAME LIBRARY 'C:\'                                            *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD LIBNAME AND       *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE LIBNAME STATEMENT                                          *
*****************************************************************************;

*FILENAME FORMATIN '<PATH OF FORMAT ASSIGNMENT STATEMENT>' ;
*****************************************************************************
* EXAMPLE:                                                                  *
*          FILENAME FORMATIN 'C:\FORMATSTATEMENT.SAS'                       *
* NOTE: MAKE SURE THE ASTERISK IS REMOVED BEFORE THE WORD FILENAME AND      *
*       MAKE SURE THAT THE GREATER THAN AND LESS THAN SIGNS < > ARE REMOVED *
*       FROM THE FILENAME STATEMENT                                         *
*****************************************************************************;

DATA DATAOUT.SASDATA ;
INFILE DATAIN MISSOVER ;
INPUT
_STATE        1-2                     /* Record Identification */
_GEOSTR       3-4
_DENSTR2      5
PRECALL       6
REPNUM        7-11
REPDEPTH      12-13
FMONTH        14-15
IDATE         $16-23
IMONTH        $16-17
IDAY          $18-19
IYEAR         $20-23
INTVID        $24-26
DISPCODE      35-37
SEQNO         38-47
_PSU          38-47
NATTMPTS      48-49
NRECSEL       50-55
NRECSTR       56-64
CTELENUM      65
PVTRESID      66
NUMADULT      67-68
NUMMEN        69-70
NUMWOMEN      71-72
GENHLTH       73                      /* Section 1: Health Status */
PHYSHLTH      74-75                   /* Section 2: Healthy Days - Health-Related Quality of Life */
MENTHLTH      76-77
POORHLTH      78-79
HLTHPLAN      80                      /* Section 3: Health Care Access */
PERSDOC2      81
MEDCOST       82
EXERANY2      83                      /* Section 4: Exercise */
EFILLAIR      84                      /* Section 5: Environmental Factors */
EFILLPOL      85
SUNBURN       86                      /* Section 6: Excess Sun Exposure */
NUMBURN       87
SMOKE100      88                      /* Section 7: Tobacco Use */
SMOKEDAY      89
STOPSMK2      90
ALCDAY3       91-93                   /* Section 8: Alcohol Consumption */
AVEDRNK       94-95
DRNK2GE5      96-97
DRINKDRI      98-99
ASTHMA2       100                     /* Section 9: Asthma */
ASTHNOW       101
DIABETE2      102                     /* Section 10: Diabetes */
LASTDEN2      103                     /* Section 11: Oral Health */
RMVTEETH      104
DENCLEAN      105
FLUSHOT2      106                     /* Section 12: Immunization */
FLUSPRAY      107
PNEUVAC2      108
AGE           109-110                 /* Section 13: Demographics */
HISPANC2      111
MRACE         $112-117
ORACE2        118
MARITAL       119
CHILDREN      120-121
EDUCA         122
EMPLOY        123
INCOME2       124-125
WEIGHT2       126-129
HEIGHT2       130-133
CTYCODE       134-136
NUMHHOL2      137
NUMPHON2      138
TELSERV       139
SEX           140
PREGNANT      141
VETERAN       142                     /* Section 14: Veterans Status */
VETSTAT2      143
VACARE        144
HADMAM        145                     /* Section 15: Women’s Health */
HOWLONG       146
PROFEXAM      147
LENGEXAM      148
HADPAP2       149
LASTPAP2      150
HADHYST2      151
PSATEST       152                     /* Section 16: Prostate Cancer Screening */
PSATIME       153
DIGRECEX      154
DRETIME       155
PROSTATE      156
BLDSTOOL      157                     /* Section 17: Colorectal Cancer Screening */
LSTBLDS2      158
HADSIGM3      159
LASTSIG2      160
BRTHCNT3      161                     /* Section 18: Family Planning */
TYPCNTR3      162-163
NOBCUSE2      164-165
FPCHLDFT      166
FPCHLDHS      167
QLACTLM2      168                     /* Section 19: Disability */
USEEQUIP      169
HIVTF1A       170                     /* Section 20: HIV/AIDS */
HIVTF1B       171
HIVTST4       172
HIVTSTNM      173-174
HIVTSTD2      175-180
RSNTST4       181-182
WHRTST6       183-184
HIVTSTCL      185
HIVTSTBY      186
HIVRISK2      187
PCSAIDS2      188
FIREARM4      189                     /* Section 21: Firearms */
GUNLOAD       190
LOADULK2      191
DIABAGE2      195-196                 /* Module 1: Diabetes */
INSULIN       197
DIABPILL      198
BLDSUGAR      199-201
FEETCHK2      202-204
FEETSORE      205
DOCTDIAB      206-207
CHKHEMO3      208-209
FEETCHK       210-211
EYEEXAM       212
DIABEYE       213
DIABEDU       214
SEXINTMN      215-216                 /* Module 2: Sexual Behavior */
SEXCONDM      217
CONDLAST      218
CONEFF2       219
NEWPARTN      220-221
STDTREAT      222
STDCLIN       223
BPHIGH3       224                     /* Module 3: Hypertension Awareness */
BPMEDS        225
BLOODCHO      226                     /* Module 4: Cholesterol Awareness */
CHOLCHK       227
TOLDHI2       228
PAINACT2      229-230                 /* Module 5: Healthy Days (Symptoms) */
QLMENTL2      231-232
QLSTRES2      233-234
QLREST2       235-236
QLHLTH2       237-238
IAQHTSRC      239                     /* Module 6: Indoor Air Quality */
IAQGASAP      240
IAQHTDYS      241-243
IAQCODTR      244
IAQMOLD       245
HEWTRSRC      246                     /* Module 7: Home Environment */
HEWTRDRK      247
HECHMHOM      248-250
HECHMYRD      251-253
FLUPRO2       254-255                 /* Module 8: Influenza */
ASTHMAGE      256-257                 /* Module 9: Adult Asthma History */
ASATTACK      258
ASERVIST      259-260
ASDRVIST      261-262
ASRCHKUP      263-264
ASACTLIM      265-267
ASYMPTOM      268
ASNOSLEP      269
ASTHMEDS      270
CASTHDX       271-272                 /* Module 10: Childhood Asthma */
CASTHNOW      273-274
HASYMP1       275                     /* Module 11: Heart Attack and Stroke */
HASYMP2       276
HASYMP3       277
HASYMP4       278
HASYMP5       279
HASYMP6       280
STRSYMP1      281
STRSYMP2      282
STRSYMP3      283
STRSYMP4      284
STRSYMP5      285
STRSYMP6      286
FIRSTAID      287
CVDFAT02      288                     /* Module 12: Cardiovascular Disease */
CVDFVG01      289
CVDEXR03      290
CVDFATR2      291
CVDFVEG       292
CVDEXRS2      293
CVDINFR2      294
CVDCRHD2      295
CVDSTRK2      296
HATTKAGE      297-298
STROKAGE      299-300
CVDREHAB      301
CVDASPRN      302
ASPUNSAF      303
WHYASPAN      304
WHYASPHA      305
WHYASPSK      306
VITAMINS      307                     /* Module 13: Folic Acid */
MULTIVIT      308
FOLICACD      309
TAKEVIT       310-312
RECOMMEN      313
USEEVER2      314                     /* Module 14: Other Tobacco Products */
USENOW2       315
USEOTHNW      316
SCLSTSMK      317-318                 /* Module 15: Smoking Cessation */
SCGETCAR      319-320
SCQITSMK      321-322
SCDSCMED      323-324
SCDSCMTH      325-326
HOUSESMK      327                     /* Module 16: Secondhand Smoke Policy */
INDOORS       328
SMKPUBLC      329
SMKWORK       330
PAIN30DY      331                     /* Module 17: Arthritis Burden */
JOINTSYM      332
JOINTRT2      333
HAVARTH2      334
LMTJOIN2      335
ARTHDISB      336
ARTTODAY      337                     /* Module 18: Arthritis Management */
ARTHWGT       338
ARTHEXER      339
ARTHEDU       340
DRNKBEER      341-342                 /* Module 19: Binge Drinking */
DRNKWINE      343-344
DRNKLIQR      345-346
DRNKLOC       347
BUYALCH       348
BINGEDRV      349
RRCLASS2      350                     /* Module 20: Reactions to Race */
RRCOGNT2      351
RRATWORK      352
RRHCARE2      353
RREMTSYM      354
RRPHYSYM      355
QSTVER        701                     /* Questionnaire Version */
QSTLANG       702-703                 /* Questionnaire Language */
_STSTR        715-719                 /* Weighting And Stratification Variables */
_STRWT        720-729
_RAW          730-739
_WT2          740-749
_POSTSTR      750-759
_FINALWT      760-769
_REGION       770-771
_AGEG_        772-773
_SEXG_        774
_RACEG3_      775
_IMPAGE       776-777
_IMPNPH       778
_RFHLTH       827                     /* Section 1: Calculated Variables */
_TOTINDA      828                     /* Section 4: Calculated Variables */
_SMOKER2      829                     /* Section 7: Calculated Variables */
_RFSMOK2      830
DROCCDY_      831-833                 /* Section 8: Calculated Variables */
DRNKANY3      834
_RFBING2      835
_DRNKDY2      836-839
_DRNKMO2      840-843
_RFDRHV2      844
_RFDRMN2      845
_RFDRWM2      846
_LTASTHM      847                     /* Section 9: Calculated Variables */
_CASTHMA      848
_ASTHMST      849
_EXTEETH      850                     /* Section 11: Calculated Variables */
_ALTEETH      851
_DENTVST      852
_FLSHOT2      853                     /* Section 12: Calculated Variables */
_PNEUMOC      854
MRACEORG      $855-860                /* Section 13: Calculated Race Variables */
MRACEASC      $861-866
_PRACE        867-868
_MRACE        869-870
RACE2         871
_RACEG2       872
_RACEGR2      873
_RACE_G       874
_CNRACE       875
_CNRACEC      876
_AGEG5YR      877-878
_AGE65YR      879
_AGE_G        880
HTIN3         881-883
HTM3          884-886
WTKG2         887-891
_BMI4         892-895
_BMI4CAT      896
_RFBMI4       897
_CHLDCNT      898
_EDUCAG       899
_INCOMG       900
_RFMAM2Y      901                     /* Section 15: Calculated Variables */
_RFPAP32      902
_RFPSA2Y      903                     /* Section 16: Calculated Variables */
_RFBLDST      904                     /* Section 17: Calculated Variables */
_RFSIGM2      905
_AIDTST2      906                     /* Section 20: Calculated Variables */
_HIGHRSK      907
_STDCND2      908
_RFFRARM      909                     /* Section 21: Calculated Variables */
_RFFRAR2      910
ENDOFREC      991                     /* End of Record */
;
*****************************************************************
* TO INCLUDE THE FORMAT ASSIGNEMT STATEMENT REMOVE THE ASTERISK *
* FROM THE BEGINNING OF THE FOLLOWING LINE                      *
*****************************************************************;
* %INCLUDE FORMATIN ;
*************************************************
* THIS SECTION CREATES LABELS FOR THE VARIABLES *
*************************************************;
Label
AGE = 'REPORTED AGE IN YEARS'
ALCDAY3 = 'DRINK DAYS PER TIME (WK OR MO)'
ARTHDISB = 'ARTHRITIS AFFECTS YOUR PAID WORK'
ARTHEDU = 'EVER TAKEN CLASS IN MANAGING ARTHRITIS OR JOINT SYMPTOMS'
ARTHEXER = 'DR. SUGGEST USE OF PHYSICAL ACTIVITY OR EXERCISE FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTHWGT = 'DR. SUGGEST LOSE WEIGHT FOR ARTHRITIS OR JOINT SYMPTOMS'
ARTTODAY = 'WHAT CAN YOU DO BECAUSE OF ARTHRITIS OR JOINT SYMPTOMS'
ASACTLIM = 'DAYS MISSED WORK DUE TO ASTHMA'
ASATTACK = 'ASTHMA ATTACK LAST 12 MOS'
ASDRVIST = 'DOC VISITS LAST 12 MOS FOR ASTHMA'
ASERVIST = 'ER VISITS LAST 12 MOS FOR ASTHMA'
ASNOSLEP = 'SLEEP PROBS FROM ASTHMA LAST 30 DAYS'
ASPUNSAF = 'HEALTH MAKES TAKING ASPIRIN UNSAFE'
ASRCHKUP = 'ROUTINE CHECKUPS LAST 12 MOS FOR ASTHMA'
ASTHMA2 = 'EVER HAD ASTHMA'
ASTHMAGE = 'AGE WHEN DOC SAID HAD ASTHMA'
ASTHMEDS = 'ASTHMA MED USAGE LAST 30 DAYS'
ASTHNOW = 'HAVE ASTHMA NOW'
ASYMPTOM = 'SYMPTOMS OF ASTHMA LAST 30 DAYS'
AVEDRNK = 'AVERAGE NUMBER OF DRINKS PER OCCASION'
BINGEDRV = 'DRIVE A MOTOR VEHICLE AFTER BINGE DRINKING'
BLDSTOOL = 'EVER HAD BLOOD STOOL TEST USING HOME KIT'
BLDSUGAR = 'HOW OFTEN CHECK BLOOD FOR GLUCOSE'
BLOODCHO = 'EVER HAD BLOOD CHOLESTEROL CHECKED'
BPHIGH3 = 'EVER TOLD BLOOD PRESSURE HIGH'
BPMEDS = 'MEDS FOR BLOOD PRESSURE'
BRTHCNT3 = 'USING BIRTH CONTROL?'
BUYALCH = 'HOW DID YOU GET BINGE DRINKING ALCOHOL'
CASTHDX = 'CHILDREN DIAGNOSED W/ASTHMA'
CASTHNOW = '# CHILDREN STILL HAVE ASTHMA'
CHILDREN = '# CHILDREN UNDER 18 IN HOUSEHOLD'
CHKHEMO3 = 'CHECKED FOR HEMOGLOBIN “A ONE C”'
CHOLCHK = 'HOW LONG SINCE CHOLESTEROL CHECKED'
CONDLAST = 'WHY DID YOU USE A CONDOM'
CONEFF2 = 'HOW GOOD ARE CONDOMS AT STOPPING HIV SPREAD'
CTELENUM = 'CORRECT NUMBER?'
CTYCODE = 'COUNTY CODE'
CVDASPRN = 'TAKE ASPIRIN DAILY OR EVERY OTHER DAY'
CVDCRHD2 = 'EVER TOLD HAD CORONARY HEART DISEASE'
CVDEXR03 = 'RED HRT ATTK RISK: PHYS ACTIVITY'
CVDEXRS2 = 'DOC SAID EXERCISE LAST 12 MOS'
CVDFAT02 = 'RED HRT ATTK RISK: EAT FEWER FATTY FDS'
CVDFATR2 = 'DOC SAID EAT LESS FAT LAST 12 MOS'
CVDFVEG = 'DOC SAID EAT FRT/VEG LAST 12 MOS'
CVDFVG01 = 'RED HRT ATTK RISK: EAT FRTS/VEG'
CVDINFR2 = 'EVER TOLD HAD MYOCARDIAL INFARCTION'
CVDREHAB = 'REHAB AFTER HRT ATTK'
CVDSTRK2 = 'EVER TOLD HAD STROKE'
DENCLEAN = 'HOW LONG SINCE LAST TEETH CLEANING'
DIABAGE2 = 'AGE TOLD HAVE DIABETES'
DIABEDU = 'EVER TAKEN CLASS TO MANAGE DIABETES'
DIABETE2 = 'EVER TOLD BY DOCTOR YOU HAVE DIABETES'
DIABEYE = 'DIABETES AFFECT EYES OR HAD RETINOPATHY'
DIABPILL = 'NOW TAKING DIABETES PILLS'
DIGRECEX = 'EVER HAD RECTAL EXAM'
DISPCODE = 'DISPOSITION OF INTERVIEW'
DOCTDIAB = 'TIMES SEEN HEALTH PROF FOR DIABETES'
DRETIME = 'TIME SINCE RECTAL EXAM'
DRINKDRI = 'DRANK AND DROVE LAST 30 DAYS'
DRNK2GE5 = 'FIVE OR MORE DRINKS ON AN OCCASION'
DRNKANY3 = 'CONSUMED ALCOHOL IN PAST 30 DAYS'
DRNKBEER = 'HOW MANY BEERS CONSUMED WHEN BINGE DRINKING'
DRNKLIQR = 'HOW MANY DRINKS OF LIQUOR CONSUMED WHEN BINGE DRINKING'
DRNKLOC = 'WHERE WERE YOU WHEN YOU BINGE DRANK'
DRNKWINE = 'HOW MANY GLASSES OF WINE CONSUMED WHEN BINGE DRINKING'
DROCCDY_ = 'DRINK-OCCASIONS-PER-DAY'
EDUCA = 'EDUCATION LEVEL'
EFILLAIR = 'Has bad air made you ill in the past 12 months?'
EFILLPOL = 'Has air pollution made you ill in the past 12 months?'
EMPLOY = 'EMPLOYMENT STATUS'
ENDOFREC = 'END OF RECORD MARKER'
EXERANY2 = 'EXERCISE LAST 30 DAYS'
EYEEXAM = 'LAST EYE EXAM WHERE PUPILS WERE DILATED'
FEETCHK = 'TIMES FEET CHECK FOR SORES/IRRITATIONS'
FEETCHK2 = 'HOW OFTEN CHECK FEET FOR SORES'
FEETSORE = 'SORES ON FEET MORE THAN 4 WEEKS TO HEAL'
FIREARM4 = 'HAVE FIREARM AROUND HOME'
FIRSTAID = 'STROKE SYMPT: 1ST RESP FOR H ATTK VICTIM'
FLUPRO2 = 'PLACE GOT LAST FLU SHOT'
FLUSHOT2 = 'HAD FLU SHOT IN PAST 12 MONTHS'
FLUSPRAY = 'HAD NASAL FLU VACCINE IN PAST 12 MONTHS'
FMONTH = 'MONTH NAME OF SOURCE FILE'
FOLICACD = 'ANY VITAMINS CONTAIN FOLIC ACID'
FPCHLDFT = 'HOW DO YOU FEEL ABOUT HAVING A CHILD IN THE FUTURE?'
FPCHLDHS = 'HOW SOON WOULD YOU WANT TO HAVE A CHILD?'
GENHLTH = 'GENERAL HEALTH'
GUNLOAD = 'FIREARMS NOW LOADED?'
HADHYST2 = 'EVER HAD A HYSTERECTOMY'
HADMAM = 'HAVE YOU EVER HAD A MAMMOGRAM'
HADPAP2 = 'EVER HAD A PAP TEST'
HADSIGM3 = 'EVER HAD A SIGMOIDOSCOPY/COLONOSCOPY'
HASYMP1 = 'HRT ATTK SYMPTOM: JAW NECK BACK PAIN'
HASYMP2 = 'HRT ATTK SYMPTOM: LIGHTHEADED, FAINT'
HASYMP3 = 'HRT ATTK SYMPTOM: CHEST PAIN'
HASYMP4 = 'HRT ATTK SYMPTOM: LOSE VISION'
HASYMP5 = 'HRT ATTK SYMPTOM: ARM SHOULDER PAIN'
HASYMP6 = 'HRT ATTK SYMPTOM: SHORTNESS OF BREATH'
HATTKAGE = 'AGE AT 1ST HRT ATTK'
HAVARTH2 = 'TOLD HAVE ARTHRITIS BY DOCTOR'
HECHMHOM = '# DAYS CHEMICALS APPLIED IN HOME TO KILL PESTS IN PAST 12 MONTHS'
HECHMYRD = '# DAYS CHEMICALS APPLIED IN LAWN TO KILL PESTS IN PAST 12 MONTHS'
HEIGHT2 = 'REPORTED HEIGHT IN FEET AND INCHES'
HEWTRDRK = 'WHICH BEST DESCRIBES WATER YOU DRINK AT HOME'
HEWTRSRC = 'MAIN SOURCE OF HOME WATER'
HISPANC2 = 'HISPANIC ORIGIN'
HIVRISK2 = 'ANY HIGH RISK SITUATIONS APPLY'
HIVTF1A = 'HIV PREVENTION BETW PREG MOTHER/INFANT'
HIVTF1B = 'TRT FOR HIV PERSON TO LIVE LONGER'
HIVTST4 = 'EVER TSTD FOR HIV OTHR THAN BLOOD DONATN'
HIVTSTBY = 'HOW WAS LAST HIV TEST DONE'
HIVTSTCL = 'TYPE OF CLINIC LAST TESTED FOR HIV'
HIVTSTD2 = 'MO/YR OF HIV TEST'
HIVTSTNM = 'HOW MANY TIMES TESTED FOR HIV IN PAST 12 MONTHS'
HLTHPLAN = 'HAVE HEALTH CARE COVERAGE'
HOUSESMK = 'SMOKING ALLOWED AT HOME'
HOWLONG = 'HOW LONG SINCE LAST MAMMOGRAM'
HTIN3 = 'REPORTED HEIGHT IN INCHES.'
HTM3 = 'REPORTED HEIGHT IN METERS.'
IAQCODTR = 'HAVE CO DETECTOR IN HOME'
IAQGASAP = 'HAVE NATRUAL GAS POWERED APPLIANCES'
IAQHTDYS = '# DAYS IN PAST 12 MONTHS  USED FUEL BURNING STOVE, FIREPLACE OR HEATER'
IAQHTSRC = 'HOME HEATED WITH FURNACE THAT BURNS FUEL'
IAQMOLD = 'HAVE MOLD GREATER THAN SIZE OF DOLLAR BILL'
IDATE = 'DATE OF INTERVIEW'
IDAY = 'DAY OF INTERVIEW'
IMONTH = 'MONTH OF INTERVIEW'
INCOME2 = 'INCOME LEVEL'
INDOORS = 'NORMALLY WORK INDOORS?'
INSULIN = 'NOW TAKING INSULIN'
INTVID = 'INTERVIEWER ID'
IYEAR = 'YEAR OF INTERVIEW'
JOINTRT2 = 'SEEN DOC FOR JOINT SYMPTOMS'
JOINTSYM = 'JOINT SYMPTOMS 1ST BEGAN 3 MOS AGO?'
LASTDEN2 = 'HOW LONG SINCE LAST DENTIST VISIT'
LASTPAP2 = 'HOW LONG SINCE LAST PAP TEST'
LASTSIG2 = 'LAST TIME HAD SIGMOIDOSCOPY/COLONOSCOPY'
LENGEXAM = 'HOW LONG SINCE LAST BREAST PHYSICAL EXAM'
LMTJOIN2 = 'LIMITED BECAUSE OF JOINT SYMPTOMS'
LOADULK2 = 'LOADED FIREARMS UNLOCKED?'
LSTBLDS2 = 'HOW LONG SINCE LAST HOME BLOOD STOOL TST'
MARITAL = 'MARITAL STATUS'
MEDCOST = 'COULD NOT SEE DR. BECAUSE OF COST'
MENTHLTH = 'NUMBER OF DAYS MENTAL HEALTH NOT GOOD'
MRACE = 'ORIGINAL REPORTED RACE'
MRACEASC = 'REPORTED MRACE VARIABLE WITH TRAILING 7,8,9’S REMOVED, IN ASCENDING ORDER.'
MRACEORG = 'REPORTED MRACE VARIABLE WITH TRAILING 7,8,9’S REMOVED.'
MULTIVIT = 'ANY OF VITS/SUPPLEMENTS A MULTIVITAMIN'
NATTMPTS = 'NUMBER OF ATTEMPTS'
NEWPARTN = 'NUMBER OF NEW SEX PARTNERS IN PAST 12 MONTHS'
NOBCUSE2 = 'REASON NOT USING BIRTH CONTROL'
NRECSEL = 'NUMBER OF SAMPLE RECORDS FOR STRATUM'
NRECSTR = 'TOTAL PH. NOS. IN STRATUM FROM SAMPLE'
NUMADULT = 'NUMBER OF ADULTS IN HOUSEHOLD'
NUMBURN = 'NUMBER OF SUNBURNS IN PAST 12 MONTHS'
NUMHHOL2 = 'MORE THAN ONE TELPHONE NUMBER IN HH'
NUMMEN = 'NUMBER OF ADULT MALES IN HOUSEHOLD'
NUMPHON2 = 'NUMBER OF RESIDENTIAL PHONE NUMBERS'
NUMWOMEN = 'NUMBER OF ADULT FEMALES IN HOUSEHOLD'
ORACE2 = 'PREFERRED RACE'
PAIN30DY = 'HAD JOINT PAIN, SWELLING LST 30 DAYS'
PAINACT2 = 'TIMES IN PAST MONTH PAIN INTERFERED'
PCSAIDS2 = 'TOLD BY DOC ABOUT STD PREV BY CONDOMS'
PERSDOC2 = 'HAVE PERSONAL HEALTH CARE PROVIDER'
PHYSHLTH = 'NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD'
PNEUVAC2 = 'EVER HAD PNEUMONIA VACCINATION'
POORHLTH = 'DAYS HEALTH IMPAIRED LAST MO'
PRECALL = 'PRECALLING STATUS'
PREGNANT = 'ARE YOU NOW PREGNANT'
PROFEXAM = 'EVER HAD BREAST PHYSICAL EXAM BY DOCTOR'
PROSTATE = 'EVER TOLD HAVE PROSTATE CANCER'
PSATEST = 'EVER HAD PSA'
PSATIME = 'TIME SINCE PSA'
PVTRESID = 'PRIVATE RESIDENCE?'
QLACTLM2 = 'ACTIVITIES LIMITED BY HEALTH PROBLEM'
QLHLTH2 = 'TIMES IN PAST MONTH FELT HEALTHY'
QLMENTL2 = 'TIMES IN PAST MONTH FELT DEPRESSED'
QLREST2 = 'TIMES IN PAST MONTH NOT ENOUGH REST'
QLSTRES2 = 'TIMES IN PAST MONTH BEEN STRESSED'
QSTLANG = 'QUESTIONNAIRE LANGUAGE'
QSTVER = 'QUESTIONNAIRE VERSION'
RACE2 = 'RACE/ETHNICITY CATEGORIES.'
RECOMMEN = 'REASONS HLTH EXPERTS RECMND FOLIC ACID'
REPDEPTH = 'REPLICATE DEPTH'
REPNUM = 'REPLICATE NUMBER'
RMVTEETH = 'NUMBER OF PERMANENT TEETH REMOVED'
RRATWORK = 'TREATED DIFF THAN OTH RACE AT WORK'
RRCLASS2 = 'OTHERS CLASSIFY YOUR RACE'
RRCOGNT2 = 'HOW OFTEN THINK ABOUR YOUR RACE'
RREMTSYM = 'EMOT UPSET FOR TRMT BASED ON RACE'
RRHCARE2 = 'TREATED DIFF THAN OTH RACE HLTH CARE'
RRPHYSYM = 'HAD PHYS SYMPTOMS FOR TRMT BASED ON RACE'
RSNTST4 = 'MAIN REASON FOR HIV TEST'
SCDSCMED = '# VISITS DOCTOR DISCUSSED MEDICATION TO ASSIST QUITTING SMOKING'
SCDSCMTH = '# VISITS DOCTOR DISCUSSED METHODS TO QUIT SMOKING'
SCGETCAR = '# TIMES SAW A DOCTOR FOR CARE LAST 12 MONTHS'
SCLSTSMK = 'TIME SINCE LAST SMOKED REGULARLY'
SCQITSMK = '# VISITS ADVISED TO QUIT SMOKING LAST 12 MONTHS'
SEQNO = 'ANNUAL SEQUENCE NUMBER'
SEX = 'SEX'
SEXCONDM = 'USED CONDOM DURING LAST SEXUAL INTERCOURSE'
SEXINTMN = 'NUMBER OF SEXUAL PARTNERS IN PAST 12 MONTHS'
SMKPUBLC = 'SMOKING POLICY AT WORK FOR COMMON AREAS'
SMKWORK = 'SMOKING POLICY AT WORK FOR WORK AREAS'
SMOKE100 = 'SMOKED AT LEAST 100 CIGARETTES'
SMOKEDAY = 'FREQUENCY OF DAYS NOW SMOKING'
STDCLIN = 'WHERE TREATED FOR S.T.D.'
STDTREAT = 'BEEN TREATED FOR S.T.D. IN PAST 5 YEARS'
STOPSMK2 = 'QUIT SMOKING A DAY OR MORE IN PAST YEAR'
STROKAGE = 'AGE AT 1ST STROKE'
STRSYMP1 = 'STROKE SYMPT: SUDDEN CONFUSION'
STRSYMP2 = 'STROKE SYMPT: NUMBNESS ON ONE SIDE BODY'
STRSYMP3 = 'STROKE SYMPT: SUDDEN VISION LOSS'
STRSYMP4 = 'STROKE SYMPT: SUDDEN CHEST PAIN'
STRSYMP5 = 'STROKE SYMPT: SUDDEN DIZZINESS'
STRSYMP6 = 'STROKE SYMPT: SEVERE UNXPLND HEADACHE'
SUNBURN = 'HAD A SUNBRUN IN PAST TWELVE MONTHS'
TAKEVIT = 'HOW OFTEN TAKE VITAMIN OR SUPPLEMENT'
TELSERV = 'HOUSEHOLD BEEN WITHOUT PHONE SERVICE IN LAST 12 MONTHS'
TOLDHI2 = 'EVER TOLD BLOOD CHOLESTEROL HIGH'
TYPCNTR3 = 'METHOD BIRTH CONTROL'
USEEQUIP = 'REQ SPECIAL EQUIPMENT FOR HLTH PROBLEM'
USEEVER2 = 'EVER USED SMOKELESS TOBACCO PRODUCTS'
USENOW2 = 'CURRENTLY USE SMOKELESS TOBACCO PRODUCTS'
USEOTHNW = 'CURRENTLY USE ANY TOBACCO PRODUCTS OTHER THAN CIGARETTES'
VACARE = 'RECEIVED HEALTH CARE FROM VA FACILITY'
VETERAN = 'ARE YOU A VETERAN'
VETSTAT2 = 'CURRENT VETERAN STATUS'
VITAMINS = 'CURRENTLY TAKE VIT PILLS OR SUPPLEMENTS'
WEIGHT2 = 'REPORTED WEIGHT IN POUNDS'
WHRTST6 = 'WHERE TESTED FOR HIV'
WHYASPAN = 'TAKE ASPIRIN TO RELIEVE PAIN'
WHYASPHA = 'TAKE ASPIRIN TO REDUCE HEART ATTACK'
WHYASPSK = 'TAKE ASPIRIN TO REDUCE STROKE'
WTKG2 = 'REPORTED WEIGHT IN KILOGRAMS.'
_AGE65YR = 'TWO LEVEL AGE CATEGORY.'
_AGEG5YR = 'FOURTEEN LEVEL AGE CATEGORY.'
_AGEG_ = 'AGE GROUPS USED IN POST-STRATIFICATION'
_AGE_G = 'SIX LEVEL IMPUTED AGE CATEGORY'
_AIDTST2 = 'EVER BEEN TESTED FOR HIV RISK FACTOR.'
_ALTEETH = 'RISK FACTOR FOR HAVING HAD ALL PERMANENT TEETH EXTRACTED.'
_ASTHMST = 'COMPUTED ASTHMA STATUS'
_BMI4 = 'BODY MASS INDEX.'
_BMI4CAT = 'BODY MASS INDEX- THREE LEVELS CATEGORY.'
_CASTHMA = 'RISK FACTOR FOR CURRENT ASTHMA PREVALENCE'
_CHLDCNT = 'NUMBER OF CHILDREN IN THE HOUSEHOLD'
_CNRACE = 'NUMBER OF CENSUS RACE CATEGORIES CHOSEN.'
_CNRACEC = 'NUMBER OF CENSUS RACE CATEGORIES CHOSEN, COLLAPSED.'
_DENSTR2 = 'DENSITY STRATUM'
_DENTVST = 'RISK FACTOR FOR HAVING VISITED A DENTIST, DENTAL HYGIENIST OR DENTAL CLINIC IN PAST YEAR.'
_DRNKDY2 = 'NUMBER OF ALCOHOL DRINKS PER DAY'
_DRNKMO2 = 'NUMBER OF ALCOHOL DRINKS PER MONTH'
_EDUCAG = 'LEVEL OF EDUCATION COMPLETED'
_EXTEETH = 'RISK FACTOR FOR HAVING HAD PERMANENT TEETH EXTRACTED.'
_FINALWT = 'PRODUCT OF _POSTSTR & _WT2'
_FLSHOT2 = 'RISK FACTOR FOR RESPONDENTS AGED 65+ THAT HAD A FLU SHOT IN THE PAST 12 MONTHS.'
_GEOSTR = 'STRATUM CODE'
_HIGHRSK = 'EVER PARTICIPATED IN HIGH-RISK BEHAVIOR RISK FACTOR.'
_IMPAGE = 'IMPUTED AGE USED IN POST-STRATIFICATION'
_IMPNPH = 'IMPUTED NUMBER OF PHONES USED IN POST-STRATIFICATION'
_INCOMG = 'INCOME CATEGORIES'
_LTASTHM = 'RISK FACTOR FOR LIFETIME ASTHMA PREVALENCE'
_MRACE = 'MULTIRACIAL RACE CATEGORIZATION.'
_PNEUMOC = 'RISK FACTOR FOR RESPONDENTS AGED 65+ THAT HAVE EVER HAD A PNEUMONIA SHOT.'
_POSTSTR = 'AGE, RACE, SEX WT ST POP'
_PRACE = 'PREFERRED RACE CATEGORY.'
_PSU = 'PRIMARY SAMPLING UNIT'
_RACEG2 = 'WHITE/HISPANIC RACE GROUP'
_RACEG3_ = 'RACE CATEGORIES USED IN POST-STRATIFICATION'
_RACEGR2 = '5 LEVEL RACE/ETHNICITY CATEGORY.'
_RACE_G = 'RACE GROUPS USED FOR INTERNET PREVALENCE TABLES'
_RAW = '# ADULTS/# PHONES'
_REGION = 'REGION'
_RFBING2 = 'BINGE DRINKING RISK FACTOR.'
_RFBLDST = 'RESPONDENTS AGED 50 AND OLDER THAT HAVE NOT HAD A BLOOD STOOL TEST WITHIN THE PAST TWO YEARS.'
_RFBMI4 = 'RISK FACTOR FOR OVERWEIGHT OR OBESE.'
_RFDRHV2 = 'HEAVY DRINKING RISK'
_RFDRMN2 = 'HEAVY DRINKING AMONG MEN RISK FACTOR.'
_RFDRWM2 = 'HEAVY DRINKING AMONG FEMALES RISK FACTOR.'
_RFFRAR2 = 'RISK FACTOR FOR LIVING IN HOME WITH LOADED AND UNLOCKED FIREARM.'
_RFFRARM = 'RISK FACTOR FOR LIVING IN HOME WITH LOADED FIREARM.'
_RFHLTH = 'HEALTH STATUS'
_RFMAM2Y = 'WOMEN AGED 40 AND OLDER THAT HAVE NOT HAD A MAMMOGRAM WITHIN THE PAST TWO YEARS.'
_RFPAP32 = 'WOMEN AGED 18 AND OLDER THAT HAVE NOT HAD A PAPTEST WITHIN THE PAST THREE YEARS.'
_RFPSA2Y = 'MEN AGED 40 AND OLDER THAT HAVE NOT HAD A PSA TEST WITHIN THE PAST TWO YEARS.'
_RFSIGM2 = 'RESPONDENTS AGED 50 AND OLDER THAT HAVE NEVER HAD A SIGMOIDOSCOPY OR COLONOSCOPY.'
_RFSMOK2 = 'CURRENT SMOKING STATUS RISK FACTOR.'
_SEXG_ = 'SEX CATEGORIES USED IN POST-STRAT'
_SMOKER2 = 'FOUR LEVEL SMOKER STATUS.'
_STATE = 'STATE FIPS CODE'
_STDCND2 = 'BEEN COUNSELED ON PREVENTION OF SEXUALLY TRANSMITTED DISEASES THROUGH CONDOM USE.'
_STRWT = 'STRATUM WEIGHT'
_STSTR = 'CONCATENATED STRATIFICATION VARIABLES'
_TOTINDA = 'NO LEISURE TIME PHYSICAL ACTIVITY OR EXERCISE PAST 30 DAYS'
_WT2 = 'DESIGN WEIGHT'
;
RUN;
